Repository operate-first/apps, pull requests merged in 2020-10, with the labels that each got.

#4 Add owners and ci config files
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  OWNERS
Labels: size/M

#3 Docs for overrides
  README.md
  components/.keep
  kfdef/jupyterhub/kfdef.yaml
  kfdef/jupyterhub/kustomization.yaml
  kfdef/superset/kfdef.yaml
  kfdef/superset/kustomization.yaml
  operator/README.md
  operator/base/kustomization.yaml
  operator/base/operator_group.yaml
  operator/base/subscription.yaml
Labels: approved, size/L

#6 Reword overrides/manifests
  README.md
  components/.keep
Labels: approved, size/S

#7 Update namespaces to use opf- prefix
  kfdef/jupyterhub/kustomization.yaml
  kfdef/superset/kustomization.yaml
Labels: approved, size/XS

#8 Make pre-commit happy
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  kfdef/jupyterhub/kfdef.yaml
  kfdef/jupyterhub/kustomization.yaml
  kfdef/superset/kfdef.yaml
  kfdef/superset/kustomization.yaml
  operator/base/kustomization.yaml
  operator/base/operator_group.yaml
  operator/base/subscription.yaml
Labels: approved, size/S
