Repository operate-first/apps, pull requests merged in 2020-11, with the labels that each got.

#21 Add monitoring components for Jupyterhub deployment
  kfdef/jupyterhub/kfdef.yaml
Labels: approved, size/S

#23 Add opf-monitoring namespace with Prometheus instance
  kfdef/monitoring/kfdef.yaml
  kfdef/monitoring/kustomization.yaml
  kfdef/monitoring/prometheus-route.yaml
  kfdef/monitoring/prometheus.yaml
Labels: approved, size/M

#22 Specify storageclass for Jupyterhub PVCs
  kfdef/jupyterhub/kfdef.yaml
Labels: approved, size/XS

#25 Add additional JH notebook imagestreams
  kfdef/jupyterhub/notebook-images/categorical-encoding.yaml
  kfdef/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S

#26 Fix pre-commit issues
  kfdef/jupyterhub/notebook-images/categorical-encoding.yaml
Labels: approved, size/S

#27 Updated "notebook-images/" to include ocp-ci-analysis project
  kfdef/jupyterhub/notebook-images/kustomization.yaml
  kfdef/jupyterhub/notebook-images/ocp-ci-analysis.yaml
Labels: approved, size/S

#28 Update to ODH 0.9 release
  kfdef/jupyterhub/kfdef.yaml
  kfdef/monitoring/kfdef.yaml
  kfdef/superset/kfdef.yaml
Labels: approved, size/S

#29 Add hard drive failure prediction notebook img to notebook-images
  kfdef/jupyterhub/notebook-images/ceph-drive-failure.yaml
  kfdef/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S

#31 added notebook images for configuration file analysis project
  kfdef/jupyterhub/notebook-images/configuration-files-analysis.yaml
  kfdef/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S

#33 Add grafana operator and resource
  .pre-commit-config.yaml
  kfdef/monitoring/grafana.yaml
  kfdef/monitoring/kfdef.yaml
  kfdef/monitoring/kustomization.yaml
  yamllint-config.yaml
Labels: approved, size/M

#34 Add argo kfdef
  kfdef/argo/kfdef.yaml
  kfdef/argo/kustomization.yaml
Labels: approved, size/M

#38 Fix grafana volume issues and oauth namespace sar
  kfdef/monitoring/grafana.yaml
Labels: approved, size/S

#40 Add superset pvc override
  kfdef/superset/kfdef.yaml
  kfdef/superset/overrides/base/pvc.yaml
Labels: approved, size/S
