Repository operate-first/apps, pull requests merged in 2020-12, with the labels that each got.

#32 feat(datacatalog): Deploy Thrift Server, Hue, Ceph into a single namespace
  kfdef/datacatalog/kfdef.yaml
  kfdef/datacatalog/kustomization.yaml
Labels: approved, size/M

#42 feat: Add dashboard
  kfdef/dashboard/kfdef.yaml
  kfdef/dashboard/kustomization.yaml
  kfdef/dashboard/overrides/overlays/cluster-role/kustomization.yaml
  kfdef/dashboard/overrides/overlays/cluster-role/rbac.yaml
  kfdef/dashboard/overrides/overlays/custom-image/kustomization.yaml
Labels: approved, size/L

#45 [Monitoring] Add argocd wave annotations for monitoring resources
  kfdef/monitoring/grafana.yaml
  kfdef/monitoring/kfdef.yaml
  kfdef/monitoring/prometheus-route.yaml
  kfdef/monitoring/prometheus.yaml
Labels: approved, size/XS

#50 Add Cloud Price Analysis notebook image to notebook-images
  kfdef/jupyterhub/notebook-images/cloud-price-analysis.yaml
  kfdef/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S

#46 Restructure to a per-downstream overlays
  base/argo/kfdef.yaml
  base/argo/kustomization.yaml
  base/dashboard/kfdef.yaml
  base/dashboard/kustomization.yaml
  base/dashboard/overrides/overlays/cluster-role/kustomization.yaml
  base/dashboard/overrides/overlays/cluster-role/rbac.yaml
  base/dashboard/overrides/overlays/custom-image/kustomization.yaml
  base/datacatalog/kfdef.yaml
  base/datacatalog/kustomization.yaml
  base/jupyterhub/kfdef.yaml
  base/jupyterhub/kustomization.yaml
  base/jupyterhub/notebook-images/categorical-encoding.yaml
  base/jupyterhub/notebook-images/ceph-drive-failure.yaml
  base/jupyterhub/notebook-images/cloud-price-analysis.yaml
  base/jupyterhub/notebook-images/configuration-files-analysis.yaml
  base/jupyterhub/notebook-images/kustomization.yaml
  base/jupyterhub/notebook-images/ocp-ci-analysis.yaml
  base/monitoring/grafana.yaml
  base/monitoring/kfdef.yaml
  base/monitoring/kustomization.yaml
  base/monitoring/prometheus-route.yaml
  base/monitoring/prometheus.yaml
  base/operator/kustomization.yaml
  base/operator/operator_group.yaml
  base/operator/subscription.yaml
  base/superset/kfdef.yaml
  base/superset/kustomization.yaml
  operator/README.md
  overlays/crc/argo/kustomization.yaml
  overlays/crc/dashboard/kustomization.yaml
  overlays/crc/datacatalog/kustomization.yaml
  overlays/crc/jupyterhub/kustomization.yaml
  overlays/crc/monitoring/kustomization.yaml
  overlays/crc/operator/kustomization.yaml
  overlays/crc/superset/kustomization.yaml
  overlays/moc/argo/kustomization.yaml
  overlays/moc/dashboard/kustomization.yaml
  overlays/moc/datacatalog/kustomization.yaml
  overlays/moc/jupyterhub/kustomization.yaml
  overlays/moc/monitoring/kustomization.yaml
  overlays/moc/superset/kustomization.yaml
  overlays/moc/superset/overrides/base/pvc.yaml
  overlays/quicklab/argo/kustomization.yaml
  overlays/quicklab/dashboard/kustomization.yaml
  overlays/quicklab/datacatalog/kustomization.yaml
  overlays/quicklab/jupyterhub/kustomization.yaml
  overlays/quicklab/monitoring/kustomization.yaml
  overlays/quicklab/operator/kustomization.yaml
  overlays/quicklab/superset/kustomization.yaml
Labels: approved, size/L

#52 Fix superset override repo
  base/superset/kfdef.yaml
  overlays/moc/superset/kustomization.yaml
Labels: approved, size/XS

#53 Added kafka component
  base/kafka/kfdef.yaml
  base/kafka/kustomization.yaml
  overlays/crc/kafka/kustomization.yaml
  overlays/moc/kafka/kustomization.yaml
  overlays/moc/kafka/overrides/kafka/base/kafka-cluster.yaml
  overlays/quicklab/kafka/kustomization.yaml
Labels: approved, size/L

#56 Add JH monitoring back in and fix kustomize build error for jh
  base/jupyterhub/kfdef.yaml
Labels: approved, size/S

#58 correct the example name referenced
  docs/add_kafka_topics.md
Labels: approved, size/XS

#62 Added kafka readme docs on access
  docs/kafka/README.md
  docs/kafka/add_kafka_topics.md
Labels: approved, size/S

#66 include project thoth kafkatopics to the kafka instance
  odh/overlays/moc/kafka/topics/kustomization.yaml
  odh/overlays/moc/kafka/topics/thoth-advise-justification.yaml
  odh/overlays/moc/kafka/topics/thoth-adviser-re-run.yaml
  odh/overlays/moc/kafka/topics/thoth-adviser-trigger.yaml
  odh/overlays/moc/kafka/topics/thoth-hash-mismatch.yaml
  odh/overlays/moc/kafka/topics/thoth-kebechet-trigger.yaml
  odh/overlays/moc/kafka/topics/thoth-missing-package-version.yaml
  odh/overlays/moc/kafka/topics/thoth-missing-package.yaml
  odh/overlays/moc/kafka/topics/thoth-package-extract-trigger.yaml
  odh/overlays/moc/kafka/topics/thoth-package-released.yaml
  odh/overlays/moc/kafka/topics/thoth-provenance-checker-trigger.yaml
  odh/overlays/moc/kafka/topics/thoth-qebhwt-trigger.yaml
  odh/overlays/moc/kafka/topics/thoth-si-unanalyzed-package.yaml
  odh/overlays/moc/kafka/topics/thoth-solved-package.yaml
  odh/overlays/moc/kafka/topics/thoth-unresolved-package.yaml
  odh/overlays/moc/kafka/topics/thoth-unrevsolved-package.yaml
  odh/overlays/moc/kafka/topics/thoth-update-provides-source-distro.yaml
Labels: approved, size/L

#67 Add Loki Stack using Observatorium
  observatorium/grafana-data-sources/kustomization.yaml
  observatorium/grafana-data-sources/opf-test-loki-source.yaml
  observatorium/grafana.yaml
  observatorium/kfdef.yaml
  observatorium/kustomization.yaml
  observatorium/observatorium.yaml
Labels: approved, size/L

#71 Revert "Add Loki Stack using Observatorium"
  observatorium/grafana-data-sources/kustomization.yaml
  observatorium/grafana-data-sources/opf-test-loki-source.yaml
  observatorium/grafana.yaml
  observatorium/kfdef.yaml
  observatorium/kustomization.yaml
  observatorium/observatorium.yaml
Labels: approved, size/L

#72 Add the Observatorium CR to deploy Loki
  observatorium/base/instance/example-loki-objectstorage-secret.yaml
  observatorium/base/instance/grafana-data-sources/kustomization.yaml
  observatorium/base/instance/grafana-data-sources/opf-test-loki-source.yaml
  observatorium/base/instance/grafana.yaml
  observatorium/base/instance/kfdef.yaml
  observatorium/base/instance/kustomization.yaml
  observatorium/base/instance/observatorium.yaml
  observatorium/base/operator/kustomization.yaml
Labels: approved, do-not-merge/hold, size/L

#76 Added docs for encrypting secrets & other resources.
  docs/encrypting_applications.md
Labels: approved, size/XS

#80 fix: Use Grafana/Prometheus as an ODH ocomponent
  odh/base/monitoring/kfdef.yaml
  odh/base/monitoring/kustomization.yaml
  odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
  odh/base/monitoring/prometheus-route.yaml
Labels: approved, size/M

#82 Add observatorium overlays
  observatorium/overlays/crc/kustomization.yaml
  observatorium/overlays/moc/kustomization.yaml
  observatorium/overlays/quicklab/kustomization.yaml
Labels: approved, size/S

#83 Add routes to access loki distributor and frontend api
  observatorium/base/instance/kustomization.yaml
  observatorium/base/instance/loki-routes.yaml
Labels: approved, size/S

#84 Add jupyterhub grafana dashboard resource
  odh/base/monitoring/overrides/dashboards/jupyterhub-dashboard.yaml
Labels: approved, size/S

#86 Update kafka kfdef name in patch
  odh/overlays/moc/kafka/kustomization.yaml
Labels: approved, size/XS

#88 Revert "Move jh grafana dashboard from /overrides into /base/monitoring"
  odh/base/monitoring/dashboards/kustomization.yaml
  odh/base/monitoring/kustomization.yaml
  odh/base/monitoring/overrides/dashboards/jupyterhub-dashboard.yaml
Labels: approved, size/XS

#91 Add jupyterhub grafana dashboard via overlays
  odh/base/monitoring/kfdef.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/kustomization.yaml
Labels: approved, size/XS

#93 Move topics into overrides and update docs
  docs/odh/kafka/add_kafka_topics.md
  odh/README.md
  odh/overlays/crc/kafka/kustomization.yaml
  odh/overlays/crc/kafka/overrides/kafka/overlays/topics/example-topic.yaml
  odh/overlays/crc/kafka/overrides/kafka/overlays/topics/kustomization.yaml
  odh/overlays/moc/kafka/kustomization.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/kustomization.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-advise-justification.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-adviser-re-run.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-adviser-trigger.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-hash-mismatch.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-kebechet-trigger.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-missing-package-version.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-missing-package.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-package-extract-trigger.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-package-released.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-qebhwt-trigger.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-solved-package.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-unresolved-package.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-unrevsolved-package.yaml
  odh/overlays/moc/kafka/overrides/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
  odh/overlays/quicklab/kafka/kustomization.yaml
  odh/overlays/quicklab/kafka/overrides/kafka/overlays/topics/example-topic.yaml
  odh/overlays/quicklab/kafka/overrides/kafka/overlays/topics/kustomization.yaml
Labels: approved, size/M
