Repository operate-first/apps, pull requests merged in 2021-07, with the labels that each got.

#823 add opf-trino to kfdefs kustomization
  kfdefs/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/XS

#824 Update thoth grafana dashboards CRDs
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
Labels: approved, lgtm, size/XS

#825 Add custom quotas for superset/trino
  cluster-scope/base/core/namespaces/opf-superset/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-superset/resourcequota.yaml
  cluster-scope/base/core/namespaces/opf-trino/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
Labels: approved, lgtm, size/S

#826 feat(slack-first): Enable github issues to be assigned to oncall
  slack-first/overlays/moc/zero/config.yaml
  slack-first/overlays/moc/zero/secret.enc.yaml
Labels: approved, lgtm, size/S

#812 update kafka onboarding docs
  docs/odh/kafka/README.md
  docs/odh/kafka/add_kafka_topics.md
  docs/odh/kafka/add_kafka_users.md
Labels: approved, lgtm, size/M

#829 Add user to argocd readonly group
  cluster-scope/overlays/prod/common/groups/argocd-readonly.enc.yaml
Labels: approved, lgtm, size/XS

#830 Add readonly group to clusters
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/common/secret-generator.yaml
Labels: lgtm, size/XS

#831 Remove rgw thanos obc that is not needed.
  observatorium/overlays/moc/zero/objectbucketclaims/kustomization.yaml
  observatorium/overlays/moc/zero/objectbucketclaims/thanos-obc.yaml
Labels: approved, lgtm, size/XS

#827 Add cpu usage dashboard to grafana.
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cpu_usage.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/kustomization.yaml
Labels: approved, lgtm, size/XL

#821 Expose Prometheus metrics for Vector
  vector/base/deployment.yaml
  vector/overlays/moc/zero/opf-observatorium/configmap.yaml
  vector/overlays/moc/zero/opf-observatorium/kustomization.yaml
  vector/overlays/moc/zero/opf-observatorium/service.yaml
Labels: approved, lgtm, size/M

#828 enlist metrics job based on service requirement
  kfdefs/overlays/moc/zero/opf-monitoring/scrape-configs/additional-scrape-configs.yaml
Labels: approved, lgtm, size/M

#834 Add cloudbeawever deployment to opf-trino in zero cluster.
  cloudbeaver/base/deployment.yaml
  cloudbeaver/base/kustomization.yaml
  cloudbeaver/base/persistentvolumeclaim.yaml
  cloudbeaver/base/route.yaml
  cloudbeaver/base/service.yaml
  cloudbeaver/overlays/moc/zero/add_configs.yaml
  cloudbeaver/overlays/moc/zero/configs/cloudbeaver.conf
  cloudbeaver/overlays/moc/zero/configs/initial-data-sources.conf
  cloudbeaver/overlays/moc/zero/configs/initial-data.conf
  cloudbeaver/overlays/moc/zero/configs/product.conf
  cloudbeaver/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm

#836 Add cluster-monitoring-config
  cluster-scope/overlays/prod/moc/zero/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#832 deprecate the thoth servicemonitor as scrapeconfig will be used
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/thoth-station-servicemonitor.yaml
Labels: approved, lgtm, size/S

#843 added group authorization for kafka user
  odh-manifests/kafka/overlays/users/audio-decoder.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#844 feat: Onboard Meteor
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
  cluster-scope/base/core/namespaces/aicoe-meteor/namespace.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#838 feat: Deploy Keycloak
  cluster-scope/base/core/namespaces/dex/kustomization.yaml
  cluster-scope/base/core/namespaces/dex/namespace.yaml
  cluster-scope/base/core/namespaces/keycloak/kustomization.yaml
  cluster-scope/base/core/namespaces/keycloak/namespace.yaml
  cluster-scope/base/core/namespaces/opf-auth/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/keycloak/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/keycloak/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rhsso-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rhsso-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
  dex/README.md
  dex/base/dex-clients.yaml
  dex/base/dex-cm.yaml
  dex/base/dex-deployment.yaml
  dex/base/dex-route.yaml
  dex/base/dex-sa-token.yaml
  dex/base/dex-sa.yaml
  dex/base/dex-service.yaml
  dex/base/kustomization.yaml
  dex/overlays/dev/dex-cm.yaml
  dex/overlays/dev/kustomization.yaml
  dex/overlays/moc/zero/dex-clients.enc.yaml
  dex/overlays/moc/zero/dex-cm.yaml
  dex/overlays/moc/zero/kustomization.yaml
  dex/overlays/moc/zero/secret-generator.yaml
  keycloak/README.md
  keycloak/base/keycloak.yaml
  keycloak/base/kustomization.yaml
  keycloak/overlays/moc/infra/.sops.yaml
  keycloak/overlays/moc/infra/kustomization.yaml
  keycloak/overlays/moc/infra/realm.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
  yamllint-config.yaml
Labels: approved, lgtm, size/L

#845 Add superset image and update trino config to match live.
  kfdefs/base/trino/kfdef.yaml
  kfdefs/overlays/moc/zero/opf-superset/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
  odh-manifests/trino/base/hive-config.yaml
Labels: approved, lgtm, size/L

#849 Added a stream for BU Computer Science online Juypter-book course mat…
  kfdefs/base/jupyterhub/notebook-images/bu-cs-jupyterbook.yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/M

#846 Remove relabeling commits to match live.
  kfdefs/base/monitoring/blackbox-exporter/probe.yaml
Labels: approved, lgtm, size/XS

#851 feat: diverge localstorage for Zero and Rick
  local-storage/base/kustomization.yaml
  local-storage/base/localstorage.yaml
  local-storage/overlays/emea/rick/kustomization.yaml
  local-storage/overlays/emea/rick/localvolumeset.yaml
  local-storage/overlays/moc/zero/kustomization.yaml
  local-storage/overlays/moc/zero/localstorage.yaml
Labels: approved, lgtm, size/M

#850 Add new user to slack-first members
  slack-first/overlays/moc/zero/config.yaml
Labels: approved, lgtm, size/XS

#856 Update grafana dashbaord for cpu usage in zero cluster.
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cpu_usage.yaml
Labels: approved, lgtm, size/XXL

#857 remove ray-odh-integration project namespace
  cluster-scope/base/core/namespaces/ray-odh-integration/kustomization.yaml
  cluster-scope/base/core/namespaces/ray-odh-integration/namespace.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
  kfdefs/base/jupyterhub/kustomization.yaml
Labels: approved, lgtm, size/S

#854 feat: seed Rick's cluster resources and enable SSO
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage-zj22x/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage-zj22x/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-storage-24n7x/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-storage-24n7x/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/openshift-local-storage-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/openshift-local-storage-operator/subscription.yaml
  cluster-scope/overlays/prod/emea/rick/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/rick/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/rick/secret-generator.yaml
  cluster-scope/overlays/prod/emea/rick/subscriptions/local-storage-operator_patch.yaml
  cluster-scope/overlays/prod/emea/rick/subscriptions/ocs-operator_patch.yaml
  cluster-scope/overlays/prod/moc/common/alertmanager-main-secret.yaml
  keycloak/overlays/moc/infra/clients/rick.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: approved, lgtm, size/L

#859 feat: Double memory quota for Pulp
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Labels: approved, lgtm, size/XS

#858 Disable sending logs Elasticsearch and send logs to Loki
  cluster-logging/base/clusterlogging.yaml
  cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml
  observatorium/base/instance/grafana.yaml
  observatorium/overlays/moc/zero/grafana-data-sources/kustomization.yaml
  observatorium/overlays/moc/zero/grafana-data-sources/opf-moc-zero-loki-source.yaml
  observatorium/overlays/moc/zero/routes/grafana-oauth-proxy.yaml
  observatorium/overlays/moc/zero/routes/kustomization.yaml
  vector/overlays/moc/zero/opf-observatorium/configmap.yaml
Labels: approved, lgtm, size/L

#861 Remove curator configmap since we are not using ES anymore
  cluster-logging/overlays/moc/zero/configmaps/curator.yaml
  cluster-logging/overlays/moc/zero/configmaps/kustomization.yaml
  cluster-logging/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#860 feat: Add Augur as external service to JH
  kfdefs/base/jupyterhub/external-services/augur.yaml
  kfdefs/base/jupyterhub/external-services/kustomization.yaml
  kfdefs/base/jupyterhub/kustomization.yaml
Labels: approved, lgtm, size/S

#863 connect infra cluster to nfs server
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
  cluster-scope/overlays/prod/moc/infra/storageclasses/moc-nfs-csi_patch.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/secret-generator.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Labels: lgtm, size/L

#865 add missing nodenetworkconfigurationpolicy
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#866 Increase cluster-monitoring storage size to 150Gi
  cluster-scope/overlays/prod/moc/zero/configmaps/cluster-monitoring-config.yaml
Labels: approved, lgtm, size/XS

#867 Increase keycloak resource allotment on infra.
  keycloak/base/keycloak.yaml
Labels: approved, lgtm, size/XS

#869 upgrade thoth-station grafana dashboards
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: approved, lgtm, size/XS

#868 feat: Added group sre with role cluster-reader to all clusters
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sre/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/sre/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
  cluster-scope/base/user.openshift.io/groups/sre/kustomization.yaml
  cluster-scope/overlays/prod/common/groups/sre.enc.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#870 Add service monitor for meteor
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/meteor-servicemonitor.yaml
Labels: approved, lgtm, size/S

#871 fix: add sre to secret generator
  cluster-scope/overlays/prod/common/secret-generator.yaml
Labels: approved, lgtm, size/XS
