Repository operate-first/apps, pull requests merged in 2021-05, with the labels that each got.

#589 update the thoth quota resources with requests setting
  cluster-scope/base/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-backend-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-frontend-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-graph-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-middletier-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-test-core/resourcequota.yaml
Labels: approved, lgtm, size/S

#590 chore: Remove martin from reviewers so he's not flooded by notifications
  OWNERS
Labels: approved, lgtm, size/XS

#591 fix typo in metallb configuration
  metallb/overlays/moc/zero/config.yaml
Labels: approved, lgtm, size/XS

#592 fix: Upgrade observatorium to solve memcached OOMKilled
  cluster-scope/base/clusterrolebindings/scc-anyuid-observatorium/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/scc-anyuid-observatorium/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  observatorium/base/instance/observatorium.yaml
  observatorium/base/operator/deployment.yaml
Labels: approved, lgtm, size/M

#572 Enable monitoring on a namespace
  .pre-commit-config.yaml
  docs/odh/prometheus/add_service_monitoring.md
  scripts/enable-monitoring.sh
Labels: approved, lgtm, size/M

#593 feat: Add data-science to viewers on opf-monitoring
  cluster-scope/base/namespaces/opf-monitoring/kustomization.yaml
  cluster-scope/components/project-view-rolebindings/data-science/kustomization.yaml
  cluster-scope/components/project-view-rolebindings/data-science/rbac.yaml
Labels: approved, lgtm, size/S

#595 Onboard user.
  cluster-scope/base/groups/team-pixel/group.yaml
  cluster-scope/base/groups/team-pixel/kustomization.yaml
  cluster-scope/base/namespaces/pixel-demos/kustomization.yaml
  cluster-scope/base/namespaces/pixel-demos/namespace.yaml
  cluster-scope/base/namespaces/pixel-vault/kustomization.yaml
  cluster-scope/base/namespaces/pixel-vault/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/team-pixel/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/team-pixel/rbac.yaml
  cluster-scope/overlays/moc/common/groups/team-pixel.enc.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#596 Add team-pixel grp to common.
  cluster-scope/overlays/moc/common/kustomization.yaml
Labels: approved, lgtm, size/XS

#594 Apicurio, added ServiceMonitor
  cluster-scope/base/namespaces/apicurio-apicurio-registry/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/apicurio-registry-servicemonitor.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/S

#598 Add custom elyera image for frequent upgrades.
  kfdefs/base/jupyterhub/notebook-images/experimental-elyra-notebook-imagestream.yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, lgtm, size/S

#599 Rename endpoint.name to endpoint.port for apicurio-monitor.
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/apicurio-registry-servicemonitor.yaml
Labels: approved, lgtm, size/XS

#615 enable thoth-devops group to view the opf-monitoring grafana dashboard
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
Labels: approved, lgtm, size/XS

#616 Change quarkus-extension-registry quota to large
  cluster-scope/base/namespaces/quarkus-extension-registry/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#613 Add network interfaces for access to nfs server
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
Labels: approved, lgtm, size/M

#617 swap interfaces for storage connection
  cluster-scope/overlays/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
Labels: approved, lgtm, size/S

#614 feature/democratic csi
  cluster-scope/base/clusterrolebindings/moc-nfs-democratic-csi-controller-rb/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/moc-nfs-democratic-csi-controller-rb/kustomization.yaml
  cluster-scope/base/clusterrolebindings/moc-nfs-democratic-csi-node-rb/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/moc-nfs-democratic-csi-node-rb/kustomization.yaml
  cluster-scope/base/clusterroles/moc-nfs-democratic-csi-controller-cr/clusterrole.yaml
  cluster-scope/base/clusterroles/moc-nfs-democratic-csi-controller-cr/kustomization.yaml
  cluster-scope/base/clusterroles/moc-nfs-democratic-csi-node-cr/clusterrole.yaml
  cluster-scope/base/clusterroles/moc-nfs-democratic-csi-node-cr/kustomization.yaml
  cluster-scope/base/csidrivers/org.democratic-csi.nfs/csidriver.yaml
  cluster-scope/base/csidrivers/org.democratic-csi.nfs/kustomization.yaml
  cluster-scope/base/namespaces/democratic-csi/kustomization.yaml
  cluster-scope/base/namespaces/democratic-csi/namespace.yaml
  cluster-scope/base/storageclasses/moc-nfs-csi/kustomization.yaml
  cluster-scope/base/storageclasses/moc-nfs-csi/storageclass.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  moc-nfs-democratic-csi/base/apps/daemonsets/moc-nfs-democratic-csi-node.yaml
  moc-nfs-democratic-csi/base/apps/deployments/moc-nfs-democratic-csi-controller.yaml
  moc-nfs-democratic-csi/base/core/secrets/controller-expand-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/controller-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/node-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/node-stage-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/provisioner-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/serviceaccounts/moc-nfs-democratic-csi-controller-sa.yaml
  moc-nfs-democratic-csi/base/core/serviceaccounts/moc-nfs-democratic-csi-node-sa.yaml
  moc-nfs-democratic-csi/base/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/zero/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/zero/secret-generator.yaml
  moc-nfs-democratic-csi/overlays/moc/zero/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Labels: approved, lgtm, size/XL

#618 fix openshift-cnv namespace
  cluster-scope/base/namespaces/openshift-cnv/namespace.yaml
Labels: approved, lgtm, size/XS

#623 chore: Move CLO PVCs from OCS to NFS and downsize
  cluster-logging/base/clusterlogging.yaml
Labels: approved, lgtm, size/XS

#625 fix: Remove Kubeflow kfdef for now
  kubeflow-components/base/kustomization.yaml
Labels: approved, lgtm, size/XS

#624 chore: Move Kafka PVCs from OCS to NFS and downsize
  odh-manifests/kafka/base/kafka-cluster.yaml
Labels: approved, lgtm, size/XS

#611 Upgrade ODH to v1.0.11
  kfdefs/base/argo/kfdef.yaml
  kfdefs/base/dashboard/kfdef.yaml
  kfdefs/base/datacatalog/kfdef.yaml
  kfdefs/base/jupyterhub/kfdef.yaml
  kfdefs/base/kafka/kfdef.yaml
  kfdefs/base/monitoring/kfdef.yaml
  kfdefs/base/superset/kfdef.yaml
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
Labels: approved, size/M

#633 fix/scripts for adr0015
  scripts/common.sh
  scripts/enable-monitoring.sh
  scripts/onboarding.sh
  scripts/tests/test-enable-monitoring.bats
  scripts/tests/test-onboarding.bats
Labels: approved, lgtm, size/L

#638 Add Oauth proxy for Thanos Query Frontend
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml
  observatorium/base/instance/kustomization.yaml
  observatorium/base/instance/thanos-routes.yaml
  observatorium/overlays/moc/zero/deployments/kustomization.yaml
  observatorium/overlays/moc/zero/deployments/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/kustomization.yaml
  observatorium/overlays/moc/zero/routes/kustomization.yaml
  observatorium/overlays/moc/zero/routes/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/serviceaccounts/kustomization.yaml
  observatorium/overlays/moc/zero/serviceaccounts/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/services/kustomization.yaml
  observatorium/overlays/moc/zero/services/thanos-query-frontend-oauth-proxy.yaml
Labels: approved, lgtm, size/L

#640 fix serviceaccount name for thanos oauth proxy
  observatorium/overlays/moc/zero/deployments/thanos-query-frontend-oauth-proxy.yaml
Labels: approved, lgtm, size/XS

#643 update argocd update_cluster_resources.sh script for new repo layout
  scripts/argocd/update_cluster_resources.sh
Labels: approved, lgtm, size/S

#628 Acme operator
  acme-operator/base/deployment.yaml
  acme-operator/base/kustomization.yaml
  acme-operator/base/serviceaccount.yaml
  acme-operator/overlays/dev/issuer-letsencrypt-staging.yaml
  acme-operator/overlays/dev/kustomization.yaml
  acme-operator/overlays/moc/zero/issuer-letsencrypt-live.yaml
  acme-operator/overlays/moc/zero/kustomization.yaml
  cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/acme-operator/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/acme-operator/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/acme-operator/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/acme-operator/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  docs/issuing_certificates.md
Labels: approved, lgtm, size/L

#645 fix: Allow ACME operator namespace in argocd
  argocd/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, lgtm, size/XS

#644 use curl instead of both wget and curl in the same script
  scripts/argocd/update_cluster_resources.sh
Labels: approved, lgtm

#646 Add OAuth Proxy for Loki query frontend endpoint
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml
  observatorium/base/instance/kustomization.yaml
  observatorium/base/instance/loki-routes.yaml
  observatorium/overlays/moc/zero/deployments/kustomization.yaml
  observatorium/overlays/moc/zero/deployments/loki-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/kustomization.yaml
  observatorium/overlays/moc/zero/rolebindings/kustomization.yaml
  observatorium/overlays/moc/zero/rolebindings/opf-observatorium-view.yaml
  observatorium/overlays/moc/zero/roles/kustomization.yaml
  observatorium/overlays/moc/zero/roles/opf-observatorium-view.yaml
  observatorium/overlays/moc/zero/routes/kustomization.yaml
  observatorium/overlays/moc/zero/routes/loki-distributor.yaml
  observatorium/overlays/moc/zero/routes/loki-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/serviceaccounts/kustomization.yaml
  observatorium/overlays/moc/zero/serviceaccounts/loki-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/zero/services/kustomization.yaml
  observatorium/overlays/moc/zero/services/loki-query-frontend-oauth-proxy.yaml
Labels: approved, lgtm, size/L

#647 fix: ACME quota for HA
  cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#650 Move image registry pv to nfs storage
  cluster-scope/base/core/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml
Labels: approved, lgtm, size/XS

#651 Remove image registry pvc storage patch from zero, unneeded.
  cluster-scope/overlays/moc/zero/imageregistryconfigs/image-registry-storage_patch.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/XS

#652 Change default storageclass for moc/zero to moc-nfs-csi
  cluster-scope/base/storage.k8s.io/storageclasses/ocs-storagecluster-cephfs/storageclass.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/storageclasses/moc-nfs-csi_patch.yaml
Labels: approved, lgtm, size/XS

#654 Update Jupyterhub StorageClass to moc-nfs-csi
  kfdefs/overlays/moc/zero/opf-jupyterhub/kustomization.yaml
Labels: approved, lgtm, size/XS

#653 Quota setup for the opf prow and pipelines
  cluster-scope/base/core/namespaces/opf-ci-pipelines/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml
  cluster-scope/base/core/namespaces/opf-ci-prow/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
Labels: approved, lgtm, size/S

#648 Update docs as per adr 15.
  cluster-scope/README.md
  docs/cluster-scope/add_resource_quotas.md
Labels: approved, lgtm, size/M

#619 Add jupyterhub-idle-culler
  jupyterhub-idle-culler/base/buildconfig.yaml
  jupyterhub-idle-culler/base/deploymentconfig.yaml
  jupyterhub-idle-culler/base/imagestream.yaml
  jupyterhub-idle-culler/base/kustomization.yaml
  jupyterhub-idle-culler/overlays/moc/zero/.sops.yaml
  jupyterhub-idle-culler/overlays/moc/zero/deploymentconfig_patch.yaml
  jupyterhub-idle-culler/overlays/moc/zero/kustomization.yaml
  jupyterhub-idle-culler/overlays/moc/zero/secrets/secret-generator.yaml
  jupyterhub-idle-culler/overlays/moc/zero/secrets/secret.enc.yaml
Labels: approved, lgtm, size/L

#656 Add missing patch fields for idle culler.
  jupyterhub-idle-culler/overlays/moc/zero/deploymentconfig_patch.yaml
Labels: size/XS

#657 use https instead of http for truenas api access
  moc-nfs-democratic-csi/overlays/moc/zero/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Labels: approved, lgtm, size/XS

#655 feat: add Apicurio to viewers on opf-monitoring
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
Labels: approved, do-not-merge/hold, lgtm, ok-to-test, size/XS

#660 update the prow resource limits
  .prow.yaml
Labels: approved, lgtm, size/S

#658 Onboard sigstore to zero cluster.
  cluster-scope/base/core/namespaces/sigstore-deploy/kustomization.yaml
  cluster-scope/base/core/namespaces/sigstore-deploy/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/sigstore/group.yaml
  cluster-scope/base/user.openshift.io/groups/sigstore/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sigstore/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sigstore/rbac.yaml
  cluster-scope/overlays/moc/common/groups/sigstore.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#659 Create an odh admins group with access to odh namespaces.
  cluster-scope/base/core/namespaces/opendatahub-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-argo/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-dashboard/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-jupyterhub-stage/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-kafka/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-monitoring/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-superset/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-trino/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
  cluster-scope/base/user.openshift.io/groups/odh-admin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/odh-admin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/odh-admin/rbac.yaml
  cluster-scope/overlays/moc/common/groups/odh-admin.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
Labels: approved, lgtm, size/L

#662 Expand thanos receive pvc
  observatorium/base/instance/observatorium.yaml
Labels: approved, lgtm, size/M

#665 Remove the pod limit for the ofp-ci-pipelines
  cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml
Labels: approved, lgtm, size/XS

#666 Give apicurio team permissions to access loki
  observatorium/overlays/moc/zero/rolebindings/opf-observatorium-view.yaml
Labels: approved, lgtm, size/XS

#661 feat: Onboard CCX to openshift-insights namespace
  cluster-scope/base/core/namespaces/openshift-insights/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/ccx/group.yaml
  cluster-scope/base/user.openshift.io/groups/ccx/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ccx/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ccx/rbac.yaml
  cluster-scope/overlays/moc/common/groups/ccx.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#670 Add data-science team to the opf-observatorium-view rolebinding
  observatorium/overlays/moc/zero/rolebindings/opf-observatorium-view.yaml
Labels: approved, lgtm, size/XS

#667 Connect grafana to openshift-monitoring Prometheus
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-openshift-monitoring-grafanadatasource.enc.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/secrets-generator.yaml
Labels: approved, lgtm, size/M

#668 Deploy odh google spark operator to zero cluster.
  cluster-scope/base/core/namespaces/opf-google-spark-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-google-spark-operator/namespace.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  kfdefs/base/google-spark-operator/kfdef.yaml
  kfdefs/base/google-spark-operator/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-google-spark-operator/kustomization.yaml
Labels: approved, lgtm, size/M

#672 Add google spark operator to root kfdef.
  kfdefs/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/XS

#673 Increase system reserved memory for worker nodes
  cluster-scope/overlays/moc/zero/kubeletconfigs/increase-worker-system-reserved-memory.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#664 feat: Add Pulp via OLM
  cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/catalogsource.yaml
  cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/pulp-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/pulp-operator/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#642 add spark operator and sdap customer resource definition
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/gitbasedconfigs.sdap.apache.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/gitbasedconfigs.sdap.apache.org/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-admin/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-edit/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-edit/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-view/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/sdap-aggregate-to-view/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, needs-ok-to-test, size/L

#675 switch the targetport with port name for thoth service monitor
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/thoth-station-servicemonitor.yaml
Labels: approved, lgtm, size/XS

#677 Increase Kafka broker PVC size
  odh-manifests/kafka/base/kafka-cluster.yaml
Labels: approved, lgtm, size/XS

#678 setting up namespace for pulp setup experiment
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/kustomization.yaml
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/namespace.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#679 Switch all Subscriptions to automatic approval
  cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/kubevirt-hyperconverged/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/local-storage-operator/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/metering-operator/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/ocs-operator/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/serverless-operator/subscription.yaml
Labels: approved, lgtm, size/S

#680 fix(#678): Pulp experiments requester
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/namespace.yaml
Labels: approved, lgtm, size/XS

#682 feat(thoth-pupl-experiments): Update quota
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/kustomization.yaml
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Labels: approved, lgtm, size/S

#578 Add blackbox exporter
  kfdefs/base/monitoring/blackbox-exporter/blackbox-prober-config.yaml
  kfdefs/base/monitoring/blackbox-exporter/blackbox-service.yaml
  kfdefs/base/monitoring/blackbox-exporter/blackbox.yaml
  kfdefs/base/monitoring/blackbox-exporter/es-secret-generator.yaml
  kfdefs/base/monitoring/blackbox-exporter/es-secret.enc.yaml
  kfdefs/base/monitoring/blackbox-exporter/kustomization.yaml
  kfdefs/base/monitoring/blackbox-exporter/probe.yaml
  kfdefs/base/monitoring/kustomization.yaml
Labels: approved, lgtm, size/L

#684 increase ray node mem to 3Gi, idle-timeout to 30min
  kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
Labels: approved, lgtm, size/XS

#683 update to latest ray nightly wheel, update RayCluster CRD
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.cluster.ray.io/customresourcedefinition.yaml
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
Labels: approved, lgtm, size/M

#685 overlays/infra: Increase system reserved memory for worker nodes
  cluster-scope/overlays/moc/infra/kubeletconfigs/increase-worker-system-reserved-memory.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/S

#686 fix(blackbox-exporter): Secret generator is not a resource
  kfdefs/base/monitoring/blackbox-exporter/kustomization.yaml
Labels: approved, lgtm, size/XS

#687 fix(blackbox-exporter): Secret is not base64 encoded
  kfdefs/base/monitoring/blackbox-exporter/es-secret.enc.yaml
Labels: approved, lgtm, size/S

#688 expose ray dashboard
  kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
Labels: approved, lgtm, size/S

#689 fix blackbox prober secret name
  kfdefs/base/monitoring/blackbox-exporter/blackbox.yaml
  odh-manifests/prometheus/operator/base/prometheus.yaml
Labels: approved, lgtm, size/XS

#690 Add spark3.0.1 notebook image
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
Labels: approved, lgtm, needs-ok-to-test, size/S
