Repository operate-first/apps, pull requests merged in 2021-04, with the labels that each got.

#464 parameterized the set-odh-release script to take in tag
  scripts/set-odh-release.sh
Labels: approved, lgtm, size/XS

#470 fix: Observatorium Grafana image
  observatorium/base/instance/grafana.yaml
Labels: approved, lgtm, size/XS

#473 Update shan PVC to 16Gi
  odh/overlays/moc/zero/jupyterhub/pvcs/user-shan-pvc.enc.yaml
Labels: approved, lgtm, size/XS

#472 fix: Lower CPU request on openshift-logging
  cluster-logging/base/clusterlogging.yaml
Labels: approved, lgtm, size/XS

#474 sync up with upstream opendatahub odh-manifests
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, size/M

#476 support jupyter book in the jupyter notebook image
  odh/base/jupyterhub/notebook-images/jupyterbook-test.yaml
  odh/base/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, lgtm, size/S

#475 Fix onboarding sdap team
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: lgtm, size/XS

#478 Onboard uky-redhat team
  cluster-scope/base/groups/uky-redhat/group.yaml
  cluster-scope/base/groups/uky-redhat/kustomization.yaml
  cluster-scope/base/namespaces/uky-hpc-workload-generator/kustomization.yaml
  cluster-scope/base/namespaces/uky-hpc-workload-generator/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/uky-redhat/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/uky-redhat/rbac.yaml
  cluster-scope/overlays/moc/common/groups/uky-redhat.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#479 feat: Add ODH Trino
  cluster-scope/base/namespaces/opf-trino/kustomization.yaml
  cluster-scope/base/namespaces/opf-trino/namespace.yaml
  cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#477 Add apicurio namespace
  cluster-scope/base/groups/apicurio/group.yaml
  cluster-scope/base/groups/apicurio/kustomization.yaml
  cluster-scope/base/namespaces/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/base/namespaces/apicurio-apicurio-registry/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/apicurio/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/apicurio/rbac.yaml
  cluster-scope/overlays/moc/common/groups/apicurio.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/L

#480 fix: uky-redhat member username
  cluster-scope/overlays/moc/common/groups/uky-redhat.enc.yaml
Labels: approved, lgtm, size/M

#481 Add 10Gi PVCs to kafka and zookeeper
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: lgtm, size/XS

#486 updated namespace yaml to set label
  cluster-scope/base/namespaces/tufts-dcc-6/namespace.yaml
Labels: approved, ok-to-test, size/XS

#484 feat: Add manifests for slack-first bot
  slack-first/base/configmap.yaml
  slack-first/base/deployment.yaml
  slack-first/base/kustomization.yaml
  slack-first/base/route.yaml
  slack-first/base/secret.yaml
  slack-first/base/service.yaml
  slack-first/overlays/moc/zero/config.yaml
  slack-first/overlays/moc/zero/kustomization.yaml
  slack-first/overlays/moc/zero/secret-generator.yaml
  slack-first/overlays/moc/zero/secret.enc.yaml
Labels: approved, lgtm, size/L

#449 subscribe curator cluster to container storage operator
  cluster-scope/overlays/moc/curator/kustomization.yaml
  cluster-scope/overlays/moc/curator/subscriptions/ocs-operator_patch.yaml
Labels: approved, lgtm, size/S

#489 Update izi PVC to 16Gi
  odh/overlays/moc/zero/jupyterhub/pvcs/user-izim-pvc.enc.yaml
Labels: approved, lgtm, size/S

#490 Add clusterlogforwarder to forward app-logs to kafka
  cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml
  cluster-logging/overlays/moc/zero/clusterlogforwarders/kustomization.yaml
  cluster-logging/overlays/moc/zero/kustomization.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
Labels: approved, size/M

#491 Add clusterlogforwarder to operate-first proj.
  argocd/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, lgtm, size/XS

#492 fix: Lab-CICD group populate
  cluster-scope/overlays/moc/common/secret-generator.yaml
Labels: approved, lgtm, size/XS

#497 chore: Reorder oncall schedule
  slack-first/overlays/moc/zero/config.yaml
Labels: approved, lgtm, size/XS

#494 fix: Thoth devops group not propagated properly
  cluster-scope/overlays/moc/common/secret-generator.yaml
Labels: approved, lgtm, size/XS

#493 feat: Create namespace for Pulp operator
  cluster-scope/base/groups/pulp/group.yaml
  cluster-scope/base/groups/pulp/kustomization.yaml
  cluster-scope/base/namespaces/pulp-operator/kustomization.yaml
  cluster-scope/base/namespaces/pulp-operator/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/pulp/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/pulp/rbac.yaml
  cluster-scope/overlays/moc/common/groups/pulp.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/M

#488 Add instructions on adding resource quotas.
  docs/cluster-scope/add_resource_quotas.md
Labels: approved, lgtm, size/M

#505 Upgrade ODH to v1.0.8
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, size/M

#508 update kubeflow url
  docs/kubeflow/kubeflow-pipelines/README.md
Labels: approved, lgtm, size/XS

#509 Update Cluster Logging Application Topic Name
  cluster-logging/overlays/moc/zero/clusterlogforwarders/clusterlogforwarder.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
  vector/overlays/moc/zero/opf-observatorium/configmap.yaml
Labels: approved, size/XS

#510 Increase Kafka PVC to 30Gi
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: approved, size/XS

#499 chore: Add list of team GPG keys and where to find them
  cluster-scope/overlays/moc/README.md
  cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
Labels: approved, size/L

#512 update loki from v1.6.1 to v2.2.0
  observatorium/base/instance/observatorium.yaml
Labels: approved, size/XS

#513 Increase kafka pvc to 100Gi
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: lgtm, size/XS

#515 set retention time for thoth kafka messages to 1 day
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-advise-justification.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-re-run.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-hash-mismatch.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-kebechet-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package-version.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-extract-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-released.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-qebhwt-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-solved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unresolved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unrevsolved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
Labels: lgtm, size/M

#517 Increase Kafka PVC size to 200Gi
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: approved

#487 Add security context tufts dcc 6
  cluster-scope/base/clusterrolebindings/scc-anyuid-tufts-dcc-6/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/scc-anyuid-tufts-dcc-6/kustomization.yaml
  cluster-scope/base/clusterrolebindings/scc-privileged-tufts-dcc-6/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/scc-privileged-tufts-dcc-6/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/M

#518 Change cluster logs message retention period to 6 hours
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
Labels: approved, size/XS

#506 Onboard Apicurio on ArgoCD
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
Labels: approved, needs-ok-to-test, size/M

#507 Add quotas to opf-* namespaces
  cluster-scope/base/namespaces/opf-alertreceiver/kustomization.yaml
  cluster-scope/base/namespaces/opf-argo/kustomization.yaml
  cluster-scope/base/namespaces/opf-auth/kustomization.yaml
  cluster-scope/base/namespaces/opf-ci-test-pods/kustomization.yaml
  cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml
  cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
  cluster-scope/base/namespaces/opf-slack-first/kustomization.yaml
  cluster-scope/base/namespaces/opf-superset/kustomization.yaml
  cluster-scope/base/namespaces/opf-trino/kustomization.yaml
  cluster-scope/components/resourcequotas/x-small/kustomization.yaml
  cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml
Labels: approved, lgtm, size/M

#521 Incrase opf-datacatalog quota to custom quota.
  cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
  cluster-scope/base/namespaces/opf-datacatalog/resourcequota.yaml
Labels: approved, lgtm, size/S

#520 Add spark operator in opf-jupyterhub namespace
  odh/base/jupyterhub/kfdef.yaml
Labels: approved, lgtm, size/XS

#522 Remove unnecessary imgstream fields for jupyter-book.
  odh/base/jupyterhub/notebook-images/jupyterbook-test.yaml
Labels: approved, lgtm, size/XS

#523 Onboard codait-advo team
  cluster-scope/base/groups/codait-advo/group.yaml
  cluster-scope/base/groups/codait-advo/kustomization.yaml
  cluster-scope/base/namespaces/codait-advo/kustomization.yaml
  cluster-scope/base/namespaces/codait-advo/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/codait-advo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/codait-advo/rbac.yaml
  cluster-scope/overlays/moc/common/groups/codait-advo.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#422 Upgrade infra cluster to 4.6.21
  cluster-scope/overlays/moc/infra/clusterversion.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, do-not-merge/hold, lgtm, size/S

#526 feat: Add hostpath SCC for UKY
  cluster-scope/base/securitycontextconstraints/uky-hpc-workload-generator-hostpath/kustomization.yaml
  cluster-scope/base/securitycontextconstraints/uky-hpc-workload-generator-hostpath/securitycontextconstraint.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#528 added new jh image
  odh/base/jupyterhub/notebook-images/audio-decoder-demo.yaml
  odh/base/jupyterhub/notebook-images/kustomization.yaml
Labels: ok-to-test, size/S

#527 added kafka topics
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/audio-decoder-decoded-speech.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/audio-decoder-sentiment-text.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/S

#529 Fix tab issue with audio-decoder imagestream.
  odh/base/jupyterhub/notebook-images/audio-decoder-demo.yaml
Labels: approved, lgtm, size/S

#496 Do not instantiate operatorgroup with hashed name
  cluster-scope/base/operatorgroups/openshift-storage/operatorgroup.yaml
Labels: approved, lgtm, size/XS

#533 Increase thanos shard PVC size to 50 Gi
  observatorium/base/instance/observatorium.yaml
Labels: approved, size/XS

#534 Fix ordering of volumes in SCC.
  cluster-scope/base/securitycontextconstraints/uky-hpc-workload-generator-hostpath/securitycontextconstraint.yaml
Labels: approved, lgtm, size/XS

#532 [MOC] Added a new user in lab-cicd group
  cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
Labels: approved, lgtm, ok-to-test, size/L

#535 enable hostpath-provisioner on curator cluster
  cluster-scope/base/hostpathprovisioners/hostpath-provisioner/hostpathprovisioner.yaml
  cluster-scope/base/hostpathprovisioners/hostpath-provisioner/kustomization.yaml
  cluster-scope/base/namespaces/hostpath-provisioner/kustomization.yaml
  cluster-scope/base/namespaces/hostpath-provisioner/namespace.yaml
  cluster-scope/overlays/moc/curator/kustomization.yaml
  cluster-scope/overlays/moc/curator/subscriptions/kubevirt-hyperconverged_patch.yaml
Labels: approved, lgtm, size/M

#537 feature/curator hostpath provisioner
  cluster-scope/base/storageclasses/hostpath-provisioner/kustomization.yaml
  cluster-scope/base/storageclasses/hostpath-provisioner/storageclass.yaml
  cluster-scope/overlays/moc/curator/kustomization.yaml
Labels: approved, size/S

#536 Upgrade ODH to v1.0.9
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, size/M

#539 Remove JH dashboard CRs
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-sli-slo.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/kustomization.yaml
  odh/overlays/moc/zero/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
  odh/overlays/moc/zero/monitoring/dashboards/operate-first/kustomization.yaml
Labels: approved, lgtm, size/S

#540 made audio-decoder namespace public
  cluster-scope/base/namespaces/fde-audio-decoder-demo/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#541 Update Vector Config
  vector/overlays/moc/zero/opf-observatorium/configmap.yaml
Labels: approved, size/S

#538 Add machineconfig to manage selinux context for /var/hpvolumes
  cluster-scope/base/machineconfigs/hostpath-provisioner-selinux/kustomization.yaml
  cluster-scope/base/machineconfigs/hostpath-provisioner-selinux/machineconfig.yaml
  cluster-scope/overlays/moc/curator/kustomization.yaml
  cluster-scope/overlays/moc/curator/storageclasses/hostpath-provisioner.yaml
Labels: approved, lgtm, size/M

#531 feat: Add a basic script for cluster version updates
  scripts/update-cluster-version.sh
Labels: approved, lgtm, size/M

#542 Move Prometheus docs from support repo to apps repo
  docs/odh/prometheus/README.md
  docs/odh/prometheus/add_service_monitoring.md
Labels: approved, lgtm, size/M

#524 Add a simple README for Thanos
  docs/observatorium/thanos/README.md
Labels: approved, lgtm, size/S

#543 Fix Prometheus doc formatting on operate-first.cloud
  docs/odh/prometheus/add_service_monitoring.md
Labels: approved, size/S

#547 Add JH PVC for user adug
  odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-adug-pvc.enc.yaml
Labels: approved, lgtm, size/M

#549 Move Cluster Metrics Federation Service Monitor to Overrides
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
  odh-manifests/prometheus/operator/base/cluster-metrics-servicemonitor.yaml
Labels: approved, size/XS

#550 Update odh yaml paths for monitoring & topics doc.
  docs/odh/kafka/add_kafka_topics.md
  docs/odh/prometheus/add_service_monitoring.md
Labels: approved, lgtm, size/S

#551 Transfer cd repo docs to apps repo.
  argocd/cluster-resources/kustomization.yaml
  argocd/overlays/dev/configs/argo_cm/dex.config
  argocd/overlays/dev/configs/argo_cm/envs
  argocd/overlays/dev/configs/argo_cm/kustomize.buildOptions
  argocd/overlays/dev/configs/argo_cm/url
  argocd/overlays/dev/kustomization.yaml
  argocd/overlays/dev/rbac/argocd-manager-role-binding.yaml
  argocd/overlays/dev/rbac/argocd-manager-role.yaml
  argocd/overlays/dev/secrets/auth/dex-server-sa.enc.yaml
  argocd/overlays/dev/secrets/clusters/.sops.yaml
  argocd/overlays/dev/secrets/clusters/dev.cluster.example.enc.yaml
  argocd/overlays/dev/secrets/clusters/secret-generator.yaml
  docs/argocd/import_dev_gpg.md
  docs/argocd/key.asc
  docs/argocd/setup_argocd_dev_environment.md
  docs/argocd/update_argocd.md
  docs/argocd/update_gpg_key.md
  docs/ocp_dev_environments/README.md
  docs/ocp_dev_environments/assets/bundle_select.png
  docs/ocp_dev_environments/assets/cluster_information.png
  docs/ocp_dev_environments/assets/cluster_log_1.png
  docs/ocp_dev_environments/assets/cluster_log_2.png
  docs/ocp_dev_environments/assets/template_select.png
  docs/ocp_dev_environments/crc-disk-size.md
  docs/ocp_dev_environments/setup_quicklab.md
  scripts/argocd/configure_development.sh
  scripts/setup_pvs/README.md
  scripts/setup_pvs/env.yaml
  scripts/setup_pvs/playbook.yaml
  yamllint-config.yaml
Labels: approved, lgtm, size/XL

#556 fix: ODH release script after moving kfdefs
  scripts/set-odh-release.sh
Labels: approved, size/XS

#554 Update Strimzi Kafka CRs to kafka.strimzi.io/v1beta2
  odh-manifests/kafka/base/kafka-cluster.yaml
  odh-manifests/kafka/overlays/topics/audio-decoder-decoded-speech.yaml
  odh-manifests/kafka/overlays/topics/audio-decoder-sentiment-text.yaml
  odh-manifests/kafka/overlays/topics/thoth-advise-justification.yaml
  odh-manifests/kafka/overlays/topics/thoth-adviser-re-run.yaml
  odh-manifests/kafka/overlays/topics/thoth-adviser-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-hash-mismatch.yaml
  odh-manifests/kafka/overlays/topics/thoth-kebechet-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-missing-package-version.yaml
  odh-manifests/kafka/overlays/topics/thoth-missing-package.yaml
  odh-manifests/kafka/overlays/topics/thoth-package-extract-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-package-released.yaml
  odh-manifests/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-qebhwt-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml
  odh-manifests/kafka/overlays/topics/thoth-solved-package.yaml
  odh-manifests/kafka/overlays/topics/thoth-unresolved-package.yaml
  odh-manifests/kafka/overlays/topics/thoth-unrevsolved-package.yaml
  odh-manifests/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
  odh-manifests/kafka/overlays/topics/zero-cluster-app-logs.yaml
Labels: approved, lgtm, size/L

#557 feat: ODH 1.0.10 z-stream release
  kfdefs/base/argo/kfdef.yaml
  kfdefs/base/dashboard/kfdef.yaml
  kfdefs/base/datacatalog/kfdef.yaml
  kfdefs/base/jupyterhub/kfdef.yaml
  kfdefs/base/kafka/kfdef.yaml
  kfdefs/base/monitoring/kfdef.yaml
  kfdefs/base/superset/kfdef.yaml
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
Labels: approved, size/M

#559 fix: Turn subscriptions in openshift-operators to automatic
  cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
  cluster-scope/base/subscriptions/web-terminal/subscription.yaml
Labels: approved, lgtm, size/XS

#560 fix: Avoid resource name conflicts with odh-operator since it reconciles now
  cluster-scope/base/clusterrolebindings/opf-cluster-metrics-federation/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/opf-cluster-metrics-federation/kustomization.yaml
  cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/XS

#553 Update ArgoCD to v2.0.1, and update docs.
  argocd/base/kustomization.yaml
  argocd/overlays/dev/configs/argo_cm/dex.config
  argocd/overlays/dev/kustomization.yaml
  cluster-scope/base/crds/applications.argoproj.io/crd.yaml
  cluster-scope/base/crds/appprojects.argoproj.io/crd.yaml
  docs/argocd/setup_argocd_dev_environment.md
  docs/argocd/update_argocd.md
  scripts/argocd/configure_development.sh
  scripts/argocd/update_cluster_resources.sh
Labels: approved, lgtm, size/XXL

#561 fix: Argo CD image replacement and kustomize flag
  argocd/base/kustomization.yaml
  argocd/overlays/dev/configs/argo_cm/envs
  argocd/overlays/moc-infra/configs/argo_cm/envs
Labels: approved, size/XS

#562 Update argocd doc to check deployment specs.
  docs/argocd/update_argocd.md
Labels: approved, lgtm, size/XS

#564 fix: ArgoCD Cluster resource for Kubeflow
  argocd/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, lgtm, size/XS

#563 Add explicit allow list for cluster management argocd proj.
  argocd/overlays/moc-infra/projects/cluster-management.yaml
Labels: approved, lgtm, size/XS

#566 Add user to operate-first grp
  cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
Labels: lgtm, size/M

#567 Add annotations to JH images.
  kfdefs/base/jupyterhub/notebook-images/jupyterbook-test.yaml
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
Labels: approved, lgtm, size/XS

#568 Update image tag annoations for jh images.
  kfdefs/base/jupyterhub/notebook-images/jupyterbook-test.yaml
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
Labels: approved, lgtm, size/XS

#570 Update argocd dev deployment docs.
  docs/argocd/setup_argocd_dev_environment.md
Labels: approved, lgtm, size/XS

#569 Onboard quarkus team/user.
  cluster-scope/base/groups/quarkus/group.yaml
  cluster-scope/base/groups/quarkus/kustomization.yaml
  cluster-scope/base/namespaces/quarkus-extension-registry/kustomization.yaml
  cluster-scope/base/namespaces/quarkus-extension-registry/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/quarkus/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/quarkus/rbac.yaml
  cluster-scope/overlays/moc/common/groups/quarkus.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#546 Add ssh keys to zero cluster
  cluster-scope/base/machineconfigs/opf-ssh-keys/kustomization.yaml
  cluster-scope/base/machineconfigs/opf-ssh-keys/machineconfig.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
Labels: approved, lgtm, size/M

#530 feat: Upgrade Zero to 4.7.7
  cluster-scope/overlays/moc/zero/clusterversion.yaml
Labels: do-not-merge/hold, size/XS

#516 set quota limits for thoth-* namespaces
  cluster-scope/base/namespaces/thoth-amun-api-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-amun-inspection-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-backend-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-backend-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-bots-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-deployment-examples/kustomization.yaml
  cluster-scope/base/namespaces/thoth-frontend-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-frontend-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-graph-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-graph-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-infra-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-middletier-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-middletier-prod/resourcequota.yaml
  cluster-scope/base/namespaces/thoth-test-core/kustomization.yaml
  cluster-scope/base/namespaces/thoth-test-core/resourcequota.yaml
Labels: approved, lgtm, size/M

#573 Add a proxy container to grafana deployment
  odh-manifests/grafana/base/grafana.yaml
Labels: approved, lgtm, size/M

#576 Add grafana override.
  kfdefs/base/monitoring/kfdef.yaml
  odh-manifests/grafana/grafana/base/datasource.yaml
  odh-manifests/grafana/grafana/base/grafana.yaml
Labels: approved, lgtm, size/XS

#580 Add grafana proxy route
  odh-manifests/grafana/grafana/base/grafana.yaml
  odh-manifests/grafana/grafana/base/route.yaml
Labels: approved, lgtm, size/S

#577 Add openshift oauth proxy to Prometheus
  kfdefs/base/monitoring/kfdef.yaml
  odh-manifests/prometheus/operator/base/prometheus.yaml
  odh-manifests/prometheus/operator/base/route.yaml
  odh-manifests/prometheus/operator/overlays/openshift-proxy/kustomization.yaml
  odh-manifests/prometheus/operator/overlays/openshift-proxy/service.yaml
  odh-manifests/prometheus/operator/overlays/openshift-proxy/serviceaccount.yaml
Labels: approved, lgtm, size/M

#582 fix: Ommit version for HyperConverged
  kubevirt-hyperconverged/base/hyperconverged.yaml
Labels: approved, size/XS

#583 feat: Make CLO and elastic automatic
  cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
  cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
Labels: approved, size/XS

#584 Add ClusterRole/Binding to enable Opf prometheus oauth token review
  cluster-scope/base/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/oauth-token-access-review/kustomization.yaml
  cluster-scope/base/clusterroles/oauth-token-access-review/clusterrole.yaml
  cluster-scope/base/clusterroles/oauth-token-access-review/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  odh-manifests/prometheus/operator/base/prometheus.yaml
Labels: approved, size/M

#585 fix prometheus oauth configuration
  odh-manifests/prometheus/operator/base/prometheus.yaml
Labels: approved, size/XS

#586 Update Grafana to use Prometheus Proxy Route
  kfdefs/overlays/moc/zero/opf-monitoring/.sops.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-observatorium-thanos-datasource.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/opf-prom-datasource.enc.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/secrets-generator.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/roles/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/roles/opf-monitoring-view.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/grafana-datasource.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/kustomization.yaml
  odh-manifests/grafana/grafana/base/datasource.yaml
Labels: approved, size/L
