Repository operate-first/apps, pull requests merged in 2021-08, with the labels that each got.

#872 add enterprise-neurosystem group and namespace
  cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/kustomization.yaml
  cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/enterprise-neurosystem/group.yaml
  cluster-scope/base/user.openshift.io/groups/enterprise-neurosystem/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/enterprise-neurosystem/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/enterprise-neurosystem/rbac.yaml
  cluster-scope/overlays/prod/common/groups/enterprise-neurosystem.enc.yaml
  cluster-scope/overlays/prod/common/secret-generator.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#874 Resolve failing NodeNetworkConfigurationPolicy
  cluster-scope/overlays/prod/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
Labels: approved, size/XS

#876 fix: group patching
  cluster-scope/overlays/prod/common/groups/sre.enc.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm

#864 Add a limited public kafka user
  odh-manifests/kafka/overlays/secrets/opf-public-demo-user-creds.yaml
  odh-manifests/kafka/overlays/users/kustomization.yaml
  odh-manifests/kafka/overlays/users/opf-public-demo.yaml
Labels: approved, lgtm, size/M

#877 fix/failing nncp
  cluster-scope/overlays/prod/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
Labels: approved, lgtm, size/XS

#879 Add quota to koku metrics operator namespace.
  cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#880 Add servicemonitor for meteor-operator
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/meteor-operator-servicemonitor.yaml
Labels: approved, size/S, lgtm

#882 Increase hive timeout for requests.
  odh-manifests/trino/base/trino-catalog-secret.yaml
Labels: approved, size/S, lgtm

#884 update aicoe-meteor with the large quota resources
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
Labels: approved, size/XS, lgtm

#885 scrape metrics from openshift pipelines services
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/servicemonitors/openshift-pipelines-servicemonitor.yaml
Labels: size/S, lgtm

#888 Update rick oidc oauth config CA and issuer url.
  cluster-scope/overlays/prod/emea/rick/oauths/cluster_patch.yaml
Labels: approved, size/XS, lgtm

#889 Update username on rick to be lowercase.
  cluster-scope/overlays/prod/emea/rick/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#891 Add auth via dex to grafana on zero.
  dex/base/dex-sa.yaml
  dex/overlays/dev/dex-cm.yaml
  dex/overlays/moc/zero/dex-cm.yaml
  docs/observatorium/loki/README.md
  docs/odh/grafana/README.md
  docs/odh/grafana/add_permissions_to_grafana.md
  kfdefs/base/monitoring/blackbox-exporter/probe.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/secrets/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/secrets/oauth-client-secret.enc.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/secrets/secret-generator.yaml
  observatorium/base/instance/example-oauth-client-secret.enc.yaml
  observatorium/base/instance/grafana.yaml
  observatorium/base/instance/kustomization.yaml
  observatorium/overlays/moc/zero/routes/grafana-route.yaml
  observatorium/overlays/moc/zero/routes/kustomization.yaml
  observatorium/overlays/moc/zero/secrets/oauth-client-secret.enc.yaml
  observatorium/overlays/moc/zero/secrets/secret-generator.yaml
  odh-manifests/grafana/grafana/base/grafana.yaml
  odh-manifests/grafana/grafana/base/route.yaml
Labels: size/L, approved, lgtm

#892 Move grafana route to argocd management.
  kfdefs/overlays/moc/zero/opf-monitoring/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/routes/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/routes/route.yaml
Labels: approved, size/XS, lgtm

#893 Add oauth to superset and trino.
  cloudbeaver/overlays/moc/zero/configs/initial-data-sources.conf
  dex/overlays/moc/zero/dex-clients.enc.yaml
  dex/overlays/moc/zero/dex-cm.yaml
  docs/odh/grafana/map_groups_to_roles.md
  docs/odh/superset/map_groups_to_roles.md
  kfdefs/overlays/moc/zero/opf-superset/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-superset/secrets/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-superset/secrets/oauth-client-secret.enc.yaml
  kfdefs/overlays/moc/zero/opf-superset/secrets/secret-generator.yaml
  kfdefs/overlays/moc/zero/opf-superset/secure-route.yaml
  kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-trino/secrets/file-auth-secret.enc.yaml
  kfdefs/overlays/moc/zero/opf-trino/secrets/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-trino/secrets/oauth-client-secret.enc.yaml
  kfdefs/overlays/moc/zero/opf-trino/secrets/secret-generator.yaml
  kfdefs/overlays/moc/zero/opf-trino/secure-route.yaml
  odh-manifests/superset/base/deployment.yaml
  odh-manifests/superset/base/secret-superset.yaml
  odh-manifests/superset/base/secret.yaml
  odh-manifests/trino/base/trino-config-secret.yaml
  odh-manifests/trino/base/trino-coordinator-dc.yaml
Labels: size/XL, approved, lgtm

#894 Update superset oauth configs and rbac access.
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
  cluster-scope/base/user.openshift.io/groups/superset-user/kustomization.yaml
  cluster-scope/overlays/prod/common/groups/odh-admin.enc.yaml
  cluster-scope/overlays/prod/common/groups/superset-user.enc.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/common/secret-generator.yaml
  dex/overlays/moc/zero/dex-cm.yaml
  odh-manifests/superset/base/secret.yaml
Labels: size/L

#895 Add curator member.
  cluster-scope/overlays/prod/common/groups/curator.enc.yaml
Labels: approved, size/XS, lgtm

#896 Update dex superset client to contain op1st subdomain url.
  dex/overlays/moc/zero/dex-cm.yaml
Labels: approved, size/XS, lgtm

#841 chore: Migrate users to dual identity
  cluster-scope/overlays/prod/common/groups/adoptium.enc.yaml
  cluster-scope/overlays/prod/common/groups/ai-services.enc.yaml
  cluster-scope/overlays/prod/common/groups/apicurio.enc.yaml
  cluster-scope/overlays/prod/common/groups/argocd-admins.enc.yaml
  cluster-scope/overlays/prod/common/groups/argocd-readonly.enc.yaml
  cluster-scope/overlays/prod/common/groups/b4mad.enc.yaml
  cluster-scope/overlays/prod/common/groups/ccx.enc.yaml
  cluster-scope/overlays/prod/common/groups/chi-rhug.enc.yaml
  cluster-scope/overlays/prod/common/groups/cnv-testing.enc.yaml
  cluster-scope/overlays/prod/common/groups/codait-advo.enc.yaml
  cluster-scope/overlays/prod/common/groups/curator.enc.yaml
  cluster-scope/overlays/prod/common/groups/data-science.enc.yaml
  cluster-scope/overlays/prod/common/groups/enterprise-neurosystem.enc.yaml
  cluster-scope/overlays/prod/common/groups/esi-project.enc.yaml
  cluster-scope/overlays/prod/common/groups/fde.enc.yaml
  cluster-scope/overlays/prod/common/groups/lab-cicd.enc.yaml
  cluster-scope/overlays/prod/common/groups/mesh-for-data.enc.yaml
  cluster-scope/overlays/prod/common/groups/mwperf.enc.yaml
  cluster-scope/overlays/prod/common/groups/odh-admin.enc.yaml
  cluster-scope/overlays/prod/common/groups/open-aiops.enc.yaml
  cluster-scope/overlays/prod/common/groups/operate-first.enc.yaml
  cluster-scope/overlays/prod/common/groups/osc.enc.yaml
  cluster-scope/overlays/prod/common/groups/prometheus-anomaly-detector.enc.yaml
  cluster-scope/overlays/prod/common/groups/pulp.enc.yaml
  cluster-scope/overlays/prod/common/groups/quarkus.enc.yaml
  cluster-scope/overlays/prod/common/groups/ray.enc.yaml
  cluster-scope/overlays/prod/common/groups/redhat-cto-team.enc.yaml
  cluster-scope/overlays/prod/common/groups/rekor.enc.yaml
  cluster-scope/overlays/prod/common/groups/sa-dach.enc.yaml
  cluster-scope/overlays/prod/common/groups/sdap-mslsp.enc.yaml
  cluster-scope/overlays/prod/common/groups/sigstore.enc.yaml
  cluster-scope/overlays/prod/common/groups/sre.enc.yaml
  cluster-scope/overlays/prod/common/groups/team-pixel.enc.yaml
  cluster-scope/overlays/prod/common/groups/thoth-devops.enc.yaml
  cluster-scope/overlays/prod/common/groups/thoth.enc.yaml
  cluster-scope/overlays/prod/common/groups/uky-redhat.enc.yaml
  cluster-scope/overlays/prod/common/groups/workshops.enc.yaml
  cluster-scope/overlays/prod/moc/curator/groups/cluster-admins.enc.yaml
  cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.enc.yaml
  cluster-scope/overlays/prod/moc/zero/groups/cluster-admins.enc.yaml
Labels: approved, size/XXL, lgtm

#897 fix user github handles in groups
  cluster-scope/overlays/prod/common/groups/esi-project.enc.yaml
  cluster-scope/overlays/prod/common/groups/odh-admin.enc.yaml
  cluster-scope/overlays/prod/common/groups/open-aiops.enc.yaml
  cluster-scope/overlays/prod/common/groups/prometheus-anomaly-detector.enc.yaml
Labels: size/L, approved, lgtm

#899 Increase trino memory request.
  cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
  kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
Labels: approved, size/XS, lgtm

#898 Increase user's pvc size in JH
  kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/secret-generator.yaml
  kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/user-bkoz-pvc.enc.yaml
Labels: size/M, approved, lgtm

#900 Update requested memory for trino.
  cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
Labels: approved, size/XS, lgtm

#875 Add first iteration of cloud flowchart to grafana.
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/opf-cloud-flowchart.yaml
Labels: approved, size/XXL, lgtm

#840 feat: Onboard Zero cluster to Keycloak
  cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/zero/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/moc/zero/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/zero.enc.yaml
Labels: size/L, approved, lgtm

#839 feat: Onboard Infra cluster to Keycloak
  cluster-scope/overlays/prod/moc/infra/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/infra/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/moc/infra/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/infra.enc.yaml
Labels: size/L, approved, lgtm

#901 update oauth openID issuer for infra/zero cluster
  cluster-scope/overlays/prod/moc/infra/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
Labels: approved, size/XS, lgtm

#902 fix: add keycloak clients to secre-generator
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/XS, lgtm

#903 update redirect uri for infra keucloak client
  keycloak/overlays/moc/infra/clients/infra.enc.yaml
Labels: size/S, lgtm

#904 Update Infra oauth sso secret
  cluster-scope/overlays/prod/moc/infra/oauths/operate-first-sso-secret.enc.yaml
Labels: size/M, approved, lgtm

#862 Revert "feat: Add Augur as external service to JH"
  kfdefs/base/jupyterhub/external-services/augur.yaml
  kfdefs/base/jupyterhub/external-services/kustomization.yaml
  kfdefs/base/jupyterhub/kustomization.yaml
Labels: approved, size/S, lgtm

#906 fix: MOC SSO for Zero client ID
  cluster-scope/overlays/prod/moc/zero/oauths/cluster_patch.yaml
Labels: approved, size/XS, lgtm

#905 feat: Enable Operate First SSO on Curator
  cluster-scope/overlays/prod/moc/curator/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/curator/oauths/operate-first-sso-secret.enc.yaml
  keycloak/overlays/moc/infra/clients/curator.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, approved, lgtm

#908 fix: JupyterHub single user profile sizes split
  odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
  odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
Labels: size/M, approved, lgtm

#907 feat:Added openshift-pipelines operator for rick
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/subscriptions/openshift-pipelines-operator-rh_patch.yaml
Labels: approved, size/S, lgtm

#910 [EMEA/Rick] Create Namespace opf-monitoring
  cluster-scope/base/operators.coreos.com/subscriptions/prometheus-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/prometheus-operator/subscription.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/subscriptions/prometheus-operator_patch.yaml
Labels: approved, size/S, lgtm

#911 feat: Set better meteor limit range
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
  cluster-scope/base/core/namespaces/aicoe-meteor/limitrange.yaml
Labels: approved, size/S, lgtm

#912 feat: Up meteor quota limit
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
  cluster-scope/base/core/namespaces/aicoe-meteor/resourcequota.yaml
Labels: approved, size/S, lgtm

#913 Schedule trino workers to os-wrk-1 on zero.
  cluster-scope/base/core/namespaces/opf-trino/resourcequota.yaml
  kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
  odh-manifests/trino/base/trino-worker-dc.yaml
Labels: size/L, approved, lgtm

#914 Add operatorgroup for opf-monitoring
  cluster-scope/base/operators.coreos.com/operatorgroups/opf-monitoring/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/opf-monitoring/operatorgroup.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/S, lgtm

#915 Update argocd dev deployment to require less post install config.
  argocd/overlays/dev/applications/dev_app/dev-app.yaml
  argocd/overlays/dev/applications/dev_app/kustomization.yaml
  argocd/overlays/dev/applications/kustomization.yaml
  argocd/overlays/dev/configs/argo_cm/dex.config
  argocd/overlays/dev/configs/argo_rbac_cm/policy.csv
  argocd/overlays/dev/kustomization.yaml
  argocd/overlays/dev/projects/kustomization.yaml
  argocd/overlays/dev/projects/projects.yaml
  scripts/argocd/configure_development.sh
Labels: size/M, approved, lgtm

#916 Add Oauth Proxy for Thanos receive component
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review/clusterrolebinding.yaml
  observatorium/overlays/moc/zero/deployments/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/zero/routes/kustomization.yaml
  observatorium/overlays/moc/zero/routes/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/zero/serviceaccounts/kustomization.yaml
  observatorium/overlays/moc/zero/serviceaccounts/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/zero/services/kustomization.yaml
  observatorium/overlays/moc/zero/services/thanos-receive-oauth-proxy.yaml
Labels: size/M, approved, lgtm

#921 Add superset users on zero cluster.
  cluster-scope/overlays/prod/common/groups/superset-user.enc.yaml
  docs/odh/superset/add_superset_users.md
Labels: approved, size/S, lgtm

#920 feat: add Hitchhiker's guide to jupyterhub
  kfdefs/base/jupyterhub/notebook-images/hitchhikers-guide.yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S, lgtm

#925 Revert "feat: Set better meteor limit range (#911)"
  cluster-scope/base/core/namespaces/aicoe-meteor/kustomization.yaml
  cluster-scope/base/core/namespaces/aicoe-meteor/limitrange.yaml
Labels: approved, size/S, lgtm

#924 Increase storage request in thoth-pulp-experiments-custom
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Labels: approved, size/XS, lgtm

#923 Update dashboards Thoth
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
Labels: approved, size/XS, lgtm

#919 Enable Cluster monitoring on EMEA/RIck Cluster
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/.sops.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/kustomization.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/prometheus.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/secrets/kustomization.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/secrets/prometheus-k8s.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/secrets/remote-write-emea-rick-sa-token.enc.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/secrets/secret-generator.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml
  kfdefs/overlays/emea/rick/opf-monitoring/servicemonitors/kustomization.yaml
  observatorium/overlays/moc/zero/serviceaccounts/remote-write-emea-rick.yaml
Labels: size/L, approved, lgtm

#922 add external label to moc/zero prometheus
  odh-manifests/zero/prometheus/operator/base/prometheus.yaml
Labels: approved, size/XS, lgtm

#926 Change trino compute to str.
  kfdefs/overlays/moc/zero/opf-trino/kustomization.yaml
Labels: approved, size/XS, lgtm

#943 feat: Onboard DevConf.US 2021 cluster
  cluster-scope/overlays/prod/emea/devconfus2021/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/secret-generator.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/subscriptions/openshift-pipelines-operator-rh_patch.yaml
  keycloak/overlays/moc/infra/clients/devconfus2021.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
  kfdefs/overlays/emea/devconfus2021/kustomization.yaml
  kfdefs/overlays/emea/devconfus2021/opf-dashboard/kustomization.yaml
  kfdefs/overlays/emea/devconfus2021/opf-jupyterhub/kustomization.yaml
  kubeflow-components/overlays/emea/devconfus2021/kfdef.yaml
  kubeflow-components/overlays/emea/devconfus2021/kustomization.yaml
  kubeflow-components/overlays/emea/devconfus2021/profiles/demo-profile.yaml
  kubeflow-components/overlays/emea/devconfus2021/profiles/kustomization.yaml
  kubeflow-components/overlays/emea/devconfus2021/rolebindings/kubeflow-tekton-view.yaml
  kubeflow-components/overlays/emea/devconfus2021/rolebindings/kustomization.yaml
  kubeflow-components/overlays/emea/devconfus2021/roles/kubeflow-tekton-view.yaml
  kubeflow-components/overlays/emea/devconfus2021/roles/kustomization.yaml
  odh-manifests/devconfus2021/dashboard/overlays/cluster-role/kustomization.yaml
  odh-manifests/devconfus2021/dashboard/overlays/cluster-role/rbac.yaml
  odh-manifests/devconfus2021/dashboard/overlays/custom-image/deployment.yaml
  odh-manifests/devconfus2021/dashboard/overlays/custom-image/kustomization.yaml
  odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-configmap.yaml
  odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-groups-configmap.yaml
  odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
  odh-manifests/devconfus2021/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
  odh-operator/overlays/emea/devconfus2021/kustomization.yaml
Labels: size/XL, approved, lgtm

#944 update oauth client secret for devconfus2021 cluster
  keycloak/overlays/moc/infra/clients/devconfus2021.enc.yaml
Labels: approved, size/S, do-not-merge/hold, lgtm

#945 fix: Odh operator namespace missing on Devconf cluster
  cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
Labels: size/XS

#946 fix: Cleanup ODH manifests for DevConfUS
  kfdefs/overlays/emea/devconfus2021/opf-jupyterhub/kustomization.yaml
  odh-manifests/devconfus2021/dashboard/overlays/cluster-role/kustomization.yaml
  odh-manifests/devconfus2021/dashboard/overlays/cluster-role/rbac.yaml
  odh-manifests/devconfus2021/dashboard/overlays/custom-image/deployment.yaml
  odh-manifests/devconfus2021/dashboard/overlays/custom-image/kustomization.yaml
Labels: size/M, approved, lgtm

#950 feat: Convert KlusterletAddonConfigs to yaml manifests
  acm/overlays/moc/infra/klusterletaddonconfigs/alex.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/curator.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/devconfus2021.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/local-cluster.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/ocp-prod.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/osc-cl1.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/rick.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/smaug.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/zero.yaml
  acm/overlays/moc/infra/kustomization.yaml
  acm/overlays/moc/infra/provider-connections/kustomization.yaml
  acm/overlays/moc/infra/provider-connections/secret-generator.yaml
Labels: size/L, approved, lgtm

#951 feat: add user workload monitoring to devconfus2021 cluster
  cluster-scope/overlays/prod/emea/devconfus2021/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
Labels: lgtm

#956 feat: Add elyra-aidevsecops-tutorials namespace
  cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/kustomization.yaml
  cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/namespace.yaml
  cluster-scope/components/project-admin-public/kustomization.yaml
  cluster-scope/components/project-admin-public/rbac.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
Labels: size/M, approved, lgtm
