Repository operate-first/apps, pull requests merged in 2021-02, with the labels that each got.

#181 Added moc infra members to owners
  OWNERS
Labels: approved, lgtm, size/XS

#190 service monitor added for metrics scraping from thoth-deployment-examples
  odh/overlays/moc/monitoring/servicemonitors/thoth-station-servicemonitor.yaml
Labels: approved, lgtm, size/XS

#191 Add Thoth Service Metrics dashboard
  odh/overlays/moc/monitoring/dashboards/thoth-station/kustomization.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
Labels: approved, size/S

#187 Add servicemonitor to federate metrics from cluser-monitor prometheus
  odh/overlays/moc/monitoring/kustomization.yaml
  odh/overlays/moc/monitoring/secrets/kustomization.yaml
  odh/overlays/moc/monitoring/secrets/prometheus-k8s.yaml
  odh/overlays/moc/monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml
  odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
Labels: approved, lgtm, size/M

#195 Add kubeflow component namespaces
  cluster-scope/base/namespaces/cert-manager/kustomization.yaml
  cluster-scope/base/namespaces/istio-system/kustomization.yaml
  cluster-scope/base/namespaces/istio-system/namespace.yaml
  cluster-scope/base/namespaces/knative-serving/kustomization.yaml
  cluster-scope/base/namespaces/knative-serving/namespace.yaml
  cluster-scope/base/namespaces/kube-system/kustomization.yaml
  cluster-scope/base/namespaces/kubeflow/kustomization.yaml
  cluster-scope/base/namespaces/kubeflow/namespace.yaml
  cluster-scope/base/namespaces/tekton-pipelines/kustomization.yaml
  cluster-scope/base/namespaces/tekton-pipelines/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/L

#199 Add black flake people to data-science group.
  cluster-scope/overlays/moc/groups/data-science.enc.yaml
Labels: approved, lgtm, size/M

#200 Remove approved-user group
  cluster-scope/base/groups/approved-users/group.yaml
  cluster-scope/base/groups/approved-users/kustomization.yaml
  cluster-scope/overlays/moc/groups/approved-users.enc.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  cluster-scope/overlays/moc/secret-generator.yaml
Labels: approved, lgtm, size/M

#196 Add monitoring dashboards
  odh/overlays/moc/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/kustomization.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/opf-availability.yaml
Labels: approved, lgtm, monitoring, size/S

#205 feat: Onboard black-flake project to data science
  cluster-scope/base/namespaces/ds-black-flake/kustomization.yaml
  cluster-scope/base/namespaces/ds-black-flake/namespace.yaml
  cluster-scope/base/namespaces/ds-example-project/kustomization.yaml
  cluster-scope/base/namespaces/ds-example-project/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/data-science/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/data-science/rbac.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/M

#201 feat: Add a Rook/Noobaa standalone application
  ceph/README.md
  ceph/base/kustomization.yaml
  ceph/base/storagecluster.yaml
  ceph/overlays/crc/kustomization.yaml
  ceph/overlays/moc/kustomization.yaml
  ceph/overlays/quicklab/kustomization.yaml
Labels: approved, size/M

#202 feat: Add a local storage standalone application
  local-storage/README.md
  local-storage/base/kustomization.yaml
  local-storage/base/localstorage.yaml
  local-storage/overlays/crc/kustomization.yaml
  local-storage/overlays/moc/kustomization.yaml
  local-storage/overlays/moc/localstorage_patch.yaml
  local-storage/overlays/quicklab/kustomization.yaml
Labels: approved, lgtm, size/M

#203 feat: Add a kubevirt standalone application
  kubevirt-hyperconverged/README.md
  kubevirt-hyperconverged/base/hyperconverged.yaml
  kubevirt-hyperconverged/base/kustomization.yaml
  kubevirt-hyperconverged/overlays/crc/kustomization.yaml
  kubevirt-hyperconverged/overlays/moc/kustomization.yaml
  kubevirt-hyperconverged/overlays/quicklab/kustomization.yaml
Labels: approved, lgtm, size/M

#208 Add kubeflow-components
  kubeflow-components/base/kfdef.yaml
  kubeflow-components/base/kustomization.yaml
  kubeflow-components/overlays/crc/kustomization.yaml
  kubeflow-components/overlays/moc/kustomization.yaml
  kubeflow-components/overlays/quicklab/kustomization.yaml
Labels: approved, lgtm, size/M

#212 fix: Namespace for local-storage operatorgroup
  cluster-scope/base/operatorgroups/local-storage/kustomization.yaml
Labels: approved, size/XS

#194 feat: Grant cluster-logs-reader ClusterRole to user groups
  cluster-scope/base/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/cluster-logs-readers/kustomization.yaml
  cluster-scope/base/clusterroles/cluster-logs-reader/clusterrole.yaml
  cluster-scope/base/clusterroles/cluster-logs-reader/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: lgtm, size/M

#214 fix: ClusterRole api group for cluster logs reader
  cluster-scope/base/clusterroles/cluster-logs-reader/clusterrole.yaml
Labels: approved, size/XS

#218 Adjust grafana dashboards and documentation
  docs/odh/grafana/add_grafana_dashboard.md
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-sli-slo.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/argocd.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/jupyterhub-usage.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/opf-availability.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: approved, size/S

#219 feat: Disable registration flow in Kubeflow
  kubeflow-components/base/kfdef.yaml
Labels: approved, lgtm, size/XS

#207 feat: Onboard ML workshops group
  cluster-scope/base/groups/workshops/group.yaml
  cluster-scope/base/groups/workshops/kustomization.yaml
  cluster-scope/base/namespaces/ws-ml-prague/kustomization.yaml
  cluster-scope/base/namespaces/ws-ml-prague/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/workshops/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/workshops/rbac.yaml
  cluster-scope/overlays/moc/groups/workshops.enc.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  cluster-scope/overlays/moc/secret-generator.yaml
Labels: approved, lgtm, size/M

#222 Add contributor docs
  contributing.md
Labels: approved, lgtm, size/M

#226 feat: Add scc:privileged for aicoe-ci
  cluster-scope/base/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/S

#224 Add PVC manifest for user mcli
  odh/overlays/moc/jupyterhub/.sops.yaml
  odh/overlays/moc/jupyterhub/kustomization.yaml
  odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/jupyterhub/pvcs/user-mcli-pvc.enc.yaml
Labels: lgtm, size/M

#221 add opf-ci-test-pods namespace
  cluster-scope/base/namespaces/opf-ci-test-pods/kustomization.yaml
  cluster-scope/base/namespaces/opf-ci-test-pods/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, sig/devops, size/S

#234 feat: Relocate ODH operator group
  cluster-scope/base/namespaces/odh-operator/kustomization.yaml
  cluster-scope/base/namespaces/odh-operator/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  odh/base/operator/kustomization.yaml
  odh/base/operator/operator_group.yaml
  odh/base/operator/subscription.yaml
  odh/overlays/crc/operator/kustomization.yaml
  odh/overlays/quicklab/operator/kustomization.yaml
Labels: approved, lgtm, size/M

#235 feat: ODH v1.0.0 upgrade: Kafka
  odh/base/kafka/kfdef.yaml
Labels: approved, lgtm, size/XS

#236 feat: ODH v1.0.0 upgrade: Data catalog
  odh/base/datacatalog/kfdef.yaml
Labels: approved, lgtm, size/S

#233 feat: ODH v1.0.0 upgrade: Argo
  odh/base/argo/kfdef.yaml
Labels: approved, lgtm, size/S

#237 feat: ODH v1.0.0 upgrade: Superset
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, size/XS

#239 feat: ODH v1.0.0 upgrade: Monitoring
  odh/base/monitoring/kfdef.yaml
Labels: approved, lgtm, size/XS

#238 feat: ODH v1.0.0 upgrade: Jupyterhub
  odh/base/jupyterhub/kfdef.yaml
Labels: approved, lgtm, size/XS

#242 fix kubeflow-pipelines docs directory name
  docs/kubeflow/kubeflow-pipelines/README.md
Labels: approved, lgtm, size/XS

#243 Add PVC manifest for user hvee
  odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/jupyterhub/pvcs/user-hvee-pvc.enc.yaml
Labels: approved, lgtm, size/M

#244 Update CLO nodeCount to 2 and PVC size to 300Gig
  cluster-logging/base/clusterlogging.yaml
Labels: approved, size/XS

#245 Update CPU requests for Elasticsearch to 6 cpus
  cluster-logging/base/clusterlogging.yaml
Labels: approved, size/XS

#241 JH add override to ignore internal cert validation
  odh/base/jupyterhub/kfdef.yaml
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
Labels: approved, lgtm, size/S

#251 fix: Move ODH JH params and overlays to the overriding app
  odh/base/jupyterhub/kfdef.yaml
  odh/overlays/moc/jupyterhub/kustomization.yaml
Labels: approved, size/S

#246 feat: Enable public access to ws-ml-prague namespace
  cluster-scope/base/namespaces/ws-ml-prague/kustomization.yaml
  cluster-scope/components/project-view-public/kustomization.yaml
  cluster-scope/components/project-view-public/rbac.yaml
Labels: approved, lgtm, size/S

#250 feat: Use OCS bucket for Data catalog on MOC
  odh/base/datacatalog/kfdef.yaml
  odh/overlays/crc/datacatalog/kfdef_patch.yaml
  odh/overlays/crc/datacatalog/kustomization.yaml
  odh/overlays/moc/datacatalog/bucket.yaml
  odh/overlays/moc/datacatalog/kfdef_patch.yaml
  odh/overlays/moc/datacatalog/kustomization.yaml
  odh/overlays/quicklab/datacatalog/kfdef_patch.yaml
  odh/overlays/quicklab/datacatalog/kustomization.yaml
Labels: approved, lgtm, size/L

#255 JH exclude path /metrics from being protected by the proxy
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
Labels: approved, lgtm, size/XS

#248 feat: Create namespace for Dex
  cluster-scope/base/namespaces/opf-auth/kustomization.yaml
  cluster-scope/base/namespaces/opf-auth/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/S

#257 feat: Make OPF cluster admins
  cluster-scope/overlays/moc/groups/cluster-admins.enc.yaml
Labels: approved, size/XS

#256 fix: Missing storage class in datacatalog
  odh/overlays/moc/datacatalog/kfdef_patch.yaml
Labels: approved, lgtm, size/S

#217 Test kustomize build
  test-kustomize-build
Labels: approved, do-not-merge/hold, lgtm, size/S

#259 Add route for elasticsearch external access.
  cluster-logging/overlays/moc/.sops.yaml
  cluster-logging/overlays/moc/kustomization.yaml
  cluster-logging/overlays/moc/routes/route.enc.yaml
  cluster-logging/overlays/moc/routes/secret-generator.yaml
Labels: lgtm, size/M

#260 jupyterlab image for ml-prague-workshop
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
Labels: approved, lgtm, size/M

#261 Test kustomize build fix
  test-kustomize-build
Labels: approved, size/S

#264 Remove odh-operator namespace from crc/quicklab
  cluster-scope/overlays/crc/kustomization.yaml
  cluster-scope/overlays/quicklab/kustomization.yaml
Labels: approved, lgtm, size/XS

#265 Expand user pvc as per request.
  odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/jupyterhub/pvcs/user-cdol-pvc.enc.yaml
Labels: approved, lgtm, size/M

#267 Increase prom pvc size
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, size/XS

#268 Update prom cluster metrics timeout
  odh/overlays/moc/monitoring/servicemonitors/cluster-metrics-servicemonitor.yaml
Labels: approved, size/XS

#269 feat: Sync the authz tasks
  .sops.yaml
  cluster-scope/base/clusterrolebindings/cluster-admins-rb/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/cluster-admins-rb/kustomization.yaml
  cluster-scope/base/imageregistryconfigs/cluster/config.yaml
  cluster-scope/base/imageregistryconfigs/cluster/kustomization.yaml
  cluster-scope/base/imageregistryconfigs/cluster/pvc.yaml
  cluster-scope/base/ingresscontrollers/default/ingresscontroller.yaml
  cluster-scope/base/ingresscontrollers/default/kustomization.yaml
  cluster-scope/base/oauths/cluster/kustomization.yaml
  cluster-scope/base/oauths/cluster/oauth.yaml
  cluster-scope/overlays/moc/imageregistryconfigs/image-registry-storage_patch.yaml
  cluster-scope/overlays/moc/ingresscontrollers/default-ingress-certificate.enc.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  cluster-scope/overlays/moc/oauths/cluster_patch.yaml
  cluster-scope/overlays/moc/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/moc/secret-generator.yaml
Labels: approved, lgtm, size/L

#270 Remove kubeflow managed namespaces.
  cluster-scope/base/namespaces/istio-system/kustomization.yaml
  cluster-scope/base/namespaces/istio-system/namespace.yaml
  cluster-scope/base/namespaces/knative-serving/kustomization.yaml
  cluster-scope/base/namespaces/knative-serving/namespace.yaml
  cluster-scope/base/namespaces/tekton-pipelines/kustomization.yaml
  cluster-scope/base/namespaces/tekton-pipelines/namespace.yaml
Labels: approved, size/M

#271 feat: MOC SSO for moc-infra
  cluster-scope/overlays/moc-infra/groups/cluster-admins.enc.yaml
  cluster-scope/overlays/moc-infra/kustomization.yaml
  cluster-scope/overlays/moc-infra/oauths/cluster_patch.yaml
  cluster-scope/overlays/moc-infra/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/moc-infra/secret-generator.yaml
Labels: approved, lgtm, size/L

#273 Give ArgoCD SA argocd-manager cluster admin
  cluster-scope/base/clusterrolebindings/argocd-manager/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/argocd-manager/kustomization.yaml
  cluster-scope/overlays/moc-infra/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/S

#275 feat: Share user groups between MOC clusters
  cluster-scope/overlays/moc-base/groups/argocd-admins.enc.yaml
  cluster-scope/overlays/moc-base/groups/data-science.enc.yaml
  cluster-scope/overlays/moc-base/groups/mesh-for-data.enc.yaml
  cluster-scope/overlays/moc-base/groups/open-aiops.enc.yaml
  cluster-scope/overlays/moc-base/groups/operate-first.enc.yaml
  cluster-scope/overlays/moc-base/groups/rekor.enc.yaml
  cluster-scope/overlays/moc-base/groups/thoth.enc.yaml
  cluster-scope/overlays/moc-base/groups/workshops.enc.yaml
  cluster-scope/overlays/moc-base/kustomization.yaml
  cluster-scope/overlays/moc-base/secret-generator.yaml
  cluster-scope/overlays/moc-infra/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  cluster-scope/overlays/moc/secret-generator.yaml
Labels: lgtm, size/M

#274 feat: Add mhild to infra cluster admins
  cluster-scope/overlays/moc-infra/groups/cluster-admins.enc.yaml
Labels: approved, lgtm, size/XS

#277 Replace user with different account for argocd admins.
  cluster-scope/overlays/moc-base/groups/argocd-admins.enc.yaml
Labels: approved, lgtm, size/XS

#276 Add alerting rule for unusually high scrape durations in cluster-monitoring
  odh/overlays/moc/monitoring/kustomization.yaml
  odh/overlays/moc/monitoring/rules/alerting/kustomization.yaml
  odh/overlays/moc/monitoring/rules/alerting/openshift-monitoring-scrape-duration.yaml
Labels: approved, lgtm, size/S

#280 Update moc-sso secret to be ignored by argocd
  cluster-scope/overlays/moc-infra/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/moc/oauths/moc-sso-client-secret.enc.yaml
Labels: approved, lgtm, size/S

#286 Add jupyterhub staging namespace
  cluster-scope/base/namespaces/opf-jupyterhub-stage/kustomization.yaml
  cluster-scope/base/namespaces/opf-jupyterhub-stage/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/S

#282 Update Jupytyerhub kfdef manifest version to 1.0.1
  odh/base/jupyterhub/kfdef.yaml
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
Labels: approved, lgtm, size/XS

#284 Sync ACM operator subscription
  acm/base/kustomization.yaml
  acm/base/multiclusterhub.yaml
  acm/overlays/moc-infra/kustomization.yaml
  cluster-scope/base/namespaces/acm/kustomization.yaml
  cluster-scope/base/namespaces/acm/namespace.yaml
  cluster-scope/base/operatorgroups/acm/kustomization.yaml
  cluster-scope/base/operatorgroups/acm/operatorgroup.yaml
  cluster-scope/base/operatorgroups/opf-auth/kustomization.yaml
  cluster-scope/base/operatorgroups/opf-auth/operatorgroup.yaml
  cluster-scope/base/subscriptions/advanced-cluster-management/kustomization.yaml
  cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml
  cluster-scope/overlays/moc-infra/kustomization.yaml
Labels: approved, lgtm, size/M
