Repository operate-first/apps, pull requests merged in 2021-03, with the labels that each got.

#293 update thoth admin users for the moc cluster
  cluster-scope/overlays/moc-base/groups/thoth.enc.yaml
Labels: approved, size/M

#294 reconfgured CI/CD to use prow and aicoe-ci
  .aicoe-ci.yaml
  .prow.yaml
Labels: approved, size/S

#295 feat: Add data-science folks to cluster-logs-readers
  cluster-scope/base/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
Labels: approved, lgtm, size/XS

#297 feat: Add PVC for Oindrilla
  odh/overlays/moc/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/jupyterhub/pvcs/user-oc-pvc.enc.yaml
Labels: approved, lgtm, size/M

#299 [CLO] Increase the ES node count to 5
  cluster-logging/base/clusterlogging.yaml
Labels: approved, lgtm, size/XS

#300 CLO - reduce cpu count per es node
  cluster-logging/base/clusterlogging.yaml
Labels: approved, lgtm, size/XS

#289 chore: Cleanup shared scripts
  test-kustomize-build
Labels: approved, lgtm, size/S

#298 feat: Add ray-odh-intagration
  cluster-scope/base/groups/ray/group.yaml
  cluster-scope/base/groups/ray/kustomization.yaml
  cluster-scope/base/namespaces/ray-odh-integration/kustomization.yaml
  cluster-scope/base/namespaces/ray-odh-integration/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/ray/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ray/rbac.yaml
  cluster-scope/overlays/moc-base/groups/ray.enc.yaml
  cluster-scope/overlays/moc-base/kustomization.yaml
  cluster-scope/overlays/moc-base/secret-generator.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, lgtm, size/M

#291 feat: Sync AWS OCTO provider connection
  acm/overlays/moc-infra/kustomization.yaml
  acm/overlays/moc-infra/provider-connections/aws-octo.enc.yaml
  acm/overlays/moc-infra/secret-generator.yaml
Labels: approved, lgtm, size/M

#290 feat: Add ODH Z-stream updater script
  hack/set-odh-release.sh
Labels: approved, lgtm, size/S

#302 integrate ray into MOC ODH
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
Labels: approved, lgtm, ok-to-test, size/S

#292 feat: ODH 1.0.2 z-stream release
  observatorium/base/instance/kfdef.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, size/M

#304 Update contributing doc with wip instructions.
  contributing.md
Labels: approved, size/XS

#303 chore: Move test-kustomize-build to .prow.yaml
  .aicoe-ci.yaml
  .prow.yaml
Labels: approved, lgtm, size/S

#309 Add JH PVC manifests that were previously applied manually
  odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-fran-pvc.enc.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-kach-pvc.enc.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-ocha-pvc.enc.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-shan-pvc.enc.yaml
Labels: approved, lgtm, size/L

#310 feat: Upgrade ACM to release-2.2 channel
  cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml
Labels: approved, lgtm, size/XS

#311 Onboard user to data science and create ml-ws ns.
  cluster-scope/base/namespaces/ds-ml-workflows-ws/kustomization.yaml
  cluster-scope/base/namespaces/ds-ml-workflows-ws/namespace.yaml
  cluster-scope/overlays/moc/common/groups/data-science.enc.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#312 make chris doan a cluster admin
  cluster-scope/overlays/moc/infra/groups/cluster-admins.enc.yaml
Labels: approved, size/XS

#313 scale github alerts receiver down
  odh/base/monitoring/github-receiver.yaml
Labels: approved, lgtm, size/XS

#308 docs: Update docs for CNV/Zero migration
  docs/kubeflow/kubeflow-dashboard/README.md
  docs/kubeflow/kubeflow-pipelines/README.md
  docs/observatorium/loki/README.md
  docs/observatorium/loki/add_loki_grafana_datasource.md
  docs/odh/grafana/README.md
  docs/odh/grafana/add_grafana_dashboard.md
  docs/odh/kafka/README.md
  docs/odh/kafka/add_kafka_topics.md
Labels: lgtm, size/M

#272 use the appropriate tag for maintaining consistency
  odh/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
Labels: approved, lgtm, size/XS

#316 add cnv to infra cluster for nmstate support
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#317 upgrade cnv subscription to 2.4.4
  cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml
Labels: approved, size/XS

#318 upgrade cnv subscription to 2.5.4
  cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml
Labels: approved, lgtm, size/XS

#319 Update installplan to manual for kubevirt
  cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml
Labels: size/XS

#320 feature/infra hco
  kubevirt-hyperconverged/base/hyperconverged.yaml
  kubevirt-hyperconverged/overlays/moc/infra/kustomization.yaml
Labels: approved, size/S

#314 Updated links to point to new cluster routes.
  docs/kubeflow/kubeflow-dashboard/README.md
Labels: approved, lgtm, size/XS

#324 update sso configuration for zero cluster
  cluster-scope/overlays/moc/zero/oauths/cluster_patch.yaml
  cluster-scope/overlays/moc/zero/oauths/moc-sso-client-secret.enc.yaml
Labels: size/XS

#322 Add network interfaces on crc provisioning network
  cluster-scope/overlays/moc/infra/crc-provisioning-vlan.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/infra/zero-provisioning-vlan.yaml
Labels: lgtm, size/L

#288 feat: Prepare subscription for MOC CNV 4.7 upgrade
  cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
  cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
  cluster-scope/base/subscriptions/kubevirt-hyperconverged/subscription.yaml
  cluster-scope/base/subscriptions/local-storage-operator/subscription.yaml
  cluster-scope/base/subscriptions/metering-ocp/subscription.yaml
  cluster-scope/base/subscriptions/ocs-operator/subscription.yaml
  cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/infra/subscriptions/kubevirt-hyperconverged_patch.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/subscriptions/cluster-logging-operator_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/elastic-operator_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/local-storage-operator_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/metering-ocp_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/ocs-operator_patch.yaml
  cluster-scope/overlays/moc/zero/subscriptions/openshift-pipelines-operator-rh_patch.yaml
Labels: do-not-merge/hold, size/L

#315 Scale up github receiver.
  odh/base/monitoring/github-receiver.yaml
Labels: approved, do-not-merge/hold, size/XS

#338 Update path for kafka/superset for override in zero cluster.
  odh/overlays/moc/zero/kafka/kustomization.yaml
  odh/overlays/moc/zero/superset/kustomization.yaml
Labels: approved, lgtm, size/XS

#339 Add clusterrolebinding for observatorium operator
  cluster-scope/base/clusterrolebindings/observatorium-operator/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/observatorium-operator/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  observatorium/base/operator/deployment.yaml
Labels: approved, lgtm, size/S

#340 feature/infra tls
  cluster-scope/overlays/moc/infra/ingresscontrollers/default-ingress-certificate.enc.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/infra/secret-generator.yaml
Labels: approved, lgtm, size/M

#342 modify subscriptions to set installPlanApproval to Manual
  cluster-scope/base/subscriptions/advanced-cluster-management/subscription.yaml
  cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
  cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
  cluster-scope/base/subscriptions/local-storage-operator/subscription.yaml
  cluster-scope/base/subscriptions/metering-ocp/subscription.yaml
  cluster-scope/base/subscriptions/ocs-operator/subscription.yaml
  cluster-scope/base/subscriptions/opendatahub-operator/subscription.yaml
  cluster-scope/base/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
Labels: approved, lgtm, size/S

#321 wire up ray cluster CRD into kustomize overlays
  cluster-scope/base/crds/cluster.ray.io/kustomization.yaml
  cluster-scope/base/crds/cluster.ray.io/ray-cluster-crd.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/XXL

#344 Fix linting on ray crd.
  cluster-scope/base/crds/cluster.ray.io/ray-cluster-crd.yaml
Labels: approved, lgtm, size/XS

#336 add ray operator objects to ofp-jupyterhub
  odh/base/jupyterhub/kustomization.yaml
  odh/base/jupyterhub/ray-odh-integration/kustomization.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-operator-role.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-operator-rolebinding.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-operator-serviceaccount.yaml
Labels: approved, lgtm, size/M

#346 Give ray users permissions to jupyterhub ns.
  cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml
Labels: approved, lgtm, size/XS

#348 Add web terminal operator to zero cluster
  cluster-scope/base/subscriptions/web-terminal/kustomization.yaml
  cluster-scope/base/subscriptions/web-terminal/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/subscriptions/web-terminal.yaml
Labels: approved, lgtm, size/S

#350 Add aggregate role for Ray CR for project admin
  cluster-scope/base/clusterroles/ray-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/clusterroles/ray-aggregate-to-admin/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/S

#351 encrypt groups/argocd-admins.enc.yaml to ipolonsk
  cluster-scope/overlays/moc/common/groups/argocd-admins.enc.yaml
Labels: size/M

#354 Revert "encrypt groups/argocd-admins.enc.yaml to ipolonsk"
  cluster-scope/overlays/moc/common/groups/argocd-admins.enc.yaml
Labels: approved, lgtm, size/M

#356 Move hack to scripts
  .pre-commit-config.yaml
  scripts/onboarding.sh
  scripts/set-odh-release.sh
Labels: approved, lgtm, size/XS

#355 docs: Add readme for MOC listing GPG key locations
  cluster-scope/overlays/moc/README.md
Labels: approved, lgtm, size/S

#349 Provide version label for grafana operator to update the json based on url
  odh/overlays/moc/zero/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
Labels: approved, size/XS

#357 added ipolonsk email to users list
  cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
Labels: approved, lgtm, size/XS

#358 docs: Update contributing guide
  contributing.md
Labels: approved, lgtm, size/M

#359 fix: Address feedback on #358 Contribution doc update
  contributing.md
Labels: approved, lgtm, size/XS

#327 [Telemetry WG] Tufts project: Setup namespace for dcc group 6
  cluster-scope/base/groups/tufts-dcc-6/group.yaml
  cluster-scope/base/groups/tufts-dcc-6/kustomization.yaml
  cluster-scope/base/namespaces/tufts-dcc-6/kustomization.yaml
  cluster-scope/base/namespaces/tufts-dcc-6/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/rbac.yaml
  cluster-scope/overlays/moc/common/groups/tufts-dcc-6.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#360 Add thanos to Observatorium CR for metrics long term storage
  observatorium/base/instance/example-thanos-objectstorage-secret.yaml
  observatorium/base/instance/observatorium.yaml
  observatorium/overlays/moc/zero/objectbucketclaims/kustomization.yaml
  observatorium/overlays/moc/zero/objectbucketclaims/thanos-obc.yaml
  observatorium/overlays/moc/zero/secrets/secret-generator.yaml
  observatorium/overlays/moc/zero/secrets/thanos-objectstorage-secret.enc.yaml
Labels: approved, lgtm, size/L

#362 Change thanos query frontend version to v0.15.0
  observatorium/base/instance/observatorium.yaml
Labels: approved, lgtm, size/XS

#363 Add Prometheus config to remote write metrics to thanos
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, lgtm, size/XS

#364 Add thanos query frontend route and grafana datasource
  observatorium/base/instance/kustomization.yaml
  observatorium/base/instance/thanos-routes.yaml
  odh/overlays/moc/zero/monitoring/datasource/kustomization.yaml
  odh/overlays/moc/zero/monitoring/datasource/opf-observatorium-thanos-datasource.yaml
Labels: approved, lgtm, size/M

#361 add ray ml singleuser profile to overlays
  odh/base/jupyterhub/ray-odh-integration/kustomization.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-jh-rolebinding.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
  odh/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
Labels: approved, lgtm, size/L

#371 feat: Add user bucket in DataCatalog for xtuchyna
  odh/overlays/moc/zero/datacatalog/.sops.yaml
  odh/overlays/moc/zero/datacatalog/kustomization.yaml
  odh/overlays/moc/zero/datacatalog/user-buckets/secret-generator.yaml
  odh/overlays/moc/zero/datacatalog/user-buckets/user-dtuch.enc.yaml
Labels: approved, lgtm, size/M

#366 feat: Create a namespace for GH alert receiver
  cluster-scope/base/namespaces/opf-alertreceiver/kustomization.yaml
  cluster-scope/base/namespaces/opf-alertreceiver/namespace.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#367 feat: Add a separate GH alert receiver deployment
  alertreceiver/base/deployment.yaml
  alertreceiver/base/kustomization.yaml
  alertreceiver/base/service.yaml
  alertreceiver/overlays/moc/common/github-secret.enc.yaml
  alertreceiver/overlays/moc/common/kustomization.yaml
  alertreceiver/overlays/moc/common/secret-generator.yaml
  alertreceiver/overlays/moc/infra/kustomization.yaml
  alertreceiver/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#368 feat: Reconnect alert receiver on Zero
  odh/base/monitoring/alertmanager-config.yaml
Labels: approved, lgtm, size/XS

#369 feat: Remove github receiver from odh-monitoring
  odh/base/monitoring/github-receiver-service.yaml
  odh/base/monitoring/github-receiver.yaml
  odh/base/monitoring/kustomization.yaml
  odh/overlays/moc/zero/monitoring/kustomization.yaml
  odh/overlays/moc/zero/monitoring/secrets/github-secret.enc.yaml
  odh/overlays/moc/zero/monitoring/secrets/secret-generator.yaml
Labels: approved, lgtm, size/L

#372 fix: Datacatalog bucket
  odh/overlays/moc/zero/datacatalog/bucket.yaml
  odh/overlays/moc/zero/datacatalog/kfdef_patch.yaml
Labels: approved, lgtm, size/XS

#376 feat: Add Anand to cluster admins
  cluster-scope/overlays/moc/infra/groups/cluster-admins.enc.yaml
  cluster-scope/overlays/moc/zero/groups/cluster-admins.enc.yaml
Labels: approved, size/S

#377 update thoth kafka topics w.r.t deployment name
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-advise-justification.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-re-run.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-adviser-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-hash-mismatch.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-kebechet-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package-version.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-missing-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-extract-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-package-released.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-qebhwt-trigger.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-si-unanalyzed-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-solved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unresolved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-unrevsolved-package.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/thoth-update-provides-source-distro.yaml
Labels: approved, lgtm, size/M

#249 feat: Add auth via DEX OpenID
  auth/README.md
  auth/base/dex-clients.yaml
  auth/base/dex-cm.yaml
  auth/base/dex-deployment.yaml
  auth/base/dex-route.yaml
  auth/base/dex-sa-token.yaml
  auth/base/dex-sa.yaml
  auth/base/dex-service.yaml
  auth/base/kustomization.yaml
  auth/overlays/.sops.yaml
  auth/overlays/dev/dex-cm.yaml
  auth/overlays/dev/kustomization.yaml
  auth/overlays/moc/zero/dex-clients.enc.yaml
  auth/overlays/moc/zero/dex-cm.yaml
  auth/overlays/moc/zero/kustomization.yaml
  auth/overlays/moc/zero/secret-generator.yaml
Labels: approved, lgtm, size/L

#374 fix: ODH Dashboard image replace
  odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml
Labels: approved, lgtm, size/XS

#380 Increase PVC size for Thanos Receive
  observatorium/base/instance/observatorium.yaml
Labels: approved, lgtm, size/XS

#378 Update monitoring
  cluster-scope/base/namespaces/openshift-operators-redhat/kustomization.yaml
  cluster-scope/base/namespaces/openshift-operators/kustomization.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/kafka-podmonitors.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/servicemonitor.yaml
Labels: approved, lgtm, size/L

#381 feat: Add memory intensive user profile
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
Labels: approved, lgtm, size/M

#384 Allow OPF monitoring Prometheus to detect Pod Monitors
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, lgtm, size/XS

#385 Fix Metrics scraping for Argo
  odh/base/monitoring/overrides/prometheus-operator/base/servicemonitor.yaml
Labels: approved, size/XS

#375 Update Kfdefs to 1.0.4
  observatorium/base/instance/kfdef.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, lgtm, sig/devops, size/M

#388 fix: Use different key for Auth app
  auth/overlays/.sops.yaml
  auth/overlays/moc/zero/dex-clients.enc.yaml
Labels: approved, lgtm, size/M

#383 Add external urls flag for Prometheus and Alertmanager
  odh/base/monitoring/alertmanager.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, do-not-merge/needs-rebase, size/XS

#370 feat: Enable GH alert receiver for Cluster Monitoring on MOC Infra
  cluster-scope/overlays/moc/infra/alertmanager-main-secret.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/M

#389 feat: Enable cluster monitoring GH receiver for all MOC clusters
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#390 attempt to upgrade cnv to 2.6.0
  cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml
Labels: approved, lgtm, size/XS

#392 Revert "attempt to upgrade cnv to 2.6.0"
  cluster-scope/overlays/moc/zero/subscriptions/kubevirt-hyperconverged_patch.yaml
Labels: approved, lgtm, size/XS

#391 Update paths in add_kafka docs.
  docs/odh/kafka/add_kafka_topics.md
Labels: approved, lgtm, size/XS

#393 Onboard ai-services project, as-pushgateway namespace
  cluster-scope/base/groups/ai-services/group.yaml
  cluster-scope/base/groups/ai-services/kustomization.yaml
  cluster-scope/base/namespaces/as-pushgateway/kustomization.yaml
  cluster-scope/base/namespaces/as-pushgateway/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/ai-services/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ai-services/rbac.yaml
  cluster-scope/overlays/moc/common/groups/ai-services.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#397 feat: Change alert receiver's repo
  alertreceiver/base/deployment.yaml
Labels: approved, size/XS

#399 Add @maulikjs to the operate-first group
  cluster-scope/overlays/moc/common/.sops.yaml
  cluster-scope/overlays/moc/common/groups/operate-first.enc.yaml
Labels: approved, lgtm, size/L

#400 Update Observatorium Servicemonitor to scrape Thanos components
  odh/overlays/moc/zero/monitoring/servicemonitors/observatorium-servicemonitor.yaml
Labels: approved, lgtm, size/XS

#398 Introduce manual ODH deployment and remove subscription.
  cluster-scope/base/clusterrolebindings/opendatahub-operator/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/opendatahub-operator/kustomization.yaml
  cluster-scope/base/clusterroles/opendatahub-operator/clusterrole.yaml
  cluster-scope/base/clusterroles/opendatahub-operator/kustomization.yaml
  cluster-scope/base/crds/kfdef.apps.kubeflow.org/crd.yaml
  cluster-scope/base/crds/kfdef.apps.kubeflow.org/kustomization.yaml
  cluster-scope/base/subscriptions/opendatahub-operator/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  odh-operator/base/deployment.yaml
  odh-operator/base/kustomization.yaml
  odh-operator/base/serviceaccount.yaml
  odh-operator/overlay/dev/kustomization.yaml
  odh-operator/overlay/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#402 Fix dir name typo.
  odh-operator/overlays/dev/kustomization.yaml
  odh-operator/overlays/moc/zero/kustomization.yaml
Labels: approved, size/XS

#403 Move ODH deployment to its own ns.
  cluster-scope/base/namespaces/opendatahub-operator/kustomization.yaml
  cluster-scope/base/namespaces/opendatahub-operator/namespace.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  odh-operator/base/kustomization.yaml
Labels: approved, lgtm, size/S

#404 Update odh crb namespace.
  cluster-scope/base/clusterrolebindings/opendatahub-operator/clusterrolebinding.yaml
Labels: approved, lgtm, size/XS

#396 feat: Subscribe to OpenShift Serverless
  cluster-scope/base/namespaces/openshift-serverless/kustomization.yaml
  cluster-scope/base/namespaces/openshift-serverless/namespace.yaml
  cluster-scope/base/operatorgroups/openshift-serverless/kustomization.yaml
  cluster-scope/base/operatorgroups/openshift-serverless/operatorgroup.yaml
  cluster-scope/base/subscriptions/serverless-operator/kustomization.yaml
  cluster-scope/base/subscriptions/serverless-operator/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/subscriptions/serverless-operator_patch.yaml
Labels: approved, lgtm, size/M

#401 Add untracked kfdefs to git.
  docs/odh/adding_kfdefs.md
  kfdefs/base/kustomization.yaml
  kfdefs/overlays/dev/kustomization.yaml
  kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kfdef.yaml
  kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kustomization.yaml
  kfdefs/overlays/moc/zero/kustomization.yaml
  kfdefs/overlays/moc/zero/thoth-infra-prod/kfdef.yaml
  kfdefs/overlays/moc/zero/thoth-infra-prod/kustomization.yaml
Labels: approved, lgtm, size/L

#408 chore: Remove naved001 from OWNERS
  OWNERS
Labels: size/XS

#407 feat: Enable Knative Serving and Eventing
  knative/base/knative-eventing.yaml
  knative/base/knative-serving.yaml
  knative/base/kustomization.yaml
  knative/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#412 Update odh to 1.0.5
  kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kfdef.yaml
  kfdefs/overlays/moc/zero/thoth-infra-prod/kfdef.yaml
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
Labels: approved, do-not-merge/hold, lgtm, size/L

#414 fix: Operator image override
  odh-operator/base/kustomization.yaml
Labels: approved, size/XS

#411 pet-image-detection imagestream
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/pet-image-detection.yaml
Labels: approved, lgtm, size/S

#415 minecraft namespace
  cluster-scope/base/groups/b4mad/group.yaml
  cluster-scope/base/groups/b4mad/kustomization.yaml
  cluster-scope/base/namespaces/b4mad-minecraft/kustomization.yaml
  cluster-scope/base/namespaces/b4mad-minecraft/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/b4mad/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/b4mad/rbac.yaml
  cluster-scope/overlays/moc/common/groups/b4mad.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#405 add metallb
  cluster-scope/base/clusterrolebindings/metallb-allow-privileged/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/metallb-allow-privileged/kustomization.yaml
  cluster-scope/base/clusterrolebindings/metallb-system-controller/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/metallb-system-controller/kustomization.yaml
  cluster-scope/base/clusterrolebindings/metallb-system-speaker/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/metallb-system-speaker/kustomization.yaml
  cluster-scope/base/clusterroles/metallb-system-controller/clusterrole.yaml
  cluster-scope/base/clusterroles/metallb-system-controller/kustomization.yaml
  cluster-scope/base/clusterroles/metallb-system-speaker/clusterrole.yaml
  cluster-scope/base/clusterroles/metallb-system-speaker/kustomization.yaml
  cluster-scope/base/namespaces/metallb-system/kustomization.yaml
  cluster-scope/base/namespaces/metallb-system/namespace.yaml
  cluster-scope/base/podsecuritypolicy/metallb-system-controller/kustomization.yaml
  cluster-scope/base/podsecuritypolicy/metallb-system-controller/podsecuritypolicy.yaml
  cluster-scope/base/podsecuritypolicy/metallb-system-speaker/kustomization.yaml
  cluster-scope/base/podsecuritypolicy/metallb-system-speaker/podsecuritypolicy.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  metallb/base/daemonset.yaml
  metallb/base/deployment.yaml
  metallb/base/kustomization.yaml
  metallb/base/role.yaml
  metallb/base/rolebinding.yaml
  metallb/base/serviceaccount.yaml
  metallb/overlays/moc/zero/config.yaml
  metallb/overlays/moc/zero/kustomization.yaml
  metallb/overlays/moc/zero/memberlist.enc.yaml
  metallb/overlays/moc/zero/secret-generator.yaml
Labels: approved, do-not-merge/hold, lgtm, size/XL

#423 Onboard curator cluster
  cluster-scope/overlays/moc/curator/groups/cluster-admins.enc.yaml
  cluster-scope/overlays/moc/curator/imageregistryconfigs/image-registry-storage_patch.yaml
  cluster-scope/overlays/moc/curator/ingresscontrollers/default-ingress-certificate.enc.yaml
  cluster-scope/overlays/moc/curator/kustomization.yaml
  cluster-scope/overlays/moc/curator/oauths/cluster_patch.yaml
  cluster-scope/overlays/moc/curator/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/moc/curator/secret-generator.yaml
  cluster-scope/overlays/moc/curator/subscriptions/web-terminal.yaml
Labels: approved, lgtm, size/L

#425 Update README to include the curator cluster
  cluster-scope/overlays/moc/README.md
Labels: approved, size/S

#424 Add overlay for staging jupyterhub
  odh/overlays/moc/zero/jupyterhub-stage/kustomization.yaml
Labels: approved, lgtm, size/S

#427 fix the thoth datasource url
  odh/overlays/moc/zero/monitoring/datasource/thoth-station-datasource.yaml
Labels: approved, lgtm, size/XS

#429 feat: Enable view on pods and pods/logs for opf-jupyterhub
  cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml
  cluster-scope/components/project-logs-reader/kustomization.yaml
  cluster-scope/components/project-logs-reader/role.yaml
  cluster-scope/components/project-logs-reader/rolebinding.yaml
Labels: approved, lgtm, size/M

#431 Add asanmukh as Jupyterhub admin
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
Labels: approved, lgtm, size/XS

#433 regression: Disable project self provisioning
  cluster-scope/base/clusterrolebindings/self-provisioners/clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/self-provisioners/kustomization.yaml
  cluster-scope/base/configs/project/kustomization.yaml
  cluster-scope/base/configs/project/project.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
Labels: approved, lgtm, priority/critical-urgent, size/M

#426 fix: ODH Dashboard RBAC to show only prod namespaces
  cluster-scope/base/namespaces/opf-argo/kustomization.yaml
  cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml
  cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
  cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml
  cluster-scope/base/namespaces/opf-kafka/kustomization.yaml
  cluster-scope/base/namespaces/opf-superset/kustomization.yaml
  cluster-scope/components/odh-dashboard/kustomization.yaml
  cluster-scope/components/odh-dashboard/odh-dashboard-role.yaml
  cluster-scope/components/odh-dashboard/odh-dashboard-rolebinding.yaml
  odh/base/dashboard/overrides/overlays/cluster-role/rbac.yaml
Labels: approved, lgtm, size/M

#434 Update route ca for CLO elasticsearch
  cluster-logging/overlays/moc/zero/routes/route.enc.yaml
Labels: approved, lgtm, size/M

#410 chore: Cleanup obsolete namespaces
  cluster-scope/base/namespaces/cert-manager/kustomization.yaml
  cluster-scope/base/namespaces/cert-manager/namespace.yaml
  cluster-scope/base/namespaces/istio-system/kustomization.yaml
  cluster-scope/base/namespaces/knative-serving/kustomization.yaml
  cluster-scope/base/namespaces/kube-system/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/M

#436 Add operate-first group as jupyterhub admins
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-configmap.yaml
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-groups-configmap.yaml
Labels: approved, lgtm, size/S

#435 feat: Enable nice URL for ODH Dashboard
  odh/overlays/moc/zero/dashboard/kustomization.yaml
  odh/overlays/moc/zero/dashboard/route.enc.yaml
  odh/overlays/moc/zero/dashboard/secret-generator.yaml
Labels: approved, lgtm, size/M

#440 fix(odh-dashboard): redirect HTTP to HTTPS
  odh/overlays/moc/zero/dashboard/route.enc.yaml
Labels: approved, lgtm, size/S

#442 Add `system:authenticated` group in the allowed groups for JH access
  odh/base/jupyterhub/overrides/jupyterhub/base/jupyterhub-groups-configmap.yaml
Labels: approved, size/XS

#441 fix(odh-monitoring): Grafana image
  odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
Labels: approved, lgtm, size/XS

#439 Add resourcequotas and limitrange components.
  cluster-scope/components/limitranges/default/kustomization.yaml
  cluster-scope/components/limitranges/default/limitrange.yaml
  cluster-scope/components/resourcequotas/large/kustomization.yaml
  cluster-scope/components/resourcequotas/large/resourcequotas.yaml
  cluster-scope/components/resourcequotas/medium/kustomization.yaml
  cluster-scope/components/resourcequotas/medium/resourcequotas.yaml
  cluster-scope/components/resourcequotas/small/kustomization.yaml
  cluster-scope/components/resourcequotas/small/resourcequotas.yaml
Labels: approved, lgtm, size/M

#443 onboard dkenigsb to zero cluster
  cluster-scope/base/groups/cnv-testing/group.yaml
  cluster-scope/base/groups/cnv-testing/kustomization.yaml
  cluster-scope/base/namespaces/cnv-testing/kustomization.yaml
  cluster-scope/base/namespaces/cnv-testing/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/cnv-testing/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/cnv-testing/rbac.yaml
  cluster-scope/overlays/moc/common/groups/cnv-testing.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#445 feat: Onboard FDE: Audio Decoder Demo
  cluster-scope/base/groups/fde/group.yaml
  cluster-scope/base/groups/fde/kustomization.yaml
  cluster-scope/base/namespaces/fde-audio-decoder-demo/kustomization.yaml
  cluster-scope/base/namespaces/fde-audio-decoder-demo/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/fde/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/fde/rbac.yaml
  cluster-scope/overlays/moc/common/groups/fde.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#447 Onboard sdap-mslsp team
  cluster-scope/base/groups/sdap-mslsp/group.yaml
  cluster-scope/base/groups/sdap-mslsp/kustomization.yaml
  cluster-scope/base/namespaces/sdap/kustomization.yaml
  cluster-scope/base/namespaces/sdap/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/sdap-mslsp/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sdap-mslsp/rbac.yaml
  cluster-scope/overlays/moc/common/groups/sdap-mslsp.enc.yaml
Labels: approved, lgtm, size/L

#446 Add thanos upstream dashboards
  odh/overlays/moc/zero/monitoring/dashboards/kustomization.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/kustomization.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-compact.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-overview.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-query.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-receive.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-rule.yaml
  odh/overlays/moc/zero/monitoring/dashboards/thanos/thanos-store.yaml
Labels: approved, lgtm, size/M

#448 Scale up Observatorium Thanos Receiver and Thanos Query
  observatorium/base/instance/observatorium.yaml
Labels: approved, size/XS

#417 feat: Onboard RH Labs - CI/CD
  cluster-scope/base/groups/lab-cicd/group.yaml
  cluster-scope/base/groups/lab-cicd/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-1-jump-app-cicd/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-1-jump-app-cicd/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-1-jump-app-dev/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-1-jump-app-dev/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-2-jump-app-cicd/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-2-jump-app-cicd/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-2-jump-app-dev/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-2-jump-app-dev/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-3-jump-app-cicd/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-3-jump-app-cicd/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-3-jump-app-dev/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-3-jump-app-dev/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-4-jump-app-cicd/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-4-jump-app-cicd/namespace.yaml
  cluster-scope/base/namespaces/lab-cicd-4-jump-app-dev/kustomization.yaml
  cluster-scope/base/namespaces/lab-cicd-4-jump-app-dev/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/lab-cicd/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/lab-cicd/rbac.yaml
  cluster-scope/overlays/moc/common/groups/lab-cicd.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, size/L

#453 chore(jupyterhub/pvcs): Enlarge user PVC for izim
  odh/overlays/moc/zero/jupyterhub/pvcs/secret-generator.yaml
  odh/overlays/moc/zero/jupyterhub/pvcs/user-izim-pvc.enc.yaml
Labels: approved, size/M

#421 Upgrade zero cluster to 4.7.2
  cluster-scope/overlays/moc/zero/clusterversion.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/S

#450 chore(prow): Lower CPU request
  .prow.yaml
Labels: approved, lgtm, size/XS

#451 fix(odh-jupyterhub): Viewing pods/log in a namespace
  cluster-scope/components/project-logs-reader/role.yaml
Labels: approved, size/S

#452 fix(hue): Set proper endpoint for S3 file explorer
  odh/overlays/moc/zero/datacatalog/kfdef_patch.yaml
Labels: approved, lgtm, size/XS

#457 Update ODH to 1.0.6 z-release.
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
  odh/base/argo/kfdef.yaml
  odh/base/dashboard/kfdef.yaml
  odh/base/datacatalog/kfdef.yaml
  odh/base/jupyterhub/kfdef.yaml
  odh/base/kafka/kfdef.yaml
  odh/base/monitoring/kfdef.yaml
  odh/base/superset/kfdef.yaml
  scripts/set-odh-release.sh
Labels: approved, lgtm, size/M

#461 feat: Onboard SA-DACH
  cluster-scope/base/groups/sa-dach/group.yaml
  cluster-scope/base/groups/sa-dach/kustomization.yaml
  cluster-scope/base/namespaces/sa-dach-anwendertreffen/kustomization.yaml
  cluster-scope/base/namespaces/sa-dach-anwendertreffen/namespace.yaml
  cluster-scope/base/namespaces/sa-dach-openshift-examples/kustomization.yaml
  cluster-scope/base/namespaces/sa-dach-openshift-examples/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/sa-dach/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sa-dach/rbac.yaml
  cluster-scope/overlays/moc/common/groups/sa-dach.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#460 Add topic for zero cluster app logs
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/kustomization.yaml
  odh/overlays/moc/zero/kafka/overrides/kafka/overlays/topics/zero-cluster-app-logs.yaml
Labels: approved, lgtm, size/S

#465 Add PVC to kafka resource
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: approved, size/S

#468 Revert "Add PVC to kafka resource"
  odh/overlays/moc/zero/kafka/overrides/kafka/base/kafka-cluster.yaml
Labels: size/S
