Repository operate-first/apps, pull requests merged in 2021-12, with the labels that each got.

#1365 Fybrik - adding ArgoCD application manifests for Vault and Arrow Flight Module
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/arrow-flight-module.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1395 Reformat smaug kustomization to fit the kustomize cli format.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#1397 Add dashboards to check how prometheus is doing
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/overview.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/remote-write.yaml
Labels: approved, size/XXL, lgtm

#1401 Set op1st authors for doc jbook.
  docs/_config.yml
Labels: approved, size/XS, lgtm

#1405 Add docs for accessing thanos metrics
  docs/content/observatorium/thanos/README.md
  docs/content/observatorium/thanos/request_grafana_access.md
  docs/content/observatorium/thanos/request_thanos_access.md
  docs/content/observatorium/thanos/thanos_programmatic_access.md
Labels: approved, lgtm

#1398 Configure VPA custom resource for opf-trino namespace's trino-worker
  kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/vpa/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/vpa/vpa-custom-resource.yaml
Labels: size/M, lgtm

#1409 Add new gpg key and remove unneeded ones for emea rick cluster-scope.
  cluster-scope/overlays/prod/emea/rick/.sops.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/rick/oauths/operate-first-sso-secret.enc.yaml
Labels: size/L

#1393 Added VPA Custom Resource manifest to opf-trino-stage.
  kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/vpa/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/vpa/vpa-custom-resource.yaml
Labels: size/S, lgtm

#1408 [fix] thanos docs listing in jupyterbook
  docs/_toc.yml
  docs/content/observatorium/thanos/request_grafana_access.md
  docs/content/observatorium/thanos/request_thanos_access.md
  docs/content/observatorium/thanos/thanos_programmatic_access.md
Labels: size/S, lgtm

#1374 [NEU CS6620] Updated grafana dashboard
  grafana/overlays/moc/smaug/dashboards/cluster-management/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/vpa-rc-cpu-and-memory-overview.yaml
Labels: size/XL, approved, lgtm

#1414 rules for row-based data vault
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1416 Add cert manager and issuer & cert to infra cluster.
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/cert-manager.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml
  cert-manager/overlays/moc/infra/api-cert.yaml
  cert-manager/overlays/moc/infra/default-ingress-cert.yaml
  cert-manager/overlays/moc/infra/kustomization.yaml
  cert-manager/overlays/moc/infra/openshift-api-issuer.yaml
  cert-manager/overlays/moc/infra/openshift-ingress-issuer.yaml
  cert-manager/overlays/moc/infra/route53-credentials.enc.yaml
  cert-manager/overlays/moc/infra/secret-generator.yaml
  cluster-scope/overlays/prod/moc/infra/apiserver/api_server_cert.yaml
  cluster-scope/overlays/prod/moc/infra/ingresscontrollers/default-ingress-certificate.enc.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-generator.yaml
Labels: size/L, approved, do-not-merge/hold, lgtm

#1400 fix: Fix issues in manifests in apps repo
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/batchtransfers.motion.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/observatoria.core.observatorium.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.batch.curator.openshift.io/batch.curator.openshift.io_reports.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/streamtransfers.motion.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-report-manager-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/opendatahub-operator/clusterrole.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/moc-nfs-csi/storageclass.yaml
  cluster-scope/overlays/prod/emea/rick/clusterversion.yaml
  cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
  cluster-scope/overlays/prod/moc/zero/clusterversion.yaml
  cluster-scope/overlays/prod/moc/zero/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
  kubevirt-hyperconverged/base/hyperconverged.yaml
Labels: approved, size/S, lgtm

#1419 Fix issuer selector invalid formatting.
  cert-manager/overlays/moc/infra/openshift-api-issuer.yaml
  cert-manager/overlays/moc/infra/openshift-ingress-issuer.yaml
Labels: approved, size/S, lgtm

#1418 Access config changes for trino-datavault-test
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/M, approved, lgtm

#1422 fix trino config json syntax
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1403 Add horizontalpodautoscalers for thanos receive components
  cluster-scope/overlays/prod/emea/balrog/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.enc.yaml
  observatorium/base/instance/thanos/receive/statefulset.yaml
  observatorium/overlays/moc/smaug/thanos/deployments/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/horizontalpodautoscalers/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/horizontalpodautoscalers/observatorium-thanos-receive-default.yaml
  observatorium/overlays/moc/smaug/thanos/horizontalpodautoscalers/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/kustomization.yaml
Labels: size/L, approved, lgtm

#1424 Give curator group access to thanos metrics
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Labels: approved, size/XS, lgtm

#1425 Fixed the label used for the node affinity
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: approved, size/XS, lgtm

#1431 Reencrypt rick emea uwm resources with new key.
  cluster-scope/overlays/prod/emea/rick/configmaps/user-workload-monitoring-config.enc.yaml
Labels: size/L, approved, lgtm

#1433 Revert clusterID for infra to it's original cluster id
  cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
Labels: approved, size/XS, lgtm

#1435 update onboarding guide link
  docs/content/argocd-gitops/onboarding_to_argocd.md
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1411 Fix various outdated links and link formatting in docs.
  docs/content/README.md
  docs/content/about/intro.md
  docs/content/acm/adding_managed_cluster_to_argocd.md
  docs/content/acme/issuing_certificates.md
  docs/content/argocd-gitops/encrypting_applications.md
  docs/content/argocd-gitops/onboarding_to_argocd.md
  docs/content/argocd-gitops/secret_management.md
  docs/content/cluster-scope/onboarding_to_cluster.md
  docs/content/grafana/README.md
  docs/content/grafana/add_grafana_dashboard.md
  docs/content/kubeflow/README.md
  docs/content/kubeflow/kubeflow-dashboard/README.md
  docs/content/kubeflow/kubeflow-pipelines/README.md
  docs/content/observatorium/loki/README.md
  docs/content/observatorium/loki/add_loki_grafana_datasource.md
  docs/content/observatorium/thanos/README.md
  docs/content/observatorium/thanos/request_grafana_access.md
  docs/content/observatorium/thanos/request_thanos_access.md
  docs/content/observatorium/thanos/thanos_programmatic_access.md
  docs/content/observatorium/vector/README.md
  docs/content/odh/README.md
  docs/content/odh/jupyterhub/access_jupyterhub.md
  docs/content/odh/jupyterhub/add_imagestream_to_jh.md
  docs/content/odh/jupyterhub/analyze_storage.md
  docs/content/odh/jupyterhub/increase_pvc_size_jh.md
  docs/content/odh/jupyterhub/user_profiles.md
  docs/content/odh/kafka/README.md
  docs/content/odh/kafka/add_kafka_users.md
  docs/content/odh/kafka/runbook.md
  docs/content/odh/superset/add_superset_users.md
  docs/content/odh/superset/runbook.md
  docs/content/odh/trino/add_more_postgress_catalogs.md
  docs/content/odh/trino/trino_superset_user_guide.md
Labels: size/L, approved, lgtm

#1441 Remove Upstream Redis SCC's to allow ArgoCD to run on OpenShift
  argocd/base/deployments/argocd-redis_patch.yaml
Labels: size/XS, lgtm

#1440 Rename certmanager issuer secret for private key due to conflict.
  cert-manager/overlays/moc/common/openshift-ingress-issuer.yaml
Labels: approved, size/XS, lgtm

#1443 Enable prune for ocp prod argocd app.
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-ocp-prod.yaml
Labels: size/XS, lgtm

#1426 Add Thanos Store API component
  observatorium/base/instance/thanos/kustomization.yaml
  observatorium/base/instance/thanos/store-bucket-cache/kustomization.yaml
  observatorium/base/instance/thanos/store-bucket-cache/service.yaml
  observatorium/base/instance/thanos/store-bucket-cache/statefulset.yaml
  observatorium/base/instance/thanos/store-index-cache/kustomization.yaml
  observatorium/base/instance/thanos/store-index-cache/service.yaml
  observatorium/base/instance/thanos/store-index-cache/statefulset.yaml
  observatorium/base/instance/thanos/store/kustomization.yaml
  observatorium/base/instance/thanos/store/shard-0/kustomization.yaml
  observatorium/base/instance/thanos/store/shard-1/kustomization.yaml
  observatorium/base/instance/thanos/store/shard-base/kustomization.yaml
  observatorium/base/instance/thanos/store/shard-base/service.yaml
  observatorium/base/instance/thanos/store/shard-base/statefulset.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-bucket-cache-memcached.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-index-cache-memcached.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-store-shard.yaml
Labels: size/L, approved, lgtm

#1451 Update resource quota for observatorium
  cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
  observatorium/base/instance/thanos/receive/statefulset.yaml
  observatorium/overlays/moc/smaug/thanos/horizontalpodautoscalers/observatorium-thanos-receive-default.yaml
Labels: approved, size/S, lgtm

#1450 Increase osc trino memory req & limit.
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/jvm.config
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/S, do-not-merge/hold, lgtm

#1449 Add user to Fybrik user group
  cluster-scope/base/user.openshift.io/groups/fybrik/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1452 update smaug clusterversion to 4.8.23 from 4.8.4
  cluster-scope/overlays/prod/moc/smaug/clusterversion.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1453 Add users to test virtual machine capabilities
  cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1455 Upgrade grafana sub channel to v4.
  cluster-scope/base/operators.coreos.com/subscriptions/opf-grafana/subscription.yaml
Labels: approved, size/XS, lgtm

#1447 tremor-demo argocd onboarding
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/tremor-demo.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1458 Add new pub bucket info in public access docs.
  docs/content/odh/trino/access_public_bucket.md
Labels: size/XS

#1457 Add access to Grafana for the thoth team
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#1459 Refactor osc trino configs to leverage configmapgenerator.
  kfdefs/overlays/osc/osc-cl1/trino/configs/access-control.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_dev.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_iceberg_dev.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_prod.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/config-coordinator.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/config-worker.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/group-provider.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/jmx.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/jvm.config
  kfdefs/overlays/osc/osc-cl1/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/configs/log.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/node.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/password-authenticator.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/password.db
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/kustomization.yaml
  odh-manifests/osc-cl1/trino/base/kustomization.yaml
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/XL, approved, lgtm, area/service/odh

#1462 Set default storage class for kafka on smaug.
  odh-manifests/smaug/kafka/base/kafka-cluster.yaml
Labels: size/XS, lgtm

#1463 Update cluster-logging kafka creds
  cluster-logging/overlays/emea/balrog/secrets/clo-kafka.enc.yaml
  cluster-logging/overlays/emea/rick/secrets/clo-kafka.enc.yaml
  cluster-logging/overlays/moc/infra/secrets/clo-kafka.enc.yaml
  cluster-logging/overlays/moc/smaug/secrets/clo-kafka.enc.yaml
  observatorium/overlays/moc/smaug/vector/clo-kafka.enc.yaml
Labels: size/M, approved, lgtm

#1460 Some small doc fixes around gpg
  docs/content/argocd-gitops/import_dev_gpg.md
  docs/content/argocd-gitops/secret_management.md
Labels: approved, size/XS, lgtm

#1448 add: reloader manifests
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/reloader.yaml
  cluster-scope/base/core/namespaces/reloader/kustomization.yaml
  cluster-scope/base/core/namespaces/reloader/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/reloader-reloader-role-binding/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/reloader-reloader-role-binding/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/reloader-reloader-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/reloader-reloader-role/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  reloader/base/deployment.yaml
  reloader/base/kustomization.yaml
  reloader/base/serviceaccount.yaml
  reloader/overlays/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#1472 Update smaug monitoring configs to use default storageclass for PVCs
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.enc.yaml
Labels: approved, size/S, lgtm

#1474 Manually add JH SA to crb for smaug.
  odh-manifests/smaug/jupyterhub/base/jupyterhub-cluster-rolebinding.yaml
Labels: approved, lgtm

#1477 Update JH kfdef to use version v1.1.1 manifests
  kfdefs/base/jupyterhub/kfdef.yaml
Labels: size/XS, lgtm

#1479 Manually managee jh-cluster rb to avoid odh conflicts on smaug.
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/jupyterhub-cluster/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/jupyterhub-cluster/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  odh-manifests/smaug/jupyterhub/base/kustomization.yaml
Labels: size/M, approved, lgtm

#1475 Make trino configurations on smaug compatible with odh 1.1.1 updates.
  kfdefs/base/trino/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
  odh-manifests/smaug/trino/base/hive-config.yaml
  odh-manifests/smaug/trino/base/kustomization.yaml
  odh-manifests/smaug/trino/base/trino-config-secret.yaml
  odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Labels: size/L, approved, lgtm

#1480 Update trino stage configs as per odh 1.1.1
  odh-manifests/smaug-stage/trino/base/hive-config.yaml
  odh-manifests/smaug-stage/trino/base/kustomization.yaml
  odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
  odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Labels: size/L, approved, lgtm

#1481 Remove trino stage image update from kfdef on smaug.
  kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
Labels: approved, size/XS, lgtm

#1482 Update trino stage image in smaug.
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
Labels: approved, size/XS, lgtm

#1483 Update jh for ds-ml-workflows on smaug.
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
Labels: approved, size/S, lgtm

#1484 Remove jmx javaagent metric exporter from trino stage/prod on smaug.
  odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
  odh-manifests/smaug/trino/base/trino-config-secret.yaml
Labels: size/XS

#1485 Update Argo, odhdashboard, kafka, seldon kfdefs to 1.1.1
  kfdefs/base/argo/kfdef.yaml
  kfdefs/base/dashboard/kfdef.yaml
  kfdefs/base/kafka/kfdef.yaml
  kfdefs/base/seldon/kfdef.yaml
Labels: approved, size/S, lgtm

#1478 Upgrade superset to odh 1.1.1 version.
  kfdefs/base/superset/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-superset/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/superset.enc.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/supersetdb.enc.yaml
  odh-manifests/smaug/superset/base/deployment.yaml
  odh-manifests/smaug/superset/base/secret-superset.yaml
Labels: size/L, approved, lgtm

#1486 Add argo, dashboard, seldon to smaug kfdef kustomization
  kfdefs/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm
