Repository operate-first/apps, pull requests merged in 2021-06, with the labels that each got.

#691 Onboard OSC group.
  cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml
  cluster-scope/base/core/namespaces/osc-playground/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/osc/group.yaml
  cluster-scope/base/user.openshift.io/groups/osc/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/osc/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/osc/rbac.yaml
  cluster-scope/overlays/moc/common/groups/osc.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#669 Apply sre-p alertmanager config to openshift-monitoring's prometheus.
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/L

#693 Add Jupyterhub to osc playground.
  kfdefs/overlays/moc/zero/kustomization.yaml
  kfdefs/overlays/moc/zero/osc-playground/kustomization.yaml
Labels: approved, lgtm, size/S

#694 Define MachineHealthCheck for worker nodes
  cluster-scope/overlays/moc/zero/kustomization.yaml
  cluster-scope/overlays/moc/zero/machinehealthchecks/work-healthcheck.yaml
Labels: approved, lgtm, size/S

#695 Update osc quota to large.
  cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml
Labels: approved, lgtm, size/XS

#696 Add custom resourcequota for osc.
  cluster-scope/base/core/namespaces/osc-playground/kustomization.yaml
  cluster-scope/base/core/namespaces/osc-playground/resourcequota.yaml
Labels: approved, lgtm, size/S

#698 feat(dashboards): Add Kubeflow Pipelines - Tekton user perspective dashboard
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kubeflow/kfp-tekton-user.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kubeflow/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kustomization.yaml
Labels: approved, lgtm, size/XXL

#699 Increase kustomize-build test prow cpu resource
  .prow.yaml
Labels: approved, lgtm, size/XS

#697 feat(dashboards): Add JH user perspective dashboard
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/jupyterhub-user.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/kustomization.yaml
Labels: approved, lgtm, size/XXL

#702 feat: Switch Zero OCP channel to `fast`
  cluster-scope/overlays/moc/zero/clusterversion.yaml
Labels: approved, lgtm, size/XS

#704 feat: Add thoth-devops to pulp-operator namespace
  cluster-scope/base/core/namespaces/pulp-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#700 Add Loki Dashboard
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/cluster-logs-quick-search.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/operate-first/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/cluster-zero-app-logs.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/datasource/kustomization.yaml
Labels: approved, lgtm, size/L

#703 feat: Switch pulp operator to upstream catalog source
  cluster-scope/base/operators.coreos.com/catalogsources/pulp-catalog/catalogsource.yaml
Labels: approved, lgtm, size/XS

#705 chore: Update cluster version updater script when multiple updates are available
  scripts/update-cluster-version.sh
Labels: approved, lgtm, size/S

#707 change opf-jupyterhub-storage class to ocs-storagecluster-cephfs
  kfdefs/overlays/moc/zero/opf-jupyterhub/kustomization.yaml
Labels: approved, lgtm, size/XS

#708 Add user to osc group on zero cluster.
  cluster-scope/overlays/moc/common/groups/osc.enc.yaml
Labels: approved, lgtm, size/XS

#706 Add odhseldon kfdef to deploy the seldon operator
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-seldon/namespace.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
  kfdefs/base/seldon/kfdef.yaml
  kfdefs/base/seldon/kustomization.yaml
  kfdefs/overlays/dev/kustomization.yaml
  kfdefs/overlays/dev/opf-seldon/kustomization.yaml
  kfdefs/overlays/moc/zero/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-seldon/kustomization.yaml
Labels: approved, lgtm, size/M

#709 Add alertname group by label to alert config.
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/XS

#710 Update default ingress certificate
  cluster-scope/overlays/moc/zero/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: approved, lgtm, size/XS

#711 feat: Add Chris to Pulp team
  cluster-scope/overlays/moc/common/groups/pulp.enc.yaml
Labels: approved, lgtm, size/XS

#712 Add additional filters for alerts.
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/S

#714 Update odh servicemonitors
  odh-manifests/prometheus/operator/base/service-monitors/application-service-monitor.yaml
  odh-manifests/prometheus/operator/base/service-monitors/operator-service-monitor.yaml
  odh-manifests/prometheus/operator/overlays/alerts/prometheus-rules.yaml
Labels: approved, lgtm, size/S

#715 fix: change scheme for prometheus serviemonitor
  odh-manifests/prometheus/operator/base/service-monitors/application-service-monitor.yaml
Labels: approved, lgtm, size/XS

#717 moc-infra: Update default ingress certificate
  cluster-scope/overlays/moc/infra/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: approved, lgtm, size/XS

#701 feat: Upgrade Zero to 4.7.13
  cluster-scope/overlays/moc/zero/clusterversion.yaml
Labels: size/XS

#716 addendum: Add spark3.0.1 notebook image
  kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#718 Add additional inhibit and silence alert rules.
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/S

#720 Onboard redhat-cto-team.
  cluster-scope/base/core/namespaces/redhat-cto-ns/kustomization.yaml
  cluster-scope/base/core/namespaces/redhat-cto-ns/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/redhat-cto-team/group.yaml
  cluster-scope/base/user.openshift.io/groups/redhat-cto-team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/redhat-cto-team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/redhat-cto-team/rbac.yaml
  cluster-scope/overlays/moc/common/groups/redhat-cto-team.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#722 fix(alerts): ClusterOperatorDown/Degraded inhibit rule dedup
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/S

#719 feat: Install Koku operator to Zero cluster
  cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/koku-metrics-operator/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/koku-metrics-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/koku-metrics-operator/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/koku-metrics-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/koku-metrics-operator/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#724 feat: Increase CPU quota for Pulp to 8 cores
  cluster-scope/base/core/namespaces/thoth-pulp-experiments/resourcequota.yaml
Labels: approved, lgtm, size/XS

#725 Onboard mwperf team.
  cluster-scope/base/core/namespaces/mwperf-horreum/kustomization.yaml
  cluster-scope/base/core/namespaces/mwperf-horreum/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/mwperf/group.yaml
  cluster-scope/base/user.openshift.io/groups/mwperf/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/mwperf/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/mwperf/rbac.yaml
  cluster-scope/overlays/moc/common/groups/mwperf.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#723 feat: Add curator team
  cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/curator/group.yaml
  cluster-scope/base/user.openshift.io/groups/curator/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/curator/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/curator/rbac.yaml
  cluster-scope/overlays/moc/common/groups/curator.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
Labels: approved, lgtm, size/M

#727 Update thanos object storage creds
  observatorium/overlays/moc/zero/secrets/thanos-objectstorage-secret.enc.yaml
Labels: approved, lgtm, size/M

#726 Apply resource quotas to namespaces that are without one.
  cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/base/core/namespaces/as-pushgateway/kustomization.yaml
  cluster-scope/base/core/namespaces/cnv-testing/kustomization.yaml
  cluster-scope/base/core/namespaces/ds-black-flake/kustomization.yaml
  cluster-scope/base/core/namespaces/ds-example-project/kustomization.yaml
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml
  cluster-scope/base/core/namespaces/fde-audio-decoder-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-1-jump-app-cicd/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-1-jump-app-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-2-jump-app-cicd/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-2-jump-app-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-3-jump-app-cicd/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-3-jump-app-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-4-jump-app-cicd/kustomization.yaml
  cluster-scope/base/core/namespaces/lab-cicd-4-jump-app-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/m4d-blueprints/kustomization.yaml
  cluster-scope/base/core/namespaces/m4d-system/kustomization.yaml
  cluster-scope/base/core/namespaces/mesh-for-data/kustomization.yaml
  cluster-scope/base/core/namespaces/open-aiops/kustomization.yaml
  cluster-scope/base/core/namespaces/ray-odh-integration/kustomization.yaml
  cluster-scope/base/core/namespaces/sa-dach-anwendertreffen/kustomization.yaml
  cluster-scope/base/core/namespaces/sa-dach-openshift-examples/kustomization.yaml
  cluster-scope/base/core/namespaces/sdap/kustomization.yaml
  cluster-scope/base/core/namespaces/tufts-dcc-6/kustomization.yaml
  cluster-scope/base/core/namespaces/uky-hpc-workload-generator/kustomization.yaml
  cluster-scope/base/core/namespaces/ws-ml-prague/kustomization.yaml
Labels: approved, lgtm, size/M

#728 fix: Semi-revert #722
  cluster-scope/overlays/moc/common/alertmanager-main-secret.yaml
Labels: approved, lgtm, size/XS

#731 Scale down observatorium operator.
  observatorium/base/operator/deployment.yaml
Labels: approved, lgtm, size/XS

#729 Create interface on the MOC production openshift provisioning network.
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/infra/ocp-prod-provisioning-vlan.yaml
Labels: approved, lgtm, size/M

#733 Increase Apicurio Registry quota
  cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#734 Apicurio quota, bumped to large
  cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
Labels: approved, lgtm, size/XS

#736 Add thoth-station SA in `opf-monitoring`
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/serviceaccounts/thoth-station.yaml
Labels: approved, lgtm, size/XS

#738 Add odh-admins to odh namespaces.
  cluster-scope/base/core/namespaces/opf-datacatalog/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-jupyterhub/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
  cluster-scope/overlays/moc/common/groups/odh-admin.enc.yaml
Labels: approved, lgtm, size/XS

#739 Add curator ns and user.
  cluster-scope/base/core/namespaces/curator-engine/kustomization.yaml
  cluster-scope/base/core/namespaces/curator-engine/namespace.yaml
  cluster-scope/overlays/moc/common/groups/curator.enc.yaml
Labels: approved, lgtm, size/M

#741 Create argocd-readonly group for read-only access to all resources
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/kustomization.yaml
  cluster-scope/overlays/moc/common/groups/argocd-readonly.enc.yaml
Labels: approved, lgtm, size/L

#730 Update infra cluster to 4.6.31
  cluster-scope/overlays/moc/infra/clusterversion.yaml
Labels: approved, lgtm, size/XS

#742 Apply custom quota to sdap namespace.
  cluster-scope/base/core/namespaces/sdap/kustomization.yaml
  cluster-scope/base/core/namespaces/sdap/resourcequota.yaml
Labels: approved, lgtm, size/S

#747 fix: team access to namespaces
  cluster-scope/base/core/namespaces/curator-engine/kustomization.yaml
  cluster-scope/base/core/namespaces/koku-metrics-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#749 remove ipolonsk from owners
  OWNERS
Labels: approved, lgtm, size/XS

#748 chore: Use latest toolbox in CI
  .prow.yaml
Labels: approved, lgtm, size/XS

#750 Update spark operator fork destination.
  kfdefs/base/google-spark-operator/kfdef.yaml
Labels: approved, lgtm, size/XS

#740 Add events creator role to sdap.
  cluster-scope/base/core/namespaces/sdap/kustomization.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/kustomization.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/role.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/rolebinding.yaml
Labels: approved, lgtm, size/M

#751 chore: Downsize ACME operator
  acme-operator/base/deployment.yaml
  cluster-scope/base/core/namespaces/acme-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#753 fix: Use common pull secret in MOC
  cluster-scope/overlays/moc/infra/.sops.yaml
  cluster-scope/overlays/moc/infra/pull-secrets/curator-pull-secret.enc.yaml
  cluster-scope/overlays/moc/infra/pull-secrets/pull-secret.enc.yaml
  cluster-scope/overlays/moc/infra/pull-secrets/zero-pull-secret.enc.yaml
  cluster-scope/overlays/moc/infra/secret-generator.yaml
Labels: approved, lgtm, size/L

#732 Add tls authentication for opf-kafka with example users
  kfdefs/overlays/moc/zero/opf-kafka/kustomization.yaml
  odh-manifests/kafka/base/kafka-cluster.yaml
  odh-manifests/kafka/overlays/topics/kustomization.yaml
  odh-manifests/kafka/overlays/users/audio-decoder.yaml
  odh-manifests/kafka/overlays/users/kustomization.yaml
  odh-manifests/kafka/overlays/users/thoth.yaml
Labels: approved, lgtm, size/M

#735 Install Horreum operator to mwperf-horreum namespace
  cluster-scope/base/operators.coreos.com/operatorgroups/mwperf-horreum/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/mwperf-horreum/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/horreum-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/horreum-operator/subscription.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, ok-to-test, size/S

#758 fix: missing namespace in kustomization
  cluster-scope/base/core/namespaces/hostpath-provisioner/kustomization.yaml
  cluster-scope/base/core/namespaces/metallb-system/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-google-spark-operator/kustomization.yaml
Labels: approved, lgtm, size/XS

#754 Aggregate events to edit
  cluster-scope/base/core/namespaces/sdap/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/events-aggregate-to-edit/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/events-aggregate-to-edit/kustomization.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/kustomization.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/role.yaml
  cluster-scope/components/project-events-creator/sdap-mslsp/rolebinding.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
Labels: approved, lgtm, size/M

#755 fix: Share pull secrets via ArgoCD
  cluster-scope/overlays/moc/common/pull-secret.enc.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/infra/pull-secrets/curator-pull-secret.enc.yaml
  cluster-scope/overlays/moc/infra/pull-secrets/zero-pull-secret.enc.yaml
  cluster-scope/overlays/moc/infra/secret-generator.yaml
Labels: approved, lgtm, size/L

#759 fix topic prefix for kafka users
  odh-manifests/kafka/overlays/users/audio-decoder.yaml
  odh-manifests/kafka/overlays/users/thoth.yaml
Labels: approved, lgtm, size/S

#761 add kcormier
  cluster-scope/overlays/moc/infra/groups/cluster-admins.enc.yaml
Labels: approved, lgtm, size/S

#763 add user grpereir to thoth group
  cluster-scope/overlays/moc/common/groups/thoth.enc.yaml
Labels: approved, lgtm, size/XS

#768 update retention to match cache time for advises and provenance
  odh-manifests/kafka/overlays/topics/thoth-adviser-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-provenance-checker-trigger.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#765 Add fde group to opf-monitoring-view role
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#767 Update docs to use cli & remove deprecated scripts.
  docs/odh/prometheus/add_service_monitoring.md
  scripts/enable-monitoring.sh
  scripts/onboarding.sh
  scripts/tests/test-enable-monitoring.bats
  scripts/tests/test-onboarding.bats
Labels: approved, lgtm, size/L

#771 Use default url for rhcos images rather than local cache
  cluster-scope/overlays/moc/infra/kustomization.yaml
  cluster-scope/overlays/moc/infra/metal3.io/provisionings/provisioning-configuration.yaml
Labels: approved, lgtm, size/S

#752 inital onboarding for adoptium
  cluster-scope/base/core/namespaces/adoptium-project/kustomization.yaml
  cluster-scope/base/core/namespaces/adoptium-project/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/adoptium/group.yaml
  cluster-scope/base/user.openshift.io/groups/adoptium/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/adoptium/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/adoptium/rbac.yaml
  cluster-scope/overlays/moc/common/groups/adoptium.enc.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/M

#772 Added group adoptium to common kustomization.
  cluster-scope/overlays/moc/common/kustomization.yaml
Labels: approved, lgtm, size/XS

#773 Upgrade ODH to v1.1.0
  kfdefs/base/argo/kfdef.yaml
  kfdefs/base/dashboard/kfdef.yaml
  kfdefs/base/datacatalog/kfdef.yaml
  kfdefs/base/google-spark-operator/kfdef.yaml
  kfdefs/base/jupyterhub/kfdef.yaml
  kfdefs/base/kafka/kfdef.yaml
  kfdefs/base/monitoring/kfdef.yaml
  kfdefs/base/seldon/kfdef.yaml
  kfdefs/base/superset/kfdef.yaml
  observatorium/base/instance/kfdef.yaml
  odh-operator/base/kustomization.yaml
Labels: approved, lgtm, size/M

#775 Fix missing names in additional image streams
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/base/jupyterhub/notebook-images/s2i-pytorch-py38-notebook.yaml
  kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
Labels: approved, lgtm, size/S

#776 fix: JH image name is not a label
  kfdefs/base/jupyterhub/notebook-images/s2i-pytorch-py38-notebook.yaml
Labels: approved, lgtm, size/XS

#777 feature/curator ingress cert
  cluster-scope/overlays/moc/curator/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: approved, lgtm, size/XS

#778 update ray images to use ray 1.4 and include ibm codeflare
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
Labels: approved, lgtm, size/XS

#779 cleanup: remove tufts team and namespace
  cluster-scope/base/core/namespaces/tufts-dcc-6/kustomization.yaml
  cluster-scope/base/core/namespaces/tufts-dcc-6/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/tufts-dcc-6/group.yaml
  cluster-scope/base/user.openshift.io/groups/tufts-dcc-6/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/tufts-dcc-6/rbac.yaml
  cluster-scope/overlays/moc/common/groups/tufts-dcc-6.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#784 fix: Don't sync acme operator configmap
  acme-operator/overlays/moc/zero/issuer-letsencrypt-live.yaml
Labels: approved, lgtm, size/XS

#785 Fix Kafka bootstrap url in Vector configmap
  vector/overlays/moc/zero/opf-observatorium/configmap.yaml
Labels: approved, lgtm, size/XS

#769 add and remove templates to reflect current state of thoth-messaging
  odh-manifests/kafka/overlays/topics/kustomization.yaml
  odh-manifests/kafka/overlays/topics/thoth-build-analysis-trigger.yaml
  odh-manifests/kafka/overlays/topics/thoth-cve-provided.yaml
  odh-manifests/kafka/overlays/topics/thoth-kebechet-run-url.yaml
Labels: approved, lgtm, ok-to-test, size/S

#721 Prevent usage of rgw storage class for buckets.
  cluster-scope/base/core/namespaces/opf-ci-pipelines/resourcequota.yaml
  cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
  cluster-scope/base/core/namespaces/opf-datacatalog/resourcequota.yaml
  cluster-scope/base/core/namespaces/osc-playground/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-backend-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-frontend-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml
  cluster-scope/components/resourcequotas/large/resourcequotas.yaml
  cluster-scope/components/resourcequotas/medium/resourcequotas.yaml
  cluster-scope/components/resourcequotas/small/resourcequotas.yaml
  cluster-scope/components/resourcequotas/x-small/resourcequotas.yaml
Labels: approved, lgtm, size/S

#766 allow "thoth.*" group ids to for the thoth kafka user
  odh-manifests/kafka/overlays/users/thoth.yaml
Labels: approved, lgtm, size/XS

#786 feat: Deploy ACME to infra cluster
  acme-operator/overlays/moc/infra/issuer-letsencrypt-live.yaml
  acme-operator/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/S

#781 feat: onboard chi-rhug
  cluster-scope/base/core/namespaces/chi-rhug/kustomization.yaml
  cluster-scope/base/core/namespaces/chi-rhug/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/chi-rhug/group.yaml
  cluster-scope/base/user.openshift.io/groups/chi-rhug/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/chi-rhug/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/chi-rhug/rbac.yaml
  cluster-scope/overlays/moc/common/groups/chi-rhug.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#757 onboard esi-project
  cluster-scope/base/core/namespaces/esi-operate-first-project/kustomization.yaml
  cluster-scope/base/core/namespaces/esi-operate-first-project/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/esi-project/group.yaml
  cluster-scope/base/user.openshift.io/groups/esi-project/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/esi-project/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/esi-project/rbac.yaml
  cluster-scope/overlays/moc/common/groups/esi-project.enc.yaml
  cluster-scope/overlays/moc/common/kustomization.yaml
  cluster-scope/overlays/moc/common/secret-generator.yaml
  cluster-scope/overlays/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#788 feat: Add new on-call members
  slack-first/overlays/moc/zero/config.yaml
  slack-first/overlays/moc/zero/secret.enc.yaml
Labels: approved, lgtm, size/S

#794 feat: Downsize JH profiles on CPU
  odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
Labels: approved, lgtm, size/S

#787 update thoth dashboards CRDs
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
Labels: approved, lgtm, size/XS

#795 fix: Reorder on-call to keep current schedule
  slack-first/overlays/moc/zero/secret.enc.yaml
Labels: approved, lgtm, size/XS

#386 Install Service Mesh operator
  cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/kiali-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/kiali-operator/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/servicemesh-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/servicemesh-operator/subscription.yaml
Labels: approved, lgtm, size/M

#797 fix: Add acme-operator namespace to infra
  argocd/overlays/moc-infra/projects/operate-first.yaml
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#798 Add data-science group as project admins for the opf-seldon namespace
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
Labels: approved, lgtm, size/XS

#780 feat: Convert routes with cert to acme-operator
  argocd/overlays/moc-infra/kustomization.yaml
  argocd/overlays/moc-infra/routes/argocd-google.enc.yaml
  argocd/overlays/moc-infra/routes/argocd-google.yaml
  argocd/overlays/moc-infra/routes/secret-generator.yaml
  kfdefs/overlays/moc/zero/opf-dashboard/kustomization.yaml
  kfdefs/overlays/moc/zero/opf-dashboard/route.yaml
  kfdefs/overlays/moc/zero/opf-dashboard/secret-generator.yaml
Labels: approved, lgtm, size/M

#800 feat: Migrate projects to argocd-apps
  argocd/overlays/moc-infra/kustomization.yaml
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
  argocd/overlays/moc-infra/projects/b4mad.yaml
  argocd/overlays/moc-infra/projects/cluster-management.yaml
  argocd/overlays/moc-infra/projects/data-science.yaml
  argocd/overlays/moc-infra/projects/global_project.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/lab-cicd.yaml
  argocd/overlays/moc-infra/projects/mesh-for-data.yaml
  argocd/overlays/moc-infra/projects/operate-first.yaml
  argocd/overlays/moc-infra/projects/rekor.yaml
  argocd/overlays/moc-infra/projects/thoth.yaml
  argocd/overlays/moc-infra/projects/workshops.yaml
Labels: lgtm, size/XL

#802 fix: Acme roles on infra
  cluster-scope/overlays/moc/infra/kustomization.yaml
Labels: approved, lgtm, size/XS

#799 increase limit to better utilize the namespace
  cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml
Labels: approved, lgtm, size/XS

#807 increase kafka and zookeeper replicas from 3 to 5
  odh-manifests/kafka/base/kafka-cluster.yaml
Labels: size/XS

#808 increase pvc size for user ater
  kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/secret-generator.yaml
  kfdefs/overlays/moc/zero/opf-jupyterhub/pvcs/user-ater-pvc.enc.yaml
Labels: approved, lgtm, size/M

#809 Upgrade quota for ns ds-ml-workflows-ws.
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml
Labels: approved, lgtm, size/XS

#810 Add custom quota for ds-ml-workflows-ws ns
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/kustomization.yaml
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/resourcequota.yaml
Labels: approved, lgtm, size/S

#811 Update kfdef for ds-ml-workflows-ws
  kfdefs/overlays/moc/zero/ds-ml-workflows-ws/kfdef.yaml
Labels: approved, lgtm, size/XS

#813 allow 2 bucket for storage use of prow
  cluster-scope/base/core/namespaces/opf-ci-prow/resourcequota.yaml
Labels: lgtm, size/XS

#801 increase the resource limit for the graph namespace
  cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml
Labels: approved, lgtm, size/XS

#814 Update image and description for Elyra AIDevSecOps Tutorial
  kfdefs/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
Labels: approved, lgtm, size/XS

#815 feat: Add gubben to pulp team
  cluster-scope/overlays/moc/common/groups/pulp.enc.yaml
Labels: approved, lgtm, size/XS

#744 Add Xskipper to pyspark packages in spark2.4 based images
  odh-manifests/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
Labels: approved, lgtm, ok-to-test, size/XS

#816 Update the CPU limit graph
  kfdefs/overlays/moc/zero/opf-monitoring/dashboards/odh/jupyterhub-user.yaml
Labels: approved, lgtm, size/XS

#818 onboard prometheus-anomaly-detector project
  cluster-scope/base/core/namespaces/prometheus-anomaly-detector/kustomization.yaml
  cluster-scope/base/core/namespaces/prometheus-anomaly-detector/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-anomaly-detector/group.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-anomaly-detector/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/prometheus-anomaly-detector/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/prometheus-anomaly-detector/rbac.yaml
  cluster-scope/overlays/prod/common/groups/prometheus-anomaly-detector.enc.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/common/secret-generator.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, lgtm, size/L

#819 Grant prometheus anomaly detector group access to monitoring
  kfdefs/overlays/moc/zero/opf-monitoring/rolebindings/opf-monitoring-view.yaml
Labels: approved, lgtm, size/XS
