Repository operate-first/apps, pull requests merged in 2021-01, with the labels that each got.

#94 Add grafana documentation
  docs/odh/grafana/README.md
  docs/odh/grafana/add_grafana_dashboard.md
Labels: approved, size/M

#95 Add openshift-anomaly-detection notebook image to notebook-images
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/openshift-anomaly-detection.yaml
Labels: approved, size/S

#96 feat: Datacatalog manifests point to ODH master
  odh/base/datacatalog/kfdef.yaml
Labels: approved, size/S

#51 [JH] add notebook-images to jh kustomization
  odh/base/jupyterhub/kustomization.yaml
Labels: approved, size/XS

#98 Add operate-first project admin rbac to as components
  observatorium/components/rbac/kustomization.yaml
  observatorium/components/rbac/rolebinding.yaml
  observatorium/overlays/moc/kustomization.yaml
  odh/components/rbac/kustomization.yaml
  odh/components/rbac/rolebinding.yaml
  odh/overlays/moc/argo/kustomization.yaml
  odh/overlays/moc/dashboard/kustomization.yaml
  odh/overlays/moc/datacatalog/kustomization.yaml
  odh/overlays/moc/jupyterhub/kustomization.yaml
  odh/overlays/moc/kafka/kustomization.yaml
  odh/overlays/moc/monitoring/kustomization.yaml
  odh/overlays/moc/superset/kustomization.yaml
Labels: approved, size/M

#68 Add github alertmanager receiver
  odh/base/monitoring/github-receiver-service.yaml
  odh/base/monitoring/github-receiver.yaml
  odh/base/monitoring/kustomization.yaml
  odh/overlays/crc/monitoring/example-github-secret.yaml
  odh/overlays/crc/monitoring/kustomization.yaml
  odh/overlays/moc/monitoring/.sops.yaml
  odh/overlays/moc/monitoring/secrets/github-secret.enc.yaml
  odh/overlays/moc/monitoring/secrets/secret-generator.yaml
  odh/overlays/quicklab/monitoring/example-github-secret.yaml
  odh/overlays/quicklab/monitoring/kustomization.yaml
Labels: approved, size/L

#70 Add prometheus alertmanager
  odh/base/monitoring/alertmanager-config.yaml
  odh/base/monitoring/alertmanager-route.yaml
  odh/base/monitoring/alertmanager-service.yaml
  odh/base/monitoring/alertmanager.yaml
  odh/base/monitoring/kustomization.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, size/M

#102 Add time series notebook imagestream to notebook-images
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/time-series.yaml
Labels: approved, size/S

#103 Add prometheus availability alerts
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus-rules.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, size/S

#105 Add argocd admins
  namespaces/overlays/moc/argocd/kustomization.yaml
  namespaces/overlays/moc/argocd/rbac.yaml
Labels: approved, size/S

#106 fix: move issue url from labels to annotations
  namespaces/overlays/moc/mesh-for-data/namespace.yaml
  namespaces/overlays/moc/open-aiops/namespace.yaml
Labels: approved, size/XS

#107 Add user to mesh-for-data group
  namespaces/overlays/moc/mesh-for-data/group.enc.yaml
Labels: approved, size/XS

#109 Move prometheus alerting rules into overlays
  odh/base/monitoring/kfdef.yaml
  odh/base/monitoring/overrides/prometheus-operator/overlays/alerts/kustomization.yaml
  odh/base/monitoring/overrides/prometheus-operator/overlays/alerts/prometheus-rules.yaml
Labels: approved, size/XS

#111 Fix jh dashboard name
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml
Labels: approved, size/XS

#113 Remove oauth proxy from grafana
  odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/dashboards/jupyterhub-dashboard.yaml
Labels: approved, monitoring, size/M

#116 Add monitoring role and rolebinding to all odh + observatorium namespaces
  observatorium/components/rbac/kustomization.yaml
  observatorium/components/rbac/monitoring-role.yaml
  observatorium/components/rbac/monitoring-rolebinding.yaml
  odh/components/rbac/kustomization.yaml
  odh/components/rbac/monitoring-role.yaml
  odh/components/rbac/monitoring-rolebinding.yaml
  odh/overlays/moc/monitoring/kustomization.yaml
  odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
  odh/overlays/moc/monitoring/servicemonitors/observatorium-servicemonitor.yaml
Labels: approved, size/M

#117 include thoth grafana dashboard to the moc monitoring
  odh/overlays/moc/monitoring/dashboards/kustomization.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/common-patch.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/kustomization.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
  odh/overlays/moc/monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
  odh/overlays/moc/monitoring/datasource/kustomization.yaml
  odh/overlays/moc/monitoring/datasource/thoth-station-datasource.yaml
  odh/overlays/moc/monitoring/kustomization.yaml
Labels: approved, do-not-merge/hold, size/L

#122 fix and update the datasource manifest for thoth
  odh/overlays/moc/monitoring/datasource/thoth-station-datasource.yaml
Labels: approved, size/XS

#119 request for namespace required for continuous integration components
  namespaces/overlays/moc/opf-ci-pipelines/kustomization.yaml
  namespaces/overlays/moc/opf-ci-pipelines/namespace.yaml
  namespaces/overlays/moc/opf-ci-pipelines/rbac.yaml
  namespaces/overlays/moc/opf-ci-prow/kustomization.yaml
  namespaces/overlays/moc/opf-ci-prow/namespace.yaml
  namespaces/overlays/moc/opf-ci-prow/rbac.yaml
Labels: approved, size/M

#123 Add servicemonitor to monitor ODH deployed components
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
  odh/base/monitoring/overrides/prometheus-operator/base/servicemonitor.yaml
Labels: approved, size/S

#127 Remove unused Prometheus from opf-jupyterhub
  odh/base/jupyterhub/kfdef.yaml
Labels: approved, size/S

#129 Add thoth members to operate-first
  cluster-scope/overlays/moc/groups/operate-first.enc.yaml
Labels: approved, size/XS

#124 feat: Add eranra to open-aiops group
  cluster-scope/overlays/moc/groups/open-aiops.enc.yaml
Labels: approved, size/XS

#133 Fix kfdef patch positioning for jh
  odh/overlays/moc/jupyterhub/kustomization.yaml
Labels: approved, size/XS

#130 Update github receiver
  odh/base/monitoring/github-receiver-service.yaml
  odh/base/monitoring/github-receiver.yaml
Labels: approved, size/S

#132 feat: Add prow CRD
  cluster-scope/base/crds/prow.k8s.io/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/XS

#134 fix gh alert receiver service port names
  odh/base/monitoring/github-receiver-service.yaml
Labels: approved, size/XS

#136 Create new app for argocd-monitoring
  argocd-monitoring/base/rbac/kustomization.yaml
  argocd-monitoring/base/rbac/monitoring-role.yaml
  argocd-monitoring/base/rbac/monitoring-rolebinding.yaml
  argocd-monitoring/overlays/moc/argocd-monitoring/kustomization.yaml
  odh/overlays/moc/monitoring/servicemonitors/argocd-servicemonitor.yaml
  odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
Labels: approved, size/M

#141 fix gh receiver auth-token arg
  odh/base/monitoring/github-receiver.yaml
Labels: approved, size/XS

#138 Move monitoring rbac to cluster-scope
  argocd-monitoring/overlays/moc/argocd-monitoring/kustomization.yaml
  cluster-scope/base/namespaces/argocd/kustomization.yaml
  cluster-scope/base/namespaces/observatorium-operator/kustomization.yaml
  cluster-scope/base/namespaces/odh-operator/kustomization.yaml
  cluster-scope/base/namespaces/opf-argo/kustomization.yaml
  cluster-scope/base/namespaces/opf-ci-pipelines/kustomization.yaml
  cluster-scope/base/namespaces/opf-ci-prow/kustomization.yaml
  cluster-scope/base/namespaces/opf-dashboard/kustomization.yaml
  cluster-scope/base/namespaces/opf-datacatalog/kustomization.yaml
  cluster-scope/base/namespaces/opf-jupyterhub/kustomization.yaml
  cluster-scope/base/namespaces/opf-kafka/kustomization.yaml
  cluster-scope/base/namespaces/opf-monitoring/kustomization.yaml
  cluster-scope/base/namespaces/opf-observatorium/kustomization.yaml
  cluster-scope/base/namespaces/opf-superset/kustomization.yaml
  cluster-scope/base/namespaces/thoth-amun-api-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-amun-inspection-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-backend-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-bots-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-frontend-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-graph-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-infra-prod/kustomization.yaml
  cluster-scope/base/namespaces/thoth-middletier-prod/kustomization.yaml
  cluster-scope/components/monitoring-rbac/kustomization.yaml
  cluster-scope/components/monitoring-rbac/monitoring-role.yaml
  cluster-scope/components/monitoring-rbac/monitoring-rolebinding.yaml
  observatorium/components/rbac/kustomization.yaml
  observatorium/components/rbac/monitoring-role.yaml
  observatorium/components/rbac/monitoring-rolebinding.yaml
  odh/components/rbac/kustomization.yaml
  odh/components/rbac/monitoring-role.yaml
  odh/components/rbac/monitoring-rolebinding.yaml
Labels: approved, size/L

#137 feat: Update ODH Argo to latest
  odh/base/argo/kfdef.yaml
Labels: approved, size/XS

#147 Add argocd to moc cluster-scope overlay
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/XS

#145 fix gh receiver args errors
  odh/base/monitoring/github-receiver.yaml
Labels: approved, size/XS

#142 feat: Remove obsolete project-admin rbac component from ODH and Observatorium
  observatorium/components/rbac/kustomization.yaml
  observatorium/components/rbac/rolebinding.yaml
  observatorium/overlays/moc/kustomization.yaml
  odh/components/rbac/kustomization.yaml
  odh/components/rbac/rolebinding.yaml
  odh/overlays/moc/argo/kustomization.yaml
  odh/overlays/moc/dashboard/kustomization.yaml
  odh/overlays/moc/datacatalog/kustomization.yaml
  odh/overlays/moc/jupyterhub/kustomization.yaml
  odh/overlays/moc/kafka/kustomization.yaml
  odh/overlays/moc/monitoring/kustomization.yaml
  odh/overlays/moc/superset/kustomization.yaml
Labels: approved, size/M

#144 feat: Add Mailing list analysis toolkit
  odh/base/jupyterhub/notebook-images/kustomization.yaml
  odh/base/jupyterhub/notebook-images/mailing-list-analysis-toolkit.yaml
Labels: approved, size/S

#149 feat: make Prow CRD static and add aggregate cluster roles
  cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-admin.yaml
  cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-edit.yaml
  cluster-scope/base/clusterroles/prow.k8s.io/aggregate-to-view.yaml
  cluster-scope/base/clusterroles/prow.k8s.io/kustomization.yaml
  cluster-scope/base/crds/prow.k8s.io/crd.yaml
  cluster-scope/base/crds/prow.k8s.io/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/L

#121 feat: Add onboarding script
  .pre-commit-config.yaml
  hack/onboarding.sh
Labels: approved, size/L

#152 Add basic up alerts for opf services
  odh/base/monitoring/overrides/prometheus-operator/overlays/alerts/prometheus-rules.yaml
Labels: approved, size/M

#156 include @pacospace as member of thoth group
  cluster-scope/overlays/moc/groups/thoth.enc.yaml
Labels: approved, size/M

#158 Adding github secret to kustomize
  odh/overlays/moc/monitoring/kustomization.yaml
Labels: approved, size/XS

#159 servicemonitor setup for thoth-station component monitoring
  odh/overlays/moc/monitoring/servicemonitors/kustomization.yaml
  odh/overlays/moc/monitoring/servicemonitors/thoth-station-servicemonitor.yaml
Labels: approved, size/S

#157 Request for creating the thoth-deployment-examples namespace
  cluster-scope/base/namespaces/thoth-deployment-examples/kustomization.yaml
  cluster-scope/base/namespaces/thoth-deployment-examples/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
  odh/overlays/moc/monitoring/dashboards/operate-first/argocd.yaml
Labels: approved, size/S

#163 feat: Create m4d-system and m4d-blueprints namespaces
  cluster-scope/base/namespaces/m4d-blueprints/kustomization.yaml
  cluster-scope/base/namespaces/m4d-blueprints/namespace.yaml
  cluster-scope/base/namespaces/m4d-system/kustomization.yaml
  cluster-scope/base/namespaces/m4d-system/namespace.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/M

#162 Rework owners file to utilize both approvers and reviewers
  OWNERS
Labels: approved, size/XS

#153 Deploy Cluster-Logging-Operator (CLO)
  cluster-scope/base/clusterloggings/clusterLogging.yaml
  cluster-scope/base/clusterloggings/kustomization.yaml
  cluster-scope/base/namespaces/openshift-logging/kustomization.yaml
  cluster-scope/base/namespaces/openshift-logging/namespace.yaml
  cluster-scope/base/namespaces/openshift-operators-redhat/kustomization.yaml
  cluster-scope/base/namespaces/openshift-operators-redhat/namespace.yaml
  cluster-scope/base/operatorgroups/cluster-logging-operator/kustomization.yaml
  cluster-scope/base/operatorgroups/cluster-logging-operator/operatorgroup.yaml
  cluster-scope/base/operatorgroups/elastic-operator/kustomization.yaml
  cluster-scope/base/operatorgroups/elastic-operator/operatorgroup.yaml
  cluster-scope/base/subscriptions/cluster-logging-operator/kustomization.yaml
  cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
  cluster-scope/base/subscriptions/elastic-operator/kustomization.yaml
  cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/L

#165 fix: Onboarding script group and rbac conditions
  hack/onboarding.sh
Labels: approved, size/XS

#169 Update channel to 4.5 for logging operator
  cluster-scope/base/subscriptions/cluster-logging-operator/subscription.yaml
  cluster-scope/base/subscriptions/elastic-operator/subscription.yaml
Labels: approved, size/XS

#161 Add monitoring rbc for openshift-monitoring namespace
  cluster-scope/base/clusterrolebindings/metrics/kustomization.yaml
  cluster-scope/base/clusterrolebindings/metrics/metrics-clusterrolebinding.yaml
  cluster-scope/base/clusterroles/metrics/kustomization.yaml
  cluster-scope/base/clusterroles/metrics/metrics-clusterrole.yaml
  cluster-scope/base/namespaces/openshift-monitoring/kustomization.yaml
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/M

#172 fix storageclassname and redundancy policy
  cluster-scope/base/clusterloggings/clusterLogging.yaml
Labels: approved, size/S

#173 feat: Relocate ClusterLogging to a separate app
  cluster-logging/base/clusterlogging.yaml
  cluster-logging/base/kustomization.yaml
  cluster-logging/overlays/crc/kustomization.yaml
  cluster-logging/overlays/moc/kustomization.yaml
  cluster-logging/overlays/quicklab/kustomization.yaml
Labels: approved, size/S

#176 Remove cluster logging from cluster-resources as it was moved to a separate location.
  cluster-scope/overlays/moc/kustomization.yaml
Labels: approved, size/XS

#177 Add clusterrolebinding for opf prometheus to get clustermetrics
  cluster-scope/base/clusterrolebindings/metrics/cluster-metrics-federation-clusterrolebinding.yaml
  cluster-scope/base/clusterrolebindings/metrics/kustomization.yaml
Labels: approved, size/S

#151 feat: Update ODH Dashboard downstream to latest
  odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml
Labels: approved, lgtm, size/XS

#179 feat: Cluster-scope maintenance guide
  cluster-scope/README.md
Labels: approved, lgtm, size/M

#183 feat: Scale down and always fetch ODH Dashboard
  odh/base/dashboard/overrides/overlays/custom-image/deployment.yaml
  odh/base/dashboard/overrides/overlays/custom-image/kustomization.yaml
Labels: approved, lgtm, size/S

#182 Enable anonymous access to grafana
  odh/base/monitoring/kfdef.yaml
  odh/base/monitoring/overrides/grafana-operator/base/grafana.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/datasources/kustomization.yaml
  odh/base/monitoring/overrides/grafana-operator/overlays/datasources/odh-datasource.yaml
Labels: approved, lgtm, size/M

#185 Fix alerting
  odh/base/monitoring/alertmanager-config.yaml
  odh/base/monitoring/github-receiver.yaml
Labels: approved, lgtm, size/XS

#186 Add storage to opf prometheus to retain metrics for 2 weeks
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, lgtm, size/XS

#188 Increase Prometheus Storage and reduce Metrics Retention
  odh/base/monitoring/overrides/prometheus-operator/base/prometheus.yaml
Labels: approved, size/XS
