Repository operate-first/apps, pull requests merged in 2021-10, with the labels that each got.

#1101 Deploy CNV operator on Rick cluster
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kubevirt-hyperconverged.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/subscriptions/kubevirt-hyperconverged_patch.yaml
  kubevirt-hyperconverged/overlays/emea/rick/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1102 fix: Rick is missing alertreceiver namespace
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/XS, lgtm

#1100 Add PVC full alerts for Jupyterhub users
  cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
Labels: size/M, approved, lgtm

#1104 feat: Add larsks to approvers
  OWNERS
Labels: approved, size/XS, lgtm

#1103 fix: CNV app placement
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kubevirt-hyperconverged.yaml
Labels: approved, size/XS, lgtm

#1107 add limit range for seldon namespace
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
Labels: approved, size/XS, lgtm

#1099 fix: Diffing in ACM ArgoCD app
  argocd/overlays/moc-infra/configs/argo_cm/resource.exclusions
Labels: approved, size/XS, lgtm

#1111 Add users to cluster admins for demo cluster.
  cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#1112 Change demo username to lowercase.
  cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
Labels: size/XS

#1113 feat(onboarding): Add team demo-team
  cluster-scope/base/core/namespaces/demo-jupyterhub/kustomization.yaml
  cluster-scope/base/core/namespaces/demo-jupyterhub/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/demo-team/group.yaml
  cluster-scope/base/user.openshift.io/groups/demo-team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/demo-team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/demo-team/rbac.yaml
  cluster-scope/overlays/prod/emea/demo/kustomization.yaml
Labels: size/M, approved, lgtm

#1106 Add OpenDataHub Subscription to the Demo Cluster
  cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/subscription.yaml
  cluster-scope/overlays/prod/emea/demo/kustomization.yaml
Labels: approved, size/S, lgtm

#1109 setup thoth-station application in the balrog cluster
  argocd/overlays/moc-infra/applications/envs/emea/balrog/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/OWNERS
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-backend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-frontend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-graph.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-infra.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-middletier.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-advise-reporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-adviser.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-amun-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-amun-inspection.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-chat-notification.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-cve-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-backup.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-refresh.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-schema-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-sync-backend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-sync-middletier.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-investigator-message-metrics.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-investigator.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-kebechet.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-management-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-extract.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-releases.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-revsolver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-security-indicators.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-solver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-user-api.yaml
Labels: size/XL, approved, lgtm

#1114 Increase Quota for octo-ushift-dev team
  cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1116 Fix AICoE OSC demo ImageStream
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/aicoe-osc-demo.yaml
Labels: approved, size/XS, lgtm

#1117 Updating Grafana access rules
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#1096 Update argocd to 2.1.3, add application sets
  argocd/base/kustomization.yaml
  argocd/cluster-resources/kustomization.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-ocp-prod.yaml
  argocd/overlays/moc-infra/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applications.argoproj.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/applicationsets.argoproj.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/appprojects.argoproj.io/customresourcedefinition.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/XXL, lgtm

#1118 Update security context perms for argocd.
  argocd/base/deployments/argocd-application-controller_patch.yaml
  argocd/base/deployments/argocd-repo-server_patch.yaml
  argocd/base/kustomization.yaml
Labels: size/M, approved, lgtm

#1123 Add Leihao Chen to curator team on opf
  cluster-scope/base/user.openshift.io/groups/curator/group.yaml
Labels: approved, size/XS, lgtm

#1124 Increase quota for ushift-dev project
  cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1025 migrating cloudbeaver to smaug
  cloudbeaver/overlays/moc/smaug/add_configs.yaml
  cloudbeaver/overlays/moc/smaug/configs/cloudbeaver.conf
  cloudbeaver/overlays/moc/smaug/configs/initial-data-sources.conf
  cloudbeaver/overlays/moc/smaug/configs/initial-data.conf
  cloudbeaver/overlays/moc/smaug/configs/product.conf
  cloudbeaver/overlays/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#1006 migration of kfdefs: opf-superset, and opf-trino to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-superset/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/oauth-client-secret.enc.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secure-route.yaml
  kfdefs/overlays/moc/smaug/opf-trino/.sops.yaml
  kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/file-auth-secret.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/oauth-client-secret.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/opf-datacatalog-bucket.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secure-route.yaml
Labels: size/L, approved, lgtm

#1125 migrating alertreciever to smaugs
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/alertreceiver.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1129 Update authenticated users to alpha on osc superset.
  odh-manifests/osc-cl1/superset/base/secret.yaml
Labels: size/XS

#1249 Add curator postgres db to trino on smaug.
  kfdefs/overlays/moc/smaug/opf-trino/secrets/postgres-dbs.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/secret-generator.yaml
  odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
  odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Labels: size/M

#1250 Fix opf-datactalog objectbucketName to match auto generated name.
  kfdefs/overlays/moc/smaug/opf-trino/obcs/opf-datacatalog.yaml
Labels: approved, size/XS, lgtm

#1251 Give cluster metrics access to logs-insights group
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm
