Repository operate-first/apps, pull requests merged in 2021-09, with the labels that each got.

#958 feat: Allow operate-first project apps to be listed by public
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
Labels: size/XS

#959 wip: feat: create grafana for devconfus cluster
  grafana/base/datasource.yaml
  grafana/base/grafana-datasource.yaml
  grafana/base/grafana.yaml
  grafana/base/kustomization.yaml
  grafana/base/route.yaml
  grafana/overlays/emea/devconfus2021/kustomization.yaml
Labels: size/L, approved

#953 feat: move ci-prow namespace to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, size/XS, lgtm

#961 feat: Added openshift-pipelines operator for smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/subscriptions/openshift-pipelines-operator-rh_patch.yaml
Labels: size/S

#963 feat: setup opf-ci-pipelines in the smaug clusters
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: lgtm

#962 feat: add grafanadatasource to grafana
  grafana/base/grafanadatasource.enc.yaml
  grafana/base/kustomization.yaml
  grafana/base/secrets-generator.yaml
Labels: size/M

#971 add thoth-website-prod to rick
  cluster-scope/base/core/namespaces/thoth-website-prod/kustomization.yaml
  cluster-scope/base/core/namespaces/thoth-website-prod/namespace.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/S, lgtm

#974 Update default ingress certificates for infra and zero
  cluster-scope/overlays/prod/moc/infra/ingresscontrollers/default-ingress-certificate.enc.yaml
  cluster-scope/overlays/prod/moc/zero/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: size/M, approved, lgtm

#975 feat: setup clusterbinding required for ofp-ci-pipelines
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-interceptor-opf-ci-pipelines/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-interceptor-opf-ci-pipelines/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#968 feat: add mimotej to Operate First group
  cluster-scope/overlays/prod/common/groups/operate-first.enc.yaml
Labels: size/XS, lgtm

#978 feat: add sre to argocd-group
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
Labels: size/XS

#979 Rename osc phys landing trino catalog.
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
Labels: approved, size/XS, lgtm

#983 Add thoth devops as admins to openshift-pipelines on smaug.
  cluster-scope/base/core/namespaces/openshift-pipelines/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#977 feat: setup cluster resources required for tekton dashboard
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-backend.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-extensions.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-dashboard/tekton-dashboard-tenant.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-backend.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-dashboard.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-extensions.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-pipelines.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-tenant.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-dashboard/tekton-dashboard-triggers.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#984 Dex migration from clean branch
  dex/overlays/moc/smaug/dex-clients.enc.yaml
  dex/overlays/moc/smaug/dex-cm.yaml
  dex/overlays/moc/smaug/kustomization.yaml
  dex/overlays/moc/smaug/secret-generator.yaml
Labels: size/L, approved, lgtm

#985 Organize osc cluster admin and odh groups.
  cluster-scope/overlays/prod/osc/common/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/common/groups/odh-users.yaml
  cluster-scope/overlays/prod/osc/common/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-users.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/M

#986 Add cluster admin rolebinding to cluster admins in osc.
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/XS

#982 Add nmstate subscription
  cluster-scope/base/core/namespaces/openshift-nmstate/kustomization.yaml
  cluster-scope/base/core/namespaces/openshift-nmstate/namespace.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/kubernetes-nmstate-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/kubernetes-nmstate-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml
Labels: size/M, approved, lgtm

#987 Add nmstate namespace to smaug.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#988 Fix: update nmstate smaug subscription channel to a string
  cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml
Labels: approved, size/XS, lgtm

#989 Add dex namespace to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#990 Add openshift-nmstate operatorgroup
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-nmstate/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-nmstate/operatorgroup.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#991 feature/smaug nmstate
  cluster-scope/base/nmstate.io/nmstates/nmstate/kustomization.yaml
  cluster-scope/base/nmstate.io/nmstates/nmstate/nmstate.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S, lgtm

#972 Use latest for experimental elyra notebook image
  kfdefs/base/jupyterhub/notebook-images/experimental-elyra-notebook-imagestream.yaml
Labels: approved, lgtm

#947 Ingress cert in response to SMAUG Onboard #366
  cert-manager/smaug/certificate.yaml
  cert-manager/smaug/issuer.yaml
  cert-manager/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/ingresscontrollers/default.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, lgtm

#992 Remove cluster-admin generator file for smaug.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#993 Fix secret name for ingresscontroller in smaug.
  cluster-scope/overlays/prod/moc/smaug/ingresscontrollers/default.yaml
Labels: approved, size/XS, lgtm

#998 alertreciever migration to smaug
  alertreceiver/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#996 Configure NFS vlan on smaug workers
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/machineconfigs/99-vlan-210-nfs.yaml
Labels: size/M, approved, lgtm

#954 feat: move slack-first namespace to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
  slack-first/overlays/moc/smaug/config.yaml
  slack-first/overlays/moc/smaug/kustomization.yaml
  slack-first/overlays/moc/smaug/secret-generator.yaml
  slack-first/overlays/moc/smaug/secret.enc.yaml
Labels: approved, size/XS, lgtm

#994 feat: add user workload monitoring to smaug cluster
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1001 Update acm to 2.3 by updating the channel.
  cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
Labels: approved, size/XS, lgtm

#1002 Fix typo in kfdef path for trino on osc.
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
Labels: approved, size/XS, lgtm

#1003 Re-add hive.properties to osc trino catalog.
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
Labels: approved, size/S, lgtm

#1010 Add users and group mappings to osc trino.
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/M

#1008 Migrate thoth-station test namespace to rick cluster
  cluster-scope/base/core/namespaces/thoth-test-core/resourcequota.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, size/XS, lgtm

#1011 Add Democratic CSI driver to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/storageclasses/moc-nfs-csi_patch.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/secret-generator.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Labels: size/L, approved, lgtm

#1009 Include new members of thoth-station in group thoth
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Labels: approved, size/XS, lgtm

#1019 Update curator to use common pull-secret
  cluster-scope/overlays/prod/moc/curator/secret-generator.yaml
Labels: approved, size/XS, lgtm

#1020 opf-monitoring dashboard migrations to smaug
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/kubeflow/kfp-tekton-user.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/kubeflow/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/odh/jupyterhub-user.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/odh/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/argocd.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/cluster-logs-quick-search.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/cpu_usage.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/opf-availability.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/operate-first/opf-cloud-flowchart.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-compact.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-overview.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-query.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-receive.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-rule.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thanos/thanos-store.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/common-patch.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-service-metrics.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-sli-slo.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-user-api-metrics.yaml
  kfdefs/overlays/moc/smaug/opf-monitoring/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: approved, size/XXL, lgtm

#1005 migrating of kfdefs: ds-ml-workloads, google-spark-operator and kafka to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-google-spark-operator/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-kafka/kustomization.yaml
Labels: size/M, approved, lgtm

#1028 Add ai4ci cluster odhmanifest overrides.
  odh-manifests/ai4ci/jupyterhub/base/jupyterhub-configmap.yaml
  odh-manifests/ai4ci/jupyterhub/base/jupyterhub-groups-configmap.yaml
  odh-manifests/ai4ci/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
  odh-manifests/ai4ci/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
  odh-manifests/ai4ci/superset/base/deployment.yaml
  odh-manifests/ai4ci/superset/base/pvc.yaml
  odh-manifests/ai4ci/superset/base/secret-superset.yaml
  odh-manifests/ai4ci/superset/base/secret.yaml
  odh-manifests/ai4ci/trino/base/hive-config.yaml
  odh-manifests/ai4ci/trino/base/trino-catalog-secret.yaml
  odh-manifests/ai4ci/trino/base/trino-config-secret.yaml
  odh-manifests/ai4ci/trino/base/trino-coordinator-dc.yaml
  odh-manifests/ai4ci/trino/base/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#1031 Adding acme-operator to emea/rick
  acme-operator/overlays/emea/rick/issuer-letsencrypt-live.yaml
  acme-operator/overlays/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/XS, lgtm

#1030 Enable installing strimzi operator on rick
  cluster-scope/base/operators.coreos.com/subscriptions/strimzi/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/strimzi/subscription.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/S, lgtm

#1032 Allow deploying argo workflows on rick
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflow.argoproj.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/workflowtemplate.argoproj.io/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: size/M, approved, lgtm

#1034 add singleuser-profiles-gpu-ui.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/singleuser-profiles-gpu-ui.yaml
Labels: approved, size/S, lgtm

#1035 Update curator ssl certificate
  cluster-scope/overlays/prod/moc/curator/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: size/M, approved, lgtm

#1027 feat: Cleanup cert-manager config and sync from live state
  cert-manager/base/ingress-certificate.yaml
  cert-manager/base/kustomization.yaml
  cert-manager/overlays/moc/common/clouddns-dns01-na-svc-acct.enc.yaml
  cert-manager/overlays/moc/common/kustomization.yaml
  cert-manager/overlays/moc/common/openshift-ingress-issuer.yaml
  cert-manager/overlays/moc/common/secret-generator.yaml
  cert-manager/overlays/moc/smaug/certificate.yaml
  cert-manager/overlays/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1036 fixed the name of the strimzi subscription
  cluster-scope/base/operators.coreos.com/subscriptions/strimzi/subscription.yaml
Labels: approved, size/XS, lgtm

#1037 Install opf-kafka operator group in rick cluster
  cluster-scope/base/operators.coreos.com/operatorgroups/opf-kafka/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/opf-kafka/operatorgroup.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/S, lgtm

#1038 Add newuser and group to osc trino.
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1039 clean up rules.json
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#1040 Update trino version for osc cluster.
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1041 Convert trino user passwords to be more secure.
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#1043 Add default catalog to trino and remove original hive catalog.
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/default/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/kustomization.yaml
  odh-manifests/osc-cl1/trino/base/kustomization.yaml
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
Labels: size/L, approved, lgtm

#1044 Enable proxy fix for superset on ai4ci.
  odh-manifests/osc-cl1/superset/base/secret.yaml
Labels: size/XS, lgtm

#1045 Disable enable proxy for osc1 and enable for ai4ci
  odh-manifests/ai4ci/superset/base/secret.yaml
  odh-manifests/osc-cl1/superset/base/secret.yaml
Labels: approved, size/XS, lgtm

#1046 Add auth, acme, cert-manager to balrog.
  acm/overlays/moc/infra/klusterletaddonconfigs/balrog.yaml
  acm/overlays/moc/infra/kustomization.yaml
  cert-manager/overlays/moc/balrog/certificate.yaml
  cert-manager/overlays/moc/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/balrog/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/balrog/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-generator.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/kustomization.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/devconfus2021/subscriptions/openshift-pipelines-operator-rh_patch.yaml
  keycloak/overlays/moc/infra/clients/balrog.enc.yaml
  keycloak/overlays/moc/infra/clients/devconfus2021.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, approved, lgtm

#1047 Remove machineconfig that configured the NFS vlan
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/machineconfigs/99-vlan-210-nfs.yaml
Labels: size/M, approved, lgtm

#1049 Add acme to balrog.
  acme-operator/overlays/emea/balrog/issuer-letsencrypt-live.yaml
  acme-operator/overlays/emea/balrog/kustomization.yaml
Labels: approved, size/S, lgtm

#1033 setup kafka and kafdrop using strimzi in rick
  kafka/base/kustomization.yaml
  kafka/base/opf-kafdrop-route.yaml
  kafka/base/opf-kafdrop-service.yaml
  kafka/base/opf-kafdrop.yaml
  kafka/base/opf-kafka-metrics-configmaps.yaml
  kafka/base/opf-kafka.yaml
  kafka/overlays/rick/kustomization.yaml
  kafka/overlays/rick/opf-kafdrop.yaml
  kafka/overlays/rick/secrets/kustomization.yaml
  kafka/overlays/rick/secrets/opf-public-demo-user-creds.yaml
  kafka/overlays/rick/topics/kustomization.yaml
  kafka/overlays/rick/topics/thoth-advise-justification.yaml
  kafka/overlays/rick/topics/thoth-adviser-trigger.yaml
  kafka/overlays/rick/topics/thoth-build-analysis-trigger.yaml
  kafka/overlays/rick/topics/thoth-cve-provided.yaml
  kafka/overlays/rick/topics/thoth-hash-mismatch.yaml
  kafka/overlays/rick/topics/thoth-kebechet-run-url.yaml
  kafka/overlays/rick/topics/thoth-kebechet-trigger.yaml
  kafka/overlays/rick/topics/thoth-missing-package-version.yaml
  kafka/overlays/rick/topics/thoth-missing-package.yaml
  kafka/overlays/rick/topics/thoth-package-extract-trigger.yaml
  kafka/overlays/rick/topics/thoth-package-released.yaml
  kafka/overlays/rick/topics/thoth-provenance-checker-trigger.yaml
  kafka/overlays/rick/topics/thoth-qebhwt-trigger.yaml
  kafka/overlays/rick/topics/thoth-si-unanalyzed-package.yaml
  kafka/overlays/rick/topics/thoth-solved-package.yaml
  kafka/overlays/rick/topics/thoth-unresolved-package.yaml
  kafka/overlays/rick/topics/thoth-unrevsolved-package.yaml
  kafka/overlays/rick/topics/thoth-update-provides-source-distro.yaml
  kafka/overlays/rick/users/kustomization.yaml
  kafka/overlays/rick/users/thoth.yaml
Labels: size/XL, approved, lgtm

#1050 feature/add nfs vlan
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/node-labeler/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/node-labeler/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/node-labeler/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/node-labeler/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-eno1-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp4s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp5s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp65s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp65s0f1np1-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/kustomization.yaml
  node-labeler/README.md
  node-labeler/add-interface-label.sh
  node-labeler/daemonset.yaml
  node-labeler/kustomization.yaml
  node-labeler/namespace.yaml
  node-labeler/serviceaccount.yaml
Labels: size/L, approved, lgtm

#1051 Fix spelling of "namespace"
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/node-labeler/clusterrolebinding.yaml
Labels: approved, size/XS, lgtm

#1052 attach labels to all the kafka users and secrets
  kafka/overlays/rick/secrets/kustomization.yaml
  kafka/overlays/rick/secrets/opf-public-demo-user-creds.yaml
  kafka/overlays/rick/users/kustomization.yaml
  kafka/overlays/rick/users/opf-public-demo.yaml
Labels: size/M, approved, lgtm

#999 migrating kfdefs-jupyterhub prod and staging to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/aakankshaduggal.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/antter.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/bkoz.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/cdolfi.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/chauhankaranraj.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/hemajv.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/isabelizimm.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/michaelclifford.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/oindrillac.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/pacospace.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/shreyanand.yaml
Labels: size/L, approved, lgtm

#1054 Add kustomization for kfdefs app in the moc/smaug overlay
  kfdefs/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1056 Add VLAN for NESE storage
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-eno1-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp4s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp5s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp65s0f0np0-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/iface-enp65s0f1np1-vlan210.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/vlan-interfaces.yaml
Labels: size/L, approved, lgtm

#1055 feat: setup balrog cluster with thoth namespace, kafka and prometheus
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
Labels: approved, size/S, lgtm

#1057 Fix missing apiVersion in manifest
  cluster-scope/overlays/prod/moc/smaug/nodenetworkconfigurationpolicies/vlan-interfaces.yaml
Labels: approved, size/XS, lgtm

#1048 Add clustersets and gitops mgmt as per acm 2.3
  acm/overlays/moc/infra/gitopsclusters/argocd-managed.yaml
  acm/overlays/moc/infra/gitopsclusters/kustomization.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/kustomization.yaml
  acm/overlays/moc/infra/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/balrog.yaml
  acm/overlays/moc/infra/managedclusters/curator.yaml
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/ocp-prod.yaml
  acm/overlays/moc/infra/managedclusters/osc-cl1.yaml
  acm/overlays/moc/infra/managedclusters/rick.yaml
  acm/overlays/moc/infra/managedclusters/smaug.yaml
  acm/overlays/moc/infra/managedclustersetbindings/argocd-managed.yaml
  acm/overlays/moc/infra/managedclustersetbindings/kustomization.yaml
  acm/overlays/moc/infra/managedclustersets/argocd-managed.yaml
  acm/overlays/moc/infra/managedclustersets/kustomization.yaml
  acm/overlays/moc/infra/placements/argocd-managed-clusters.yaml
  acm/overlays/moc/infra/placements/kustomization.yaml
Labels: size/L, approved, do-not-merge/hold, lgtm

#1059 Add koku metrics operator to smaug.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#1060 Add grafana operator subscription to moc/smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#1061 add memory size options to os-climate cluster
  kfdefs/overlays/osc/osc-cl1/jupyterhub/profiles/singleuser-profiles-container-sizes.yaml
  odh-manifests/osc-cl1/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
Labels: approved, size/S, lgtm

#1062 Add Grafana instance to moc/smaug
  grafana/base/grafana-datasource-serviceaccount.yaml
  grafana/base/grafana.yaml
  grafana/base/kustomization.yaml
  grafana/base/route.yaml
  grafana/overlays/emea/devconfus2021/grafanadatasource.enc.yaml
  grafana/overlays/emea/devconfus2021/kustomization.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
  grafana/overlays/moc/smaug/grafanadatasource.enc.yaml
  grafana/overlays/moc/smaug/kustomization.yaml
  grafana/overlays/moc/smaug/oauth-client-secret.enc.yaml
  grafana/overlays/moc/smaug/secrets-generator.yaml
Labels: size/L, approved

#1063 Fix endpoints, add oauth aud, and adjust perms for osc trino.
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#1067 Add my keys to smaug nodes
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/99-master-ssh/machineconfig.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/99-worker-ssh/machineconfig.yaml
Labels: approved, size/XS, lgtm

#1068 Add seldon operator to opf-seldon in moc/smaug
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
Labels: approved, size/XS, lgtm

#1069 Add servicemonitors for various components
  grafana/base/kustomization.yaml
  grafana/base/servicemonitor.yaml
  kfdefs/base/argo/kustomization.yaml
  kfdefs/base/argo/servicemonitor.yaml
  kfdefs/base/jupyterhub/kustomization.yaml
  kfdefs/base/jupyterhub/servicemonitor.yaml
  kfdefs/base/kafka/kafka-podmonitors.yaml
  kfdefs/base/kafka/kustomization.yaml
  odh-operator/base/kustomization.yaml
  odh-operator/base/servicemonitor.yaml
Labels: size/L, approved, lgtm

#1071 chore: Cleanup klusterletaddonconfigs
  acm/overlays/moc/infra/klusterletaddonconfigs/alex.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/balrog.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/curator.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/kustomization.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/local-cluster.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/ocp-prod.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/osc-cl1.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/rick.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/smaug.yaml
  acm/overlays/moc/infra/klusterletaddonconfigs/zero.yaml
  acm/overlays/moc/infra/kustomization.yaml
Labels: size/M, approved, lgtm

#1072 chore: Move user workload monitoring to base
  cluster-scope/base/core/configmaps/cluster-monitoring-config/configmap.yaml
  cluster-scope/base/core/configmaps/cluster-monitoring-config/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, size/S, lgtm

#1074 fix: Attempt to ACM's sync for ArgoCD
  acm/overlays/moc/infra/managedclustersets/argocd-managed.yaml
  acm/overlays/moc/infra/provider-connections/aws-octo.enc.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/acm.yaml
Labels: size/M, approved, lgtm

#1075 feat: Add imageregistry storage to Rick
  cluster-scope/base/core/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/XS, lgtm

#1076 Rename osc trino catalogs.
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/OSC_DataCommons_Dev/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/OSC_DataCommons_Prod/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/demo1/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/secrets/s3buckets.yaml
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/L

#1077 Rename osc catalogs in kustomization
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/kustomization.yaml
Labels: approved, size/XS, lgtm

#1078 Fix osc hive dev k8s resource naming scheme.
  kfdefs/overlays/osc/osc-cl1/trino/hive-metastores/OSC_DataCommons_Dev/kustomization.yaml
Labels: approved, size/S, lgtm

#1079 Converted osc catalog names to lowercase.
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
Labels: approved, size/XS, lgtm

#1080 Update osc trino dev catalog uri.
  odh-manifests/osc-cl1/trino/base/trino-catalog-secret.yaml
Labels: approved, size/XS, lgtm

#1081 Update osc trino group perms casing.
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1082 chore: Fix formatting for kustomize edit
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/M, approved, lgtm

#1083 fix: Mark cephfs storageclass default on rick
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/storageclasses/ocs-storagecluster-cephfs_patch.yaml
Labels: approved, size/XS, lgtm

#1087 fix: Emea is missing common
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: approved, size/S, lgtm

#1090 feat(onboarding): Add cluster demo
  acm/overlays/moc/infra/managedclusters/demo.yaml
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  alertreceiver/overlays/emea/demo/kustomization.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-demo.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/alertreceiver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/emea/demo/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/demo/kustomization.yaml
  cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/demo/kustomization.yaml
  cluster-scope/overlays/prod/emea/demo/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/demo/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/demo/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/demo.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, approved, lgtm

#1084 feat(onboarding): Add team octo-ushift-dev
  cluster-scope/base/core/namespaces/ushift-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/ushift-dev/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-ushift-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-ushift-dev/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1093 Add more rigorous access control to osc trino
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/M, approved, lgtm

#1088 Add Gregory to thoth
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
Labels: approved, size/XS, lgtm

#1094 enabling workflow and workflow template CRDs
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm
