Repository operate-first/apps, pull requests merged in 2021-11, with the labels that each got.

#1253 add DanNiESh to sre user group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1213 fix: Remove nmstate from Smaug, revert to CNV
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/subscriptions/kubernetes-nmstate-operator_patch.yaml
Labels: approved, size/S, do-not-merge/hold, lgtm

#1262 Switch to https for precommit config.
  .pre-commit-config.yaml
Labels: size/XS, lgtm

#1258 chore: Migrate apicurio to smaug
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/zero/kustomization.yaml
Labels: approved, size/XS, lgtm

#1261 Include operate-first-sso-secret in generated manifests
  cluster-scope/overlays/prod/moc/curator/secret-generator.yaml
Labels: approved, size/XS, lgtm

#1259 Make ocs-external-storagecluster-ceph-rbd the default storage class
  cluster-scope/base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd/kustomization.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/ocs-external-storagecluster-ceph-rbd/storageclass.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/storageclasses/ocs-external-storagecluster-ceph-rbd.yaml
Labels: size/M, approved, lgtm

#1233 Remove demo app of apps from argocd.
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
Labels: size/XS, lgtm

#1222 creating a trial cluster
  triage-party/overlays/moc/smaug/config.yaml
Labels: approved, size/S, lgtm

#1231 Add nooba.io/backingstore to increase ceph storage
  cluster-scope/base/noobaa.io/backingstores/kustomization.yaml
  cluster-scope/base/noobaa.io/backingstores/noobaa-default-backing-store.yaml
  cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-default-backing-store_patch.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1266 Change octo aws secret key val to str.
  acm/overlays/moc/infra/provider-connections/aws-octo.enc.yaml
Labels: approved, size/S, lgtm

#1269 Make memory overview dashboard uid unique.
  grafana/base/dashboards/cluster-management/cluster-memory-overview.yaml
Labels: approved, size/XS, lgtm

#1252 Add instructions on adding postgresql connector to trino on smaug.
  docs/odh/trino/add_more_buckets.md
  docs/odh/trino/add_more_postgress_catalogs.md
Labels: size/M, lgtm

#1267 Add cnv ns to infra.
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/XS, lgtm

#1268 Remove unused jh pvcs from smaug.
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/bkoz.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/cdolfi.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/kustomization.yaml
Labels: approved, size/S, lgtm

#1271 update smaug grafana datasource to include balrog,infra,rick clusters
  grafana/overlays/moc/smaug/grafanadatasource.enc.yaml
Labels: size/M, approved, lgtm

#1272 Bind cluster admin grp to admin role in curator.
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
Labels: approved, size/XS, lgtm

#1270 Increase oindrilla's PVC on OS Climate Jupyterhub
  kfdefs/overlays/osc/osc-cl1/jupyterhub/pvcs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/pvcs/oindrillac.yaml
Labels: approved, size/S, lgtm

#1273 Document public bucket in smaug.
  docs/odh/trino/access_public_bucket.md
Labels: approved, size/S, lgtm

#1274 Reformat public bucket docs.
  docs/odh/trino/access_public_bucket.md
Labels: approved, size/S, lgtm

#1276 Add user to osc odh admin group.
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
Labels: approved, size/XS, lgtm

#1277 Updating Fybrik CRD manifests
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/batchtransfers.motion.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/streamtransfers.motion.fybrik.io/customresourcedefinition.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1280 curator-team-added
  cluster-scope/overlays/prod/moc/curator/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#1234 smaug dashboard updates
  grafana/overlays/moc/smaug/dashboards/kubeflow/kfp-tekton-user.yaml
  grafana/overlays/moc/smaug/dashboards/kubeflow/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/odh/jupyterhub-user.yaml
  grafana/overlays/moc/smaug/dashboards/odh/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/cluster-logs-quick-search.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/cpu_usage.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/opf-availability.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/opf-cloud-flowchart.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-compact.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-overview.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-query.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-receive.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-rule.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-store.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/common-patch.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1248 enabling argocd for thoth-monitoring in overlay
  argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/prod/kustomization.yaml
Labels: approved, size/XS, lgtm

#1282 Add ocp-staging cluster to ACM (and argocd).
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/ocp-staging.yaml
Labels: approved, size/XS, lgtm

#1283 Re-organize smaug grafana dashboards.
  grafana/base/dashboards/kustomization.yaml
  grafana/base/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-pod-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/namespace_cpu_and_memory_overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/node-feature-discovery.yaml
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/cpu_usage.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/opf-cloud-flowchart.yaml
Labels: size/XXL, lgtm

#1285 Deploy oservatorium loki in moc smaug
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/observatorium.yaml
  observatorium/base/instance/loki/chunk-cache/kustomization.yaml
  observatorium/base/instance/loki/chunk-cache/service.yaml
  observatorium/base/instance/loki/chunk-cache/statefulset.yaml
  observatorium/base/instance/loki/common/example-loki-objectstorage-secret.yaml
  observatorium/base/instance/loki/common/kustomization.yaml
  observatorium/base/instance/loki/common/observatorium-loki-configmap.yaml
  observatorium/base/instance/loki/compactor/kustomization.yaml
  observatorium/base/instance/loki/compactor/services/grpc.yaml
  observatorium/base/instance/loki/compactor/services/http.yaml
  observatorium/base/instance/loki/compactor/services/kustomization.yaml
  observatorium/base/instance/loki/compactor/statefulset.yaml
  observatorium/base/instance/loki/distributor/deployment.yaml
  observatorium/base/instance/loki/distributor/kustomization.yaml
  observatorium/base/instance/loki/distributor/services/grpc.yaml
  observatorium/base/instance/loki/distributor/services/http.yaml
  observatorium/base/instance/loki/distributor/services/kustomization.yaml
  observatorium/base/instance/loki/gossip-ring/kustomization.yaml
  observatorium/base/instance/loki/gossip-ring/service.yaml
  observatorium/base/instance/loki/index-query-cache/kustomization.yaml
  observatorium/base/instance/loki/index-query-cache/service.yaml
  observatorium/base/instance/loki/index-query-cache/statefulset.yaml
  observatorium/base/instance/loki/ingester/kustomization.yaml
  observatorium/base/instance/loki/ingester/services/grpc.yaml
  observatorium/base/instance/loki/ingester/services/http.yaml
  observatorium/base/instance/loki/ingester/services/kustomization.yaml
  observatorium/base/instance/loki/ingester/statefulset.yaml
  observatorium/base/instance/loki/kustomization.yaml
  observatorium/base/instance/loki/querier/kustomization.yaml
  observatorium/base/instance/loki/querier/services/grpc.yaml
  observatorium/base/instance/loki/querier/services/http.yaml
  observatorium/base/instance/loki/querier/services/kustomization.yaml
  observatorium/base/instance/loki/querier/statefulset.yaml
  observatorium/base/instance/loki/query-frontend/deployment.yaml
  observatorium/base/instance/loki/query-frontend/kustomization.yaml
  observatorium/base/instance/loki/query-frontend/services/grpc.yaml
  observatorium/base/instance/loki/query-frontend/services/http.yaml
  observatorium/base/instance/loki/query-frontend/services/kustomization.yaml
  observatorium/base/instance/loki/results-cache/kustomization.yaml
  observatorium/base/instance/loki/results-cache/service.yaml
  observatorium/base/instance/loki/results-cache/statefulset.yaml
  observatorium/overlays/moc/smaug/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/configmaps/observatorium-loki-configmap_patch.yaml
  observatorium/overlays/moc/smaug/loki/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/secrets/loki-objectstorage-secret.enc.yaml
  observatorium/overlays/moc/smaug/loki/secrets/secrets-generator.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-chunk-cache.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-compactor.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-distributor.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-index-query-cache.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-ingester.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-querier.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-query-frontend.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-results-cache.yaml
Labels: approved, size/XXL, lgtm

#1286 update `app.kubernetes.io/instance` label in loki to match argocd
  observatorium/overlays/moc/smaug/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-chunk-cache.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-compactor.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-distributor.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-index-query-cache.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-ingester.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-querier.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-query-frontend.yaml
  observatorium/overlays/moc/smaug/loki/servicemonitors/observatorium-loki-results-cache.yaml
Labels: size/S, lgtm

#1284 Add routes for ipmi access to curator cluster
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/machineconfigs/50-ipmi-route.yaml
Labels: size/M, approved, lgtm

#1287 Create app-of-apps for ocp-staging
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-ocp-staging.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
Labels: approved, size/S, lgtm

#1291 Add instructions on selecting ocp ver in quiclab docs.
  docs/development/setup_quicklab.md
Labels: size/XS, lgtm

#1289 Adding Project OTEL-DEV to Smaug
  cluster-scope/base/core/namespaces/otel-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/otel-dev/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/octo-otel-dev/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-otel-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-otel-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-otel-dev/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1275 Add public bucket to trino on Smaug.
  docs/odh/trino/add_more_buckets.md
  kfdefs/overlays/moc/smaug/opf-trino/hive-metastores/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/hive-metastores/operate-first_general/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/secrets/s3buckets.enc.yaml
  odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
Labels: size/L, lgtm

#1292 Configure curator cluster to allow 4.8 -> 4.9 upgrade
  cluster-scope/overlays/prod/moc/curator/configmaps/admin-acks.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
Labels: approved, size/XS, lgtm

#1290 enabling prometheus rule to argocd in moc-infra overlay
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: size/XS, lgtm

#1293 Adding Helm parameter to Fybrik ArgoCD application
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/fybrik.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1255 re-sync trino user groups with github teams
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/M, approved, lgtm

#1296 Allow mocops group access to ocp-staging cluster
  argocd/overlays/moc-infra/projects/mocops.yaml
Labels: approved, size/XS, lgtm

#1288 Add vector app for moc/smaug logs
  cluster-scope/base/core/namespaces/opf-observatorium/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  docs/observatorium/vector/README.md
  observatorium/base/instance/vector/deployment.yaml
  observatorium/base/instance/vector/kustomization.yaml
  observatorium/overlays/moc/smaug/kustomization.yaml
  observatorium/overlays/moc/smaug/vector/.sops.yaml
  observatorium/overlays/moc/smaug/vector/clo-kafka.enc.yaml
  observatorium/overlays/moc/smaug/vector/configmap.yaml
  observatorium/overlays/moc/smaug/vector/kustomization.yaml
  observatorium/overlays/moc/smaug/vector/secret-generator.yaml
  observatorium/overlays/moc/smaug/vector/service.yaml
Labels: size/L, approved, lgtm

#1300 [Fix] target cluster name infra logging argocd app
  argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/cluster-logging.yaml
Labels: approved, size/XS, lgtm

#1302 Set kafka/zookeeper resources in smaug
  cluster-scope/base/core/namespaces/opf-kafka/resourcequota.yaml
  odh-manifests/smaug/kafka/base/kafka-cluster.yaml
Labels: approved, size/S, lgtm

#1303 [Fix] kafka broker url in CLO configs
  cluster-logging/overlays/emea/balrog/clusterlogforwarders/clusterlogforwarder.yaml
  cluster-logging/overlays/emea/rick/clusterlogforwarders/clusterlogforwarder.yaml
  cluster-logging/overlays/moc/infra/clusterlogforwarders/clusterlogforwarder.yaml
Labels: approved, size/S, lgtm

#1307 b4mad-racing: add paolo / change argocd repoURL
  argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/racing.yml
  cluster-scope/base/user.openshift.io/groups/b4mad/group.yaml
Labels: approved, size/XS, lgtm

#1310 Adding myself to the superset users group
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1305 Add OSPO's project San Diego postgresql db to trino on smaug
  kfdefs/overlays/moc/smaug/opf-trino/secrets/postgres-dbs.enc.yaml
  odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
Labels: size/S, lgtm

#1308 prometheus-ai group added
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#1311 Add Jupyterhub resource tiers based on usage analysis
  odh-manifests/smaug/jupyterhub/base/jupyterhub-singleuser-profiles-sizes-configmap.yaml
Labels: size/M, approved, lgtm

#1312 Added my GitHub username to thoth group in group.yaml
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1313 Update configmap
  kfdefs/base/jupyterhub/kfdef.yaml
Labels: size/XS, lgtm

#1319 feat: Onboard Project Seraph
  cluster-scope/base/core/namespaces/seraph-ingress/kustomization.yaml
  cluster-scope/base/core/namespaces/seraph-ingress/namespace.yaml
  cluster-scope/base/core/namespaces/seraph-platform-mq/kustomization.yaml
  cluster-scope/base/core/namespaces/seraph-platform-mq/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
  cluster-scope/base/user.openshift.io/groups/seraph/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/seraph/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/seraph/rbac.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1316 Fybrik - adding cluster role binding for Vault
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault-server-binding/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#1320 fix apicurio destination cluster
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/registry.yml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/zero/kustomization.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1264 adding grafana dashboards to balrog and thoth argocd dashboard CRD
  grafana/overlays/moc/smaug/dashboards/thoth-station/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/common-patch.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/common-patch.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
Labels: size/L, approved, priority/important-soon, lgtm

#1323 Provide access to curator team for Grafana.
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#1278 setup namespace, rbac and roles for the tekton chains
  cluster-scope/base/core/namespaces/tekton-chains/kustomization.yaml
  cluster-scope/base/core/namespaces/tekton-chains/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/tekton-chains-controller-cluster-access.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/tekton-chains/tekton-chains-controller-tenant-access.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/tekton-chains-controller-cluster-access.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/tekton-chains/tekton-chains-controller-tenant-access.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#1326 Provide curator team editor access to Grafana
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#1324 apicurio: fix AppProject
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1329 Add grafana piechart plugin to cluster-mgmt dashboards on smaug.
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-pod-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/namespace_cpu_and_memory_overview.yaml
Labels: approved, size/S, lgtm

#1331 Add multi-cluster support to graf overview dashboards.
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml
Labels: approved, size/XXL, lgtm

#1333 Add thanos receive deployment to moc smaug
  observatorium/base/instance/thanos/common/example-thanos-objectstorage-secret.yaml
  observatorium/base/instance/thanos/common/kustomization.yaml
  observatorium/base/instance/thanos/kustomization.yaml
  observatorium/base/instance/thanos/receive-controller/configmap.yaml
  observatorium/base/instance/thanos/receive-controller/deployment.yaml
  observatorium/base/instance/thanos/receive-controller/kustomization.yaml
  observatorium/base/instance/thanos/receive-controller/role.yaml
  observatorium/base/instance/thanos/receive-controller/rolebinding.yaml
  observatorium/base/instance/thanos/receive-controller/service.yaml
  observatorium/base/instance/thanos/receive-controller/serviceaccount.yaml
  observatorium/base/instance/thanos/receive/kustomization.yaml
  observatorium/base/instance/thanos/receive/services/default-hashring.yaml
  observatorium/base/instance/thanos/receive/services/kustomization.yaml
  observatorium/base/instance/thanos/receive/services/service.yaml
  observatorium/base/instance/thanos/receive/statefulset.yaml
  observatorium/overlays/moc/smaug/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/secrets/secrets-generator.yaml
  observatorium/overlays/moc/smaug/thanos/secrets/thanos-objectstorage-secret.enc.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-receive-controller.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-receive.yaml
Labels: size/L, lgtm

#1334 update the thoth-station dashboard with new content
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
Labels: size/M, approved, lgtm

#1335 Add prometheus-anomaly-detection demo grafana dashboard
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/pad-demo.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: size/L, approved, lgtm

#1336 Add trino staging env to smaug.
  cluster-scope/base/core/namespaces/opf-trino-stage/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-trino-stage/namespace.yaml
  cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  dex/overlays/moc/smaug/dex-clients.enc.yaml
  dex/overlays/moc/smaug/dex-cm.yaml
  kfdefs/overlays/moc/smaug/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/.sops.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/hive-metastores/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/hive-metastores/operate-first_general/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/obcs/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/obcs/trino-stage-bucket.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/file-auth-secret.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/postgres-dbs.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/s3buckets.enc.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/trino-oauth.enc.yaml
  odh-manifests/smaug-stage/trino/base/hive-config.yaml
  odh-manifests/smaug-stage/trino/base/kustomization.yaml
  odh-manifests/smaug-stage/trino/base/trino-catalog-secret.yaml
  odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug-stage/trino/base/trino-route.yaml
  odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
Labels: size/XL, approved, lgtm, area/service/odh

#1338 Remotewrite smaug cluster and uwm metrics to thanos
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.yaml
Labels: approved, size/XS, lgtm

#1339 Correct op1st trino staging catalog env vars:x.
  kfdefs/overlays/moc/smaug/opf-trino-stage/secrets/file-auth-secret.enc.yaml
  odh-manifests/smaug-stage/trino/base/trino-catalog-secret.yaml
Labels: size/S, area/service/odh

#1340 Increase memory quota for trino stage on smaug.
  cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
Labels: approved, size/XS, lgtm

#1341 Add cloudbeaver stage instance to smaug.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/cloudbeaver-stage.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/cloudbeaver.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  cloudbeaver/overlays/moc/smaug-stage/add_configs.yaml
  cloudbeaver/overlays/moc/smaug-stage/configs/cloudbeaver.conf
  cloudbeaver/overlays/moc/smaug-stage/configs/initial-data-sources.conf
  cloudbeaver/overlays/moc/smaug-stage/configs/initial-data.conf
  cloudbeaver/overlays/moc/smaug-stage/configs/product.conf
  cloudbeaver/overlays/moc/smaug-stage/kustomization.yaml
Labels: size/L

#1337 Add Thanos Query/Query-Frontend deployment
  observatorium/base/instance/thanos/kustomization.yaml
  observatorium/base/instance/thanos/query-frontend/deployment.yaml
  observatorium/base/instance/thanos/query-frontend/kustomization.yaml
  observatorium/base/instance/thanos/query-frontend/service.yaml
  observatorium/base/instance/thanos/query/deployment.yaml
  observatorium/base/instance/thanos/query/kustomization.yaml
  observatorium/base/instance/thanos/query/service.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query-frontend.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query.yaml
Labels: size/L, approved, lgtm

#1342 Increase trino stage cpu quota on smaug.
  cluster-scope/base/core/namespaces/opf-trino-stage/resourcequota.yaml
Labels: approved, size/XS, lgtm

#1343 fix apicurio project
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1344 Fix thanos deployment sync issues
  cluster-scope/base/core/namespaces/opf-observatorium/resourcequota.yaml
  observatorium/base/instance/thanos/query/deployment.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query-frontend.yaml
  observatorium/overlays/moc/smaug/thanos/servicemonitors/observatorium-thanos-query.yaml
Labels: approved, size/S, lgtm

#1346 increase spu/memory resources for thanos receive sts
  observatorium/base/instance/thanos/receive/statefulset.yaml
Labels: approved, size/XS, lgtm

#1347 clean and update osc trino groups
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/S, lgtm

#1345 upgrade ACM to 2.4
  cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
Labels: size/XS, lgtm, ok-to-test

#1351 fix apicurio project
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1353 Attach PVCs to openshift-monitoring and uwm prometheuses in MOC/Smaug
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.yaml
Labels: approved, size/S, lgtm

#1356 Add osc owners to osc overlays.
  cloudbeaver/overlays/osc/OWNERS
  cluster-scope/overlays/prod/osc/OWNERS
  dex/overlays/osc/OWNERS
  kfdefs/overlays/osc/OWNERS
  odh-manifests/osc-cl1/OWNERS
Labels: size/M, approved, lgtm

#1359 default tables in osc_datacommons_dev to readable
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1315 added camel-k operator
  cluster-scope/base/operators.coreos.com/subscriptions/camel-k/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1314 docs: Updates to OCS documentation
  docs/ocs/claiming_object_store.md
  docs/ocs/runbook.md
Labels: size/L, approved, lgtm

#1364 remove '#' comments they break trino
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1360 docs: Document how to access object buckets externally
  docs/ocs/buckets-external-access.md
Labels: size/L, approved, lgtm

#1363 Add oauth proxy for opf-observatorium thanos query and receive endpoints
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-observatorium/clusterrolebinding.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  docs/observatorium/thanos/README.md
  docs/observatorium/thanos/request_thanos_access.md
  observatorium/overlays/moc/smaug/thanos/deployments/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/deployments/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/deployments/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/rolebindings/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
  observatorium/overlays/moc/smaug/thanos/roles/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/roles/opf-observatorium-view.yaml
  observatorium/overlays/moc/smaug/thanos/routes/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/routes/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/routes/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/thanos-receive-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/services/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/services/thanos-query-frontend-oauth-proxy.yaml
  observatorium/overlays/moc/smaug/thanos/services/thanos-receive-oauth-proxy.yaml
Labels: size/L, approved, lgtm

#1332 Add docs based on recent support cases.
  docs/acm/adding_managed_cluster_to_argocd.md
  docs/argocd-gitops/get_access_to_argocd.md
  docs/cluster-scope/add_user_to_group.md
  docs/odh/trino/add_more_postgress_catalogs.md
Labels: size/M

#1370 Correct conflict with configmap name for osc dev trino.
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/node.properties
  odh-manifests/osc-cl1/trino-dev/base/trino-coordinator-dc.yaml
  odh-manifests/osc-cl1/trino-dev/base/trino-worker-dc.yaml
Labels: approved, size/S, lgtm

#1373 Configure a separate osc trino dev bucket catalog.
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/catalogs/osc_datacommons_dev.properties
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/catalogs/osc_devcatalog.properties
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/hive-metastores/OSC_DevCatalog/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/hive-metastores/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/secrets/s3buckets.yaml
Labels: size/L, approved, lgtm

#1372 Update api version for gitopscluster resource in acm infra.
  acm/overlays/moc/infra/gitopsclusters/argocd-managed.yaml
Labels: approved, size/XS, lgtm

#1367 Use odh admin group for superset admins over cluster admins group.
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-users.yaml
  odh-manifests/osc-cl1/superset/base/secret.yaml
Labels: approved, size/XS, lgtm

#1375 Add prometheus-ai-project for team promethues-ai
  cluster-scope/base/core/namespaces/prometheus-ai-project/kustomization.yaml
  cluster-scope/base/core/namespaces/prometheus-ai-project/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/prometheus-ai/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/prometheus-ai/rbac.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1358 feat(onboarding): Add team tremor-demo
  cluster-scope/base/core/namespaces/tremor-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/tremor-demo/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/tremor-demo/group.yaml
  cluster-scope/base/user.openshift.io/groups/tremor-demo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/tremor-demo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/tremor-demo/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1376 Added: dystewart to on call members list
  slack-first/overlays/moc/smaug/config.yaml
Labels: approved, size/XS, lgtm

#1325 Patch the pulp instance with node affinity to allow RDX storage mode
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: approved, size/S, lgtm

#1354 Add thanos frontend grafana datasource
  grafana/overlays/moc/smaug/grafanadatasource.enc.yaml
Labels: approved, size/XS, lgtm

#1381 Fix the image tags for the pulp instance
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: approved, size/XS, lgtm

#1378 Give `prometheus-ai` group access to thanos metrics
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Labels: approved, size/XS, lgtm

#1380 Adding suppathak to Data-Science group
  cluster-scope/base/user.openshift.io/groups/data-science/group.yaml
Labels: approved, size/XS, lgtm

#1383 configure data vault demo access
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: size/M, approved, lgtm

#1385 fix bug in access control for data vault demo
  odh-manifests/osc-cl1/trino/base/trino-config-secret.yaml
Labels: approved, size/XS, lgtm

#1379 Remove reviewers list to disable auto reviewer assignment.
  OWNERS
Labels: approved, size/XS, lgtm

#1384 add schwesig to users | sort members alphabetical where needed
  cluster-scope/base/user.openshift.io/groups/data-science/group.yaml
  cluster-scope/base/user.openshift.io/groups/operate-first/group.yaml
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: size/M, approved, lgtm

#1377 [Fix] Update link in Thanos API Access doc
  docs/observatorium/thanos/request_thanos_access.md
Labels: approved, size/XS, lgtm

#1389 Update resource quota for opf-jupyterhub ns
  cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
Labels: approved, size/XS, lgtm

#1350 Correct outdated links and info in argocd docs.
  docs/argocd-gitops/onboarding_to_argocd.md
Labels: size/M, do-not-merge/hold, lgtm

#1386 Remove web-terminal operator from curator cluster
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
Labels: size/XS, lgtm

#1387 Add Elyra image to OSC
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/elyra-image.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S, lgtm, area/service/odh

#1391 Enable Remote Write for openshift monitoring tand write metrics to opf-observatorium thanos
  cluster-scope/overlays/prod/emea/balrog/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/user-workload-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-generator.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/rick/configmaps/user-workload-monitoring-config.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/secret-generator.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/user-workload-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-generator.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/user-workload-monitoring-config.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-generator.yaml
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/remote-write-emea-balrog.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/remote-write-emea-rick.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/remote-write-moc-infra.yaml
  observatorium/overlays/moc/smaug/thanos/serviceaccounts/remote-write-moc-smaug.yaml
Labels: size/XL, approved, lgtm

#1392 Add manual trigger for jbook action.
  .github/workflows/book.yml
Labels: approved, size/XS, lgtm
