Repository operate-first/apps, pull requests merged in 2022-10, with the labels that each got.

#2505 Correct date format for edb-fx topic.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
Labels: size/XS

#2507 feat(catalog): Add rest of clusters to service catalog
  service-catalog/resources.yaml
  service-catalog/resources/curator.yaml
  service-catalog/resources/jerry.yaml
  service-catalog/resources/osc-cl1.yaml
  service-catalog/resources/osc-cl2.yaml
Labels: size/M, approved, lgtm

#2439 feat(catalog): Add extra permisions to SA on infra
  cluster-scope/overlays/prod/moc/infra/clusterroles/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm

#2504 feat(catalog): Add ConfigMap for jerry in service catalog
  cluster-scope/overlays/prod/emea/jerry/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: approved, size/XS, lgtm

#2511 fix: Backstage cluster role for ACM on Infra
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin-acm/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin-acm/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm

#2513 feat: Add peribolos to service catalog
  service-catalog/apis.yaml
  service-catalog/apis/github-webhooks-consumer.yaml
  service-catalog/components.yaml
  service-catalog/components/openshift-pipelines-operator-smaug.yaml
  service-catalog/components/peribolos-controller.yaml
  service-catalog/components/probot-kubernetes.yaml
  service-catalog/components/probot-metrics.yaml
  service-catalog/domains.yaml
  service-catalog/domains/community.yaml
  service-catalog/systems.yaml
  service-catalog/systems/openshift-pipelines-smaug.yaml
  service-catalog/systems/peribolos.yaml
Labels: size/L, approved, lgtm

#2503 update Operate First logo on GitOps Docs
  docs/img/favicon.png
  docs/img/icon.png
Labels: approved, size/XS, lgtm, kind/documentation, kind/cleanup

#2516 Correct ecb-fx topic name in trino config.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
Labels: size/XS

#2498 Add docs on how to unseal and rejoin, vault node.
  docs/_toc.yml
  docs/content/vault_eso/runbook.md
  docs/content/vault_eso/unsealing_vault.md
Labels: size/L

#2517 explict rule to make system catalog readable
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: approved, size/XS, lgtm

#2514 Update the prow entrypoint image to work with new standards
  prow/overlays/smaug/imagestreamtags.yaml
Labels: approved, size/XS, lgtm

#2515 feat: Add Prow to service catalog
  service-catalog/components.yaml
  service-catalog/components/prow-controller-manager.yaml
  service-catalog/components/prow-crier.yaml
  service-catalog/components/prow-deck.yaml
  service-catalog/components/prow-ghproxy.yaml
  service-catalog/components/prow-hook.yaml
  service-catalog/components/prow-horologium.yaml
  service-catalog/components/prow-needs-rebase.yaml
  service-catalog/components/prow-plank.yaml
  service-catalog/components/prow-sinker.yaml
  service-catalog/components/prow-statusreconciler.yaml
  service-catalog/components/prow-tide.yaml
  service-catalog/systems.yaml
  service-catalog/systems/prow.yaml
Labels: size/L, approved, lgtm

#2510 onboard gingersnap
  cluster-scope/base/core/namespaces/gingersnap/kustomization.yaml
  cluster-scope/base/core/namespaces/gingersnap/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/gingersnap/group.yaml
  cluster-scope/base/user.openshift.io/groups/gingersnap/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/gingersnap/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/gingersnap/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2512 chore: Change cert manager server to prod server
  cert-manager/overlays/emea/jerry/api/issuer.yaml
  cert-manager/overlays/emea/jerry/ingress/issuer.yaml
Labels: approved, size/XS, lgtm

#2519 Aggregate servicemonitor write access to admins.
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/monitors-create-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/monitors-create-aggregate-to-admin/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2509 Vault onboarding
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  docs/_toc.yml
  docs/content/README.md
  docs/content/argocd-gitops/onboarding_to_argocd.md
  docs/content/grafana/docs/add_grafana_dashboard.md
  docs/content/observatorium/loki/loki_query_api.md
  docs/content/observatorium/vector/README.md
  docs/content/odh/seldon/README.md
  docs/content/odh/trino/trino_superset_user_guide.md
  docs/content/openmetadata/operator_manual/updating_om.md
  docs/content/prometheus/README.md
  docs/content/vault_eso/README.md
  docs/content/vault_eso/create_external_secret.md
  docs/content/vault_eso/enable_cluster_to_eso_and_vault.md
  docs/content/vault_eso/enable_es_in_namespace.md
  docs/content/vault_eso/install_es_operator_in_cluster.md
  docs/content/vault_eso/onboard_team_to_vault.md
  docs/content/vault_eso/restore_vault.md
  docs/content/vault_eso/runbook.md
  docs/content/vault_eso/write_to_vault_with_k8s.md
Labels: size/L, lgtm

#2518 feat(infra): ODF - set default storage class and enable NooBaa scheduling
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-0.moc-infra.massopen.cloud.yaml
  cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-1.moc-infra.massopen.cloud.yaml
  cluster-scope/overlays/prod/moc/infra/nodes/os-ctrl-2.moc-infra.massopen.cloud.yaml
  cluster-scope/overlays/prod/moc/infra/storageclasses/ocs-external-storagecluster-ceph-rbd.yaml
Labels: approved, size/S, lgtm

#2522 chore: Add tumido to jerry admins
  cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
Labels: size/XS

#2520 Add uwm prometheus connector to osc-cl2 trino.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/uwm_prometheus.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/trino-secret-files.yaml
Labels: approved, size/S, do-not-merge/hold, lgtm

#2495 bumping resource quota for b4mad-racing
  cluster-scope/base/core/namespaces/b4mad-racing/kustomization.yaml
  cluster-scope/base/core/namespaces/b4mad-racing/resourcequota.yaml
  grafana/overlays/moc/common/dashboards/b4mad/kustomization.yaml
  grafana/overlays/moc/common/dashboards/b4mad/telemeter.yaml
  grafana/overlays/moc/common/dashboards/kustomization.yaml
Labels: size/M, approved, lgtm

#2526 fix: Thanos storage on Infra
  cluster-scope/overlays/prod/moc/infra/externalsecrets/multiclusterhub-operator-pull-secret.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/thanos-object-storage.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/objectbucketclaims/thanos.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
Labels: approved, size/S, lgtm

#2529 Increase storage quota for sostrades.
  cluster-scope/base/core/namespaces/sostrades/resourcequota.yaml
Labels: size/XS

#2531 updating dex container image to 2.35.1
  dex/base/deployments/dex-deployment.yaml
Labels: size/XS

#2534 Upgrade openmetadata to 0.12.1
  openmetadata/base/openmetadata-dependencies/configmaps/files/pod_template.yaml
  openmetadata/base/openmetadata-dependencies/configmaps/mysql-init-scripts.yaml
  openmetadata/base/openmetadata-dependencies/configmaps/openmetadata-dependencies-config-envs.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airlfow-triggerer.yaml
  openmetadata/base/openmetadata-dependencies/poddisruptionbudgets/elasticsearch-pdb.yaml
  openmetadata/base/openmetadata-dependencies/poddisruptionbudgets/kustomization.yaml
  openmetadata/base/openmetadata-dependencies/statefulsets/mysql.yaml
  openmetadata/base/openmetadata/configmaps/files/openmetadata.yaml
  openmetadata/base/openmetadata/deployments/openmetadata.yaml
  openmetadata/overlays/osc/osc-cl2/kustomization.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/openmetadata.yaml
Labels: size/L, approved, lgtm

#2537 Onboard kepler edge demo
  cluster-scope/base/core/namespaces/kepler-edge/kustomization.yaml
  cluster-scope/base/core/namespaces/kepler-edge/namespace.yaml
  cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/S, lgtm

#2538 Add kepler edge argocd app
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kepler-edge-demo.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kustomization.yaml
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  argocd/overlays/moc-infra/projects/kepler.yaml
  argocd/overlays/moc-infra/projects/os-climate.yaml
  cluster-scope/base/user.openshift.io/groups/kepler-admins/group.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/kepler-admins.yaml
Labels: size/M, lgtm

#2540 Add user to kepler admins in osc-cl1.
  cluster-scope/overlays/prod/osc/osc-cl1/groups/kepler-admins.yaml
Labels: size/XS

#2543 Fix kepler edge namespace in kepler proj.
  argocd/overlays/moc-infra/projects/kepler.yaml
Labels: size/XS

#2536 [prow] Add branch cleaner plugin configuration
  prow/overlays/smaug/config.yaml
Labels: size/M, approved, lgtm

#2547 onboard highlander
  cluster-scope/base/core/namespaces/highlander/kustomization.yaml
  cluster-scope/base/core/namespaces/highlander/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/highlander/group.yaml
  cluster-scope/base/user.openshift.io/groups/highlander/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/highlander/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/highlander/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2544 onboard ai4cloudops
  cluster-scope/base/core/namespaces/ai4cloudops/kustomization.yaml
  cluster-scope/base/core/namespaces/ai4cloudops/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/ai4cloudops/group.yaml
  cluster-scope/base/user.openshift.io/groups/ai4cloudops/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ai4cloudops/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ai4cloudops/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2545 feat(catalog): Add new resource permissions for k8s plugin
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml
Labels: approved, size/XS, lgtm

#2549 Deploy cnbi component on aicoe-meteor namespace
  kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/cnbi/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/M, approved, lgtm

#2555 adding myself to jerry cluster admins for secret acces
  cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
Labels: size/XS

#2556 increase number of threads in pods on osc-cl2
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/containerruntimeconfigs/trino/60-set-container-pid-limit.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/containerruntimeconfigs/trino/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigpools/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigpools/osc-platform.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigs/kepler/55-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigs/kepler/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigs/trino/60-worker-kubeconfig-pid-limit.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfiguration.openshift.io/machineconfigs/trino/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-worker.yaml
Labels: size/L

#2553 Apply trino optimizations and monitoring visuals.
  grafana/overlays/osc/common/dashboards/data-pipeline-resources.yaml
  grafana/overlays/osc/common/dashboards/json/data-pipeline-resources.json
  grafana/overlays/osc/common/dashboards/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-coordinator.config
  kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-worker.config
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/co2signal-trino-schema.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/configs/monitoring-config.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/OSC_DataCommons_Dev.yaml
  kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/osc_datacommons_hive_ingest.yaml
  kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/trino-coordinator.yaml
  kfdefs/overlays/osc/osc-cl2/trino/servicemonitors/trino-workers.yaml
Labels: do-not-merge/hold, size/XXL

#2532 Disable observability for os-climate clusters.
  acm/overlays/moc/infra/managedclusters/osc-cl1.yaml
  acm/overlays/moc/infra/managedclusters/osc-cl2.yaml
Labels: size/XS, hacktoberfest

#2561 [prow] Add myself as an approver/reviewer for prow
  prow/OWNERS
Labels: approved, size/XS, lgtm

#2552 Adding myself for odh-admin (osc-cl1)
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
Labels: approved, size/XS, lgtm

#2554 Enforce use of lgtm and approved for thoth org PR merges
  prow/overlays/smaug/config.yaml
Labels: approved, size/S, lgtm

#2565 Update thoth-station grafana dashboards
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-service-metrics.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-sli-slo.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-user-api-metrics.yaml
  grafana/overlays/moc/common/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: size/S

#2570 Add node resource usage dashboard.
  grafana/overlays/common/dashboards/compute-resources-overview/cluster-node-resource-consumption.yaml
  grafana/overlays/common/dashboards/compute-resources-overview/configmaps/files/cluster-node-resource-consumption.json
  grafana/overlays/common/dashboards/compute-resources-overview/configmaps/kustomization.yaml
  grafana/overlays/common/dashboards/compute-resources-overview/kustomization.yaml
Labels: size/L, lgtm

#2548 feat(catalog): Add cluster status API documentation
  service-catalog/apis/backstage.yaml
Labels: size/L, approved, lgtm

#2571 fix: Correctly reference API endpoints
  service-catalog/apis/backstage.yaml
Labels: approved, size/XS, lgtm

#2546 fix(catalog): Add description to needs-rebase component
  service-catalog/components/prow-needs-rebase.yaml
  service-catalog/systems/prow.yaml
Labels: approved, size/XS, lgtm

#2550 Add GeoEducator to OKD WG group
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml
Labels: approved, size/XS, lgtm

#2573 add goern to odh-admin group on osc cl1
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
Labels: approved, size/XS, lgtm

#2574 Add cluster admin user to osc-cl1.
  cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
Labels: size/XS

#2575 Update project-id in riskthinking.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/riskthinking.properties
Labels: approved, size/XS, lgtm

#2577 Allow all argocd projects to deploy external secret resource.
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: approved, size/XS, lgtm

#2579 Update vault onboard docs.
  docs/content/vault_eso/onboard_team_to_vault.md
Labels: size/XS

#2578 Add cgwalters to okd-team and okd-wg groups
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/base/user.openshift.io/groups/okd-team/group.yaml
  cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml
Labels: size/XS

#2521 onboard ray-bu
  cluster-scope/base/core/namespaces/ray-bu/kustomization.yaml
  cluster-scope/base/core/namespaces/ray-bu/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/ray-bu/group.yaml
  cluster-scope/base/user.openshift.io/groups/ray-bu/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2580 Add authentication overlay to odh-dashboard in osc cl1 CNBi stage
  kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
Labels: approved, size/XS, lgtm

#2585 onboard wildfly
  cluster-scope/base/core/namespaces/wildlfy-service/kustomization.yaml
  cluster-scope/base/core/namespaces/wildlfy-service/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/wildfly/group.yaml
  cluster-scope/base/user.openshift.io/groups/wildfly/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/wildfly/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/wildfly/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M

#2584 granting vault access to the okd-team in nses okd-centos and okd-team
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-centos/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-centos/opf-vault-store.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-team/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/okd-team/opf-vault-store.yaml
Labels: size/M, approved, lgtm

#2588 Fix limitRanges for okd-team defaults
  cluster-scope/base/core/namespaces/okd-team/limits.yaml
Labels: approved, size/XS, lgtm

#2587 fix(catalog): RHACM plugin API endpoint
  service-catalog/apis/backstage.yaml
Labels: approved, size/XS, lgtm
