Repository operate-first/apps, pull requests merged in 2022-07, with the labels that each got.

#2110 Feature/add ddas user topic
  kafka/overlays/smaug/topics/ddas-commands.yaml
  kafka/overlays/smaug/topics/kustomization.yaml
  kafka/overlays/smaug/users/ddas.yaml
  kafka/overlays/smaug/users/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#2111 increased jh cpu resources
  cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
Labels: approved, size/XS, lgtm

#2113 Add cluster management runbooks to docs.
  docs/_toc.yml
  docs/content/cluster-scope/runbooks/emea/runbook.md
  docs/content/cluster-scope/runbooks/moc/runbook.md
  docs/content/cluster-scope/runbooks/runbook.md
Labels: size/M

#2112 Added a publicly visible personal sandbox for @MichaelTiemannOSC
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#2121 add durandom to sre group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: size/XS

#2122 pointing argocd applications to migrated prow
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/ci-prow-test-pods.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/ci-prow.yaml
  prow/OWNERS
  prow/README.md
  prow/add-ist
  prow/base/branchprotector.yaml
  prow/base/crier.yaml
  prow/base/deck.yaml
  prow/base/hook.yaml
  prow/base/horologium.yaml
  prow/base/imagestreams.yaml
  prow/base/ingress.yaml
  prow/base/kustomization.yaml
  prow/base/label_sync_job.yaml
  prow/base/needs-rebase.yaml
  prow/base/pipeline.yaml
  prow/base/plank.yaml
  prow/base/prow-controller-manager.yaml
  prow/base/sinker.yaml
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug-test-pods/crier_rbac.yaml
  prow/overlays/smaug-test-pods/deck_rbac.yaml
  prow/overlays/smaug-test-pods/kustomization.yaml
  prow/overlays/smaug-test-pods/prow-controller-manager_rbac.yaml
  prow/overlays/smaug-test-pods/sinker_rbac.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/ghproxy.yaml
  prow/overlays/smaug/imagestreamtags.yaml
  prow/overlays/smaug/integration-test-configmap.yaml
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/plugins.yaml
  prow/overlays/smaug/route-ghproxy-metrics.yaml
  prow/overlays/smaug/routes.yaml
  prow/overlays/smaug/s3-storage.yaml
  prow/overlays/smaug/secret-generator.yaml
  prow/overlays/smaug/secrets.enc.yaml
  prow/overlays/smaug/service-monitor.yaml
  prow/overlays/smaug/unsuspend_branchprotector.yaml
Labels: do-not-merge/invalid-owners-file, size/XXL

#2127 feat: Add logos to service catalog components
  service-catalog/components/argo.yaml
  service-catalog/components/dex.yaml
  service-catalog/components/grafana.yaml
  service-catalog/components/observatorium.yaml
  service-catalog/components/odf.yaml
  service-catalog/components/odh.yaml
Labels: approved, size/S, lgtm

#2130 Strimzi operator subscription targeting default openshift-operators ns
  cluster-scope/base/operators.coreos.com/subscriptions/strimzi-global-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/strimzi-global-operator/subscription.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/S, lgtm

#2133 Reencrypt grafana datasource in smaug.
  grafana/overlays/moc/smaug/datasources/.sops.yaml
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
Labels: size/M

#2134 Rotate grafana datasource tokens.
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
Labels: size/M, approved, lgtm

#2135 Sync grafana datasource tokens with live.
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
Labels: size/M, approved, lgtm

#1917 Adding pod monitor for seldon
  kfdefs/overlays/moc/smaug/seldon/kustomization.yaml
  kfdefs/overlays/moc/smaug/seldon/seldon-podmonitor.yaml
  kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
Labels: approved, size/S, lgtm

#2129 feat: Add ArgoCD widget to components service catalog
  service-catalog/components/argo.yaml
  service-catalog/components/dex.yaml
  service-catalog/components/grafana.yaml
  service-catalog/components/observatorium.yaml
  service-catalog/components/odf.yaml
  service-catalog/components/odh.yaml
Labels: approved, size/XS, lgtm

#2138 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: size/XL, approved, lgtm

#2139 Use tektonconfig instead of configmap.
  cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/configmap.yaml
  cluster-scope/base/operator.tekton.dev/tektonconfigs/config/kustomization.yaml
  cluster-scope/base/operator.tekton.dev/tektonconfigs/config/tektonconfig.yaml
  cluster-scope/bundles/openshift-pipelines/kustomization.yaml
Labels: size/M

#2140 Fix artifact passing in kfp on osc-cl2 & smaug.
  kfp-tekton/base/deployments/ml-pipeline.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/base/secrets/mlpipeline-minio-artifact.yaml
  kfp-tekton/overlays/moc/smaug/kustomization.yaml
  kfp-tekton/overlays/moc/smaug/params.yaml
  kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-minio-artifact.enc.yaml
  kfp-tekton/overlays/osc/osc-cl2/kustomization.yaml
  kfp-tekton/overlays/osc/osc-cl2/params.yaml
  kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-minio-artifact.enc.yaml
Labels: size/L

#2142 :zap: Update the new datasource sa token for grafana
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
Labels: size/M, approved, lgtm

#2143 Onboard aiops-tools workshop.
  cluster-scope/base/core/namespaces/aiops-tools-workshop/kustomization.yaml
  cluster-scope/base/core/namespaces/aiops-tools-workshop/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/aiops-tools-workshop-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/aiops-tools-workshop-admins/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2146 Correct typo in namespace display name.
  cluster-scope/base/core/namespaces/aiops-tools-workshop/namespace.yaml
Labels: size/XS

#2148 Replace secrets
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/dex/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  docs/content/vault_eso/runbook.md
Labels: size/S

#2141 feat(service-catalog): Add github slugs to components
  service-catalog/components/argo.yaml
  service-catalog/components/dex.yaml
  service-catalog/components/grafana.yaml
  service-catalog/components/observatorium.yaml
  service-catalog/components/odf.yaml
  service-catalog/components/odh.yaml
Labels: approved, size/XS, lgtm

#2136 fix: Fix issues in manifests apps repository
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fetchdata.curatoropertor.openshift.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-manager-role/clusterrole.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-compute-notebook.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-g.yaml
  node-labeler/serviceaccount.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
  openmetadata/base/openmetadata-dependencies/services/mysql-headless.yaml
  openmetadata/base/openmetadata-dependencies/services/mysql.yaml
  openmetadata/base/openmetadata-dependencies/statefulsets/elasticsearch.yaml
  openmetadata/base/openmetadata-dependencies/statefulsets/mysql.yaml
  openmetadata/base/openmetadata/jobs/openmetadata-db-migrations-hook.yaml
  prow/overlays/smaug/ghproxy.yaml
  prow/overlays/smaug/imagestreamtags.yaml
  vault/overlays/moc/smaug/backup-job/cronjob.yaml
Labels: size/L, approved, lgtm

#2152 Use alpha api fields for tekton.
  cluster-scope/base/operator.tekton.dev/tektonconfigs/config/tektonconfig.yaml
Labels: size/XS

#2154 Added suppathak as workshop admin
  cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/group.yaml
Labels: size/XS

#2149 feat(service-catalog): Add peribolos-as-a-service and probot-extensions to service catalog
  service-catalog/all-components.yaml
  service-catalog/components/peribolos-as-a-service.yaml
  service-catalog/components/probot-extensions.yaml
Labels: size/M, approved, lgtm

#2155 Switch to external secrets for smaug cluster scope.
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/image-registry-private-configuration-user.yaml
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/rook-ceph-external-cluster-details.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/image-registry-private-configuration-user.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/rook-ceph-external-cluster-details.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/secret-generator.yaml
Labels: size/L

#2156 feat(service-catalog): Add clusterrolebinding and clusterrole required for k8s plugin in backstage
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2162 Add project admin and view options for strimzi.
  cluster-scope/base/core/namespaces/kafka/kustomization.yaml
  cluster-scope/base/core/namespaces/kafka/namespace.yaml
  cluster-scope/base/core/namespaces/openshift-operators/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/strimzi-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/strimzi-aggregate-to-admin/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/kafka-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/kafka-admins/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/openshift-operators-admin/group.yaml
  cluster-scope/base/user.openshift.io/groups/openshift-operators-admin/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/openshift-operators-view/group.yaml
  cluster-scope/base/user.openshift.io/groups/openshift-operators-view/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kafka-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kafka-admins/rbac.yaml
  cluster-scope/components/project-admin-rolebindings/openshift-operators-admin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/openshift-operators-admin/rbac.yaml
  cluster-scope/components/project-view-rolebindings/openshift-operators-view/kustomization.yaml
  cluster-scope/components/project-view-rolebindings/openshift-operators-view/rbac.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/kafka-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/openshift-operators-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/openshift-operators-view.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  kafka/overlays/osc/osc-cl2/kustomization.yaml
Labels: size/L, approved, lgtm

#2164 Add Eric Ball and Ryan Day to OSC and Smaug admin
  cluster-scope/base/user.openshift.io/groups/osc-admins/group.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-osc-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Labels: approved, size/XS

#2167 Add kafka testing namespace in osc-cl2.
  cluster-scope/base/core/namespaces/markets-svc-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/markets-svc-dev/namespace.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/S, lgtm

#2168 Resolving service account naming issue from curator-operator
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-manager-rb/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-oauth-proxy-rb/clusterrolebinding.yaml
  curator-operator-system/base/rbac.authorization.k8s.io/rolebindings/rolebinding.yaml
  curator-operator-system/base/serviceaccounts/serviceaccount.yaml
Labels: approved, size/XS, lgtm

#2169 Add aiops tools workshop admins.
  cluster-scope/base/user.openshift.io/groups/aiops-tools-workshop-admins/group.yaml
Labels: size/XS

#2172 Add argocd app & proj for aiops tools workshop.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/workshops/aiops-tools-workshop.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/workshops/kustomization.yaml
  argocd/overlays/moc-infra/projects/workshops.yaml
Labels: size/M

#2176 adding scsaol group to opf-observatorium-view rolebinding
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Labels: approved, size/XS, lgtm

#2178 Added Traytorous to vault-moc-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-moc-admins.yaml
Labels: approved, size/XS, lgtm

#2180 Provide cluster reader for osc clusters to user.
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-readers.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-readers.yaml
Labels: size/XS, lgtm

#2183 Correct workshoip cloudbeaver's memory request.
  workshops/aiops-tools/smaug/patches/cb_resources_patch.yaml
Labels: approved, size/XS, lgtm

#2184 Adjust aiops tools workshop jh sizes.
  workshops/aiops-tools/base/odh-configs/jupyterhub/container-sizes.yaml
  workshops/aiops-tools/base/odh-configs/jupyterhub/jupyterhub-singleuser-profiles-configmap.yaml
Labels: approved, size/XS, lgtm

#2185 Add set up docs for aiops tools workshop.
  workshops/aiops-tools/README.md
  workshops/aiops-tools/base/dex/configmaps/files/config.yaml
  workshops/aiops-tools/base/dex/configmaps/kustomization.yaml
  workshops/aiops-tools/base/dex/kustomization.yaml
  workshops/aiops-tools/base/external-secrets-operator/kustomization.yaml
  workshops/aiops-tools/base/secrets/dex-clients.yaml
  workshops/aiops-tools/base/secrets/file-auth-secret.yaml
  workshops/aiops-tools/base/secrets/kustomization.yaml
  workshops/aiops-tools/base/secrets/postgres-dbs.yaml
  workshops/aiops-tools/base/secrets/s3buckets.yaml
  workshops/aiops-tools/base/secrets/superset-custom.yaml
  workshops/aiops-tools/base/secrets/supersetdb.yaml
  workshops/aiops-tools/base/secrets/trino-oauth.yaml
Labels: size/L, lgtm

#2182 Add aiops-tools-workshop monitoring dashboard.
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/workshops/aiops-tools-workshop.yaml
  grafana/overlays/moc/smaug/dashboards/workshops/kustomization.yaml
Labels: approved, size/XXL

#2177 Updating curator-operator fetchdata and report crds
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fetchdata.curator.operatefirst.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fetchdata.curator.operatefirst.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reportapis.curator.operatefirst.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reportapis.curator.operatefirst.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/customresourcedefinition.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-manager-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-api-editor-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-api-editor-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-api-viewer-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-api-viewer-role/kustomization.yaml
  cluster-scope/bundles/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#2179 feat(schema-store): Add service account for schema store
  cluster-scope/base/core/serviceaccounts/schemastore-ci/kustomization.yaml
  cluster-scope/base/core/serviceaccounts/schemastore-ci/serviceaccount.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/S, lgtm

#2188 fix: Fix issues in clusters
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-p.yaml
Labels: approved, size/XS, lgtm

#2187 Added fybrik bundle and groups to osc-cl2
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/XS, lgtm

#2194 curator-operator curatorconfig crd cluster roles
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-curatorconfig-editor-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-curatorconfig-editor-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-curatorconfig-viewer-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-curatorconfig-viewer-role/kustomization.yaml
  cluster-scope/bundles/curator/kustomization.yaml
Labels: size/M, approved, lgtm

#2191 Update the list of users in fybrik group.
  cluster-scope/base/user.openshift.io/groups/fybrik/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2196 Added argocd yaml for curator-operator
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/curator-operator.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
Labels: approved, size/S, lgtm

#2166 feat(service-catalog): Add k8s plugin annotation to peribolos
  service-catalog/components/peribolos-as-a-service.yaml
Labels: approved, size/XS, lgtm

#2199 Added ravitejamanepalli in argocd-readonly group
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
Labels: approved, size/XS, lgtm

#2175 Configured alerts for Seldon and Trino
  kfdefs/overlays/moc/smaug/seldon/alerts.yaml
  kfdefs/overlays/moc/smaug/seldon/kustomization.yaml
  kfdefs/overlays/moc/smaug/seldon/seldon-servicemonitor.yaml
  kfdefs/overlays/moc/smaug/trino/alerts.yaml
  kfdefs/overlays/moc/smaug/trino/kustomization.yaml
Labels: size/M, approved, lgtm

#2197 Added stackrox namespace
  cluster-scope/base/core/namespaces/stackrox/kustomization.yaml
  cluster-scope/base/core/namespaces/stackrox/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2201 Add openmetadata-admins group to the openmetadata namespace
  cluster-scope/base/core/namespaces/openmetadata/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/openmetadata-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/openmetadata-admins/rbac.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/openmetadata-admins.yaml
  openmetadata/base/openmetadata-dependencies/persistentvolumeclaims/airflow-logs.yaml
Labels: approved, size/S, lgtm
