Repository operate-first/apps, pull requests merged in 2022-05, with the labels that each got.

#1942 Remove demo managed cluster from acm.
  acm/overlays/moc/infra/managedclusters/demo.yaml
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
Labels: size/XS

#1941 Changing smaug cluster auth to be managed by identitatem
  acm/overlays/moc/infra/managedclusters/smaug.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/smaug/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/smaug.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, lgtm

#1923 Increase ns quota for datahub on osc-cl1.
  cluster-scope/base/core/namespaces/datahub-linkedin/kustomization.yaml
  cluster-scope/base/core/namespaces/datahub-linkedin/resourcequota.yaml
Labels: approved, size/S, lgtm

#1943 Switch curator, infra, rick to use identitatem.
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/rick/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/rick/secret-generator.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/curator/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/prod/moc/curator/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/moc/curator/secret-generator.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/moc/infra/oauths/moc-sso-client-secret.enc.yaml
  cluster-scope/overlays/prod/moc/infra/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/moc/infra/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/curator.enc.yaml
  keycloak/overlays/moc/infra/clients/demo.enc.yaml
  keycloak/overlays/moc/infra/clients/infra.enc.yaml
  keycloak/overlays/moc/infra/clients/rick.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/XL

#1945 Remove oauths inherited from base for idp clusters
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: size/XS

#1946 Switch moc infra auth.
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/local-cluster.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/oauth/clients/github.enc.yaml
  cluster-scope/overlays/prod/moc/infra/oauth/clients/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/oauth/clients/secret-generator.yaml
  cluster-scope/overlays/prod/moc/infra/oauth/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/oauth/oauth.yaml
Labels: size/L

#1947 Add new group with access to acm cluster provisioning.
  acm/overlays/moc/infra/managedclustersetbindings/base/drvbw.yaml
  acm/overlays/moc/infra/managedclustersetbindings/base/kustomization.yaml
  acm/overlays/moc/infra/managedclustersets/drvbw.yaml
  acm/overlays/moc/infra/managedclustersets/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:drvbw/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/open-cluster-management:managedclusterset:admin:drvbw/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/drvbw/group.yaml
  cluster-scope/base/user.openshift.io/groups/drvbw/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/clusterrolebindings/self-provisioners_patch.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: size/M, lgtm

#1949 Add kluster addon config editor rolebinding.
  cluster-scope/overlays/prod/moc/infra/clusterrolebindings/klusteraddonconfig-editor.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm

#1951 Remove unused field for nfd in morty.
  nfd/base/nfd.yaml
Labels: size/XS, lgtm

#1937 onboarding ns api-designer for team apicurio
  cluster-scope/base/core/namespaces/api-designer/kustomization.yaml
  cluster-scope/base/core/namespaces/api-designer/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S, lgtm

#1959 Update container image registry in Smaug to use OBC instead of PVC
  cluster-scope/overlays/prod/moc/smaug/imageregistry.operator.openshift.io/configs/cluster/config_patch.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/objectbucketclaims/openshift-image-registry-bucket.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-generator.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/image-registry-private-configuration-user.enc.yaml
Labels: size/L, approved, lgtm

#1922 set peribolos-as-a-service argo app for deployment
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/open-services-group/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/open-services-group/peribolos-as-a-service.yaml
Labels: size/M, approved, lgtm

#1961 fix: Peribolos service app project server settings
  argocd/overlays/moc-infra/projects/peribolos-service.yaml
Labels: approved, size/XS, lgtm

#1732 Adding external secrets operator subscription and deploying to smaug
  cluster-scope/base/operators.coreos.com/subscriptions/external-secrets-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/external-secrets-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1965 Add ocp route for vault on smaug.
  vault/base/kustomization.yaml
  vault/base/route/kustomization.yaml
  vault/base/route/route.yaml
Labels: approved, size/S, lgtm

#1967 Remove Fabian, Add Enda to group apicurio
  cluster-scope/base/user.openshift.io/groups/apicurio/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1966 trino acl dsl 0.3.1
  .pre-commit-config.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/trino-acl-dsl.yaml
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/XL, lgtm

#1977 Switch back to default alertmanager config.
  cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secrets/files/alertmanager.yaml
  cluster-scope/overlays/prod/emea/balrog/secrets/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/secrets/files/alertmanager.yaml
  cluster-scope/overlays/prod/emea/morty/secrets/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/secrets/files/alertmanager.yaml
  cluster-scope/overlays/prod/emea/rick/secrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secrets/files/alertmanager.yaml
  cluster-scope/overlays/prod/moc/infra/secrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-generator.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/files/alertmanager.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/secret-generator.yaml
Labels: size/L, approved, lgtm

#1976 Add a second noobaa backing store and associated bucketclass
  cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-pool-01.yaml
  cluster-scope/overlays/prod/moc/smaug/bucketclasses/noobaa-pool-01-bucket-class.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S

#1981 Add shared secret to trino.
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
  kfdefs/overlays/osc/osc-cl2/trino/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/shared-secret.yaml
Labels: size/M

#1983 Add External Secrets instance to smaug.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/external-secrets.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  cluster-scope/base/core/namespaces/external-secrets-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/external-secrets-operator/namespace.yaml
  cluster-scope/bundles/external-secrets-operator/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  docs/_toc.yml
  docs/content/external-secrets/README.md
  docs/content/external-secrets/add_eso_to_cluster.md
  external-secrets/base/eso.yaml
  external-secrets/base/kustomization.yaml
  external-secrets/overlay/moc/smaug/kustomization.yaml
Labels: size/L

#1985 Fix the crd of extension tekton dashboard
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/customresourcedefinition.yaml
Labels: size/XS, lgtm

#1986 upgrade the ray jupyterhub instance with latest ray
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
  kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
Labels: size/S

#1980 Add pool to default bucket class
  cluster-scope/overlays/prod/moc/smaug/bucketclasses/noobaa-default-bucket-class.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S

#1989 Fix the labels of cm feature flags
  cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/configmap.yaml
Labels: size/XS

#1988 Add oidc via dex to vault smaug.
  dex/overlays/moc/smaug/dex-clients.enc.yaml
  dex/overlays/moc/smaug/dex-cm.yaml
  vault/base/route/route.yaml
Labels: size/S, lgtm

#1990 create application api-designer
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/api-designer.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/kustomization.yaml
  argocd/overlays/moc-infra/projects/apicurio-registry.yaml
Labels: size/S, lgtm

#1991 Correct secretstore name in monitoring ns.
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/alert-manager.yaml
  cluster-scope/overlays/prod/moc/smaug/secretstores/openshift-monitoring.yaml
Labels: approved, size/XS, lgtm

#1994 Add ocp groups for vault access by env.
  cluster-scope/overlays/prod/moc/smaug/groups/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-emea-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-moc-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-osc-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1995 Change path for slack api url in smaug.
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/alert-manager.yaml
  cluster-scope/overlays/prod/moc/smaug/secretstores/openshift-monitoring.yaml
Labels: approved, size/XS, lgtm

#2000 Restructure the cert-manager folder.
  cert-manager/overlays/emea/common/api-issuer/kustomization.yaml
  cert-manager/overlays/emea/common/api-issuer/openshift-api-issuer.yaml
  cert-manager/overlays/emea/common/ingress-issuer/kustomization.yaml
  cert-manager/overlays/emea/common/ingress-issuer/openshift-ingress-issuer.yaml
  cert-manager/overlays/emea/morty/api/certificate.yaml
  cert-manager/overlays/emea/morty/api/issuer.yaml
  cert-manager/overlays/emea/morty/api/kustomization.yaml
  cert-manager/overlays/emea/morty/ingress/certificate.yaml
  cert-manager/overlays/emea/morty/ingress/issuer.yaml
  cert-manager/overlays/emea/morty/ingress/kustomization.yaml
  cert-manager/overlays/emea/morty/kustomization.yaml
  cert-manager/overlays/emea/morty/secrets/.sops.yaml
  cert-manager/overlays/emea/morty/secrets/clouddns-dns01-emea-svc-acct.enc.yaml
  cert-manager/overlays/emea/morty/secrets/kustomization.yaml
  cert-manager/overlays/emea/morty/secrets/secret-generator.yaml
  cert-manager/overlays/moc/common/api-issuer/kustomization.yaml
  cert-manager/overlays/moc/common/api-issuer/openshift-api-issuer.yaml
  cert-manager/overlays/moc/common/ingress-issuer/kustomization.yaml
  cert-manager/overlays/moc/common/ingress-issuer/openshift-ingress-issuer.yaml
  cert-manager/overlays/moc/infra/api/api-cert.yaml
  cert-manager/overlays/moc/infra/api/certificate.yaml
  cert-manager/overlays/moc/infra/api/issuer.yaml
  cert-manager/overlays/moc/infra/api/kustomization.yaml
  cert-manager/overlays/moc/infra/api/openshift-api-issuer.yaml
  cert-manager/overlays/moc/infra/ingress/certificate.yaml
  cert-manager/overlays/moc/infra/ingress/issuer.yaml
  cert-manager/overlays/moc/infra/ingress/kustomization.yaml
  cert-manager/overlays/moc/infra/ingress/openshift-ingress-issuer.yaml
  cert-manager/overlays/moc/infra/kustomization.yaml
  cert-manager/overlays/moc/smaug/api/certificate.yaml
  cert-manager/overlays/moc/smaug/api/issuer.yaml
  cert-manager/overlays/moc/smaug/api/kustomization.yaml
  cert-manager/overlays/moc/smaug/ingress/certificate.yaml
  cert-manager/overlays/moc/smaug/ingress/issuer.yaml
  cert-manager/overlays/moc/smaug/ingress/kustomization.yaml
  cert-manager/overlays/moc/smaug/secrets/clouddns-dns01-na-svc-acct.enc.yaml
  cert-manager/overlays/moc/smaug/secrets/kustomization.yaml
  cert-manager/overlays/moc/smaug/secrets/secret-generator.yaml
  cert-manager/overlays/osc/osc-cl1/api/kustomization.yaml
  cert-manager/overlays/osc/osc-cl1/ingress/certificate.yaml
  cert-manager/overlays/osc/osc-cl1/ingress/issuer.yaml
  cert-manager/overlays/osc/osc-cl1/ingress/kustomization.yaml
  cert-manager/overlays/osc/osc-cl1/kustomization.yaml
  cert-manager/overlays/osc/osc-cl1/secrets/kustomization.yaml
  cert-manager/overlays/osc/osc-cl1/secrets/route53.enc.yaml
  cert-manager/overlays/osc/osc-cl1/secrets/secret-generator.yaml
  cert-manager/overlays/route53/us-east-1/osc-cl1/certificate.yaml
  cert-manager/overlays/route53/us-east-1/osc-cl1/kustomization.yaml
Labels: size/L

#2002 change path and ignore deploymentConfig diff
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/api-designer.yaml
Labels: size/XS

#2008 Add docs on enabling cluster with eso & vault.
  docs/_toc.yml
  docs/content/vault/README.md
  docs/content/vault/add_cluster_to_eso_and_vault.md
Labels: size/L

#2015 Withdraw Thoth deployment in rick cluster
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/OWNERS
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/core-test.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-advise-reporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-adviser.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-amun-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-chat-notification.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-cve-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-backup.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-refresh.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-sync.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-investigator.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-kebechet.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-management-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-mi.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-extract.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-releases.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-revsolver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-security-indicators.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-solver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-user-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/kustomization.yaml
Labels: size/M, approved, lgtm

#2020 Add morty s3
  cluster-scope/base/core/namespaces/opf-obcs/kustomization.yaml
  cluster-scope/base/core/namespaces/opf-obcs/namespace.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  docs/content/odh/trino/add_more_buckets.md
  kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general_morty.properties
  kfdefs/overlays/moc/smaug/trino/configs/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/hive-metastores/data_science_general_morty/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/hive-metastores/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/s3buckets.enc.yaml
  odf/overlays/emea/morty/kustomization.yaml
  odf/overlays/emea/morty/route.yaml
Labels: size/L

#2021 Correct trino hive metastore route for morty s3 bucket.
  kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general_morty.properties
Labels: size/XS

#2007 Adding curator-operator namespace to smaug cluster
  cluster-scope/base/core/namespaces/curator-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/curator-operator/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm, cluster/smaug
