Repository operate-first/apps, pull requests merged in 2022-12, with the labels that each got.

#2668 Add initial test of Iris notebook for osc-cl1
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/iris-notebook.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/S, lgtm

#2669 Fixed patch for OSC grafana to include sostrades as editors
  grafana/overlays/osc/common/grafana_oauth_patch.yaml
  grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml
  grafana/overlays/osc/osc-cl2/grafana_oauth_patch.yaml
Labels: size/XS

#2657 feat: Add pulp to service catalog
  service-catalog/apis.yaml
  service-catalog/apis/pulp.yaml
  service-catalog/components.yaml
  service-catalog/components/pulp-operator.yaml
  service-catalog/components/pulp.yaml
  service-catalog/groups.yaml
  service-catalog/groups/pulp.yaml
  service-catalog/systems.yaml
  service-catalog/systems/pulp.yaml
  service-catalog/users.yaml
  service-catalog/users/pulp.yaml
Labels: size/L, approved, lgtm, ok-to-test

#2670 Add Mikhail Mikhailitchenko to approvers list
  OWNERS
Labels: approved, size/XS, lgtm

#2672 Include data science members to ttm-as-a-service group
  cluster-scope/base/user.openshift.io/groups/ttm-as-a-service/group.yaml
Labels: approved, size/XS, lgtm

#2651 Add ryanaslett (Linux Foundation) as cluster-admin
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2652 Add ryanaslett (Linux Foundation) to cluster admins
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2667 Added project view public access for openshift-tuning
  cluster-scope/base/core/namespaces/openshift-tuning/kustomization.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2673 Requesting 16 cpu limit for smart-village-view
  cluster-scope/base/core/namespaces/smart-village-view/kustomization.yaml
  cluster-scope/base/core/namespaces/smart-village-view/resourcequota.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2643 Create custom resource quotas for okd-team
  cluster-scope/base/core/namespaces/okd-team/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-team/resourcequota.yaml
Labels: approved, size/S, lgtm

#2645 update rolebinding for ray-operator
  .gitignore
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.ray.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.ray.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayjobs.ray.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayjobs.ray.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayservices.ray.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayservices.ray.io/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/kuberay-operator/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/kuberay-operator/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/kuberay-operator/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/kuberay-operator/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/ray/rbac.yaml
Labels: approved, size/XXL, lgtm, tide/merge-method-squash, ok-to-test

#2666 update imagestreamtags to point to todays release 🎄
  prow/overlays/smaug/imagestreamtags.yaml
Labels: size/M, approved, lgtm

#2674 chore: Remove duplicit namespace definitions from cert-manager manifests
  cert-manager/overlays/emea/jerry/api/certificate.yaml
  cert-manager/overlays/emea/jerry/api/issuer.yaml
  cert-manager/overlays/emea/jerry/ingress/certificate.yaml
  cert-manager/overlays/emea/jerry/ingress/issuer.yaml
  cert-manager/overlays/moc/curator/api/certificate.yaml
  cert-manager/overlays/moc/curator/api/issuer.yaml
  cert-manager/overlays/moc/curator/ingress/certificate.yaml
  cert-manager/overlays/moc/curator/ingress/issuer.yaml
  cert-manager/overlays/moc/infra/api/certificate.yaml
  cert-manager/overlays/moc/infra/api/issuer.yaml
  cert-manager/overlays/moc/smaug/api/certificate.yaml
  cert-manager/overlays/moc/smaug/api/issuer.yaml
  cert-manager/overlays/moc/smaug/ingress/certificate.yaml
  cert-manager/overlays/moc/smaug/ingress/issuer.yaml
  cert-manager/overlays/osc/osc-cl1/ingress/certificate.yaml
  cert-manager/overlays/osc/osc-cl1/ingress/issuer.yaml
Labels: approved, size/S, lgtm

#2675 feat: Create SCC with seccomp runtime/default
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-restricted-seccomp/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-restricted-seccomp/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/README.md
  cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/restricted-seccomp/securitycontextconstraint.yaml
  cluster-scope/bundles/cert-manager/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/M, approved, lgtm

#2676 feat: Create certificate for pulp.operate-first.cloud
  pulp/overlays/moc/smaug/certificate.yaml
  pulp/overlays/moc/smaug/issuer.yaml
  pulp/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2677 feat: Allow Certificate and Issuer in ArgoCD global_project template
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: approved, size/XS, lgtm

#2662 Adding route TLS secret to pulp
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2658 Adding Kruize HPO as part of ArgoCD
  argocd/overlays/moc-infra/projects/kruize.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2681 feat: Deploy ray operator cluster resources to Smaug
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayclusters.ray.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayjobs.ray.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/rayservices.ray.io/customresourcedefinition.yaml
  cluster-scope/bundles/ray-operator/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2650 Add Linux Foundation user ryanaslett
  kfdefs/overlays/osc/OWNERS
Labels: approved, size/XS, lgtm, ok-to-test

#2682 increase the resource quota of some thoth namespaces
  cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-backend-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-frontend-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-graph-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-middletier-prod/resourcequota.yaml
  cluster-scope/base/core/namespaces/thoth-test-core/resourcequota.yaml
Labels: size/M, approved, lgtm

#2684 bump storage for b4mad-racing
  cluster-scope/base/core/namespaces/b4mad-racing/resourcequota.yaml
Labels: size/XS

#2687 make argocd free again
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_cm/envs
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.default
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  docs/content/argocd-gitops/docs/get_access_to_argocd.md
  docs/content/argocd-gitops/docs/onboarding_to_argocd.md
Labels: size/M, approved, lgtm

#2671 Add Pep to ArgoCD admins
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Labels: approved, size/XS, lgtm

#2689 let dex map any group to argocd
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  docs/content/argocd-gitops/docs/get_access_to_argocd.md
  docs/content/argocd-gitops/docs/onboarding_to_argocd.md
Labels: size/M, approved, lgtm

#2690 Onboard Apex to ArgoCD
  argocd/overlays/moc-infra/projects/apex.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#2694 argocd: Fix Apex Destinations
  argocd/overlays/moc-infra/projects/apex.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2695 argocd: Add postgres operator to global_project template
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2699 Added machinesets to osc cl1 to sync with cl2
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-compute-notebook.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m4.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m5.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m6.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-notebook-gpu-g.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-worker.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/nodefeaturediscovery/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/nodefeaturediscovery/nfd-instance.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/nvidia-gpu/gpu-cluster-policy.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/nvidia-gpu/kustomization.yaml
Labels: size/L
