Repository operate-first/apps, pull requests merged in 2022-09, with the labels that each got.

#2360 fix(infra): eno1 connection renamed on node/ctrl-1
  cluster-scope/overlays/prod/moc/infra/nodenetworkconfigurationpolicies/vlan-211-nese.yaml
Labels: approved, size/XS, lgtm

#2362 Adding Vincent for Kepler Grafana on cl1 and cl2
  cluster-scope/overlays/prod/osc/osc-cl1/groups/kepler-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/kepler-admins.yaml
Labels: approved, size/XS, lgtm

#2343 OKD image updates
  kvm-device-plugin/base/buildconfig.yaml
  okd-centos/base/imagestream.yaml
Labels: approved, size/S, lgtm

#2365 enable debug for bq plugin, per request from trino devs
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
Labels: approved, size/XS, lgtm

#2364 copilot ops namespace and permissions
  cluster-scope/base/core/namespaces/copilot-ops/kustomization.yaml
  cluster-scope/base/core/namespaces/copilot-ops/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/copilot-ops/group.yaml
  cluster-scope/base/user.openshift.io/groups/copilot-ops/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/copilot-ops/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/copilot-ops/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, kind/onboarding, sig/community

#2368 Revert "enable debug for bq plugin, per request from trino devs"
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
Labels: approved, size/XS

#2367 add grafana-public dashboard
  grafana/overlays/moc/smaug-public/dashboards/operate-first/opf-projects-overview.yaml
Labels: size/XL, approved, lgtm, area/community, area/contributor, kind/metrics, area/monitoring, sig/community

#2369 configure debug for bigquery plugin on log.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/log.properties
Labels: approved, size/XS, lgtm

#2373 :recycle: Switch back to smaug obc for opf-ci-prow
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/M, approved, lgtm

#2344 feat(catalog): Create CronJob to upload SA tokens to vault
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/base/core/namespaces/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/base/core/namespaces/service-catalog-k8s-plugin/namespace.yaml
  cluster-scope/base/core/secrets/service-catalog-k8s-plugin-token/kustomization.yaml
  cluster-scope/base/core/secrets/service-catalog-k8s-plugin-token/secret.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-k8s-plugin/clusterrolebinding.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
Labels: size/L, approved, lgtm

#2379 feat: Add myself to argocd-admins
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Labels: approved, size/XS, lgtm

#2286 feat: Install ODF in external mode to Infra cluster
  cluster-scope/base/ocs.openshift.io/ocsinitializations/ocsinit/kustomization.yaml
  cluster-scope/base/ocs.openshift.io/ocsinitializations/ocsinit/ocsinitialization.yaml
  cluster-scope/base/ocs.openshift.io/storageclusters/ocs-external-storagecluster/storagecluster.yaml
  cluster-scope/base/odf.openshift.io/storagesystems/ocs-external-storagecluster-storagesystem/kustomization.yaml
  cluster-scope/base/odf.openshift.io/storagesystems/ocs-external-storagecluster-storagesystem/storagesystem.yaml
  cluster-scope/bundles/odf-external/kustomization.yaml
  cluster-scope/bundles/odf/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/rook-ceph-external-cluster-details.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/openshift-storage/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/subscriptions/odf-operator_patch.yaml
Labels: size/M, approved, lgtm

#2384 fix: Unlist Smaug specific storage class from a bundle
  cluster-scope/bundles/odf-external/kustomization.yaml
Labels: approved, size/XS, lgtm

#2382 updated readme
  docs/_toc.yml
  docs/content/README.md
  docs/content/about/README.md
  docs/content/about/intro.md
  docs/content/argocd-gitops/get_access_to_argocd.md
  docs/content/vault_eso/README.md
Labels: size/L, approved, lgtm

#2319 documentation for project admin created
  docs/content/cluster-scope/add_user_to_project_admin.md
Labels: approved, size/S, lgtm

#2388 feat(catalog): Allow CronJob to write secrets to vault
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
  cluster-scope/base/core/serviceaccounts/vault-secret-writer/kustomization.yaml
  cluster-scope/base/core/serviceaccounts/vault-secret-writer/serviceaccount.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/curator/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/service-catalog-k8s-plugin/kustomization.yaml
Labels: size/M, approved, lgtm

#2391 Fake metrics endpoint to make ODF happy
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/odf-fake-metrics-exporter.yaml
  fake-metrics-server/base/deployment.yaml
  fake-metrics-server/base/kustomization.yaml
  fake-metrics-server/base/service.yaml
  fake-metrics-server/overlays/openshift-storage/deploy_patch.yaml
  fake-metrics-server/overlays/openshift-storage/kustomization.yaml
  fake-metrics-server/overlays/openshift-storage/metrics.json
Labels: size/M, approved, lgtm

#2392 feat(catalog): Move manifests to a bundle, fix cronjob
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
  cluster-scope/bundles/service-catalog-k8s-plugin/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/S, lgtm

#2395 whitelist grafana resources for b4mad
  argocd/overlays/moc-infra/projects/b4mad.yaml
Labels: approved, size/XS, lgtm

#2338 enabling amc-mco on infra
  cluster-scope/base/core/namespaces/open-cluster-management-observability/kustomization.yaml
  cluster-scope/base/core/namespaces/open-cluster-management-observability/namespace.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/multiclusterhub-operator-pull-secret.yaml
  cluster-scope/overlays/prod/moc/infra/externalsecrets/thanos-object-storage.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/multiclusterobservability/observability.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/open-cluster-management-observability/kustomization.yaml
Labels: size/M, approved, do-not-merge/hold

#2396 moving prow storage to ionos s3 bucket
  prow/base/statusreconciler.yaml
  prow/base/tide.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/M, lgtm

#2397 :recycle: Fix the rbac of prow for argocd sync
  prow/base/horologium.yaml
  prow/base/plank.yaml
Labels: approved, size/XS, lgtm

#2400 add erikerlandson to admin on osc-cl2
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Labels: size/XS

#2394 feat(catalog): Replace put with patch in cronjob
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
Labels: approved, size/XS, lgtm

#2399 Removed the secret for public-demo secrets
  kafka/overlays/smaug/kustomization.yaml
  kafka/overlays/smaug/secrets/kustomization.yaml
  kafka/overlays/smaug/secrets/opf-public-demo-user-creds.yaml
Labels: approved, size/S, lgtm

#2311 set uniq table loc and increase max partitions
  kfdefs/overlays/osc/osc-cl1/trino/configs/catalogs/osc_datacommons_iceberg_dev.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
Labels: size/XS

#2402 feat(catalog): Add k8s plugin bundle to osc clusters
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/XS

#2403 Remove old smaug trino catalogs.
  kfdefs/overlays/moc/smaug/trino/.sops.yaml
  kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general.properties
  kfdefs/overlays/moc/smaug/trino/configs/catalogs/data_science_general_morty.properties
  kfdefs/overlays/moc/smaug/trino/configs/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/externalsecrets/file-auth-secret.yaml
  kfdefs/overlays/moc/smaug/trino/externalsecrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/externalsecrets/postgres-dbs.yaml
  kfdefs/overlays/moc/smaug/trino/externalsecrets/s3buckets.yaml
  kfdefs/overlays/moc/smaug/trino/externalsecrets/trino-oauth.yaml
  kfdefs/overlays/moc/smaug/trino/hive-metastores/data-science_general/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/hive-metastores/data_science_general_morty/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/hive-metastores/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/file-auth-secret.enc.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/postgres-dbs.enc.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/s3buckets.enc.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/trino/secrets/trino-oauth.enc.yaml
Labels: size/L, approved, lgtm

#2406 Include ESO secrets into smaug trino kustomization.
  kfdefs/overlays/moc/smaug/trino/externalsecrets/kustomization.yaml
Labels: size/XS

#2383 Add machineconfig and machineconfigpool to enable nested-virtualization
  cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigpools/mcp-kvm-device-plugin/kustomization.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigpools/mcp-kvm-device-plugin/machineconfigpool.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/80-enable-nested-virt/kustomization.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/80-enable-nested-virt/machineconfig.yaml
  cluster-scope/bundles/kvm-device-plugin/kustomization.yaml
Labels: size/M, approved, do-not-merge/hold, lgtm

#2410 Add osc owners to openmetadata folder.
  openmetadata/OWNERS
Labels: size/S

#2408 feat: Label nodes to enable kvm machineconfigpool
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-00-compute.yaml
  cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-01-compute.yaml
  cluster-scope/overlays/prod/moc/smaug/nodes/oct-03-03-compute.yaml
Labels: size/S, lgtm

#2393 prow metrics
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/route-ghproxy-metrics.yaml
  prow/overlays/smaug/routes.yaml
  prow/overlays/smaug/service-monitor.yaml
Labels: size/M, approved, lgtm

#2412 feat(catalog): Use a common role in cronjob
  cluster-scope/base/batch/cronjobs/service-catalog-k8s-plugin/cronjob.yaml
Labels: size/XS

#2390 fix: NFD channel '4.8' no longer exist on Smaug, use 'stable' instead
  cluster-scope/overlays/prod/moc/smaug/subscriptions/nfd_patch.yaml
Labels: approved, size/XS, lgtm

#2398 Add the Custom Notebook Image (CNBi) operator to osc-cl1 stage
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
Labels: approved, size/XS, lgtm

#2416 :pray: welcome redhatet repo homomorphic to be handled by prow
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/plugins.yaml
Labels: size/M, approved, lgtm

#2418 OKD-TEAM namespace: increase limit ranges for pods
  cluster-scope/base/core/namespaces/okd-team/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-team/limits.yaml
Labels: approved, size/S, lgtm

#2420 Add oidc login to airflow for openmetadata.
  dex/overlays/osc/osc-cl2/configmaps/files/config.yaml
  openmetadata/base/openmetadata-dependencies/configmaps/files/webserver_config.py
  openmetadata/base/openmetadata-dependencies/rolebindings/airflow.yaml
  openmetadata/overlays/osc/osc-cl2/configmaps/files/auth_roles_mapping.json
  openmetadata/overlays/osc/osc-cl2/configmaps/files/dex_provider_cfg.json
  openmetadata/overlays/osc/osc-cl2/configmaps/kustomization.yaml
  openmetadata/overlays/osc/osc-cl2/externalsecrets/dex-provider-cfg.yaml
  openmetadata/overlays/osc/osc-cl2/externalsecrets/kustomization.yaml
  openmetadata/overlays/osc/osc-cl2/kustomization.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-db-migrations.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-scheduler.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-sync-users.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/airflow-web.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/airlfow-triggerer.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/elasticsearch.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/mysql.yaml
Labels: size/L, approved

#2419 fix(catalog): Add bundle and change configmap
  cluster-scope/overlays/prod/moc/curator/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/configmaps/service-catalog-k8s-plugin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/configmaps/service-catalog-k8s-plugin.yaml
Labels: approved, size/XS, lgtm

#2424 externalizing alertreceiver secrets and removing emea overlay
  alertreceiver/overlays/common/github-secret.enc.yaml
  alertreceiver/overlays/common/kustomization.yaml
  alertreceiver/overlays/common/secret-generator.yaml
  alertreceiver/overlays/emea/demo/kustomization.yaml
  alertreceiver/overlays/moc/infra/github-secrets.yaml
  alertreceiver/overlays/moc/infra/kustomization.yaml
  alertreceiver/overlays/moc/smaug/github-secrets.yaml
  alertreceiver/overlays/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#2425 externalizing triage-party secret
  triage-party/overlays/moc/smaug/externalsecret.yaml
  triage-party/overlays/moc/smaug/kustomization.yaml
  triage-party/overlays/moc/smaug/secret-generator.yaml
  triage-party/overlays/moc/smaug/secret.enc.yaml
Labels: size/M, approved, lgtm

#2427 whitelisting external secrets for argocd op1st project
  argocd/overlays/moc-infra/projects/operate-first.yaml
Labels: size/XS

#2426 externalizing slack-first secrets
  slack-first/overlays/moc/smaug/externalsecret.yaml
  slack-first/overlays/moc/smaug/kustomization.yaml
  slack-first/overlays/moc/smaug/secret-generator.yaml
  slack-first/overlays/moc/smaug/secret.enc.yaml
Labels: size/M, approved, lgtm

#2407 chore: Update group/user in service catalog
  service-catalog/groups/operate-first.yaml
  service-catalog/users/operate-first.yaml
Labels: approved, size/XS, lgtm

#2421 onboard octo-et-platform group and IPFS project
  cluster-scope/base/core/namespaces/ipfs/kustomization.yaml
  cluster-scope/base/core/namespaces/ipfs/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/octo-et-platform/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-et-platform/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-et-platform/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-et-platform/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, lgtm

#2415 Add docs on updating jwt for vault runbook.
  docs/content/vault_eso/runbook.md
Labels: approved, size/S, lgtm

#2430 feat: Add apicurio project to vault secret managament
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
Labels: approved, size/S, lgtm

#2429 bumping resource requests for prow jobs
  .prow.yaml
Labels: approved, size/S, lgtm

#2431 externalizing pachyderm secrets
  pachyderm/overlays/osc/osc-cl2/externalsecret.yaml
  pachyderm/overlays/osc/osc-cl2/kustomization.yaml
  pachyderm/overlays/osc/osc-cl2/secret-generator.yaml
  pachyderm/overlays/osc/osc-cl2/secret.enc.yaml
Labels: size/M

#2440 Remove secret from pachyderm.
  pachyderm/base/kustomization.yaml
  pachyderm/base/secret.yaml
Labels: size/S

#2436 removing morty overlay from k8s-annotations-exporter deployment
  k8s-annotations-exporter/overlays/emea/morty/kustomization.yaml
Labels: size/XS

#2438 adding an argocd app for cert-manager to curator under cluster-management
  argocd/overlays/moc-infra/applications/envs/moc/curator/cluster-management/cert-manager.yaml
  argocd/overlays/moc-infra/applications/envs/moc/curator/cluster-management/kustomization.yaml
Labels: approved, size/S, lgtm

#2437 externalizing jupyterhub-idle-culler secrets
  jupyterhub-idle-culler/overlays/moc/smaug/.sops.yaml
  jupyterhub-idle-culler/overlays/moc/smaug/externalsecrets/jupyterhub-api-token.yaml
  jupyterhub-idle-culler/overlays/moc/smaug/externalsecrets/kustomization.yaml
  jupyterhub-idle-culler/overlays/moc/smaug/kustomization.yaml
  jupyterhub-idle-culler/overlays/moc/smaug/secrets/secret-generator.yaml
  jupyterhub-idle-culler/overlays/moc/smaug/secrets/secret.enc.yaml
Labels: size/M

#2434 externalizing kfdef-secrets
  kfdefs/overlays/moc/smaug/superset/externalsecrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/superset/externalsecrets/superset-custom.yaml
  kfdefs/overlays/moc/smaug/superset/externalsecrets/superset-db-custom.yaml
  kfdefs/overlays/moc/smaug/superset/kustomization.yaml
  kfdefs/overlays/moc/smaug/superset/secrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/superset/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/superset/secrets/superset.enc.yaml
  kfdefs/overlays/moc/smaug/superset/secrets/supersetdb.enc.yaml
  kfdefs/overlays/moc/smaug/trino-stage/externalsecrets/file-auth-secret.yaml
  kfdefs/overlays/moc/smaug/trino-stage/externalsecrets/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino-stage/externalsecrets/postgres-dbs.yaml
  kfdefs/overlays/moc/smaug/trino-stage/externalsecrets/s3buckets.yaml
  kfdefs/overlays/moc/smaug/trino-stage/externalsecrets/trino-oauth.yaml
  kfdefs/overlays/moc/smaug/trino-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino-stage/secrets/file-auth-secret.enc.yaml
  kfdefs/overlays/moc/smaug/trino-stage/secrets/postgres-dbs.enc.yaml
  kfdefs/overlays/moc/smaug/trino-stage/secrets/s3buckets.enc.yaml
  kfdefs/overlays/moc/smaug/trino-stage/secrets/secret-generator.yaml
  kfdefs/overlays/moc/smaug/trino-stage/secrets/trino-oauth.enc.yaml
  kfdefs/overlays/osc/.sops.yaml
Labels: size/L

#2442 externalizing das secrets
  das/overlays/osc-cl1/kustomization.yaml
  das/overlays/osc-cl1/secret-generator.yaml
  das/overlays/osc-cl1/secret.enc.yaml
  das/overlays/osc-cl1/secret.yaml
  das/overlays/osc-cl2/kustomization.yaml
  das/overlays/osc-cl2/secret-generator.yaml
  das/overlays/osc-cl2/secret.enc.yaml
  das/overlays/osc-cl2/secret.yaml
Labels: size/L

#2450 feat: Add myself as vault admin
  cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
Labels: approved, size/XS, lgtm

#2452 fix: Change apicurio Vault role
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/api-designer/opf-vault-store.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apicurio-apicurio-registry/opf-vault-store.yaml
Labels: approved, size/S, lgtm

#2413 Drop prow autoclosing for thoth-station
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2454 feat: Add copilot-ops to vaul secret management
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/copilot-ops/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/copilot-ops/opf-vault-store.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
Labels: approved, size/S, lgtm

#2447 externalizing argocd-notifications secrets
  argocd-notifications/overlays/infra/argocd-notifications-secret.yaml
  argocd-notifications/overlays/infra/kustomization.yaml
  argocd-notifications/overlays/infra/secret-generator.yaml
  argocd-notifications/overlays/infra/secret.enc.yaml
Labels: size/M

#2453 Onboarding Kruize HPO project
  cluster-scope/base/core/namespaces/openshift-tuning/kustomization.yaml
  cluster-scope/base/core/namespaces/openshift-tuning/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/kruize/group.yaml
  cluster-scope/base/user.openshift.io/groups/kruize/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kruize/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kruize/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2443 removing keycloack deployment
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/keycloak.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml
  cluster-scope/base/core/namespaces/keycloak/kustomization.yaml
  cluster-scope/base/core/namespaces/keycloak/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/keycloak/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/keycloak/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rhsso-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rhsso-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  keycloak/README.md
  keycloak/base/keycloak.yaml
  keycloak/base/kustomization.yaml
  keycloak/overlays/moc/infra/.sops.yaml
  keycloak/overlays/moc/infra/kustomization.yaml
  keycloak/overlays/moc/infra/realm.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L

#2449 externalizing acm secrets
  acm/overlays/moc/infra/identitatem/clients/github.enc.yaml
  acm/overlays/moc/infra/identitatem/clients/github.yaml
  acm/overlays/moc/infra/identitatem/clients/kustomization.yaml
  acm/overlays/moc/infra/identitatem/clients/secret-generator.yaml
  acm/overlays/moc/infra/provider-connections/aws-octo.enc.yaml
  acm/overlays/moc/infra/provider-connections/aws-octo.yaml
  acm/overlays/moc/infra/provider-connections/kustomization.yaml
  acm/overlays/moc/infra/provider-connections/secret-generator.yaml
Labels: size/L

#2448 externalizing argocd secrets
  argocd/overlays/dev/.sops.yaml
  argocd/overlays/dev/configs/argo_cm/configManagementPlugins
  argocd/overlays/dev/configs/argo_cm/dex.config
  argocd/overlays/dev/configs/argo_cm/envs
  argocd/overlays/dev/configs/argo_rbac_cm/policy.csv
  argocd/overlays/dev/kustomization.yaml
  argocd/overlays/dev/secrets/auth/argocd-secret.enc.yaml
  argocd/overlays/dev/secrets/auth/dex-server-sa.enc.yaml
  argocd/overlays/dev/secrets/auth/secret-generator.yaml
  argocd/overlays/dev/secrets/gpg/secret-generator.yaml
  argocd/overlays/dev/secrets/gpg/secret.enc.yaml
  argocd/overlays/dev/serviceaccounts/argocd-dex-server.yaml
  argocd/overlays/moc-infra/externalsecrets/auth/argocd-dex-server-oauth-token.yaml
  argocd/overlays/moc-infra/externalsecrets/auth/argocd-secret.yaml
  argocd/overlays/moc-infra/externalsecrets/auth/kustomization.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/kustomization.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/moc-infra.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/octo-gohan.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/octo-summit-cl1.yaml
  argocd/overlays/moc-infra/externalsecrets/gpg/ksops-pgp-key.yaml
  argocd/overlays/moc-infra/externalsecrets/kustomization.yaml
  argocd/overlays/moc-infra/kustomization.yaml
  argocd/overlays/moc-infra/secrets/.sops.yaml
  argocd/overlays/moc-infra/secrets/auth/argocd-secret.yaml
  argocd/overlays/moc-infra/secrets/auth/dex-server-sa.yaml
  argocd/overlays/moc-infra/secrets/clusters/.sops.yaml
  argocd/overlays/moc-infra/secrets/clusters/moc-infra.enc.yaml
  argocd/overlays/moc-infra/secrets/clusters/octo-gohan.enc.yaml
  argocd/overlays/moc-infra/secrets/clusters/octo-summit-cl1.enc.yaml
  argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml
  argocd/overlays/moc-infra/secrets/gpg/secret-generator.yaml
  argocd/overlays/moc-infra/secrets/gpg/secret.enc.yaml
Labels: size/XL

#2473 Add dex oauth sa annotations to argocd dex.
  argocd/overlays/moc-infra/kustomization.yaml
Labels: size/XS

#2476 fix: Rename consoles folder to plural
  cluster-scope/base/operator.openshift.io/consoles/cluster/console.yaml
  cluster-scope/base/operator.openshift.io/consoles/cluster/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/XS, lgtm

#2432 externalizing opf-observatorium secrets
  observatorium/overlays/moc/smaug/loki/externalsecrets/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/externalsecrets/loki-objectstorage-secret.yaml
  observatorium/overlays/moc/smaug/loki/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/secrets/loki-objectstorage-secret.enc.yaml
  observatorium/overlays/moc/smaug/loki/secrets/secrets-generator.yaml
  observatorium/overlays/moc/smaug/thanos/externalsecrets/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/externalsecrets/thanos-objectstorage-secret.yaml
  observatorium/overlays/moc/smaug/thanos/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/secrets/secrets-generator.yaml
  observatorium/overlays/moc/smaug/thanos/secrets/thanos-objectstorage-secret.enc.yaml
  observatorium/overlays/moc/smaug/vector/.sops.yaml
  observatorium/overlays/moc/smaug/vector/clo-kafka.enc.yaml
  observatorium/overlays/moc/smaug/vector/clo-kafka.yaml
  observatorium/overlays/moc/smaug/vector/kustomization.yaml
  observatorium/overlays/moc/smaug/vector/secret-generator.yaml
Labels: size/L, do-not-merge/hold

#2481 Move prow secrets to vault.
  prow/overlays/smaug/externalsecrets/cookie.yaml
  prow/overlays/smaug/externalsecrets/github-oauth-config.yaml
  prow/overlays/smaug/externalsecrets/github-token.yaml
  prow/overlays/smaug/externalsecrets/hmac-token.yaml
  prow/overlays/smaug/externalsecrets/kustomization.yaml
  prow/overlays/smaug/externalsecrets/oauth-token.yaml
  prow/overlays/smaug/externalsecrets/s3-credentials.yaml
  prow/overlays/smaug/externalsecrets/ssh-secret.yaml
  prow/overlays/smaug/kustomization.yaml
  prow/overlays/smaug/secret-generator.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/L, approved, lgtm

#2478 Add ingress/api certs to ingress-controller & apiserver config.
  cluster-scope/overlays/prod/emea/jerry/apiserver/api_server_cert.yaml
  cluster-scope/overlays/prod/emea/jerry/apiserver/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/ingresscontrollers/default.yaml
  cluster-scope/overlays/prod/emea/jerry/ingresscontrollers/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: size/M, approved, lgtm

#2484 :fire_engine: Remove cluster logging from balrog
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/cluster-logging.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/kustomization.yaml
  cluster-logging/overlays/emea/balrog/.sops.yaml
  cluster-logging/overlays/emea/balrog/clusterlogforwarders/clusterlogforwarder.yaml
  cluster-logging/overlays/emea/balrog/clusterlogforwarders/kustomization.yaml
  cluster-logging/overlays/emea/balrog/kustomization.yaml
  cluster-logging/overlays/emea/balrog/secret-generator.yaml
  cluster-logging/overlays/emea/balrog/secrets/clo-kafka.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  prow/overlays/smaug/config.yaml
Labels: size/L, approved, lgtm

#2486 :fire_engine: Remove config for sending cluster metrics out of balrog
  cluster-scope/overlays/prod/emea/balrog/configmaps/cluster-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/configmaps/user-workload-monitoring-config.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-generator.yaml
  cluster-scope/overlays/prod/emea/balrog/subscriptions/cluster-logging-operator_patch.yaml
Labels: size/L, approved, lgtm

#2487 Add copilot group to argocd dex.
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
Labels: size/XS

#2475 Added openmetadata dev deployment with docs.
  openmetadata/overlays/dev/README.md
  openmetadata/overlays/dev/kustomization.yaml
  openmetadata/overlays/dev/patches/configmaps/openmetadata-dependencies-config-envs.yaml
  openmetadata/overlays/dev/patches/deployments/openmetadata.yaml
  openmetadata/overlays/dev/secret/airflow-mysql-secrets.yaml
  openmetadata/overlays/dev/secret/airflow-secrets.yaml
  openmetadata/overlays/dev/secret/kustomization.yaml
  openmetadata/overlays/dev/secret/mysql-init-scripts.yaml
  openmetadata/overlays/dev/secret/mysql-secrets.yaml
  openmetadata/overlays/dev/secret/mysql.yaml
  openmetadata/overlays/dev/secret/openmetadata-dependencies-config-envs.yaml
  openmetadata/overlays/dev/secret/openmetadata-envs.yaml
Labels: size/L

#2488 Added roastdeer
  cluster-scope/base/user.openshift.io/groups/grafana-viewer/group.yaml
Labels: approved, size/XS, lgtm

#2491 onboard kaoto
  cluster-scope/base/core/namespaces/kaoto/kustomization.yaml
  cluster-scope/base/core/namespaces/kaoto/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/kaoto/group.yaml
  cluster-scope/base/user.openshift.io/groups/kaoto/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kaoto/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/kaoto/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2492 Adding new pipeline schemas for osc-cl2
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/L, approved, lgtm

#2494 fix kaoto namespace
  cluster-scope/base/core/namespaces/kaoto/kustomization.yaml
  cluster-scope/base/core/namespaces/kaoto/namespace.yaml
Labels: approved, size/XS, lgtm

#2497 :turtle: Decommission: Clearing out kafka workloads from balrog
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/opf-kafka.yaml
  kafka/overlays/balrog/kafka-podmonitors.yaml
  kafka/overlays/balrog/kustomization.yaml
  kafka/overlays/balrog/opf-kafdrop.yaml
  kafka/overlays/balrog/topics/kustomization.yaml
  kafka/overlays/balrog/topics/thoth-advise-justification.yaml
  kafka/overlays/balrog/topics/thoth-adviser-trigger.yaml
  kafka/overlays/balrog/topics/thoth-build-analysis-trigger.yaml
  kafka/overlays/balrog/topics/thoth-cve-provided.yaml
  kafka/overlays/balrog/topics/thoth-hash-mismatch.yaml
  kafka/overlays/balrog/topics/thoth-kebechet-run-url.yaml
  kafka/overlays/balrog/topics/thoth-kebechet-trigger.yaml
  kafka/overlays/balrog/topics/thoth-missing-package-version.yaml
  kafka/overlays/balrog/topics/thoth-missing-package.yaml
  kafka/overlays/balrog/topics/thoth-package-extract-trigger.yaml
  kafka/overlays/balrog/topics/thoth-package-released.yaml
  kafka/overlays/balrog/topics/thoth-provenance-checker-trigger.yaml
  kafka/overlays/balrog/topics/thoth-qebhwt-trigger.yaml
  kafka/overlays/balrog/topics/thoth-si-unanalyzed-package.yaml
  kafka/overlays/balrog/topics/thoth-solved-package.yaml
  kafka/overlays/balrog/topics/thoth-unresolved-package.yaml
  kafka/overlays/balrog/topics/thoth-unrevsolved-package.yaml
  kafka/overlays/balrog/topics/thoth-update-provides-source-distro.yaml
  kafka/overlays/balrog/users/kustomization.yaml
  kafka/overlays/balrog/users/thoth.yaml
  kafka/overlays/smaug/topics/balrog-cluster-app-logs.yaml
  kafka/overlays/smaug/topics/balrog-cluster-audit-logs.yaml
  kafka/overlays/smaug/topics/balrog-cluster-infra-logs.yaml
  kafka/overlays/smaug/topics/kustomization.yaml
Labels: size/XL, approved, lgtm

#2496 :turtle: Decommission: Clearing out user thoth workloads from balrog
  argocd/overlays/moc-infra/applications/envs/emea/balrog/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/OWNERS
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-backend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-frontend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-graph.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-infra.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/core-middletier.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-advise-reporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-adviser.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-amun-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-amun-inspection.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-chat-notification.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-cve-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-backup.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-refresh.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-schema-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-sync-backend.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-graph-sync-middletier.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-investigator-message-metrics.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-investigator.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-kebechet.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-management-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-extract.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-releases.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-package-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-revsolver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-security-indicators.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-solver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/thoth/prod/prod-thoth-user-api.yaml
Labels: size/XL, approved, lgtm

#2500 Add ecb-fx kafka topic to trino.
  kafka/overlays/osc/osc-cl2/kustomization.yaml
  kafka/overlays/osc/osc-cl2/topics/ecb-fx.yaml
  kafka/overlays/osc/osc-cl2/topics/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/ecb-trino-schema.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: size/M

#2501 Remove remote write kepler metrics in oscl2.
  cluster-scope/overlays/prod/osc/osc-cl2/configmaps/user-workload-monitoring-config.yaml
Labels: size/XS
