Repository operate-first/apps, pull requests merged in 2022-03, with the labels that each got.

#1670 Adding Blackbox deployment
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/config-map.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/deployment.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/route.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/service.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
Labels: size/L, approved, lgtm

#1674 Fixing the blackbox exporter Name in JupyterHub
  kfdefs/overlays/moc/smaug/opf-jupyterhub/blackbox-exporter/deployment.yaml
Labels: approved, size/XS, lgtm

#1676 Remove the namespace field
  cosigned/base/kustomization.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1678 Fix the namespace and separate out the overlay's content for cosigned
  cosigned/base/configmap.yaml
  cosigned/base/deployment.yaml
  cosigned/base/kustomization.yaml
  cosigned/base/secret.yaml
  cosigned/base/service.yaml
  cosigned/base/serviceaccount.yaml
  cosigned/overlays/octo/kustomization.yaml
  cosigned/overlays/octo/public_secret.yaml
  cosigned/overlays/octo/rolebinding.yaml
Labels: approved, size/S, lgtm

#1673 new kfdef pointers and removed overrides
  kfdefs/overlays/osc/osc-cl1/jupyterhub/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/seldon/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/superset/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/seldon/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/superset/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
  odh-manifests/osc/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml
  odh-manifests/osc/jupyterhub/jupyterhub/base/jupyterhub-groups-configmap.yaml
  odh-manifests/osc/jupyterhub/jupyterhub/base/jupyterhub-singleuser-profiles-configmap.yaml
  odh-manifests/osc/odhseldon/cluster/base/kustomization.yaml
  odh-manifests/osc/odhseldon/cluster/base/subscription.yaml
  odh-manifests/osc/superset/base/deployment.yaml
  odh-manifests/osc/superset/base/kustomization.yaml
  odh-manifests/osc/superset/base/secret-superset.yaml
  odh-manifests/osc/trino/base/hive-config.yaml
  odh-manifests/osc/trino/base/kustomization.yaml
  odh-manifests/osc/trino/base/trino-coordinator-dc.yaml
  odh-manifests/osc/trino/base/trino-worker-dc.yaml
Labels: size/XL, approved, lgtm, ok-to-test

#1681 adding gregory and gage to both osc-cl* odh-admin groups
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-admin.yaml
Labels: approved, size/XS, lgtm

#1672 Introduce a parameter to specify an artifact secret name
  kfp-tekton/base/deployments/ml-pipeline-ui.yaml
  kfp-tekton/base/deployments/ml-pipeline.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/base/params.env
  kfp-tekton/base/params.yaml
  kfp-tekton/overlays/moc/smaug/kustomization.yaml
  kfp-tekton/overlays/moc/smaug/params.yaml
  kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-ceph-artifact.enc.yaml
Labels: size/S

#1657 Set up summit cluster to be handled with opf argocd
  argocd/overlays/moc-infra/secrets/clusters/octo-gohan.enc.yaml
  argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml
Labels: size/M, approved, lgtm

#1684 Adding myself to the superset users group
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
Labels: approved, size/XS, lgtm

#1688 update smaug grafana instance to v8.4.3
  grafana/base/grafana.yaml
Labels: approved, size/XS, lgtm

#1689 Give admin replicationsource read/write perms.
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-rs-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-rs-aggregate-to-admin/kustomization.yaml
  cluster-scope/bundles/volsync/kustomization.yaml
Labels: approved, size/S, lgtm

#1690 Add Shreyanand to superset users
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
Labels: approved, size/XS, lgtm

#1683 Fix the cosigned namespace to be default cosign-system
  cluster-scope/base/core/namespaces/cosign-system/kustomization.yaml
  cluster-scope/base/core/namespaces/cosign-system/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cosigned/overlays/octo/rolebinding.yaml
Labels: approved, size/XS, lgtm

#1692 Add lowercase constraint for Superset users
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
  docs/content/odh/superset/add_superset_users.md
Labels: approved, size/XS, lgtm

#1693 Fix bad quotes in snapshotschedule
  cluster-scope/overlays/prod/moc/smaug/snapshotschedules/schedule.yaml
Labels: approved, size/XS, lgtm

#1697 Correct idp-mgmt operator subscription name.
  cluster-scope/base/operators.coreos.com/subscriptions/idp-mgmt-operator/subscription.yaml
Labels: size/XS, lgtm

#1700 Remove namespace entries in kfp-tekton rolebinding objects
  kfp-tekton/base/rolebindings/kubeflow-pipelines-metadata-writer-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-persistenceagent-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-scheduledworkflow-binding.yaml
Labels: approved, size/XS, lgtm

#1639 Use one dashboard for different overlays
  grafana/overlays/moc/smaug/dashboards/thoth-station/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/common-patch.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/common-patch.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: size/L, approved, lgtm

#1682 Switch odh deployment to use olm for osc-cl1.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/odh-operator.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  odh-operator/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/M, lgtm

#1704 Redirect oscl1 kfdefs to oscl1 odh-manifests branch.
  kfdefs/overlays/osc/osc-cl1/jupyterhub/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/seldon/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/superset/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
Labels: approved, size/XS, lgtm

#1701 Rearrange code
  grafana/overlays/moc/smaug/blackbox-exporter/config-map.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/deployment.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/kustomization.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/route.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/service.yaml
  grafana/overlays/moc/smaug/kustomization.yaml
  kfdefs/base/monitoring/blackbox-exporter/blackbox-prober-config.yaml
  kfdefs/base/monitoring/blackbox-exporter/blackbox-service.yaml
  kfdefs/base/monitoring/blackbox-exporter/blackbox.yaml
  kfdefs/base/monitoring/blackbox-exporter/es-secret-generator.yaml
  kfdefs/base/monitoring/blackbox-exporter/es-secret.enc.yaml
  kfdefs/base/monitoring/blackbox-exporter/kustomization.yaml
  kfdefs/base/monitoring/blackbox-exporter/probe.yaml
  kfdefs/base/monitoring/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
Labels: size/L, approved, lgtm

#1710 Configure image registry storage
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: approved, size/S, lgtm

#1705 Onboarding Redhat-Impact team
  cluster-scope/base/core/namespaces/chrisproject/kustomization.yaml
  cluster-scope/base/core/namespaces/chrisproject/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/redhat-impact/group.yaml
  cluster-scope/base/user.openshift.io/groups/redhat-impact/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/redhat-impact/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/redhat-impact/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved

#1709 Onboarding ManageIQ
  cluster-scope/base/core/namespaces/manageiq/kustomization.yaml
  cluster-scope/base/core/namespaces/manageiq/namespace.yaml
  cluster-scope/base/core/namespaces/manageiq/resourcequota.yaml
  cluster-scope/base/user.openshift.io/groups/manageiq/group.yaml
  cluster-scope/base/user.openshift.io/groups/manageiq/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/manageiq/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/manageiq/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1708 Onboarding Fedora
  cluster-scope/base/core/namespaces/fedora/kustomization.yaml
  cluster-scope/base/core/namespaces/fedora/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/fedora/group.yaml
  cluster-scope/base/user.openshift.io/groups/fedora/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/fedora/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/fedora/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1711 Add namespace for seraph host inventory
  cluster-scope/base/core/namespaces/seraph-host-inventory/kustomization.yaml
  cluster-scope/base/core/namespaces/seraph-host-inventory/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
  cluster-scope/bundles/seraph/kustomization.yaml
Labels: approved, size/S, lgtm

#1596 Added section to Grafana Docs on how to back working dashboard
  docs/content/grafana/add_grafana_dashboard.md
  docs/content/grafana/img/share-icon.png
Labels: approved, size/S, lgtm

#1714 Add seraph group into overlay
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/XS, lgtm

#1716 Adding service monitor to the grafana/blackbox-exporter kustomization file in Smaug
  grafana/overlays/moc/smaug/blackbox-exporter/kustomization.yaml
Labels: approved, size/XS, lgtm

#1719 Fix the namespace cosigned in the agrocd app
  argocd/overlays/moc-infra/applications/envs/octo/gohan/cosigned.yaml
  argocd/overlays/moc-infra/applications/envs/octo/summit-cl1/cosigned.yaml
Labels: approved, size/XS, lgtm

#1715 updating managedIQ group with additional users
  cluster-scope/base/user.openshift.io/groups/manageiq/group.yaml
Labels: approved, size/XS, lgtm

#1720 Add harshad as a argocd admins
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Labels: approved, size/XS, lgtm

#1718 Update superset kfdef in osc-cl2.
  kfdefs/overlays/osc/osc-cl2/superset/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/superset-oidc.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/superset.enc.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/supersetdb.enc.yaml
Labels: size/L, approved, lgtm

#1721 Update trino kfdef in osc-cl2.
  kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-coordinator.config
  kfdefs/overlays/osc/osc-cl2/trino/configs/jvm-worker.config
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
Labels: approved, size/S, lgtm

#1723 Update jupyterhub kfdef in osc-cl2.
  kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml
Labels: approved, size/XS, lgtm

#1724 Update seldon kfdef to odh 1.1.2 in osc-cl2.
  kfdefs/overlays/osc/osc-cl2/seldon/kfdef.yaml
Labels: approved, size/XS, lgtm

#1685 fix runbook url in smaug Jupyterhub PVC alerts
  kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml
Labels: approved, size/XS, lgtm, jupyterhub

#1722 Deprecate prescritption refresh job application from argocd
  argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/prod/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/prod/prod-thoth-prescriptions-refresh-job.yaml
Labels: approved, size/S, lgtm

#1728 Fix grafana share image
  docs/content/grafana/add_grafana_dashboard.md
  docs/content/grafana/img/share-icon.png
Labels: approved, size/XS, lgtm

#1729 Add rbo to sre group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1730 Create project rbo-builder - operate-first/support/issues/341
  cluster-scope/base/core/namespaces/rbo-builder/kustomization.yaml
  cluster-scope/base/core/namespaces/rbo-builder/namespace.yaml
  cluster-scope/components/project-admin-rolebindings/rbo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/rbo/rbac.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: size/M, approved, lgtm

#1731 Onboard examples.openshift.pub operate-first/support/issues/343
  cluster-scope/base/core/namespaces/examples-openshift-pub/kustomization.yaml
  cluster-scope/base/core/namespaces/examples-openshift-pub/namespace.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: approved, size/S, lgtm

#1743 Add link to morty cluster
  docs/content/README.md
Labels: approved, size/XS, lgtm

#1744 Add custom folder name for thoth dashboards
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/thoth-workflow-controllers-metrics.yaml
Labels: approved, size/XS, lgtm

#1736 add sandbox schema to cl2 trino
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#1687 Meta labels added to the project namespace manifests
  cluster-scope/base/core/namespaces/acm/namespace.yaml
  cluster-scope/base/core/namespaces/acme-operator/namespace.yaml
  cluster-scope/base/core/namespaces/opf-jupyterhub/namespace.yaml
  cluster-scope/base/core/namespaces/opf-kafka/namespace.yaml
  cluster-scope/base/core/namespaces/opf-observatorium/namespace.yaml
Labels: approved, size/S, lgtm

#1751 Deploy ray operator and images on smaug jupyterhub
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
Labels: approved, size/XS, lgtm

#1754 Add cuda buildchain to osc-cl2 jupyterhub.
  kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml
Labels: approved, size/XS, lgtm

#1753 Remove highlight-text fragment from docs link
  cluster-scope/base/core/namespaces/acme-operator/namespace.yaml
Labels: approved, size/XS, lgtm

#1755 Use image directly in manifest instead of using imagestream
  kfdefs/base/jupyterhub/ray-odh-integration/kustomization.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-node-imagestream.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-imagestream.yaml
Labels: size/M, approved, lgtm

#1733 add pcaf_sovereign_footprint, add privs for patryciabp
  kfdefs/overlays/osc/osc-cl1/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml
Labels: size/M, lgtm

#1757 Fix the execution directories for ray operator and node
  kfdefs/base/jupyterhub/ray-odh-integration/ray-cluster-template-cm.yaml
  kfdefs/base/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
Labels: approved, size/S, lgtm

#1759 setup pulp backup for replication
  pulp/overlays/moc/smaug/kustomization.yaml
  pulp/overlays/moc/smaug/opf-pulp-backup.yaml
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: size/M, approved, lgtm

#1760 Fix the version typo for pulp backup
  pulp/overlays/moc/smaug/opf-pulp-backup.yaml
Labels: approved, size/XS, lgtm

#1758 feat(onboarding): Add team team-pixel
  cluster-scope/base/core/namespaces/pixel-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/pixel-demo/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/team-pixel/group.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: size/M, approved, lgtm, needs-ok-to-test

#1761 Include pulp backup and restore to be deployed via argocd
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: approved, size/XS, lgtm

#1756 Change number of machines of p type to 3
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-p.yaml
Labels: approved, size/XS, lgtm

#1762 Get OSC admins argocd access to all osc apps
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/acme-operator.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/cloudbeaver.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/dex.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kfdefs.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/acme-operator.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/cloudbeaver.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/das.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/dex.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kfdefs.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/os-climate.yaml
  cluster-scope/base/user.openshift.io/groups/osc-admins/group.yaml
Labels: size/L, approved, lgtm

#1763 Remove invalid argocd cluster secret.
  argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml
Labels: approved, size/XS, lgtm

#1764 Fix summit-cl1 setup secrets
  argocd/overlays/moc-infra/secrets/clusters/octo-summit-cl1.enc.yaml
  argocd/overlays/moc-infra/secrets/clusters/secret-generator.yaml
Labels: size/M, approved, lgtm

#1738 Update trino kfdef in osc-cl1 to ODH v1.1.2
  kfdefs/overlays/osc/osc-cl1/trino/configs/jvm-coordinator.config
  kfdefs/overlays/osc/osc-cl1/trino/configs/jvm-worker.config
  kfdefs/overlays/osc/osc-cl1/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
Labels: size/S, lgtm

#1739 Update jupyterhub kfdef to ODH v1.1.2 in osc-cl1
  kfdefs/overlays/osc/osc-cl1/jupyterhub/kfdef.yaml
Labels: size/XS, do-not-merge/hold

#1740 Update seldon kfdef to odh 1.1.2 in osc-cl1
  kfdefs/overlays/osc/osc-cl1/seldon/kfdef.yaml
Labels: approved, lgtm

#1737 Update superset kfdef in osc-cl1 to ODH v1.1.2
  kfdefs/overlays/osc/osc-cl1/superset/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/superset/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl1/superset/secrets/superset-oidc.yaml
  kfdefs/overlays/osc/osc-cl1/superset/secrets/superset.enc.yaml
  kfdefs/overlays/osc/osc-cl1/superset/secrets/supersetdb.enc.yaml
Labels: size/L, do-not-merge/hold, lgtm

#1750 feat: Add mimotej to Seraph group
  cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
Labels: approved, size/XS, lgtm

#1765 adding adiy10 as username
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1747 onboarding rh-curator-eval
  cluster-scope/base/core/namespaces/rh-curator-eval/kustomization.yaml
  cluster-scope/base/core/namespaces/rh-curator-eval/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/rh-curator-eval/group.yaml
  cluster-scope/base/user.openshift.io/groups/rh-curator-eval/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/rh-curator-eval/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/rh-curator-eval/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1767 Remove spark operator from osc-cl2 odh.
  kfdefs/overlays/osc/osc-cl2/jupyterhub/kfdef.yaml
Labels: approved, size/XS

#1768 Switch osc datacommons data catalog to iceberg.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
Labels: approved, size/XS, lgtm

#1770 add esg-matching schema
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#1742 [grafana] Add the pulp-metrics dashboard
  grafana/overlays/moc/smaug/dashboards/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/pulp/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/pulp/pulp-metrics.yaml
Labels: approved, size/S, lgtm

#1771 Add myself to the microshift group
  cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml
Labels: approved, size/XS, lgtm

#1741 Adding recording rules to blackbox exporter and adding more services to service monitor in blackbox
  grafana/overlays/moc/smaug/blackbox-exporter/recording-rules.yaml
  grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml
Labels: size/L, approved, lgtm

#1777 Add oc pipelines as a bundle to os-cl2.
  cluster-scope/base/operators.coreos.com/subscriptions/openshift-pipelines-operator-rh/subscription.yaml
  cluster-scope/bundles/openshift-pipelines/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/subscriptions/openshift-pipelines-operator-rh_patch.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/S, lgtm

#1779 Add kfp-tekton app to osc-cl2.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kfp-tekton.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  kfp-tekton/overlays/osc/osc-cl2/kustomization.yaml
  kfp-tekton/overlays/osc/osc-cl2/params.yaml
  kfp-tekton/overlays/osc/osc-cl2/secret-generator.yaml
  kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-ceph-artifact.enc.yaml
Labels: size/M, lgtm

#1783 update the version of the nfd operator for 4.9 ocp cluster to use nfd…
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/patches/nfd-sub-patch.yaml
Labels: approved, size/XS, lgtm

#1786 Add kfp tekton bundle to osc-cl2.
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/XS, lgtm

#1787 Add minio artifact secret to osc-cl2 kfptekton.
  kfp-tekton/overlays/osc/osc-cl2/secret-generator.yaml
  kfp-tekton/overlays/osc/osc-cl2/secrets/mlpipeline-minio-artifact.enc.yaml
Labels: size/M, approved, lgtm

#1789 Add tzumainn to sre group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1791 Added missing display names to Namespace manifests
  cluster-scope/base/core/namespaces/aicoe-meteor/namespace.yaml
  cluster-scope/base/core/namespaces/boatrockers/namespace.yaml
  cluster-scope/base/core/namespaces/chrisproject/namespace.yaml
  cluster-scope/base/core/namespaces/curator-engine/namespace.yaml
Labels: size/XS

#1794 creating grafana-viewer group and adding to smaug grafana oauth
  cluster-scope/base/user.openshift.io/groups/grafana-viewer/group.yaml
  cluster-scope/base/user.openshift.io/groups/grafana-viewer/kustomization.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/S, lgtm

#1795 fixing map_groups_to_roles and adding grafana viewer group to smaug
  cluster-scope/overlays/prod/common/kustomization.yaml
  docs/content/grafana/map_groups_to_roles.md
Labels: approved, size/XS, lgtm

#1772 pointing kfdefs to odh-manifests migration
  kfdefs/overlays/moc/smaug/opf-dashboard/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-dashboard/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/servicemonitor.yaml
  kfdefs/overlays/moc/smaug/opf-seldon/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-superset/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-superset/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
Labels: size/L, approved, lgtm

#1796 adding the additional overlay for the jupyterhub notebook-images kfdef
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
Labels: size/XS, lgtm

#1797 Move kfdef jh parameters to appropriate app in smaug.
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
Labels: size/S, lgtm

#1798 Add auto sync of notebooks to hitchhiker repo.
  .github/sync.yml
  .github/workflows/sync.yml
Labels: approved, size/S, lgtm

#1799 Fix typo in sync action.
  .github/sync.yml
Labels: size/XS, lgtm

#1793 adding opf-instance label in blackbox-service monitor
  grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml
Labels: approved, size/S, lgtm

#1803 add dystewar to sudoers group in morty cluster
  cluster-scope/overlays/prod/emea/morty/groups/sudoers.yaml
Labels: approved, size/XS, lgtm

#1804 SCSAOL access to Grafana Console & Loki API
  grafana/overlays/moc/smaug/grafana-oauth.yaml
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1801 Update group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/L, approved, ok-to-test

#1675 Move smaug kafka overlays to use the kafka operator and create kafka app
  argocd/overlays/moc-infra/applications/envs/emea/rick/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/opf-kafka.yaml
  kafka/overlays/smaug/kafka-podmonitors.yaml
  kafka/overlays/smaug/kustomization.yaml
  kafka/overlays/smaug/secrets/kustomization.yaml
  kafka/overlays/smaug/secrets/opf-public-demo-user-creds.yaml
  kafka/overlays/smaug/topics/audio-decoder-decoded-speech.yaml
  kafka/overlays/smaug/topics/audio-decoder-sentiment-text.yaml
  kafka/overlays/smaug/topics/balrog-cluster-app-logs.yaml
  kafka/overlays/smaug/topics/balrog-cluster-audit-logs.yaml
  kafka/overlays/smaug/topics/balrog-cluster-infra-logs.yaml
  kafka/overlays/smaug/topics/infra-cluster-app-logs.yaml
  kafka/overlays/smaug/topics/infra-cluster-audit-logs.yaml
  kafka/overlays/smaug/topics/infra-cluster-infra-logs.yaml
  kafka/overlays/smaug/topics/kustomization.yaml
  kafka/overlays/smaug/topics/rick-cluster-app-logs.yaml
  kafka/overlays/smaug/topics/rick-cluster-audit-logs.yaml
  kafka/overlays/smaug/topics/rick-cluster-infra-logs.yaml
  kafka/overlays/smaug/topics/smaug-cluster-app-logs.yaml
  kafka/overlays/smaug/topics/smaug-cluster-audit-logs.yaml
  kafka/overlays/smaug/topics/smaug-cluster-infra-logs.yaml
  kafka/overlays/smaug/topics/thoth-advise-justification.yaml
  kafka/overlays/smaug/topics/thoth-adviser-trigger.yaml
  kafka/overlays/smaug/topics/thoth-build-analysis-trigger.yaml
  kafka/overlays/smaug/topics/thoth-cve-provided.yaml
  kafka/overlays/smaug/topics/thoth-hash-mismatch.yaml
  kafka/overlays/smaug/topics/thoth-kebechet-run-url.yaml
  kafka/overlays/smaug/topics/thoth-kebechet-trigger.yaml
  kafka/overlays/smaug/topics/thoth-missing-package-version.yaml
  kafka/overlays/smaug/topics/thoth-missing-package.yaml
  kafka/overlays/smaug/topics/thoth-package-extract-trigger.yaml
  kafka/overlays/smaug/topics/thoth-package-released.yaml
  kafka/overlays/smaug/topics/thoth-provenance-checker-trigger.yaml
  kafka/overlays/smaug/topics/thoth-qebhwt-trigger.yaml
  kafka/overlays/smaug/topics/thoth-si-unanalyzed-package.yaml
  kafka/overlays/smaug/topics/thoth-solved-package.yaml
  kafka/overlays/smaug/topics/thoth-unresolved-package.yaml
  kafka/overlays/smaug/topics/thoth-unrevsolved-package.yaml
  kafka/overlays/smaug/topics/thoth-update-provides-source-distro.yaml
  kafka/overlays/smaug/users/audio-decoder.yaml
  kafka/overlays/smaug/users/cluster-logging.yaml
  kafka/overlays/smaug/users/kustomization.yaml
  kafka/overlays/smaug/users/opf-public-demo.yaml
  kafka/overlays/smaug/users/thoth.yaml
  kfdefs/base/kafka/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-kafka/kustomization.yaml
  odh-manifests/smaug/kafka/base/kafka-cluster.yaml
Labels: size/L, lgtm

#1808 [dashboard] Fix the node feature discovery grafana dashboard
  grafana/overlays/moc/smaug/dashboards/cluster-management/node-feature-discovery.yaml
Labels: size/L, approved, lgtm

#1810 Remove opf-kafka from smaug kfdef root kustomization.
  kfdefs/overlays/moc/smaug/kustomization.yaml
Labels: size/XS, lgtm

#1812 Add opf-kafdrop patch in opf-kafka-smaug app
  kafka/overlays/smaug/kustomization.yaml
  kafka/overlays/smaug/opf-kafdrop.yaml
Labels: size/M, approved, lgtm

#1712 add manifests to create Hashicorp Vault cluster in Operate First
  argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/operate-first/opf-vault.yaml
  cluster-scope/base/core/namespaces/vault/kustomization.yaml
  cluster-scope/base/core/namespaces/vault/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/vault/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  vault/base/configmaps/configmap.yaml
  vault/base/configmaps/kustomization.yaml
  vault/base/kustomization.yaml
  vault/base/policy/kustomization.yaml
  vault/base/policy/poddisruptionbudget.yaml
  vault/base/rbac.authorization.k8s.io/kustomization.yaml
  vault/base/rbac.authorization.k8s.io/rolebindings/rolebinding.yaml
  vault/base/rbac.authorization.k8s.io/roles/role.yaml
  vault/base/serviceaccounts/kustomization.yaml
  vault/base/serviceaccounts/serviceaccount.yaml
  vault/base/services/kustomization.yaml
  vault/base/services/opf-vault-active/service.yaml
  vault/base/services/opf-vault-internal/service.yaml
  vault/base/services/opf-vault-standby/service.yaml
  vault/base/services/opf-vault-ui/service.yaml
  vault/base/services/opf-vault/service.yaml
  vault/base/statefulsets/kustomization.yaml
  vault/base/statefulsets/statefulset.yaml
  vault/overlays/moc/infra/kustomization.yaml
Labels: size/L, approved, lgtm

#1818 removing opf-kafka from dev kfdefs overlay
  kfdefs/overlays/dev/kustomization.yaml
Labels: approved, size/XS, lgtm

#1814 update cl2 size options
  kfdefs/overlays/osc/osc-cl2/jupyterhub/profiles/singleuser-profiles-container-sizes.yaml
Labels: approved, size/S, lgtm

#1817 [Smaug][kafka] Fix: Update kafka instance in smaug
  cluster-scope/base/core/namespaces/opf-kafka/resourcequota.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/strimzi-kafka-overview.yaml
  kafka/base/opf-kafka.yaml
  kafka/overlays/rick/kustomization.yaml
  kafka/overlays/rick/opf-kafdrop.yaml
  kafka/overlays/rick/secrets/kustomization.yaml
  kafka/overlays/rick/secrets/opf-public-demo-user-creds.yaml
  kafka/overlays/rick/topics/kustomization.yaml
  kafka/overlays/rick/topics/thoth-advise-justification.yaml
  kafka/overlays/rick/topics/thoth-adviser-trigger.yaml
  kafka/overlays/rick/topics/thoth-build-analysis-trigger.yaml
  kafka/overlays/rick/topics/thoth-cve-provided.yaml
  kafka/overlays/rick/topics/thoth-hash-mismatch.yaml
  kafka/overlays/rick/topics/thoth-kebechet-run-url.yaml
  kafka/overlays/rick/topics/thoth-kebechet-trigger.yaml
  kafka/overlays/rick/topics/thoth-missing-package-version.yaml
  kafka/overlays/rick/topics/thoth-missing-package.yaml
  kafka/overlays/rick/topics/thoth-package-extract-trigger.yaml
  kafka/overlays/rick/topics/thoth-package-released.yaml
  kafka/overlays/rick/topics/thoth-provenance-checker-trigger.yaml
  kafka/overlays/rick/topics/thoth-qebhwt-trigger.yaml
  kafka/overlays/rick/topics/thoth-si-unanalyzed-package.yaml
  kafka/overlays/rick/topics/thoth-solved-package.yaml
  kafka/overlays/rick/topics/thoth-unresolved-package.yaml
  kafka/overlays/rick/topics/thoth-unrevsolved-package.yaml
  kafka/overlays/rick/topics/thoth-update-provides-source-distro.yaml
  kafka/overlays/rick/users/kustomization.yaml
  kafka/overlays/rick/users/opf-public-demo.yaml
  kafka/overlays/rick/users/thoth.yaml
Labels: size/L, lgtm

#1806 Update group.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1822 Fixing vault statefulset.yaml to include missing volume claims
  vault/base/statefulsets/statefulset.yaml
Labels: size/M, approved, lgtm

#1826 Add reporef to smaug jh kfdef.
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kfdef.yaml
Labels: approved, size/XS, lgtm

#1821 Add pachyderm osc admin group.
  cluster-scope/base/core/namespaces/pachyderm/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/pachyderm-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/pachyderm-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/osc-pachyderm-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/osc-pachyderm-admins/rbac.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/pachyderm-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/pachyderm-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  pachyderm/base/pachyderm.yaml
  pachyderm/overlays/osc/OWNERS
Labels: size/M, approved, lgtm

#1827 Add imagestream for htm-applications notebooks image for Jupyterhub smaug cluster
  kfdefs/base/jupyterhub/notebook-images/htm-applications.yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/kustomization.yaml
Labels: approved, size/XS, lgtm

#1782 add: Reloader deployment to osc-cl2 cluster
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/reloader.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  reloader/overlays/osc/osc-cl2/kustomization.yaml
Labels: approved, size/S, lgtm

#1825 Adding custom resource quota for vault deployment in smaug
  cluster-scope/base/core/namespaces/vault/kustomization.yaml
  cluster-scope/base/core/namespaces/vault/resourcequota.yaml
Labels: approved, size/S, do-not-merge/hold, lgtm

#1830 adjust vault pod volume claims and namespace resource quota
  cluster-scope/base/core/namespaces/vault/resourcequota.yaml
  vault/base/statefulsets/statefulset.yaml
Labels: approved, size/XS, lgtm

#1820 Add k8s-annotations-exporter to osc clusters
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/k8s-annotations-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/k8s-annotations-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  k8s-annotations-exporter/overlays/osc/osc-cl1/kustomization.yaml
  k8s-annotations-exporter/overlays/osc/osc-cl2/kustomization.yaml
Labels: size/M, lgtm

#1833 Add opf-monitoring cluster-scope bundle
  cluster-scope/bundles/opf-monitoring/grafana-serviceaccount.yaml
  cluster-scope/bundles/opf-monitoring/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1835 Use identitatem to manage morty cluster auth.
  acm/overlays/moc/infra/identitatem/authrealms/primary.yaml
  acm/overlays/moc/infra/managedclusters/morty.yaml
  acm/overlays/moc/infra/managedclustersetbindings/argocd/kustomization.yaml
  acm/overlays/moc/infra/managedclustersetbindings/base/kustomization.yaml
  acm/overlays/moc/infra/managedclustersetbindings/idp-auth-primary/kustomization.yaml
  acm/overlays/moc/infra/placements/primary-auth.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/morty/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/morty/secret-generator.yaml
  docs/_toc.yml
  docs/content/acm/adding_managed_cluster_to_identitatem.md
  keycloak/overlays/moc/infra/clients/morty.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, approved, lgtm

#1836 Upgrade api version for grafana viewer crb.
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-monitoring-grafana-cluster-view/clusterrolebinding.yaml
Labels: approved, size/XS, lgtm
