Repository operate-first/apps, pull requests merged in 2022-08, with the labels that each got.

#2190 Increase the ResourceQuota from medium to large for the smart-village-view project
  cluster-scope/base/core/namespaces/smart-village-view/kustomization.yaml
Labels: size/XS

#2192 Add okd-team group
  cluster-scope/base/user.openshift.io/groups/okd-team/group.yaml
  cluster-scope/base/user.openshift.io/groups/okd-team/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2193 Add okd-wg group
  cluster-scope/base/user.openshift.io/groups/okd-wg/group.yaml
  cluster-scope/base/user.openshift.io/groups/okd-wg/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2212 Added a new image stream for under the covers the secret life of soft…
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/base/jupyterhub/notebook-images/ucsls.yaml
Labels: size/M, approved, lgtm, ok-to-test

#2170 Add banzaicloud-vault ns to smaug and banzaicloud vault operator subscription
  cluster-scope/base/core/namespaces/banzaicloud-vault/kustomization.yaml
  cluster-scope/base/core/namespaces/banzaicloud-vault/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/subscription.yaml
  cluster-scope/bundles/banzaicloud-vault/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2223 adding myself to morty cluster admins and removing 4n4nd
  cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#2202 Adding argocd apps to osc-cl2.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/fybrik.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/vault.yaml
  argocd/overlays/moc-infra/projects/fybrik.yaml
Labels: size/M, approved, lgtm, needs-ok-to-test

#2226 Adjust osc-cl2 argocd project structure.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
Labels: approved, size/S, lgtm

#2224 otel-dev public viewable
  cluster-scope/base/core/namespaces/otel-dev/kustomization.yaml
Labels: size/XS

#2216 Change on-call rotation period and add members to on-call duty
  slack-first/overlays/moc/smaug/config.yaml
Labels: approved, size/S, lgtm

#2227 Add Kafka connector to osc-cl2 trino.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: size/XS, lgtm

#2230 Add fx table schema for osc-cl2 trino.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/fx.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: size/M

#2215 added stackrox to secret management
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/stackrox/kustomization.yaml
Labels: size/XS

#2217 adding cooktheryan to ACM users and docs
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
  docs/content/acm/README.md
Labels: approved, size/XS, lgtm

#2231 Update vault operator catalogSource & operatorGroup
  cluster-scope/base/operators.coreos.com/operatorgroups/banzaicloud-vault/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/banzaicloud-vault/subscription.yaml
Labels: approved, size/XS, lgtm

#2232 :arrow_up: Updated the version of ray components to ray v1.13.0
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
  kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-operator-deployment.yaml
Labels: approved, size/XS, lgtm

#2233 Fix landing page logo for grafana.
  grafana/overlays/moc/smaug/landingpage-dashboard-configmap.yaml
Labels: approved, size/XS, lgtm

#2229 add otel-dev sample otlp app to argocd
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/hello-opentelemetry.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/kustomization.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/otel-dev.yaml
Labels: size/M

#2237 fix octo-otel-dev helm paramaters
  argocd/overlays/moc-infra/applications/envs/moc/smaug/octo-otel-dev/hello-opentelemetry.yaml
Labels: approved, size/XS, lgtm

#2235 update thoth members
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Labels: approved, size/XS, lgtm

#2234 declare a new hive catalog for trino ingest on osc-cl2
  docs/content/odh/trino/add_more_buckets.md
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_hive_ingest.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/hive-metastores/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/hive-metastores/osc_datacommons_hive_ingest/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml
Labels: size/L, approved, lgtm

#2240 Correct metastore uri in trino docs.
  docs/content/odh/trino/add_more_buckets.md
Labels: size/XS

#2243 Convert osc-cl2 trino secrets to ES.
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/s3buckets.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/shared-secret.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/trino-oauth.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/shared-secret.yaml
  kfdefs/overlays/osc/osc-cl2/trino/secrets/trino-oauth.yaml
Labels: size/L, approved, lgtm

#2244 Switch superset in osc-cl2 to use eso.
  kfdefs/overlays/osc/osc-cl2/superset/externalsecrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/superset/externalsecrets/superset.yaml
  kfdefs/overlays/osc/osc-cl2/superset/externalsecrets/supersetdb.yaml
  kfdefs/overlays/osc/osc-cl2/superset/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/superset.enc.yaml
  kfdefs/overlays/osc/osc-cl2/superset/secrets/supersetdb.enc.yaml
Labels: size/L, approved, lgtm

#2246 Created stackrox-admin group and added traytorous as a member
  cluster-scope/base/core/namespaces/stackrox/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/stackrox-admin/group.yaml
  cluster-scope/base/user.openshift.io/groups/stackrox-admin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/stackrox-admin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/stackrox-admin/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: size/M

#2245 hive "ingest" schema on CL2
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M

#2247 Increase ResourceQuota for Apicurio projects
  cluster-scope/base/core/namespaces/api-designer/kustomization.yaml
  cluster-scope/base/core/namespaces/api-designer/resourcequota.yaml
  cluster-scope/base/core/namespaces/apicurio-apicurio-registry/kustomization.yaml
  cluster-scope/base/core/namespaces/apicurio-apicurio-registry/resourcequota.yaml
Labels: approved, size/S, lgtm

#2248 Add Pep to the odh-admin group
  cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
Labels: size/S

#2251 :hatched_chick: Updated the prow config, plugin and secrets
  prow/OWNERS
  prow/README.md
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/imagestreamtags.yaml
  prow/overlays/smaug/plugins.yaml
  prow/overlays/smaug/secrets.enc.yaml
  prow/update-imagestreams.py
Labels: approved, size/XXL

#2252 :recycle: Empty annotation is causing issue in argo sync
  prow/overlays/smaug/imagestreamtags.yaml
  prow/update-imagestreams.py
Labels: size/L, approved, lgtm

#2255 Switch osc-cl1 trino secrets to use eso.
  kfdefs/overlays/osc/osc-cl1/trino/externalsecrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/externalsecrets/s3buckets.yaml
  kfdefs/overlays/osc/osc-cl1/trino/externalsecrets/trino-oauth.yaml
  kfdefs/overlays/osc/osc-cl1/trino/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/trino/secrets/s3buckets.yaml
  kfdefs/overlays/osc/osc-cl1/trino/secrets/secret-generator.yaml
  kfdefs/overlays/osc/osc-cl1/trino/secrets/trino-oauth.yaml
Labels: size/L, lgtm

#2256 Fix the image for init contianer for prow task
  prow/README.md
  prow/overlays/smaug/ghproxy.yaml
  prow/overlays/smaug/imagestreamtags.yaml
Labels: size/M, approved, lgtm

#2258 feat: Remove max from on-call
  slack-first/overlays/moc/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2260 [prow] Fix command path for prow commenter image
  prow/overlays/smaug/config.yaml
Labels: size/XS

#2219 Add various OKD infrastructure
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/kvm-device-plugin.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/okd-centos.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/okd-team.yaml
  cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml
  cluster-scope/base/apps/daemonsets/kvm-device-plugin/kustomization.yaml
  cluster-scope/base/core/namespaces/kvm-device-plugin/kustomization.yaml
  cluster-scope/base/core/namespaces/kvm-device-plugin/namespace.yaml
  cluster-scope/base/core/namespaces/okd-centos/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-centos/namespace.yaml
  cluster-scope/base/core/namespaces/okd-team/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-team/namespace.yaml
  cluster-scope/base/core/namespaces/okd-wg/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-wg/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/rolebindings/kvm-device-plugin/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/rolebindings/kvm-device-plugin/rolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/roles/kvm-device-plugin/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/roles/kvm-device-plugin/role.yaml
  cluster-scope/bundles/kvm-device-plugin/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/okd-team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/okd-team/rbac.yaml
  cluster-scope/components/project-admin-rolebindings/okd-wg/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/okd-wg/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kvm-device-plugin/base/buildconfig.yaml
  kvm-device-plugin/base/imagestream.yaml
  kvm-device-plugin/base/kustomization.yaml
  kvm-device-plugin/base/serviceaccount.yaml
  kvm-device-plugin/overlays/smaug/kustomization.yaml
  okd-centos/base/buildconfig.yaml
  okd-centos/base/imagestream.yaml
  okd-centos/base/kustomization.yaml
  okd-centos/base/rolebinding.yaml
  okd-centos/overlays/smaug/kustomization.yaml
Labels: size/L, do-not-merge/hold, ok-to-test

#2259 Add pep to osc-cl1 odh-admin group
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
Labels: approved, size/S, lgtm

#2262 OKD infra fixups
  cluster-scope/base/core/namespaces/kvm-device-plugin/kustomization.yaml
  cluster-scope/base/core/namespaces/okd-centos/kustomization.yaml
  kvm-device-plugin/base/buildconfig.yaml
Labels: approved, lgtm

#2254 add reloader annotation to slack first operator
  slack-first/base/deployment.yaml
Labels: size/XS

#2263 Specify resource limits and requests on kvm-device-plugin containers in DS
  cluster-scope/base/apps/daemonsets/kvm-device-plugin/daemonset.yaml
Labels: size/XS, needs-ok-to-test

#2220 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: approved, size/XXL, lgtm

#2267 :recycle: Switch to morty obc for temp fix.
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/secrets.enc.yaml
Labels: size/L, approved, lgtm

#2265 Add okd-wg members to argocd-readonly group
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#2266 giving apicurio group thanos and grafana access
  grafana/overlays/moc/smaug/grafana-oauth.yaml
  observatorium/overlays/moc/smaug/thanos/rolebindings/opf-observatorium-view.yaml
Labels: approved, lgtm

#2271 adding jerry to acm managedclusters
  acm/overlays/moc/infra/managedclusters/jerry.yaml
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
Labels: approved, size/XS, lgtm

#2274 add durandom to argocd and smaug admins
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#2272 add cluster-admins for jerry
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-jerry.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/jerry/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/emea/jerry/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/jerry/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: size/M, approved, lgtm

#2276 upgrading openshift on infra cluster to version 4.8.47
  cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
Labels: size/XS

#2275 feat: Add myself to vault admins
  cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
Labels: approved, lgtm

#2279 add users to hive_ingest and port workflow schemas to CL2
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
Labels: approved, lgtm

#2277 upgrading openshift on infra cluster to version 4.9.45
  cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
Labels: size/XS

#2280 Add aicoe_osc_demo_results schema
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#2281 upgrading openshift on infra cluster to version 4.10.26
  cluster-scope/overlays/prod/moc/infra/clusterversion.yaml
Labels: approved, size/XS, lgtm

#2287 updating documentation for getting acm acess
  docs/content/acm/README.md
  docs/content/argocd-gitops/get_access_to_argocd.md
Labels: approved, size/XS, lgtm

#2291 Update github handle of Shreyanand
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
Labels: approved, size/XS, lgtm

#2292 correct aicoe_osc_demo schema group name
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: approved, size/XS, lgtm

#2289 doubling kubeval check memory limits and requires
  .prow.yaml
Labels: size/XS

#2282 chore: Remove unused OCS and migrate docs to ODF
  argocd/overlays/moc-infra/applications/envs/dev/cluster-management/ceph.yaml
  argocd/overlays/moc-infra/applications/envs/dev/cluster-management/kustomization.yaml
  ceph/README.md
  ceph/base/kustomization.yaml
  ceph/base/storagecluster.yaml
  ceph/overlays/dev/kustomization.yaml
  docs/_toc.yml
  docs/content/ocs/README.md
  docs/content/odf/README.md
  docs/content/odf/buckets-external-access.md
  docs/content/odf/claiming_object_store.md
  docs/content/odf/runbook.md
Labels: approved, lgtm

#2295 feat: Upgrade ACM operator to 2.5
  cluster-scope/base/operators.coreos.com/subscriptions/acm-operator-subscription/subscription.yaml
Labels: approved, size/XS, kind/feature, lgtm, triage/accepted, sig/operations

#2293 Exclude kvm daemonset img field in argocd app.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/cluster-resources.yaml
Labels: approved, size/XS

#2269 Deploy Kepler on Morty
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kepler.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kustomization.yaml
  cluster-scope/base/apps/daemonsets/kepler-exporter/daemonset.yaml
  cluster-scope/base/apps/daemonsets/kepler-exporter/kustomization.yaml
  cluster-scope/base/core/namespaces/kepler-monitoring/kustomization.yaml
  cluster-scope/base/core/namespaces/kepler-monitoring/namespace.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/50-master-kernel-devel-cgroupv2/50-master-kernel-devel-cgroupv2.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/50-master-kernel-devel-cgroupv2/kustomization.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/50-worker-kernel-devel-cgroupv2/50-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/50-worker-kernel-devel-cgroupv2/kustomization.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/kepler/50-master-kernel-devel-cgroupv2.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/kepler/50-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/base/machineconfiguration.openshift.io/machineconfigs/kepler/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/kepler-clusterrole-binding/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/kepler-clusterrole-binding/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/kepler-clusterrole/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/kepler-clusterrole/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/kepler-scc/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/kepler-scc/securitycontextconstraints.yaml
  cluster-scope/bundles/kepler/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  kepler/base/kustomization.yaml
  kepler/base/service.yaml
  kepler/base/serviceaccount.yaml
  kepler/base/servicemonitor.yaml
  kepler/overlays/emea/morty/kustomization.yaml
Labels: size/L, lgtm, ok-to-test

#2299 Fix unit for kepler ds memory.
  cluster-scope/base/apps/daemonsets/kepler-exporter/daemonset.yaml
Labels: size/XS

#2301 Roeorder volumes in kepler scc.
  cluster-scope/base/security.openshift.io/securitycontextconstraints/kepler-scc/securitycontextconstraints.yaml
Labels: size/XS, lgtm

#2297 fix: Add web terminal already present on infra and change to Automatic
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/subscriptions/web-terminal_patch.yaml
Labels: approved, size/S, lgtm

#2304 Correct apigroup for kvm device plugin rbac.
  cluster-scope/base/rbac.authorization.k8s.io/rolebindings/kvm-device-plugin/rolebinding.yaml
Labels: approved, size/XS, lgtm

#2306 Remove none cluster ip for kepler.
  kepler/base/service.yaml
Labels: size/XS

#2308 adding myself to osc group for ml-kubeflow-pipelines access
  cluster-scope/base/user.openshift.io/groups/osc/group.yaml
Labels: approved, size/XS, lgtm

#2309 adding myself to osc cluster admins for ml-kubeflow-pipelines access
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Labels: size/XS

#2302 Add kepler to osc-cl1 cluster.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kepler.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  cluster-scope/bundles/kepler/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/machineconfigs/kepler/50-master-kernel-devel-cgroupv2.yaml
  cluster-scope/overlays/prod/emea/morty/machineconfigs/kepler/50-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/overlays/prod/emea/morty/machineconfigs/kepler/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machineconfigs/kepler/55-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machineconfigs/kepler/kustomization.yaml
  kepler/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/M, do-not-merge/hold, lgtm

#2312 Opf monitoring eso osc
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/opf-monitoring/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/secret-mgmt/opf-monitoring/kustomization.yaml
  grafana/overlays/osc/osc-cl1/datasources/grafanadatasource.yaml
  grafana/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/S

#2285 removing all references of rick
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/OWNERS
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/core-test.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-advise-reporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-adviser.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-amun-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-chat-notification.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-cve-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-backup.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-refresh.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-graph-sync.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-investigator.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-kebechet.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-management-api.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-metrics-exporter.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-mi.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-extract.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-releases.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-package-update.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-revsolver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-security-indicators.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-solver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/thoth/test/test-thoth-user-api.yaml
  grafana/overlays/moc/smaug/landingpage-dashboard-configmap.yaml
  kafka/overlays/smaug/opf-kafdrop.yaml
Labels: size/XL, approved, lgtm

#2273 Add kubeval docs
  contributing.md
  docs/_toc.yml
  docs/content/kubeval/README.md
  docs/content/kubeval/updating_schema_store.md
Labels: size/M, approved, lgtm

#2205 feat(catalog): Add service catalog as a component following new ADR
  service-catalog/all-components.yaml
  service-catalog/all.yaml
  service-catalog/apis.yaml
  service-catalog/apis/argocd.yaml
  service-catalog/apis/backstage.yaml
  service-catalog/apis/grafana.yaml
  service-catalog/components.yaml
  service-catalog/components/argocd.yaml
  service-catalog/components/backstage.yaml
  service-catalog/components/crunchy-postgres-db.yaml
  service-catalog/components/dex.yaml
  service-catalog/components/grafana.yaml
  service-catalog/components/observatorium.yaml
  service-catalog/components/odf.yaml
  service-catalog/components/odh.yaml
  service-catalog/components/peribolos-as-a-service.yaml
  service-catalog/components/probot-extensions.yaml
  service-catalog/domains.yaml
  service-catalog/domains/sre.yaml
  service-catalog/groups.yaml
  service-catalog/groups/operate-first.yaml
  service-catalog/resources.yaml
  service-catalog/resources/crunchy-postgres-operator.yaml
  service-catalog/resources/s3-bucket.yaml
  service-catalog/resources/smaug.yaml
  service-catalog/systems.yaml
  service-catalog/systems/argocd.yaml
  service-catalog/systems/grafana.yaml
  service-catalog/systems/operate-first-cloud.yaml
  service-catalog/systems/service-catalog.yaml
  service-catalog/users.yaml
Labels: size/L, approved, lgtm

#2325 add trino-secret-env
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/trino/externalsecrets/trino-secret-env.yaml
Labels: size/S

#2257 ignore deploymentconfig diff for images
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/registry.yml
Labels: approved, size/XS, lgtm

#2313 riskthinking catalog
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/riskthinking.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: size/XS, do-not-merge/hold

#2321 chore: Set prow to skip yaml checks on docs/aux files
  .prow.yaml
Labels: approved, size/XS, lgtm

#2326 Give kerpler admins access to osc-cl1 grafana.
  grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml
Labels: size/XS

#2328 Make kepler dashboard in osc generic.
  grafana/overlays/osc/dashboards/kepler/files/kepler.json
  grafana/overlays/osc/dashboards/kepler/grafanadashboard.yaml
  grafana/overlays/osc/dashboards/kepler/kustomization.yaml
  grafana/overlays/osc/dashboards/kustomization.yaml
  grafana/overlays/osc/osc-cl1/dashboards/kepler/kepler.yaml
  grafana/overlays/osc/osc-cl1/dashboards/kepler/kustomization.yaml
  grafana/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/XXL

#2330 Add configmap
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/grafana.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  grafana/overlays/osc/common/dashboards/kustomization.yaml
Labels: size/S

#2221 feat(catalog): Redefine grafana component following a new ADR
  .github/workflows/techdocs.yaml
  docs/_toc.yml
  docs/content/grafana/docs/README.md
  docs/content/grafana/docs/add_grafana_dashboard.md
  docs/content/grafana/docs/img/share-icon.png
  docs/content/grafana/docs/map_groups_to_roles.md
  docs/content/grafana/mkdocs.yaml
  grafana/overlays/moc/smaug-public/grafana-public.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
  service-catalog/apis.yaml
  service-catalog/apis/dex.yaml
  service-catalog/components.yaml
  service-catalog/components/dex.yaml
  service-catalog/components/grafana.yaml
  service-catalog/components/grafana/grafana-oauth.yaml
  service-catalog/components/grafana/grafana-public.yaml
  service-catalog/resources.yaml
  service-catalog/resources/sqlite.yaml
  service-catalog/systems.yaml
  service-catalog/systems/dex.yaml
Labels: size/L, approved, lgtm

#2335 chore: Add myself to SRE group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: size/XS

#2331 Add kepler to osc-cl2.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kepler.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfigs/kepler/55-worker-kernel-devel-cgroupv2.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machineconfigs/kepler/kustomization.yaml
  kepler/overlays/osc/osc-cl2/kustomization.yaml
Labels: size/M, do-not-merge/hold, lgtm

#2333 docs: Remove getting started page
  docs/content/about/intro.md
Labels: size/M, approved, lgtm

#2336 Configure helm chart not to deploy namespaces.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/fybrik/fybrik.yaml
Labels: size/XS

#2340 Fix backupjob
  docs/content/vault_eso/vault_backup_job.md
  vault/overlays/moc/smaug/backup-job/kustomization.yaml
  vault/overlays/moc/smaug/backup-job/scripts/backup-snapshot-to-s3.sh
  vault/overlays/moc/smaug/backup-job/scripts/cleanup-old-taskruns.sh
  vault/overlays/moc/smaug/backup-job/scripts/create-snapshot.sh
  vault/overlays/moc/smaug/backup-job/scripts/prune-old-snapshots.sh
  vault/overlays/moc/smaug/backup-job/secret.yaml
  vault/overlays/moc/smaug/backup-job/task.yaml
  vault/overlays/moc/smaug/backup-job/taskrun.yaml
  vault/overlays/moc/smaug/kustomization.yaml
  vault/overlays/moc/smaug/obc.yaml
Labels: size/L

#2268 [prow] Switch the merge strategy for thoth-station back to 'merge'
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2342 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: approved, size/XXL, lgtm

#2327 removing MOC's Smaug and Infra deployments of nfs-democratic-csi and related resources
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/moc-nfs-democratic-csi.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/moc-nfs-democratic-csi.yaml
  cluster-scope/base/core/namespaces/democratic-csi/kustomization.yaml
  cluster-scope/base/core/namespaces/democratic-csi/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-controller-rb/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-controller-rb/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-node-rb/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/moc-nfs-democratic-csi-node-rb/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-controller-cr/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-controller-cr/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-node-cr/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/moc-nfs-democratic-csi-node-cr/kustomization.yaml
  cluster-scope/base/storage.k8s.io/csidrivers/org.democratic-csi.nfs/csidriver.yaml
  cluster-scope/base/storage.k8s.io/csidrivers/org.democratic-csi.nfs/kustomization.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/moc-nfs-csi/kustomization.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/moc-nfs-csi/storageclass.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/nodenetworkconfigurationpolicies/moc-nfs-network.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/democratic-csi/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/storageclasses/moc-nfs-csi_patch.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/democratic-csi/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  moc-nfs-democratic-csi/base/apps/daemonsets/moc-nfs-democratic-csi-node.yaml
  moc-nfs-democratic-csi/base/apps/deployments/moc-nfs-democratic-csi-controller.yaml
  moc-nfs-democratic-csi/base/core/secrets/controller-expand-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/controller-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/node-publish-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/node-stage-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/secrets/provisioner-secret-moc-nfs-csi-moc-nfs-democratic-csi.yaml
  moc-nfs-democratic-csi/base/core/serviceaccounts/moc-nfs-democratic-csi-controller-sa.yaml
  moc-nfs-democratic-csi/base/core/serviceaccounts/moc-nfs-democratic-csi-node-sa.yaml
  moc-nfs-democratic-csi/base/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/secret-generator.yaml
  moc-nfs-democratic-csi/overlays/moc/infra/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/kustomization.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/secret-generator.yaml
  moc-nfs-democratic-csi/overlays/moc/smaug/secrets/moc-nfs-democratic-csi-driver-config.enc.yaml
Labels: size/XL, do-not-merge/hold

#2345 Add Pep to balrog cluster admins, replacing Anand
  cluster-scope/overlays/prod/emea/balrog/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#2356 Add kepler metrics to osc-cl2 trino.
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/kafka_fx.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kafka-table-description-dir/kepler.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: size/S

#2358 add acl declarations for riskthinking
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm
