Repository operate-first/apps, pull requests merged in 2022-04, with the labels that each got.

#1837 Add identitatem to acm build.
  acm/overlays/moc/infra/kustomization.yaml
Labels: approved, size/XS, lgtm

#1838 add pcaf_sovereign_footprint to cl2
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#1845 Switch identitatem to use op1st github app.
  acm/overlays/moc/infra/identitatem/authrealms/primary.yaml
  acm/overlays/moc/infra/identitatem/clients/github.enc.yaml
Labels: size/M, approved, lgtm

#1850 Add larsks to morty cluster-admins
  cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml
Labels: size/XS, lgtm

#1848 Update reloader docs to list reloader deployments by cluster
  docs/content/reloader/monitoring-secrets-configmaps.md
Labels: approved, size/XS, lgtm

#1856 Add jpweiser to psse-research group
  cluster-scope/base/user.openshift.io/groups/psse-research/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1854 Update api/ingress certs for osc-cl1.
  cluster-scope/overlays/prod/osc/osc-cl1/apiserver/api-certs.enc.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/ingresscontroller/router-certs.enc.yaml
Labels: size/M, approved, lgtm

#1859 Remove oauth base resource from morty cluster.
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: approved, size/XS, lgtm

#1860 Update mapping method for idp authrealm.
  acm/overlays/moc/infra/identitatem/authrealms/primary.yaml
Labels: approved, size/XS, lgtm

#1407 Add role/rolebind for cluster-monitoring prom to see openshift-logging namespace
  cluster-logging/base/kustomization.yaml
  cluster-logging/base/rolebindings/kustomization.yaml
  cluster-logging/base/rolebindings/prometheus-k8s.yaml
  cluster-logging/base/roles/kustomization.yaml
  cluster-logging/base/roles/prometheus-k8s.yaml
Labels: size/M, approved, lifecycle/stale

#1847 feat(onboarding): Add team sostrades
  cluster-scope/base/core/namespaces/sostrades-namespace/kustomization.yaml
  cluster-scope/base/core/namespaces/sostrades-namespace/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/sostrades/group.yaml
  cluster-scope/base/user.openshift.io/groups/sostrades/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sostrades/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/sostrades/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/L, approved, lgtm, ok-to-test

#1862 include admin for osc-cl1
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#1865 Point the osc-cl1 odh-dashboard to byon tag of manifests
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/dashboard/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/dashboard/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/kustomization.yaml
Labels: approved, size/S, lgtm

#1816 Adding burn rate based alerts for JupyterHub in Smaug cluster
  kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml
Labels: size/M, approved, lgtm

#1870 Correct ds-ml-workflows seldon kfdef repo.
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/routes/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/routes/trino-route.yaml
  odh-manifests/smaug-stage/trino/base/hive-config.yaml
  odh-manifests/smaug-stage/trino/base/kustomization.yaml
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
Labels: size/L, lgtm

#1871 Move JH images to base folder.
  kfdefs/base/jupyterhub/notebook-images/audio-decoder-demo.yaml
  kfdefs/base/jupyterhub/notebook-images/bu-cs-jupyterbook.yaml
  kfdefs/base/jupyterhub/notebook-images/categorical-encoding.yaml
  kfdefs/base/jupyterhub/notebook-images/ceph-drive-failure.yaml
  kfdefs/base/jupyterhub/notebook-images/cloud-price-analysis.yaml
  kfdefs/base/jupyterhub/notebook-images/configuration-files-analysis.yaml
  kfdefs/base/jupyterhub/notebook-images/experimental-elyra-notebook-imagestream.yaml
  kfdefs/base/jupyterhub/notebook-images/hitchhikers-guide.yaml
  kfdefs/base/jupyterhub/notebook-images/htm-applications.yaml
  kfdefs/base/jupyterhub/notebook-images/jupyterbook-test.yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/base/jupyterhub/notebook-images/mailing-list-analysis-toolkit.yaml
  kfdefs/base/jupyterhub/notebook-images/ml-prague-workshop.yaml
  kfdefs/base/jupyterhub/notebook-images/ocp-ci-analysis.yaml
  kfdefs/base/jupyterhub/notebook-images/openshift-anomaly-detection.yaml
  kfdefs/base/jupyterhub/notebook-images/operate-first-jupyterhub-analysis.yaml
  kfdefs/base/jupyterhub/notebook-images/pet-image-detection.yaml
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/base/jupyterhub/notebook-images/s2i-pytorch-py38-notebook.yaml
  kfdefs/base/jupyterhub/notebook-images/s2i-spark3.0.1-minimal-notebook.yaml
  kfdefs/base/jupyterhub/notebook-images/summit-2021-octo-keynote.yaml
  kfdefs/base/jupyterhub/notebook-images/time-series.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/kustomization.yaml
Labels: approved, size/XS, lgtm

#1872 fix `opf_instance` label in Jupyterhub alerts and blackbox servicemonitor
  grafana/overlays/moc/smaug/blackbox-exporter/service-monitor.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/alerts.yaml
Labels: approved, size/S, lgtm

#1874 Update crb apiversion to v1.
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-logs-readers/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view-balrog/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/metrics/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-monitoring/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/oauth-token-access-review-opf-observatorium/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/opf-cluster-metrics-federation/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-observatorium/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-anyuid-tufts-dcc-6/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-opf-ci-pipelines-aicoe-ci/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/scc-privileged-tufts-dcc-6/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-auth-proxy-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/metrics/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/oauth-token-access-review/clusterrole.yaml
Labels: approved, size/S, lgtm

#1790 Swap volsync-rs-aggregate-to-admin role with view and edit roles
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-edit/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-edit/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-view/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-view/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-rs-aggregate-to-admin/clusterrole.yaml
  cluster-scope/bundles/volsync/kustomization.yaml
  docs/content/volsync/using-volsync.md
Labels: size/M, approved, lgtm

#1785 Adding apirequestcount cluster read rights to sre group
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/apirequest-count-read-cr/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/apirequest-count-read-cr/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1878 Remove invalid kfdef parameter.
  kfdefs/overlays/osc/osc-cl1/trino-dev/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/trino/kfdef.yaml
  kfdefs/overlays/osc/osc-cl2/trino/kfdef.yaml
Labels: approved, size/XS, lgtm

#1853 manage the kafka for balrog cluster via operate-first
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/balrog/operate-first/opf-kafka.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  kafka/overlays/balrog/kafka-podmonitors.yaml
  kafka/overlays/balrog/kustomization.yaml
  kafka/overlays/balrog/opf-kafdrop.yaml
  kafka/overlays/balrog/topics/kustomization.yaml
  kafka/overlays/balrog/topics/thoth-advise-justification.yaml
  kafka/overlays/balrog/topics/thoth-adviser-trigger.yaml
  kafka/overlays/balrog/topics/thoth-build-analysis-trigger.yaml
  kafka/overlays/balrog/topics/thoth-cve-provided.yaml
  kafka/overlays/balrog/topics/thoth-hash-mismatch.yaml
  kafka/overlays/balrog/topics/thoth-kebechet-run-url.yaml
  kafka/overlays/balrog/topics/thoth-kebechet-trigger.yaml
  kafka/overlays/balrog/topics/thoth-missing-package-version.yaml
  kafka/overlays/balrog/topics/thoth-missing-package.yaml
  kafka/overlays/balrog/topics/thoth-package-extract-trigger.yaml
  kafka/overlays/balrog/topics/thoth-package-released.yaml
  kafka/overlays/balrog/topics/thoth-provenance-checker-trigger.yaml
  kafka/overlays/balrog/topics/thoth-qebhwt-trigger.yaml
  kafka/overlays/balrog/topics/thoth-si-unanalyzed-package.yaml
  kafka/overlays/balrog/topics/thoth-solved-package.yaml
  kafka/overlays/balrog/topics/thoth-unresolved-package.yaml
  kafka/overlays/balrog/topics/thoth-unrevsolved-package.yaml
  kafka/overlays/balrog/topics/thoth-update-provides-source-distro.yaml
  kafka/overlays/balrog/users/kustomization.yaml
  kafka/overlays/balrog/users/thoth.yaml
Labels: size/XL, approved, lgtm

#1875 Update crds to v1.
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/extensions.dashboard.tekton.dev/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/gitbasedconfigs.sdap.apache.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/gitbasedconfigs.sdap.apache.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/kfdefs.kfdef.apps.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/observatoria.core.observatorium.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/observatoria.core.observatorium.io/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/prowjobs.prow.k8s.io/customresourcedefinition.yaml
Labels: approved, size/XXL, lgtm

#1880 Add training operator.
  .pre-commit-config.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/training-operator.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mpijobs.kubeflow.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/mxjobs.kubeflow.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/pytorchjobs.kubeflow.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/tfjobs.kubeflow.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/xgboostjobs.kubeflow.org/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/training-operator/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/training-operator/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/training-operator/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/training-operator/kustomization.yaml
  cluster-scope/bundles/training-operator/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  training-operator/base/deployment.yaml
  training-operator/base/kustomization.yaml
  training-operator/base/service.yaml
  training-operator/base/serviceaccount.yaml
  training-operator/overlays/osc/osc-cl1/kustomization.yaml
Labels: approved, size/XXL, lgtm

#1881 Onboard multienode demo team.
  cluster-scope/base/core/namespaces/multinode-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/multinode-demo/namespace.yaml
  cluster-scope/base/core/namespaces/multinode-demo/resourcequota.yaml
  cluster-scope/base/user.openshift.io/groups/multinode-demo/group.yaml
  cluster-scope/base/user.openshift.io/groups/multinode-demo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/multinode-demo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/multinode-demo/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/M, approved, lgtm

#1884 Update group.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1883 Set query.max-length=10M (overriding 1M default)
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
Labels: approved, size/XS, lgtm, ok-to-test

#1887 Revert "Set query.max-length=10M (overriding 1M default) (#1883)"
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_dev.properties
Labels: size/XS

#1886 Kafka: Add user and topic for od-demo project
  kafka/overlays/smaug/topics/emea-sa-od-demo-images.yaml
  kafka/overlays/smaug/topics/emea-sa-od-demo-objects.yaml
  kafka/overlays/smaug/topics/kustomization.yaml
  kafka/overlays/smaug/users/emea-sa-od-demo.yaml
  kafka/overlays/smaug/users/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1888 Aggregate pytorchjobs creation to project admin osc-cl2.
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/pytorchjobs-create-aggregate-to-admin/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/pytorchjobs-create-aggregate-to-admin/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/S, lgtm

#1879 Added enhanced Cluster Storage Overview Dashboard
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml
Labels: size/XL, approved, lgtm

#1852 Adding argocd alerts in moc-infra
  argocd/overlays/moc-infra/alerts.yaml
Labels: size/M, approved, lgtm

#1889 Disable self provisioning projects in osc clusters.
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/XS, lgtm

#1890 Set query.max-length=10M in correct files
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-coordinator.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/config-worker.properties
Labels: approved, size/XS, lgtm

#1846 Gave 15 namespaces meta-labels
  cluster-scope/base/core/namespaces/debezium-ui/namespace.yaml
  cluster-scope/base/core/namespaces/democratic-csi/namespace.yaml
  cluster-scope/base/core/namespaces/dex/namespace.yaml
  cluster-scope/base/core/namespaces/ds-example-project/namespace.yaml
  cluster-scope/base/core/namespaces/ds-github-labeler/namespace.yaml
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/namespace.yaml
  cluster-scope/base/core/namespaces/elyra-aidevsecops-tutorial/namespace.yaml
  cluster-scope/base/core/namespaces/enterprise-neurosystem-collaboration/namespace.yaml
  cluster-scope/base/core/namespaces/esi-operate-first-project/namespace.yaml
  cluster-scope/base/core/namespaces/fde-audio-decoder-demo/namespace.yaml
  cluster-scope/base/core/namespaces/fedora/namespace.yaml
  cluster-scope/base/core/namespaces/fybrik-applications/namespace.yaml
Labels: size/M, approved, lgtm

#1892 feat(osc-cl1): Fix BYON deployment
  kfdefs/overlays/osc/osc-cl1/dashboard/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
Labels: approved, size/XS, lgtm

#1895 Added display-name to namespaces
  cluster-scope/base/core/namespaces/democratic-csi/namespace.yaml
  cluster-scope/base/core/namespaces/fedora/namespace.yaml
  cluster-scope/base/core/namespaces/fybrik-applications/namespace.yaml
Labels: approved, size/XS, lgtm

#1891 Switch to manual odh deploy on osc clusters.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/odh-operator.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/odh-operator.yaml
  cluster-scope/bundles/opendatahub-operator-manual/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  odh-operator/overlays/osc/osc-cl1/kustomization.yaml
  odh-operator/overlays/osc/osc-cl2/kustomization.yaml
Labels: size/M, do-not-merge/hold, lgtm

#1898 Correct spirequest count crb subject apigroup.
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/apirequest-count-reader/clusterrolebinding.yaml
Labels: approved, size/XS, lgtm

#1900 Increasing resource limitations for the demo
  cluster-scope/base/core/namespaces/multinode-demo/resourcequota.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#1894 added peribolos namespace
  cluster-scope/base/core/namespaces/peribolos-as-a-service/kustomization.yaml
  cluster-scope/base/core/namespaces/peribolos-as-a-service/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/peribolos-as-a-service/group.yaml
  cluster-scope/base/user.openshift.io/groups/peribolos-as-a-service/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/peribolos-as-a-service/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/peribolos-as-a-service/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1903 Add datahub linkedin namespace to osc-cl1.
  cluster-scope/base/core/namespaces/datahub-linkedin/kustomization.yaml
  cluster-scope/base/core/namespaces/datahub-linkedin/namespace.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: approved, size/S, lgtm

#1904 Remove kubeflow kfdef from osc-cl1.
  kfdefs/overlays/osc/osc-cl1/kubeflow/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/kubeflow/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/kustomization.yaml
Labels: size/M, approved, lgtm

#1902 onboarding boston-univeristy-redhat team
  cluster-scope/base/core/namespaces/smart-village-view/kustomization.yaml
  cluster-scope/base/core/namespaces/smart-village-view/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/boston-university-redhat/group.yaml
  cluster-scope/base/user.openshift.io/groups/boston-university-redhat/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/boston-university-redhat/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/boston-university-redhat/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#1909 Add kubeflow admins to osc-cl2.
  cluster-scope/overlays/prod/osc/osc-cl2/groups/kubeflow-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: approved, size/XS, lgtm

#1911 Adding 2 more users to boston-university-redhat group, yqchenn and anlianni
  cluster-scope/base/user.openshift.io/groups/boston-university-redhat/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1914 row/col access controls on sandbox.gppd
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#1915 Adding Greg and Dylan to cluster-admins group in smaug/infra
  cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#1910 Add argocd project for peribolos service
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/peribolos-service.yaml
Labels: approved, size/S, lgtm

#1908 Adding service monitors for Trino and seldon to expose their metrics to prometheus.
  kfdefs/overlays/moc/smaug/seldon/kustomization.yaml
  kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
  kfdefs/overlays/moc/smaug/trino/kustomization.yaml
  kfdefs/overlays/moc/smaug/trino/servicemonitor.yaml
Labels: approved, size/S, lgtm

#1815 Add Keylime registrar and verifier
  cluster-scope/base/core/namespaces/keylime/kustomization.yaml
  cluster-scope/base/core/namespaces/keylime/namespace.yaml
  cluster-scope/base/core/namespaces/opf-ci-pipelines/namespace.yaml
  cluster-scope/base/core/namespaces/opf-ci-prow/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: size/M, approved, lgtm

#1924 Upgrade ODH to v1.2.0
  odh-operator/base/kustomization.yaml
Labels: approved, size/XS, lgtm

#1916 Change LimitRange and Resourcequota for SoSTrades Namespace [OS-CLIMATE]
  cluster-scope/base/core/namespaces/sostrades-namespace/kustomization.yaml
  cluster-scope/base/core/namespaces/sostrades-namespace/limitrange.yaml
  cluster-scope/base/core/namespaces/sostrades-namespace/resourcequota.yaml
Labels: approved, size/S, lgtm, ok-to-test

#1927 add grafana operator to b4mad-racing namespace
  cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/operatorgroup.yaml
  cluster-scope/bundles/b4mad-racing/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1928 Adding github usernames with uppercase letters to OPF groups (excludi…
  cluster-scope/base/user.openshift.io/groups/ai-services/group.yaml
  cluster-scope/base/user.openshift.io/groups/apicurio/group.yaml
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
  cluster-scope/base/user.openshift.io/groups/ccx/group.yaml
  cluster-scope/base/user.openshift.io/groups/data-science/group.yaml
  cluster-scope/base/user.openshift.io/groups/demo-team/group.yaml
  cluster-scope/base/user.openshift.io/groups/esi-project/group.yaml
  cluster-scope/base/user.openshift.io/groups/fde/group.yaml
  cluster-scope/base/user.openshift.io/groups/manageiq/group.yaml
  cluster-scope/base/user.openshift.io/groups/neu-students/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-ushift-dev/group.yaml
  cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
  cluster-scope/base/user.openshift.io/groups/operate-first/group.yaml
  cluster-scope/base/user.openshift.io/groups/osc-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/osc/group.yaml
  cluster-scope/base/user.openshift.io/groups/prometheus-ai/group.yaml
  cluster-scope/base/user.openshift.io/groups/rh-dus/group.yaml
  cluster-scope/base/user.openshift.io/groups/seraph/group.yaml
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
  cluster-scope/base/user.openshift.io/groups/team-pixel/group.yaml
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
  cluster-scope/base/user.openshift.io/groups/tremor-demo/group.yaml
  cluster-scope/base/user.openshift.io/groups/uky-redhat/group.yaml
  cluster-scope/base/user.openshift.io/groups/varangian/group.yaml
  cluster-scope/overlays/prod/emea/balrog/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/demo/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/rick/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
Labels: size/M, lgtm

#1929 [Smaug][Grafana] Add instance label to grafana-serviceaccount smaug
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: size/XS

#1932 Add jaeger operator to smaug.
  cluster-scope/base/core/namespaces/openshift-distributed-tracing/kustomization.yaml
  cluster-scope/base/core/namespaces/openshift-distributed-tracing/namespace.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/jaeger-operator/subscription.yaml
  cluster-scope/bundles/jaeger-operator/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S, lgtm

#1933 Add operatorgroup for jaeger on smaug.
  cluster-scope/base/operators.coreos.com/operatorgroups/jaeger-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/jaeger-operator/operatorgroup.yaml
  cluster-scope/bundles/jaeger-operator/kustomization.yaml
Labels: size/S, lgtm

#1934 Adding user to the octo-otel-dev group
  cluster-scope/base/user.openshift.io/groups/octo-otel-dev/group.yaml
Labels: approved, size/XS, lgtm

#1930 Add docs on how to add superset db. And osc access.
  docs/_toc.yml
  docs/content/odh/superset/add_superset_users.md
  docs/content/odh/superset/add_trino_db.md
Labels: size/M

#1935 Adding Michael Peters to octo group
  cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1939 :recycle: upgrade pulp image pull policy to always
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: approved, size/XS, lgtm

#1940 :city_sunrise: Include project thoth and opf-pulp on the opf workload website
  cluster-scope/base/core/namespaces/opf-ci-pipelines/namespace.yaml
  cluster-scope/base/core/namespaces/opf-ci-prow/namespace.yaml
  cluster-scope/base/core/namespaces/opf-pulp/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-amun-api-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-amun-inspection-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-backend-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-bots-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-deployment-examples/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-frontend-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-graph-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-infra-prod/namespace.yaml
  cluster-scope/base/core/namespaces/thoth-middletier-prod/namespace.yaml
Labels: size/M, approved, lgtm

#1931 Changing balrog cluster auth to be managed by identitatem
  acm/overlays/moc/infra/managedclusters/balrog.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/balrog/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-generator.yaml
  keycloak/overlays/moc/infra/clients/balrog.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L
