Repository operate-first/apps, pull requests merged in 2022-01, with the labels that each got.

#1487 new project and admins
  cluster-scope/base/core/namespaces/training-model/kustomization.yaml
  cluster-scope/base/core/namespaces/training-model/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
  cluster-scope/base/user.openshift.io/groups/octo-training-model/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-training-model/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/octo-training-model/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, lgtm, ok-to-test

#1488 Update OSC ingress & api certs.
  cluster-scope/overlays/prod/osc/osc-cl1/apiserver/api-certs.enc.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/ingresscontroller/router-certs.enc.yaml
Labels: size/M, lgtm

#1470 Onboard Morty Cluster.
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/morty.yaml
  alertreceiver/overlays/emea/morty/kustomization.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-morty.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/alertreceiver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/.sops.yaml
  cluster-scope/overlays/prod/emea/morty/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/oauths/cluster_patch.yaml
  cluster-scope/overlays/prod/emea/morty/oauths/operate-first-sso-secret.enc.yaml
  cluster-scope/overlays/prod/emea/morty/secret-generator.yaml
  docs/content/acm/adding_managed_cluster_to_argocd.md
  keycloak/overlays/moc/infra/clients/morty.enc.yaml
  keycloak/overlays/moc/infra/secret-generator.yaml
Labels: size/L, lgtm

#1495 Match smaug superset db name existing postgres in opf-superset.
  kfdefs/overlays/moc/smaug/opf-superset/secrets/superset.enc.yaml
  kfdefs/overlays/moc/smaug/opf-superset/secrets/supersetdb.enc.yaml
  odh-manifests/smaug/superset/base/secret.yaml
Labels: size/M, approved, lgtm

#1496 Give argocd standard access to osc admins.
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
Labels: approved, size/XS, lgtm, area/service/argocd

#1497 Give curator team permissions to view cluster metrics
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cluster-monitoring-view/clusterrolebinding.yaml
Labels: approved, size/XS, lgtm

#1494 Remove Jh instance from ds-ml-worklows-ws kfdef
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
Labels: approved, size/S, lgtm

#1491 Removed the deprecated dashboard from thoth-station dashboard list
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/kustomization.yaml
Labels: approved, size/S, lgtm

#1498 Send alerts from opf-* namespaces to github
  cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
Labels: approved, size/XS, lgtm

#1500 training model - add additional user to project
  cluster-scope/base/user.openshift.io/groups/octo-training-model/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1492 Remove arrow flight module argoCD application
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/arrow-flight-module.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#1469 Add dnsname to infra api cert.
  cert-manager/overlays/moc/infra/api/api-cert.yaml
Labels: approved, size/XS, lgtm

#1499 Remove unneeded argoproj crds from smaug.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#1503 Add dystewar and Gregory-Pereira to argocd admins list
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Labels: approved, size/XS, lgtm

#1502 Add empty reviewers list in owners. And add new approver.
  OWNERS
Labels: approved, size/XS, lgtm

#1504 Restructure smaug trino to move cfg mgmt to argocd.
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/catalogs/operate_first_general.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/config-coordinator.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/config-worker.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/jmx.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/jvm-coordinator.config
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/jvm-worker.config
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/log.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/node.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/password-authenticator.properties
  kfdefs/overlays/moc/smaug/opf-trino-stage/configs/password.db
  kfdefs/overlays/moc/smaug/opf-trino-stage/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/configs/catalogs/curator_general.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/catalogs/data_science_general.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/catalogs/operate_first_general.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/catalogs/ospo_sandiego.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/config-coordinator.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/config-worker.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/jmx.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/jvm-coordinator.config
  kfdefs/overlays/moc/smaug/opf-trino/configs/jvm-worker.config
  kfdefs/overlays/moc/smaug/opf-trino/configs/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-trino/configs/log.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/node.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/password-authenticator.properties
  kfdefs/overlays/moc/smaug/opf-trino/configs/password.db
  kfdefs/overlays/moc/smaug/opf-trino/kustomization.yaml
  odh-manifests/osc-cl1/trino/base/trino-coordinator-dc.yaml
  odh-manifests/osc-cl1/trino/base/trino-worker-dc.yaml
  odh-manifests/smaug-stage/trino/base/kustomization.yaml
  odh-manifests/smaug-stage/trino/base/trino-catalog-secret.yaml
  odh-manifests/smaug-stage/trino/base/trino-config-secret.yaml
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
  odh-manifests/smaug/trino/base/kustomization.yaml
  odh-manifests/smaug/trino/base/trino-catalog-secret.yaml
  odh-manifests/smaug/trino/base/trino-config-secret.yaml
  odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Labels: size/L, approved, lgtm

#1505 Update curator ssl certificate
  cluster-scope/overlays/prod/moc/curator/ingresscontrollers/default-ingress-certificate.enc.yaml
Labels: approved, size/XS, lgtm

#1508 Include new thoth-station member to thoth group
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Labels: approved, size/XS, lgtm

#1510 Change vault ArgoCD application to point to different repository
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1506 Install & configure openshift data foundation including argocd app
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/local-storage.yaml
  argocd/overlays/moc-infra/applications/envs/emea/morty/cluster-management/odf.yaml
  cluster-scope/base/core/namespaces/openshift-local-storage/kustomization.yaml
  cluster-scope/base/core/namespaces/openshift-local-storage/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/openshift-local-storage/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/odf-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/odf-operator/subscription.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
  cluster-scope/overlays/prod/emea/morty/subscriptions/local-storage-operator_patch.yaml
  cluster-scope/overlays/prod/emea/morty/subscriptions/odf-operator_patch.yaml
  local-storage/overlays/emea/morty/kustomization.yaml
  local-storage/overlays/emea/morty/localvolumediscovery.yaml
  local-storage/overlays/emea/morty/localvolumeset.yaml
  odf/README.md
  odf/base/kustomization.yaml
  odf/overlays/emea/morty/kustomization.yaml
  odf/overlays/emea/morty/ocs-storagecluster-storagesystem.yaml
  odf/overlays/emea/morty/ocs-storagecluster.yaml
Labels: size/L, lgtm

#1507 request more cpu for learning models
  cluster-scope/base/core/namespaces/training-model/kustomization.yaml
  cluster-scope/base/core/namespaces/training-model/resourcequota.yaml
Labels: approved, size/S, lgtm, needs-ok-to-test

#1514 Added to SRE list
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1515 adding cloudbeaver ui route to docs
  docs/content/odh/README.md
Labels: approved, size/XS, lgtm

#1518 Add superset docs on fixing missing user issue.
  docs/content/odh/superset/img/nouser.png
  docs/content/odh/superset/runbook.md
Labels: size/S, lgtm

#1521 fix: switch to quay.io from docker.io
  kfdefs/base/jupyterhub/notebook-images/bu-cs-jupyterbook.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1254 updating the alerting rules with prometheus standard and thoth rules
  cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
Labels: approved, size/XS, lgtm

#1519 Added ababar to cluster admin
  cluster-scope/base/user.openshift.io/groups/curator/group.yaml
  cluster-scope/overlays/prod/moc/curator/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#1525 Add instructions on how to add an ocp group.
  docs/_toc.yml
  docs/content/argocd-gitops/onboarding_to_argocd.md
  docs/content/cluster-scope/create_ocp_group.md
Labels: size/M, lgtm

#1524 updating argocd-gitops readme with how to get read and read/write access
  docs/content/argocd-gitops/get_access_to_argocd.md
Labels: approved, size/XS, lgtm

#1526 Updated the README file
  scripts/setup_pvs/README.md
Labels: approved, size/XS, lgtm

#1528 change image formatting in doc
  docs/content/odh/trino/trino_superset_user_guide.md
Labels: size/M, approved, lgtm

#1530 Updated Grafana Dashboard creation doc to newer file structure
  docs/content/grafana/add_grafana_dashboard.md
Labels: approved, size/S, lgtm

#1535 permissions to add the training model group
  cluster-scope/base/core/namespaces/opf-ci-pipelines/kustomization.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1533 Update apps repo readme.
  README.md
  docs/img/apps_repo.png
Labels: size/M, approved, lgtm

#1527 adding link to explanation of cpu limits or requests in the onboarding doc
  docs/content/cluster-scope/quotas.md
Labels: approved, size/XS, lgtm, ok-to-test

#1538 Update docs on requesting access to moc/smaug loki instance
  docs/content/observatorium/loki/README.md
  docs/content/observatorium/loki/request_loki_access.md
  docs/content/observatorium/thanos/request_grafana_access.md
Labels: size/L, approved, lgtm

#1537 Adding suppathak as SRE group member
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1541 Add opf jh analysis notebook image yaml
  kfdefs/base/jupyterhub/notebook-images/kustomization.yaml
  kfdefs/base/jupyterhub/notebook-images/operate-first-jupyterhub-analysis.yaml
Labels: approved, size/S, lgtm

#1543 fix: Remove null value from deployment of reloader securityContext
  reloader/base/deployment.yaml
Labels: approved, size/XS, lgtm

#1544 added to sre group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1545 Changed default time range of the Cluster CPU dashboard
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
Labels: approved, size/XS, lgtm

#1523 add reloader annotations to trino deployments
  odh-manifests/smaug-stage/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug-stage/trino/base/trino-worker-dc.yaml
  odh-manifests/smaug/trino/base/trino-coordinator-dc.yaml
  odh-manifests/smaug/trino/base/trino-worker-dc.yaml
Labels: size/S, lgtm

#1548 Grant thoth-devops access to tekton-chains
  cluster-scope/base/core/namespaces/tekton-chains/kustomization.yaml
Labels: approved, size/XS, lgtm

#1550 increase smaug openshift-monitoring prom pvc size from 100Gi to 200Gi
  cluster-scope/overlays/prod/moc/smaug/configmaps/cluster-monitoring-config.enc.yaml
Labels: approved, size/XS, lgtm

#1555 Add scripts/fake-ksops.sh to ease testing w/o ksops
  scripts/fake-ksops.sh
Labels: approved, size/S, lgtm

#1556 add DSL management for trino rules.json files
  .pre-commit-config.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/trino-acl-dsl.yaml
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml
Labels: size/XL, approved, lgtm

#1563 feat: Add temporary a devconf.cz 2022 namespace
  cluster-scope/base/core/namespaces/devconfcz-2022-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/devconfcz-2022-demo/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1564 Revert "feat: Add temporary a devconf.cz 2022 namespace"
  cluster-scope/base/core/namespaces/devconfcz-2022-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/devconfcz-2022-demo/namespace.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1565 fix secret generator in moc/smaug kustomization
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#1567 pvc request added for prometheus-ai group
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/benlugasi.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/guyelf.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/kustomization.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/moradnir.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/ofir-shechtman.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1568 adding greg and dylan as reviewers
  OWNERS
Labels: approved, size/XS, lgtm

#1552 adding resource bundling for acme and reloader
  cluster-scope/bundles/acme-operator/kustomization.yaml
  cluster-scope/bundles/curator/kustomization.yaml
  cluster-scope/bundles/fybrik/kustomization.yaml
  cluster-scope/bundles/meteor-operator/kustomization.yaml
  cluster-scope/bundles/reloader/kustomization.yaml
  cluster-scope/bundles/seraph/kustomization.yaml
  cluster-scope/bundles/tekton-chains/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm
