Repository operate-first/apps, pull requests merged in 2022-02, with the labels that each got.

#1572 feat(onboarding): Add team psse-research
  cluster-scope/base/core/namespaces/rapidast/kustomization.yaml
  cluster-scope/base/core/namespaces/rapidast/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/psse-research/group.yaml
  cluster-scope/base/user.openshift.io/groups/psse-research/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/psse-research/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/psse-research/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, needs-ok-to-test

#1554 Add Tekton-backed Kubeflow Pipelines
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kfp-tekton.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/scheduledworkflows.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/scheduledworkflows.kubeflow.org/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/viewers.kubeflow.org/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/viewers.kubeflow.org/kustomization.yaml
  cluster-scope/bundles/kfp-tekton/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfp-tekton/README.md
  kfp-tekton/base/kfp-tekton.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/overlays/moc/smaug/kustomization.yaml
  kfp-tekton/overlays/moc/smaug/secret-generator.yaml
  kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-ceph-artifact.enc.yaml
Labels: approved, do-not-merge/hold, size/XXL, lgtm

#1575 Change kfp tekton ns to kubeflow.
  kfp-tekton/overlays/moc/smaug/kustomization.yaml
Labels: size/XS, lgtm

#1573 Enable custom tasks and switch api to alpha for ocp pipelines in smaug.
  cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/configmap.yaml
  cluster-scope/base/core/configmaps/openshift-pipelines-feature-flags/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/S, lgtm

#1574 Correct smaug jh user pvc with actual pvc on live.
  kfdefs/overlays/moc/smaug/opf-jupyterhub/pvcs/ofir-shechtman.yaml
Labels: approved, size/XS, lgtm

#1216 feat: Autoscale balrog
  cluster-scope/base/autoscaling.openshift.io/clusterautoscalers/default/clusterautoscaler.yaml
  cluster-scope/base/autoscaling.openshift.io/clusterautoscalers/default/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/clusterautoscaler.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/machineautoscalers.yaml
Labels: size/M, approved, lgtm

#1581 Create klusterletaddonconfigs-editor RBAC and group
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/klusterletaddonconfig-editor/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/klusterletaddonconfig-editor/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/klusterletaddonconfig-editor/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/klusterletaddonconfig-editor/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/group.yaml
  cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/kustomization.yaml
  cluster-scope/bundles/klusterletaddonconfig-editor/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: size/M, approved, lgtm

#1579 Fix typo 'Jupypter'
  docs/content/cluster-scope/onboarding_to_cluster.md
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1582 Add octo/osc cluster's clustersetbinding to argocd.
  acm/overlays/moc/infra/managedclustersetbindings/kustomization.yaml
Labels: approved, size/XS, lgtm

#1570 Adding the documentation for resource bundling
  cluster-scope/README.md
Labels: approved, size/XS, lgtm

#1578 bundling resources in emea, infra and smaug clusters
  cluster-scope/bundles/nfd/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/rick/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1583 added carlosGimeno to the sre group
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm

#1584 Correct artifact object storage config for kfp-tekton on smaug.
  kfp-tekton/base/kfp-tekton.yaml
  kfp-tekton/overlays/moc/smaug/secrets/mlpipeline-ceph-artifact.enc.yaml
Labels: size/M

#1520 Argocd notifications slack integration
  argocd-notifications/base/configmap.yaml
  argocd-notifications/base/kustomization.yaml
  argocd-notifications/overlays/infra/kustomization.yaml
  argocd-notifications/overlays/infra/secret-generator.yaml
  argocd-notifications/overlays/infra/secret.enc.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/cluster-resources.yaml
  docs/_toc.yml
  docs/content/argocd-gitops/argocd_notifications.md
Labels: size/L, approved, lgtm

#1587 Update Grafana CRDs to v1 on smaug.
  grafana/base/datasource.yaml
  grafana/base/grafana.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-pod-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/namespace_cpu_and_memory_overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/node-feature-discovery.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/vpa-rc-cpu-and-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/kubeflow/kfp-tekton-user.yaml
  grafana/overlays/moc/smaug/dashboards/odh/jupyterhub-user.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/cluster-logs-quick-search.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/opf-availability.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/pad-demo.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/overview.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/remote-write.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-compact.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-overview.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-query.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-receive.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-rule.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-store.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/datasources/cluster-logs.yaml
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: size/L, lgtm

#1588 Revert "Merge pull request #1587 from HumairAK/update_defs"
  grafana/base/datasource.yaml
  grafana/base/grafana.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-cpu-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-pod-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/cluster-storage-overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/namespace_cpu_and_memory_overview.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/node-feature-discovery.yaml
  grafana/overlays/moc/smaug/dashboards/cluster-management/vpa-rc-cpu-and-memory-overview.yaml
  grafana/overlays/moc/smaug/dashboards/kubeflow/kfp-tekton-user.yaml
  grafana/overlays/moc/smaug/dashboards/odh/jupyterhub-user.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/argocd.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/cluster-logs-quick-search.yaml
  grafana/overlays/moc/smaug/dashboards/operate-first/opf-availability.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus-anomaly-detector/pad-demo.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/overview.yaml
  grafana/overlays/moc/smaug/dashboards/prometheus/remote-write.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-compact.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-overview.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-query.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-receive.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-rule.yaml
  grafana/overlays/moc/smaug/dashboards/thanos/thanos-store.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/moc/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/kustomization.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-kafka-argo-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-knowledge-graph-content-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-postgresql-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-service-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-sli-slo.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-user-api-metrics.yaml
  grafana/overlays/moc/smaug/dashboards/thoth-station/prod/thoth-workflow-controllers-metrics.yaml
  grafana/overlays/moc/smaug/datasources/cluster-logs.yaml
  grafana/overlays/moc/smaug/datasources/grafanadatasource.enc.yaml
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: size/L, approved, lgtm

#1593 removing capitals from thoth group
  cluster-scope/base/user.openshift.io/groups/thoth/group.yaml
Labels: approved, size/XS, lgtm

#1597 Previous commit used the wrong issue for the api certificate
  cert-manager/overlays/moc/common/api-issuer/openshift-api-issuer.yaml
  cert-manager/overlays/moc/common/ingress-issuer/openshift-ingress-issuer.yaml
  cert-manager/overlays/moc/smaug/api/kustomization.yaml
Labels: approved, size/S, lgtm

#1594 Switch strimzi management to argocd on smaug.
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  kfdefs/base/kafka/kfdef.yaml
Labels: approved, size/XS, lgtm

#1592 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikmodules.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: size/XL, approved, lgtm, needs-ok-to-test

#1599 Provision klusteraddonconfig access to osc admin.
  cluster-scope/base/user.openshift.io/groups/klusterletaddonconfig-editors/group.yaml
Labels: size/XS, lgtm

#1600 Add osc-cl2 to osc clusterset.
  acm/overlays/moc/infra/managedclusters/kustomization.yaml
  acm/overlays/moc/infra/managedclusters/osc-cl2.yaml
Labels: size/XS, lgtm

#1601 Initialize osc-cl2 clusterscope overlay structure.
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-osc-cl2.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/OWNERS
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/apiserver/api-certs.enc.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/apiserver/apiserver.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/apiserver/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/apiserver/secret-generator.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/configmaps/cluster-monitoring-config.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/configmaps/user-workload-monitoring-config.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-users.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/seldon-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/ingresscontroller/ingresscontroller.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/ingresscontroller/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/ingresscontroller/router-certs.enc.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/ingresscontroller/secret-generator.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/L

#1585 feat(onboarding): Add team team-pixel
  cluster-scope/base/core/namespaces/pixel-secrets/kustomization.yaml
  cluster-scope/base/core/namespaces/pixel-secrets/namespace.yaml
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#1607 Install volsync via helm chart
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/volsync/application.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/volsync/kustomization.yaml
Labels: size/S, lgtm

#1609 Installing volsync using kustomize
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/volsync.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/volsync/application.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationdestinations.volsync.backube/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationdestinations.volsync.backube/kustomization.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationsources.volsync.backube/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationsources.volsync.backube/kustomization.yaml
  cluster-scope/base/core/namespaces/volsync-system/kustomization.yaml
  cluster-scope/base/core/namespaces/volsync-system/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-manager/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-manager/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-proxy/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-proxy/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-manager/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-manager/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-metrics-reader/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-metrics-reader/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-proxy/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-proxy/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/volsync-mover/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/volsync-mover/securitycontextconstraints.yaml
  cluster-scope/bundles/volsync/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  volsync/base/apps/deployments/volsync/deployment.yaml
  volsync/base/core/serviceaccounts/volsync/serviceaccount.yaml
  volsync/base/core/services/volsync-metrics/service.yaml
  volsync/base/kustomization.yaml
  volsync/base/rbac.authorization.k8s.io/rolebindings/volsync-leader-election/rolebinding.yaml
  volsync/base/rbac.authorization.k8s.io/roles/volsync-leader-election/role.yaml
  volsync/overlays/smaug/kustomization.yaml
  volsync/src/.gitignore
  volsync/src/Makefile
  volsync/src/kustomization.yaml
Labels: approved, size/XXL, lgtm

#1612 Fix volsync smaug overlay path
  volsync/overlays/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm

#1604 Add parameter to argocd vault application.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/fybrik/vault.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#1603 Onboard project doc update to clarify instructions for newcomers
  docs/content/cluster-scope/onboarding_to_cluster.md
  docs/content/notebooks/onboarding_project.ipynb
Labels: approved, size/XS, needs-ok-to-test

#1616 Increase Opf Kafka PVC size from 40Gi to 60Gi
  kafka/base/opf-kafka.yaml
Labels: approved, size/XS, lgtm

#1576 Adding Reloader docs to apps/docs/content
  docs/_toc.yml
  docs/content/reloader/README.md
  docs/content/reloader/monitoring-secrets-configmaps.md
Labels: size/M, approved, lgtm

#1610 Refactor kfp-tekton
  kfp-tekton/base/configmaps/kfp-tekton-config.yaml
  kfp-tekton/base/configmaps/ml-pipeline-ui-configmap.yaml
  kfp-tekton/base/configmaps/pipeline-install-config.yaml
  kfp-tekton/base/deployments/metadata-envoy-deployment.yaml
  kfp-tekton/base/deployments/metadata-grpc-deployment.yaml
  kfp-tekton/base/deployments/metadata-writer.yaml
  kfp-tekton/base/deployments/ml-pipeline-persistenceagent.yaml
  kfp-tekton/base/deployments/ml-pipeline-scheduledworkflow.yaml
  kfp-tekton/base/deployments/ml-pipeline-ui.yaml
  kfp-tekton/base/deployments/ml-pipeline-viewer-crd.yaml
  kfp-tekton/base/deployments/ml-pipeline-visualizationserver.yaml
  kfp-tekton/base/deployments/ml-pipeline.yaml
  kfp-tekton/base/deployments/mysql.yaml
  kfp-tekton/base/kfp-tekton.yaml
  kfp-tekton/base/kustomization.yaml
  kfp-tekton/base/persistentvolumeclaims/mysql-pv-claim.yaml
  kfp-tekton/base/rolebindings/kubeflow-pipelines-metadata-writer-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-persistenceagent-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-scheduledworkflow-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-ui.yaml
  kfp-tekton/base/rolebindings/ml-pipeline-viewer-crd-binding.yaml
  kfp-tekton/base/rolebindings/ml-pipeline.yaml
  kfp-tekton/base/rolebindings/pipeline-runner-binding.yaml
  kfp-tekton/base/roles/kubeflow-pipelines-metadata-writer-role.yaml
  kfp-tekton/base/roles/ml-pipeline-persistenceagent-role.yaml
  kfp-tekton/base/roles/ml-pipeline-scheduledworkflow-role.yaml
  kfp-tekton/base/roles/ml-pipeline-ui.yaml
  kfp-tekton/base/roles/ml-pipeline-viewer-controller-role.yaml
  kfp-tekton/base/roles/ml-pipeline.yaml
  kfp-tekton/base/roles/pipeline-runner.yaml
  kfp-tekton/base/routes/ml-pipeline-ui.yaml
  kfp-tekton/base/secrets/mlpipeline-ceph-artifact.yaml
  kfp-tekton/base/secrets/mysql-secret.yaml
  kfp-tekton/base/serviceaccounts/kubeflow-pipelines-container-builder.yaml
  kfp-tekton/base/serviceaccounts/kubeflow-pipelines-metadata-writer.yaml
  kfp-tekton/base/serviceaccounts/kubeflow-pipelines-viewer.yaml
  kfp-tekton/base/serviceaccounts/metadata-grpc-server.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline-persistenceagent.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline-scheduledworkflow.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline-ui.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline-viewer-crd-service-account.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline-visualizationserver.yaml
  kfp-tekton/base/serviceaccounts/ml-pipeline.yaml
  kfp-tekton/base/serviceaccounts/mysql.yaml
  kfp-tekton/base/serviceaccounts/pipeline-runner.yaml
  kfp-tekton/base/services/metadata-envoy-service.yaml
  kfp-tekton/base/services/metadata-grpc-service.yaml
  kfp-tekton/base/services/ml-pipeline-ui.yaml
  kfp-tekton/base/services/ml-pipeline-visualizationserver.yaml
  kfp-tekton/base/services/ml-pipeline.yaml
  kfp-tekton/base/services/mysql.yaml
Labels: approved, size/XXL, lgtm

#1619 Move superset configs to argocd management for osc.
  dex/overlays/osc/osc-cl2/dex-cm.yaml
  kfdefs/overlays/osc/osc-cl1/superset/configmaps/custom_sso_security_manager.py
  kfdefs/overlays/osc/osc-cl1/superset/configmaps/kustomization.yaml
  kfdefs/overlays/osc/osc-cl1/superset/configmaps/superset_config.py
  kfdefs/overlays/osc/osc-cl1/superset/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/superset/configmaps/custom_sso_security_manager.py
  kfdefs/overlays/osc/osc-cl2/superset/configmaps/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/superset/configmaps/superset_config.py
  kfdefs/overlays/osc/osc-cl2/superset/kustomization.yaml
  odh-manifests/osc/superset/base/deployment.yaml
  odh-manifests/osc/superset/base/kustomization.yaml
  odh-manifests/osc/superset/base/secret.yaml
Labels: size/L, lgtm

#1621 Correct osc superset kustomization to 1.1.0 version.
  odh-manifests/osc/superset/base/kustomization.yaml
Labels: size/L

#1622 Add osc superset db parameters.
  kfdefs/overlays/osc/osc-cl1/superset/configmaps/superset_config.py
  kfdefs/overlays/osc/osc-cl2/superset/configmaps/superset_config.py
  odh-manifests/osc/superset/base/deployment.yaml
Labels: size/M

#1589 adding argocd-notifications argocd application manifests
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/argocd-notifications.yaml
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/kustomization.yaml
Labels: size/S, lgtm

#1624 Update server to name for argocd notification app.
  argocd/overlays/moc-infra/applications/envs/moc/infra/cluster-management/argocd-notifications.yaml
Labels: size/XS

#1625 Fix argocd url format for argocd notif config.
  argocd-notifications/base/configmap.yaml
  argocd-notifications/overlays/infra/kustomization.yaml
Labels: size/XS

#1618 Add manifests to manage OCS odh-cl2 cluster infrastructure parameters
  cluster-scope/base/core/namespaces/nvidia-gpu-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/nvidia-gpu-operator/namespace.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-compute-notebook.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-g.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/machinesets/machineset-notebook-gpu-p.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/nodefeaturediscovery/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/nodefeaturediscovery/nfd-instance.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/nvidia-gpu/gpu-cluster-policy.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/nvidia-gpu/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/oauths/cluster-patch.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/operatorgroups/nvidia-gpu-operator/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/operatorgroups/nvidia-gpu-operator/operatorgroup.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/patches/nfd-sub-patch.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/subscriptions/nvidia-gpu-operator/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/operators.coreos.com/subscriptions/nvidia-gpu-operator/subscription.yaml
Labels: size/L, approved, do-not-merge/hold, lgtm

#1627 Correct osc cl2 trino dev bucket name.
  kfdefs/overlays/osc/osc-cl2/trino/secrets/s3buckets.yaml
Labels: size/XS

#1611 Remove starting csv from odhseldon subscription in odh.
  kfdefs/overlays/moc/smaug/ds-ml-workflows-ws/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-seldon/kustomization.yaml
  odh-manifests/osc-cl1/odhseldon/cluster/base/kustomization.yaml
  odh-manifests/osc-cl1/odhseldon/cluster/base/subscription.yaml
  odh-manifests/smaug/odhseldon/cluster/base/kustomization.yaml
  odh-manifests/smaug/odhseldon/cluster/base/subscription.yaml
Labels: size/M, approved, lgtm

#1630 Move odh seldon manifests for osc to new location.
  odh-manifests/osc/odhseldon/cluster/base/kustomization.yaml
  odh-manifests/osc/odhseldon/cluster/base/subscription.yaml
Labels: approved, size/XS, lgtm

#1623 Creating Openshift group and adding a user to the group
  cluster-scope/base/user.openshift.io/groups/opf-alerting/group.yaml
  cluster-scope/base/user.openshift.io/groups/opf-alerting/kustomization.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
Labels: approved, size/S, lgtm

#1606 Make sparkoperator in jh ocp 4.9 compatible.
  kfdefs/base/jupyterhub/kfdef.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/crds.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/deployment.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/kustomization.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/role.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/rolebinding.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/serviceaccount.yaml
Labels: size/L

#1632 Remove manual spark deployment for jh prod in smaug.
  kfdefs/base/jupyterhub/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub-stage/kustomization.yaml
Labels: approved, size/S, lgtm

#1634 Giving Grafana Admin permissions to opf-alerting group
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#1631 Add two OBCs for Observatorium storage move to ceph
  observatorium/overlays/moc/smaug/loki/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/obcs/kustomization.yaml
  observatorium/overlays/moc/smaug/loki/obcs/opf-observatorium-logs.yaml
  observatorium/overlays/moc/smaug/thanos/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/obcs/kustomization.yaml
  observatorium/overlays/moc/smaug/thanos/obcs/opf-observatorium-metrics.yaml
Labels: approved, size/S, lgtm

#1633 Add my username to Thoth groups
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
Labels: approved, size/XS, do-not-merge/hold, lgtm, needs-ok-to-test

#1635 apply v0.2.5 of osc-trino-acl-dsl
  .pre-commit-config.yaml
  kfdefs/overlays/osc/osc-cl1/trino-dev/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
Labels: size/M, approved, lgtm

#1638 Adding approvers as outcome of DevSecOps WG meeting Feb 15th
  OWNERS
Labels: approved, size/XS, lgtm

#1641 add mersin35 to corp-data and itr groups
  kfdefs/overlays/osc/osc-cl1/trino/configs/group-mapping.properties
Labels: approved, size/XS, lgtm

#1640 Allow smaug to install operatorhub.io operators
  cluster-scope/base/operators.coreos.com/catalogsources/operatorhubio-catalog/catalogsource.yaml
  cluster-scope/base/operators.coreos.com/catalogsources/operatorhubio-catalog/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1643 Fix setup for NFS pvs on local node using ansible
  scripts/setup_pvs/README.md
  scripts/setup_pvs/playbook.yaml
  scripts/setup_pvs/requirements.yaml
Labels: size/M, approved, lgtm

#1645 Giving Admin Privileges to the opf-alerting group
  cluster-scope/base/core/namespaces/opf-jupyterhub-stage/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/opf-alerting/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/opf-alerting/rbac.yaml
Labels: approved, size/S, lgtm

#1644 Add subscription to snapscheduler operator
  cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#1650 Corrected namespace for snapscheduler
  cluster-scope/base/operators.coreos.com/subscriptions/snapscheduler/kustomization.yaml
Labels: approved, size/XS, lgtm

#1642 add workstream groups to iceberg catalog
  kfdefs/overlays/osc/osc-cl1/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl1/trino/configs/trino-acl-dsl.yaml
Labels: size/L, approved, lgtm

#1653 Remove spark operator from smaug.
  kfdefs/base/jupyterhub/kfdef.yaml
  kfdefs/overlays/moc/smaug/opf-jupyterhub-stage/kustomization.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/crds.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/deployment.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/kustomization.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/role.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/rolebinding.yaml
  odh-manifests/smaug/radanalyticsio/spark/cluster/base/serviceaccount.yaml
Labels: size/L, approved, lgtm

#1647 Updating Smaug clusterversion.yaml to upgrade to OCP 4.9
  cluster-scope/overlays/prod/moc/smaug/clusterversion.yaml
Labels: size/XS, lgtm

#1658 Switch odh deployment to use olm for osc-cl2.
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/cluster-management/odh-operator.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/opendatahub-operator/subscription.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
  odh-operator/overlays/osc/osc-cl2/kustomization.yaml
Labels: size/M, approved, lgtm

#1659 Remove manual kfdef resource mgmt from odh-cl2.
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/XS

#1656 :fire: Update num of volume in pvPool for noobaa storage
  cluster-scope/overlays/prod/moc/smaug/backingstores/noobaa-default-backing-store_patch.yaml
Labels: approved, size/XS, lgtm

#1660 setup a thoth namespace in morty cluster
  cluster-scope/overlays/prod/emea/morty/kustomization.yaml
Labels: approved, size/XS, lgtm

#1636 add docs for volsync to gitops jupyterbook
  docs/_toc.yml
  docs/content/volsync/README.md
  docs/content/volsync/using-volsync.md
Labels: approved, size/S, lgtm

#1664 :guardsman: Include harshad16 as cluster admin for infra, smaug, osc
  cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#1667 moving to lowercase
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
Labels: approved, size/XS, lgtm

#1651 Add snapshotschedule to take daily snapshots of noobaa db
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/snapshotschedules/schedule.yaml
Labels: approved, size/S, lgtm

#1668 updating Margaret's permissions
  cluster-scope/base/user.openshift.io/groups/argocd-readonly/group.yaml
Labels: approved, size/XS, lgtm

#1669 updating access to argocd docs
  docs/content/argocd-gitops/get_access_to_argocd.md
Labels: approved, size/XS, lgtm

#1560 Cosigned: Webhook to ensure defined namespaces use signed images
  cluster-scope/base/core/namespaces/cosigned/kustomization.yaml
  cluster-scope/base/core/namespaces/cosigned/namespace.yaml
  cluster-scope/base/cosigned/kustomization.yaml
  cluster-scope/base/cosigned/mutatingwebhook.yaml
  cluster-scope/base/cosigned/validatingwebhook.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cosigned/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/cosigned/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/cosigned/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/cosigned/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cosigned/base/configmap.yaml
  cosigned/base/deployment.yaml
  cosigned/base/kustomization.yaml
  cosigned/base/publicsecret.yaml
  cosigned/base/role.yaml
  cosigned/base/rolebinding.yaml
  cosigned/base/secret.yaml
  cosigned/base/service.yaml
  cosigned/base/serviceaccount.yaml
Labels: size/L, approved, lgtm, ok-to-test

#1666 onboarding boatroackers
  cluster-scope/base/core/namespaces/boatrockers/kustomization.yaml
  cluster-scope/base/core/namespaces/boatrockers/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/boatroackers/group.yaml
  cluster-scope/base/user.openshift.io/groups/boatroackers/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/boatroackers/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/boatroackers/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm
