Repository operate-first/apps, pull requests merged in 2022-06, with the labels that each got.

#2023 Onboarding chrisproject
  cluster-scope/base/core/namespaces/chrisproject-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/chrisproject-dev/namespace.yaml
  cluster-scope/base/core/namespaces/chrisproject-staging/kustomization.yaml
  cluster-scope/base/core/namespaces/chrisproject-staging/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/chris-project/group.yaml
  cluster-scope/base/user.openshift.io/groups/chris-project/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/chris-project/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/chris-project/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2027 Enable automatic self-healing and pruning
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apicurio/api-designer.yaml
Labels: size/XS

#2026 Added chris project to argocd apps
  argocd/overlays/moc-infra/applications/envs/moc/smaug/chris/chris.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/chris/kustomization.yaml
  argocd/overlays/moc-infra/projects/chris.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  cluster-scope/base/core/namespaces/chrisproject-dev/kustomization.yaml
Labels: size/M, ok-to-test

#2028 Chris
  argocd/overlays/moc-infra/configs/argo_cm/dex.config
  argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv
Labels: size/XS, ok-to-test

#2029 Added new GH users
  argocd/overlays/moc-infra/applications/envs/moc/smaug/chris/kustomization.yaml
  argocd/overlays/moc-infra/projects/chris.yaml
  cluster-scope/base/user.openshift.io/groups/chris-project/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2037 Update the ray worker and notebook to v0.2.0 version
  kfdefs/base/jupyterhub/notebook-images/ray-ml-notebook.yaml
  kfdefs/overlays/moc/smaug/jupyterhub/ray-odh-integration/ray-ml-profile-cm.yaml
Labels: approved, size/XS, lgtm

#2010 Add resources needed to deploy rapidast-operator to smaug cluster
  cluster-scope/base/operators.coreos.com/catalogsources/rapidast/catalogsource.yaml
  cluster-scope/base/operators.coreos.com/catalogsources/rapidast/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/rapidast/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/rapidast/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rapidast/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/rapidast/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, ok-to-test

#2031 chore(cosigned.sigstore.dev): Housekeeping
  cluster-scope/base/admissionregistration.k8s.io/mutatingwebhookconfigurations/cosigned.sigstore.dev/kustomization.yaml
  cluster-scope/base/admissionregistration.k8s.io/mutatingwebhookconfigurations/cosigned.sigstore.dev/mutatingwebhookconfiguration.yaml
  cluster-scope/base/admissionregistration.k8s.io/validatingwebhookconfigurations/cosigned.sigstore.dev/kustomization.yaml
  cluster-scope/base/admissionregistration.k8s.io/validatingwebhookconfigurations/cosigned.sigstore.dev/validatingwebhookconfiguration.yaml
  cluster-scope/overlays/prod/octo/kustomization.yaml
Labels: size/S, lgtm

#2033 Update group.yaml
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2011 Added avrajath to cluster admin for curator cluster
  cluster-scope/base/user.openshift.io/groups/curator/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2040 Add Teja to SRE
  cluster-scope/base/user.openshift.io/groups/sre/group.yaml
Labels: size/XS

#2044 Include another member to thoth devsecops team
  cluster-scope/base/user.openshift.io/groups/thoth-devops/group.yaml
Labels: approved, size/XS, lgtm

#2045 feat(onboarding): Add team eldritch-team13
  cluster-scope/base/core/namespaces/ddas-proj/kustomization.yaml
  cluster-scope/base/core/namespaces/ddas-proj/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/eldritch-team13/group.yaml
  cluster-scope/base/user.openshift.io/groups/eldritch-team13/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/eldritch-team13/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/eldritch-team13/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm, ok-to-test

#2046 Clarify onboading notebook push instructions.
  docs/content/notebooks/onboarding_project.ipynb
Labels: approved, size/S, lgtm

#2047 Added EldritchJS and wjscheirer to group.yaml
  cluster-scope/base/user.openshift.io/groups/eldritch-team13/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2049 Remove quota from vault namespace
  cluster-scope/base/core/namespaces/vault/kustomization.yaml
  cluster-scope/base/core/namespaces/vault/resourcequota.yaml
Labels: size/S

#2055 Disable csrf for smaug superset.
  kfdefs/overlays/moc/smaug/superset/configmaps/superset_config.py
Labels: approved, size/XS, lgtm

#1978 Remove stale dev overlay in cluster-scope.
  cluster-scope/overlays/dev/group-user_patch.yaml
  cluster-scope/overlays/dev/kustomization.yaml
Labels: size/M

#2056 onboarding demolab
  cluster-scope/base/core/namespaces/demolab-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/demolab-dev/namespace.yaml
  cluster-scope/base/core/namespaces/demolab-staging/kustomization.yaml
  cluster-scope/base/core/namespaces/demolab-staging/namespace.yaml
  cluster-scope/base/core/namespaces/demolab/kustomization.yaml
  cluster-scope/base/core/namespaces/demolab/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/demolab_team/group.yaml
  cluster-scope/base/user.openshift.io/groups/demolab_team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/demolab_team/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/demolab_team/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, lgtm

#2062 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: size/XL, approved, lgtm

#2065 fixing grafana_oauth spec labels
  grafana/overlays/moc/smaug/grafana-oauth.yaml
Labels: approved, size/XS, lgtm

#2063 Add secret stores balrog cluster
  cluster-scope/overlays/prod/emea/balrog/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/acme-operator/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/opf-vault-store.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/base/vault-secret-fetcher.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-config/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-ingress/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-logging/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-monitoring/kustomization.yaml
  cluster-scope/overlays/prod/emea/balrog/secret-mgmt/openshift-user-workload-monitoring/kustomization.yaml
  docs/content/vault_eso/add_external_secrets_to_ns.md
Labels: size/L, approved, lgtm

#2067 Set temp obc for image-registry smaug from morty cluster
  cluster-scope/overlays/prod/moc/smaug/.sops.yaml
  cluster-scope/overlays/prod/moc/smaug/imageregistry.operator.openshift.io/configs/cluster/config_patch.yaml
  cluster-scope/overlays/prod/moc/smaug/secrets/image-registry-private-configuration-user.enc.yaml
Labels: size/L, approved, lgtm

#2069 Add curator-operator-report-crd to Smaug Cluster
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/reports.curator.operatefirst.io/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#2071 feat: Make peribolos visible to public in OCP
  cluster-scope/base/core/namespaces/peribolos-as-a-service/kustomization.yaml
Labels: approved, size/XS

#2058 feat(service-catalog): Create ArgoCD app
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/service-catalog.yaml
  argocd/overlays/moc-infra/projects/operate-first.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/service-catalog/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/service-catalog/operator-group.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/service-catalog/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/service-catalog/subscription.yaml
  cluster-scope/bundles/service-catalog/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2078 curator operator cluster level roles and role bindings
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-manager-rb/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-manager-rb/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-oauth-proxy-rb/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/curator-operator-oauth-proxy-rb/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-fetchdata-editor-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-fetchdata-editor-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-fetchdata-viewer-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-fetchdata-viewer-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-manager-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-manager-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-metrics-reader/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-metrics-reader/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-editor-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-editor-role/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-viewer-role/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/curator-operator-report-viewer-role/kustomization.yaml
  cluster-scope/bundles/curator/kustomization.yaml
Labels: size/L, approved, lgtm

#2080 fix(service-catalog): Increase resource quota
  cluster-scope/base/core/namespaces/service-catalog/kustomization.yaml
Labels: approved, size/XS, lgtm

#2082 increased jh limit and updated runbook
  cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
  docs/content/odh/jupyterhub/runbook.md
Labels: approved, size/S, lgtm

#2083 increase curator-operator-system namespace resource quota
  cluster-scope/base/core/namespaces/curator-operator/kustomization.yaml
Labels: approved, size/XS, lgtm, cluster/smaug

#2075 Disable argocd prune on osc api certs.
  cluster-scope/overlays/prod/osc/osc-cl1/externalsecrets/api-certs.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/externalsecrets/api-certs.yaml
Labels: size/XS

#2079 Set temp obc for observatorium components from morty
  observatorium/overlays/moc/smaug/loki/secrets/loki-objectstorage-secret.enc.yaml
  observatorium/overlays/moc/smaug/thanos/secrets/thanos-objectstorage-secret.enc.yaml
Labels: size/L, approved, lgtm

#2081 Update Fybrik manifests to new release
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/assets.katalog.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/blueprints.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikapplications.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/fybrikstorageaccounts.app.fybrik.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/plotters.app.fybrik.io/customresourcedefinition.yaml
Labels: size/XL, approved, lgtm

#2084 Add docs on resolving superset perm issue.
  docs/content/odh/superset/runbook.md
Labels: size/S

#2050 Remove argocd manifests for rick cluster
  argocd/overlays/moc-infra/applications/app-of-apps/app-of-apps-rick.yaml
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/alertreceiver.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/cert-manager.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/cluster-resources.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/external-secrets.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kubevirt-hyperconverged.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/local-storage.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/cluster-management/nfd.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/operate-first/acme-operator.yaml
  argocd/overlays/moc-infra/applications/envs/emea/rick/operate-first/kustomization.yaml
Labels: size/L, approved, lgtm

#2086 Add inception namespace to osc-cl1.
  cluster-scope/base/core/namespaces/inception/kustomization.yaml
  cluster-scope/base/core/namespaces/inception/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/inception-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/inception-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/inception-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/inception-admins/rbac.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/inception-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
Labels: size/M, lgtm

#2088 curator-operator-leader-election-roles-rb
  curator-operator-system/base/kustomization.yaml
  curator-operator-system/base/rbac.authorization.k8s.io/kustomization.yaml
  curator-operator-system/base/rbac.authorization.k8s.io/rolebindings/rolebinding.yaml
  curator-operator-system/base/rbac.authorization.k8s.io/roles/role.yaml
  curator-operator-system/base/serviceaccounts/kustomization.yaml
  curator-operator-system/base/serviceaccounts/serviceaccount.yaml
  curator-operator-system/overlays/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2090 Create superset admin group.
  cluster-scope/base/user.openshift.io/groups/superset-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/superset-admins/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/superset-user/group.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  docs/content/odh/superset/add_superset_users.md
  kfdefs/overlays/moc/smaug/superset/configmaps/superset_config.py
Labels: size/S

#2092 curator-operator-config-crd
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/curatorconfig.curatoroperator.io/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2093 Added new member to group.yaml
  cluster-scope/base/user.openshift.io/groups/scsaol/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2097 Add a new seldon admins group for smaug.
  cluster-scope/base/core/namespaces/opf-seldon/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/seldon-admin/group.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  docs/content/odh/seldon/README.md
Labels: size/M, approved, lgtm

#2101 increased memory limit for seldon ns
  cluster-scope/base/core/namespaces/ds-ml-workflows-ws/resourcequota.yaml
Labels: size/XS, lgtm

#2034 feat(onboarding): Add team sostrades in os-cli2
  cluster-scope/base/core/namespaces/sostrades/kustomization.yaml
  cluster-scope/base/core/namespaces/sostrades/limitrange.yaml
  cluster-scope/base/core/namespaces/sostrades/namespace.yaml
  cluster-scope/base/core/namespaces/sostrades/resourcequota.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/M, approved, lgtm, needs-ok-to-test

#2100 add docs on distributed tracing & deploy OTel data collection
  cluster-scope/base/core/namespaces/opentelemetry-collector-operator/kustomization.yaml
  cluster-scope/base/core/namespaces/opentelemetry-collector-operator/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/opentelemetry-collector-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/opentelemetry-collector-operator/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/opentelemetry-collector-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/opentelemetry-collector-operator/subscription.yaml
  cluster-scope/bundles/opentelemetry-collector-operator/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  docs/_toc.yml
  docs/content/jaeger/README.md
  docs/content/jaeger/using-distributed-tracing-jaeger.md
  docs/content/opentelemetry-collector/README.md
  docs/content/opentelemetry-collector/using-opentelemetry-collector.md
Labels: size/L

#2103 Add subscription for minio in smaug
  cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2105 Add Alex-exe-dev to B4mad group
  cluster-scope/base/user.openshift.io/groups/b4mad/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2106 Add Pep to the operate-first group
  cluster-scope/base/user.openshift.io/groups/operate-first/group.yaml
Labels: approved, size/XS, lgtm

#2108 Fix minio operator source
  cluster-scope/base/operators.coreos.com/subscriptions/minio-operator/subscription.yaml
Labels: size/XS

#2109 Add backup job.
  docs/_toc.yml
  docs/content/vault_eso/restore_vault.md
  docs/content/vault_eso/runbook.md
  docs/content/vault_eso/vault_backup_job.md
  vault/overlays/moc/smaug/backup-job/cronjob.yaml
  vault/overlays/moc/smaug/backup-job/kustomization.yaml
  vault/overlays/moc/smaug/backup-job/pvc.yaml
  vault/overlays/moc/smaug/backup-job/rolebinding.yaml
  vault/overlays/moc/smaug/backup-job/sa.yaml
  vault/overlays/moc/smaug/backup-job/secret.yaml
  vault/overlays/moc/smaug/backup-job/task.yaml
  vault/overlays/moc/smaug/backup-job/taskrun.yaml
  vault/overlays/moc/smaug/backup-job/toolkitpod.yaml
  vault/overlays/moc/smaug/kustomization.yaml
Labels: size/L, approved, lgtm

#2098 Add bu-cs-book-dev namespace and group to smaug
  cluster-scope/base/core/namespaces/bu-cs-book-dev/kustomization.yaml
  cluster-scope/base/core/namespaces/bu-cs-book-dev/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/bu-cs-book-dev/group.yaml
  cluster-scope/base/user.openshift.io/groups/bu-cs-book-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/bu-cs-book-dev/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/bu-cs-book-dev/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm
