Repository operate-first/apps, pull requests merged in 2022-11, with the labels that each got.

#2527 WIP inception config
  inception/base/deployments/inception-deployment.yaml
  inception/base/deployments/kustomization.yaml
  inception/base/deployments/proxy-deployment.yaml
  inception/base/kustomization.yaml
  inception/base/routes/inception-route.yaml
  inception/base/routes/kustomization.yaml
  inception/base/secrets/inception-proxy.yaml
  inception/base/secrets/inception-secrets.yaml
  inception/base/secrets/kustomization.yaml
  inception/base/services/inception-service.yaml
  inception/base/services/kustomization.yaml
  inception/base/services/proxy-service.yaml
  inception/overlays/osc/osc-cl1/kustomization.yaml
  inception/overlays/osc/osc-cl2/kustomization.yaml
Labels: do-not-merge/work-in-progress, size/L, lgtm

#2594 Add robozome ns
  cluster-scope/base/core/namespaces/robozome/kustomization.yaml
  cluster-scope/base/core/namespaces/robozome/namespace.yaml
  cluster-scope/base/core/namespaces/robozome/resourcequota.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/robozome/kustomization.yaml
  scripts/jsonnet/group.jsonnet
  scripts/jsonnet/namespace.jsonnet
  scripts/jsonnet/rbac.jsonnet
  scripts/offboarding.sh
  scripts/onboarding.sh
  scripts/payload_examples/offboarding.yaml
  scripts/payload_examples/onboarding.yaml
Labels: size/L, approved, lgtm

#2595 feat(catalog): Create exeternal secret for service-catalog
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/service-catalog.yaml
Labels: approved, size/S, lgtm

#2590 chore: Remove clusters from service catalog in favor of autodiscovery
  service-catalog/resources.yaml
  service-catalog/resources/curator.yaml
  service-catalog/resources/infra.yaml
  service-catalog/resources/jerry.yaml
  service-catalog/resources/osc-cl1.yaml
  service-catalog/resources/osc-cl2.yaml
  service-catalog/resources/smaug.yaml
Labels: size/L, approved, lgtm

#2596 increasing quota for ai4cloudops project
  cluster-scope/base/core/namespaces/ai4cloudops/kustomization.yaml
  cluster-scope/base/core/namespaces/ai4cloudops/resourcequota.yaml
Labels: approved, size/S, lgtm

#2597 [prow] Remove legacy presubmit check for from tide config
  prow/overlays/smaug/config.yaml
Labels: approved, size/XS, lgtm

#2598 Create robozome argocd app and add deployment manifests.
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/robozome.yaml
  robozome/base/kustomization.yaml
  robozome/overlays/moc/smaug/externalsecret.yaml
  robozome/overlays/moc/smaug/kustomization.yaml
Labels: size/M

#2599 Specify images for robozome from apps repo
  robozome/overlays/moc/smaug/kustomization.yaml
Labels: size/XS

#2600 Increase pvc size for user in osc-cl2 jh.
  kfdefs/overlays/osc/osc-cl2/jupyterhub/pvcs/kustomization.yaml
  kfdefs/overlays/osc/osc-cl2/jupyterhub/pvcs/suppathak.yaml
Labels: size/S

#2604 feat(service catalog): Add service account with role for prometheus plugin
  cluster-scope/base/core/serviceaccounts/service-catalog-prometheus-plugin/kustomization.yaml
  cluster-scope/base/core/serviceaccounts/service-catalog-prometheus-plugin/serviceaccount.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-prometheus-plugin/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/service-catalog-prometheus-plugin/kustomization.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm

#2606 chore: Fix techdocs CI
  .github/workflows/techdocs.yaml
Labels: size/M, approved, lgtm

#2607 bump quota for ai4cloudops
  cluster-scope/base/core/namespaces/ai4cloudops/resourcequota.yaml
Labels: size/XS

#2605 feat: Add apicurio SCC allowing SYS_ADMIN for debugging
  cluster-scope/base/security.openshift.io/securitycontextconstraints/apicurio-debug-scc/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/apicurio-debug-scc/securitycontextconstraint.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2593 nfs-server-and-provisioner
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/nfs-server-and-provisioner.yaml
  cluster-scope/base/core/namespaces/nfs-server-and-provisioner/kustomization.yaml
  cluster-scope/base/core/namespaces/nfs-server-and-provisioner/namespace.yaml
  cluster-scope/base/core/namespaces/nfs-server-and-provisioner/resourcequota.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nfs-provisioner-runner/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/nfs-provisioner-runner/kustomization.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nfs-provisioner-runner/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/nfs-provisioner-runner/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/nfs-server-and-provisioner/kustomization.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/nfs-server-and-provisioner/securitycontextconstraints.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/nfs-provisioner/kustomization.yaml
  cluster-scope/base/storage.k8s.io/storageclasses/nfs-provisioner/storageclass.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  nfs-server-and-provisioner/README.md
  nfs-server-and-provisioner/base/deployment.yaml
  nfs-server-and-provisioner/base/export-pv-claim.yaml
  nfs-server-and-provisioner/base/kustomization.yaml
  nfs-server-and-provisioner/base/rbac.yaml
  nfs-server-and-provisioner/overlays/moc/smaug/kustomization.yaml
Labels: size/XL, approved, lgtm

#2611 allow robozome-op1st for prow trigger plugin
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS, lgtm

#2613 add secret store to prow
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/opf-ci-prow/kustomization.yaml
  prow/overlays/smaug/externalsecrets/cookie.yaml
  prow/overlays/smaug/externalsecrets/github-oauth-config.yaml
  prow/overlays/smaug/externalsecrets/github-token.yaml
  prow/overlays/smaug/externalsecrets/hmac-token.yaml
  prow/overlays/smaug/externalsecrets/oauth-token.yaml
  prow/overlays/smaug/externalsecrets/s3-credentials.yaml
  prow/overlays/smaug/externalsecrets/ssh-secret.yaml
Labels: approved, size/S, lgtm

#2612 feat: Upgrade camel-k to stable channel
  cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml
Labels: approved, size/XS, lgtm

#2615 Update Pulp CR
  pulp/base/opf-pulp.yaml
  pulp/overlays/moc/smaug/kustomization.yaml
  pulp/overlays/moc/smaug/opf-pulp-backup.yaml
  pulp/overlays/moc/smaug/opf-pulp-route.yaml
  pulp/overlays/moc/smaug/opf-pulp.yaml
Labels: size/M, approved, lgtm, ok-to-test

#2616 Fix the new pulp CR reference in argocd list
  argocd/overlays/moc-infra/projects/global_project.yaml
Labels: approved, size/XS, lgtm

#2619 fix: Increase ghproxy resources to avoid OOM kills
  prow/overlays/smaug/ghproxy.yaml
Labels: size/XS, lgtm

#2621 Adding pulp users
  cluster-scope/base/user.openshift.io/groups/pulp/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2623 add mbaldessari to cluster admins
  cluster-scope/overlays/prod/emea/jerry/groups/cluster-admins.yaml
Labels: size/XS

#2627 Move the OSC cl1 staging ODH deployment to the meteor namespace
  kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
Labels: size/M, approved, lgtm

#2625 fix: Match ghproxy resource request and limit
  prow/overlays/smaug/ghproxy.yaml
Labels: approved, size/XS, lgtm

#2629 Using odhdashboardconfig overlays for cnbi
  kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
  kfdefs/overlays/osc/osc-cl1/jupyterhub-stage/kfdef.yaml
Labels: approved, size/XS, lgtm

#2631 configure internal registry for jerry
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: size/S

#2634 change image registry
  cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/config.yaml
  cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/persistentvolumeclaims/image-registry-storage/kustomization.yaml
  cluster-scope/overlays/prod/emea/jerry/persistentvolumeclaims/image-registry-storage/persistentvolumeclaim.yaml
Labels: size/M

#2630 add additional admin to emporous project
  cluster-scope/base/user.openshift.io/groups/emporous-devs/group.yaml
Labels: approved, size/XS, lgtm

#2626 feat: Trust renovate and dependabot to run CI in Prow
  prow/overlays/smaug/plugins.yaml
Labels: approved, size/XS, lgtm

#2637 make crunchy postgres PGO available cluster wide
  cluster-scope/base/operators.coreos.com/operatorgroups/service-catalog/operator-group.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/crunchy-postgres/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/crunchy-postgres/subscription.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/service-catalog/kustomization.yaml
  cluster-scope/bundles/service-catalog/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2638 add hostPath to scc
  cluster-scope/base/security.openshift.io/securitycontextconstraints/nfs-server-and-provisioner/securitycontextconstraints.yaml
Labels: approved, size/XS, lgtm

#2624 Install RH SSO operator into `apex` namespace
  cluster-scope/base/operators.coreos.com/operatorgroups/apex/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/apex/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/apex-rhsso-operator/kustomization.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/apex-rhsso-operator/subscription.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: size/M, approved, lgtm

#2617 Pin custom elyra image until 0.2.x bug is fixed
  kfdefs/overlays/osc/osc-cl1/jupyterhub/notebook-images/elyra-image.yaml
  kfdefs/overlays/osc/osc-cl2/jupyterhub/notebook-images/elyra-image.yaml
Labels: approved, size/XS, lgtm

#2639 add LF folks to owners
  kfdefs/overlays/osc/OWNERS
Labels: approved, size/XS, lgtm

#2640 Add Pep to the cluster admins group for the osc-cl1 cluster
  cluster-scope/overlays/prod/osc/osc-cl1/groups/cluster-admins.yaml
Labels: approved, size/XS, lgtm

#2641 allow pgo resource in racing ns
  argocd/overlays/moc-infra/projects/b4mad.yaml
Labels: size/XS

#2642 adjust path for minecraft app
  argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/minecraft.yml
Labels: size/XS

#2644 :zap: Update pulp version and include nodeaffinity to pulp backup
  cluster-scope/base/operators.coreos.com/subscriptions/pulp-operator/subscription.yaml
  pulp/overlays/moc/smaug/opf-pulp-backup.yaml
Labels: approved, size/S, lgtm

#2646 Request large quota for WildFly
  cluster-scope/base/core/namespaces/wildfly-service/kustomization.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2649 add openshift-pipelines to jerry
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: approved, size/XS, lgtm

#2655 OKD: Update builder Dockerfile path and image name
  kvm-device-plugin/base/buildconfig.yaml
  okd-centos/base/buildconfig.yaml
Labels: approved, size/S, lgtm

#2656 Change branch ref from master to main
  kvm-device-plugin/base/buildconfig.yaml
Labels: approved, size/XS, lgtm

#2660 Add OpenShift Pipeline annotations to namespace apex
  cluster-scope/base/core/namespaces/apex/namespace.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2663 osc-cl1: Add CNBi / CRE pipelines to the osc-cl1 deployment
  kfdefs/overlays/osc/osc-cl1/cnbi/kfdef.yaml
Labels: approved, size/XS, lgtm

#2654 grant access to grafana to sostrades team
  grafana/overlays/osc/osc-cl1/grafana_oauth_patch.yaml
  grafana/overlays/osc/osc-cl2/grafana_oauth_patch.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2665 Add inception deployment docs as README
  inception/README.md
Labels: size/XL, approved, lgtm
