Repository operate-first/apps, pull requests merged in 2023-01, with the labels that each got.

#2702 argocd: Allow apex project to deploy to apex-*
  argocd/overlays/moc-infra/projects/apex.yaml
Labels: approved, size/XS, lgtm

#2703 feat: Enable Grafana* resources in ArgoCD globally
  argocd/overlays/moc-infra/projects/b4mad.yaml
  argocd/overlays/moc-infra/projects/global_project.yaml
  argocd/overlays/moc-infra/projects/operate-first.yaml
Labels: approved, size/S, lgtm

#2414 thoth-station: Close unactive issues needing reporter input
  prow/overlays/smaug/config.yaml
Labels: size/M, approved, lgtm

#2715 moving prow storage to ionos s3 bucket
  prow/overlays/smaug/config.yaml
Labels: size/XS

#2713 Add Sostrades project and applications to argocd
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/sostrades/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl2/sostrades/sostrades.yaml
  argocd/overlays/moc-infra/projects/sostrades.yaml
Labels: size/M, approved, lgtm

#2716 Update kustomization.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2707 chore: Update ocm API definition
  service-catalog/apis/backstage.yaml
Labels: approved, size/S, lgtm

#2708 chore(catalog): Update ClusterRole for OCM plugin
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin-acm/clusterrole.yaml
Labels: approved, lgtm

#2705 fix: Fix issue with rolebinding being listed as component
  scripts/onboarding.sh
Labels: approved, size/XS, lgtm

#2591 Include oef_openclimate in catalog
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/oef_openclimate.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/kustomization.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2718 Update Openmetadata to 0.13.1
  openmetadata/base/openmetadata-dependencies/configmaps/files/pod_template.yaml
  openmetadata/base/openmetadata-dependencies/configmaps/openmetadata-dependencies-config-envs.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-db-migrations.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-scheduler.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-sync-users.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airflow-web.yaml
  openmetadata/base/openmetadata-dependencies/deployments/airlfow-triggerer.yaml
  openmetadata/base/openmetadata/deployments/openmetadata.yaml
  openmetadata/overlays/osc/osc-cl2/kustomization.yaml
  openmetadata/overlays/osc/osc-cl2/patches/deployments/openmetadata.yaml
Labels: size/M, approved, lgtm

#2721 fix: Project admin component has to be of a Component kind, not Kustomization
  scripts/onboarding.sh
Labels: approved, size/XS, lgtm

#2693 docs: Fix typo in mco entity name for docs generation
  .github/workflows/techdocs.yaml
Labels: approved, size/XS, lgtm

#2700 Update kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
Labels: approved, size/XS, lgtm
