Repository operate-first/apps, pull requests merged in 2023-03, with the labels that each got.

#2754 Updating Kruize.yaml to add smaug server URL
  argocd/overlays/moc-infra/projects/kruize.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2752 feat: Add namespace for users service-catalog
  cluster-scope/base/core/namespaces/web-terminal-service-catalog/kustomization.yaml
  cluster-scope/base/core/namespaces/web-terminal-service-catalog/namespace.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm

#2757 Updating Kruize application name
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kruize/kruize.yaml
Labels: approved, size/XS, lgtm

#2746 feat: Add Open Metadata to OSC-CL1
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/cluster-management/openmetadata.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/openmetadata-admins.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/secret-mgmt/openmetadata/kustomization.yaml
  openmetadata/overlays/osc/osc-cl1/configmaps/files/auth_roles_mapping.json
  openmetadata/overlays/osc/osc-cl1/configmaps/files/dex_provider_cfg.json
  openmetadata/overlays/osc/osc-cl1/configmaps/kustomization.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/airflow-mysql-secrets.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/airflow-secrets.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/dex-provider-cfg.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/kustomization.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/mysql-init-scripts.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/mysql-secrets.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/mysql.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/openmetadata-auth.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/openmetadata-dependencies-config-envs.yaml
  openmetadata/overlays/osc/osc-cl1/externalsecrets/openmetadata-envs.yaml
  openmetadata/overlays/osc/osc-cl1/kustomization.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/airflow-db-migrations.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/airflow-scheduler.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/airflow-sync-users.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/airflow-web.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/airlfow-triggerer.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/elasticsearch.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/mysql.yaml
  openmetadata/overlays/osc/osc-cl1/patches/deployments/openmetadata.yaml
Labels: size/L, approved, lgtm

#2755 add goern to some admin groups, so that he can help out
  .pre-commit-config.yaml
  .prow.yaml
  cluster-scope/base/user.openshift.io/groups/argocd-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/odh-admin/group.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
Labels: size/M, approved, lgtm

#2760 feat: Add higher timeout for kubeval job
  .prow.yaml
Labels: approved, size/XS, lgtm

#2761 fix: Increase kubeval job memory request to 1GB
  .prow.yaml
Labels: approved, size/XS, lgtm

#2762 Add Pep to the OS-Climate aicos demo team
  cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/group.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/groups/odh-users.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2763 Adding 2 smartvillage Kafka topics and a smartvillage Kafka user
  kafka/overlays/smaug/topics/kustomization.yaml
  kafka/overlays/smaug/topics/smartvillage-sumo-run-report.yaml
  kafka/overlays/smaug/topics/smartvillage-sumo-run.yaml
  kafka/overlays/smaug/users/kustomization.yaml
  kafka/overlays/smaug/users/smartvillage.yaml
Labels: size/M, approved, lgtm, ok-to-test

#2764 fix: Increase kubeval job memory request to 4GB
  .prow.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2759 feat: Add metrics to observability
  cluster-scope/overlays/prod/moc/infra/configmaps/observability-metrics-custom-allowlist.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm

#2766 Update OpenShift Pipelines at Jerry to version 1.8
  cluster-scope/overlays/prod/emea/jerry/kustomization.yaml
Labels: approved, size/XS, lgtm

#2765 feat: Add MachineWithoutValidNode alert
  cluster-scope/overlays/prod/moc/infra/configmaps/thanos-ruler-custom-rules.yaml
  cluster-scope/overlays/prod/moc/infra/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2770 feat: Increase quota for web-terminal-service-catalog namespace
  cluster-scope/base/core/namespaces/web-terminal-service-catalog/kustomization.yaml
Labels: approved, size/XS, lgtm

#2772 removal of volsync based items
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/volsync.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationdestinations.volsync.backube/customresourcedefinition.yaml
  cluster-scope/base/apiextensions.k8s.io/customresourcedefinitions/replicationsources.volsync.backube/customresourcedefinition.yaml
  cluster-scope/base/core/namespaces/volsync-system/kustomization.yaml
  cluster-scope/base/core/namespaces/volsync-system/namespace.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-manager/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/volsync-proxy/clusterrolebinding.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-edit/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-aggregate-to-view/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-manager/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-metrics-reader/clusterrole.yaml
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/volsync-proxy/clusterrole.yaml
  cluster-scope/base/security.openshift.io/securitycontextconstraints/volsync-mover/securitycontextconstraints.yaml
  cluster-scope/bundles/volsync/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  docs/_toc.yml
  docs/content/volsync/docs/using-volsync.md
  docs/content/volsync/mkdocs.yaml
  volsync/base/apps/deployments/volsync/deployment.yaml
  volsync/base/core/serviceaccounts/volsync/serviceaccount.yaml
  volsync/base/core/services/volsync-metrics/service.yaml
  volsync/base/kustomization.yaml
  volsync/base/rbac.authorization.k8s.io/rolebindings/volsync-leader-election/rolebinding.yaml
  volsync/base/rbac.authorization.k8s.io/roles/volsync-leader-election/role.yaml
  volsync/overlays/moc/smaug/kustomization.yaml
  volsync/src/.gitignore
  volsync/src/Makefile
  volsync/src/kustomization.yaml
Labels: approved, size/XXL, lgtm

#2771 removal of apex based items
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/apex-qa.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/apex.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/apex/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/kustomization.yaml
  argocd/overlays/moc-infra/externalsecrets/clusters/octo-gohan.yaml
  argocd/overlays/moc-infra/projects/apex.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  cluster-scope/base/core/namespaces/apex-monitoring/kustomization.yaml
  cluster-scope/base/core/namespaces/apex-monitoring/namespace.yaml
  cluster-scope/base/core/namespaces/apex-qa/kustomization.yaml
  cluster-scope/base/core/namespaces/apex-qa/namespace.yaml
  cluster-scope/base/core/namespaces/apex/kustomization.yaml
  cluster-scope/base/core/namespaces/apex/namespace.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/apex/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/apex/operatorgroup.yaml
  cluster-scope/base/operators.coreos.com/subscriptions/apex-rhsso-operator/kustomization.yaml
  cluster-scope/base/user.openshift.io/groups/apex/group.yaml
  cluster-scope/components/project-admin-rolebindings/apex/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apex/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/apex/opf-vault-store.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
Labels: size/L, approved, lgtm

#2774 fix: Add openmetadata-airflow to cli1 dex config
  dex/overlays/osc/osc-cl1/configmaps/files/config.yaml
Labels: size/XS, lgtm

#2775 fix: Set dex redirect uri to cl1
  dex/overlays/osc/osc-cl1/configmaps/files/config.yaml
Labels: size/XS

#2776 needed permissions in infra for context when migrating osc clusters
  cluster-scope/overlays/prod/moc/infra/groups/cluster-admins.yaml
Labels: size/XS, lgtm
