Repository operate-first/apps, pull requests merged in 2023-04, with the labels that each got.

#2778 removing osc argocd apps from op1st management
  argocd/overlays/moc-infra/applications/app-of-apps/kustomization.yaml
Labels: size/XS

#2787 bump resources
  cluster-scope/base/core/namespaces/janus-idp/kustomization.yaml
  cluster-scope/base/core/namespaces/janus-idp/resourcequota.yaml
Labels: size/S

#2788 missing G in quota defintion
  cluster-scope/base/core/namespaces/janus-idp/resourcequota.yaml
Labels: approved, size/XS, lgtm
