Repository operate-first/apps, pull requests merged in 2023-05, with the labels that each got.

#2791 feat(tekton): Add new pipeline resource permissions for tekton plugin
  cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2790 OKD-89: feature: adds a new argoCD app to deploy okd tekton pipeline
  argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/okd-team/okd-tekton-release-pipeline.yaml
Labels: size/S, ok-to-test

#2796 🧽 remove pulp from deployment, but keep the assets in the repo
  argocd/overlays/moc-infra/applications/envs/moc/smaug/operate-first/kustomization.yaml
  argocd/overlays/moc-infra/projects/global_project.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  grafana/overlays/moc/common/dashboards/kustomization.yaml
  service-catalog/apis.yaml
  service-catalog/apis/pulp.yaml
  service-catalog/components.yaml
  service-catalog/components/pulp-operator.yaml
  service-catalog/components/pulp.yaml
  service-catalog/groups.yaml
  service-catalog/groups/pulp.yaml
  service-catalog/systems.yaml
  service-catalog/systems/pulp.yaml
  service-catalog/users.yaml
  service-catalog/users/pulp.yaml
Labels: size/L, approved, lgtm

#2795 ⚡ removing the b4mad related stuff #clarety
  argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/minecraft.yml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/b4mad/racing.yml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
  argocd/overlays/moc-infra/projects/b4mad.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  cluster-scope/base/core/namespaces/b4mad-minecraft/kustomization.yaml
  cluster-scope/base/core/namespaces/b4mad-minecraft/namespace.yaml
  cluster-scope/base/core/namespaces/b4mad-racing/kustomization.yaml
  cluster-scope/base/core/namespaces/b4mad-racing/namespace.yaml
  cluster-scope/base/core/namespaces/b4mad-racing/resourcequota.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/kustomization.yaml
  cluster-scope/base/operators.coreos.com/operatorgroups/b4mad-racing/operatorgroup.yaml
  cluster-scope/base/user.openshift.io/groups/b4mad/group.yaml
  cluster-scope/base/user.openshift.io/groups/b4mad/kustomization.yaml
  cluster-scope/bundles/b4mad-racing/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/b4mad/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/b4mad/rbac.yaml
  cluster-scope/overlays/prod/common/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/kustomization.yaml
  grafana/overlays/moc/common/dashboards/b4mad/kustomization.yaml
  grafana/overlays/moc/common/dashboards/b4mad/telemeter.yaml
  grafana/overlays/moc/common/dashboards/kustomization.yaml
  prow/overlays/smaug/config.yaml
  prow/overlays/smaug/plugins.yaml
Labels: size/L, approved, kind/feature, lgtm
