Repository operate-first/apps, pull requests merged in 2023-02, with the labels that each got.

#2722 Upgrade openmetadata
  openmetadata/base/openmetadata/configmaps/files/openmetadata.yaml
  openmetadata/overlays/dev/patches/configmaps/openmetadata-dependencies-config-envs.yaml
Labels: approved, size/XS, lgtm

#2725 Update ai4cloudops group
  cluster-scope/base/user.openshift.io/groups/ai4cloudops/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2728 increased cpu limits
  cluster-scope/base/core/namespaces/opf-jupyterhub/resourcequota.yaml
Labels: approved, size/XS, lgtm

#2727 Add scripts and job to perform db validation and repair
  openmetadata/base/openmetadata/configmaps/files/check_db_migrations.sh
  openmetadata/base/openmetadata/configmaps/kustomization.yaml
  openmetadata/base/openmetadata/jobs/openmetadata-db-migrations-hook.yaml
Labels: size/L, approved, lgtm

#2731 change rollout strategy
  cluster-scope/overlays/prod/emea/jerry/imageregistry.operator.openshift.io/configs/cluster/config.yaml
Labels: approved, size/XS, lgtm

#2729 Add A.Guidi to okd-team group
  cluster-scope/base/user.openshift.io/groups/okd-team/group.yaml
Labels: approved, size/XS, lgtm

#2730 Add Janus-IDP users
  cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml
Labels: approved, size/XS, lgtm, needs-ok-to-test

#2732 set hive.timestamp-precision to MICROSECONDS
  kfdefs/overlays/osc/osc-cl2/trino/configs/catalogs/osc_datacommons_hive_ingest.properties
Labels: approved, size/XS, lgtm

#2733 Add additionnal Janus Idp users
  cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2735 feat: Enable Vault and ArgoCD for Janus-IDP
  argocd/overlays/moc-infra/projects/janus-idp.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/janus-idp/kustomization.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/janus-idp/opf-vault-store.yaml
  cluster-scope/overlays/prod/moc/smaug/secret-mgmt/kustomization.yaml
Labels: size/M, approved, lgtm

#2736 add current dump of Google Cloud DNS configuration
  dns/OWNERS
  dns/README.md
  dns/emea-operate-first.zone
  dns/na-operate-first.zone
  dns/operate-first.zone
  dns/operatefirst.zone
  dns/zones.txt
Labels: size/L, approved, lgtm, kind/documentation

#2734 Adding new namespace for to OS-Climate cl2
  cluster-scope/base/core/namespaces/aicos-osc-demo/kustomization.yaml
  cluster-scope/base/core/namespaces/aicos-osc-demo/namespace.yaml
  cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/group.yaml
  cluster-scope/base/user.openshift.io/groups/aicos-osc-admins/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/aicos-osc-demo/kustomization.yaml
  cluster-scope/components/project-admin-rolebindings/aicos-osc-demo/rbac.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/kubeflow-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/groups/odh-admin.yaml
  cluster-scope/overlays/prod/osc/osc-cl2/kustomization.yaml
Labels: size/M, approved, lgtm

#2737 remove deployment of Thoth's traige party
  argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/bots/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/thoth/bots/prod-thoth-triage-party.yaml
Labels: size/M, approved, lgtm

#2738 Add Janus-IDP Showcase app
  argocd/overlays/moc-infra/applications/envs/moc/smaug/janus-idp/janus-idp.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/janus-idp/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/moc/smaug/kustomization.yaml
Labels: approved, size/S, lgtm, ok-to-test

#2739 create rmi schema
  kfdefs/overlays/osc/osc-cl2/trino/configs/group-mapping.properties
  kfdefs/overlays/osc/osc-cl2/trino/configs/rules.json
  kfdefs/overlays/osc/osc-cl2/trino/configs/trino-acl-dsl.yaml
Labels: size/M, approved, lgtm

#2741 chore: Add myself to the janus-idp group
  cluster-scope/base/user.openshift.io/groups/janus-idp/group.yaml
Labels: approved, size/XS, lgtm

#2742 feat: Add k8s plugin tokens to janus-idp
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/janus-idp.yaml
Labels: approved, size/S, lgtm

#2743 feat: Revert adding janus-idp external secret
  cluster-scope/overlays/prod/moc/smaug/externalsecrets/janus-idp.yaml
Labels: approved, size/S, lgtm

#2748 adding ryan cook to smaug and vault admins
  cluster-scope/overlays/prod/moc/smaug/groups/cluster-admins.yaml
  cluster-scope/overlays/prod/moc/smaug/groups/vault-admins.yaml
Labels: size/XS

#2744 removing kepler-edge from argocd and OS-C Cluster1
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kepler-edge-demo.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kepler/kustomization.yaml
  argocd/overlays/moc-infra/applications/envs/osc/osc-cl1/kustomization.yaml
  argocd/overlays/moc-infra/projects/kepler.yaml
  argocd/overlays/moc-infra/projects/kustomization.yaml
  argocd/overlays/moc-infra/projects/os-climate.yaml
  cluster-scope/base/core/namespaces/kepler-edge/kustomization.yaml
  cluster-scope/base/core/namespaces/kepler-edge/namespace.yaml
  cluster-scope/base/core/namespaces/kepler-edge/resourcequota.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/kustomization.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m4.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m5.yaml
  cluster-scope/overlays/prod/osc/osc-cl1/machinesets/machineset-kepler-edge-m6.yaml
Labels: size/L, approved, lgtm

#2749 chore: Update physrisk-resilience resource quotas
  cluster-scope/base/core/namespaces/physrisk-resilience/kustomization.yaml
  cluster-scope/base/core/namespaces/physrisk-resilience/resourcequota.yaml
Labels: approved, size/S, lgtm
